Step5 -  로또(수동) 미션 리뷰 요청드립니다.
next-step/java-lotto-pro pull request #139
Opened 2021-11-05 07:41 UTC by pageprologue

안녕하세요🙂
5단계 로또(수동) 미션을 구현하여 리뷰 요청드립니다.
마지막 미션까지 올 수 있도록 코드 리뷰 해 주셔서 감사합니다.🙇‍♀️

2021-11-05 17:36 UTC, na-mul requested changes
안녕하세요 희진님. 벌써 로또 미션의 마지막 단계이군요.
전 단계까지 구조를 잘 잡아주셔서, 이번 단계의 기능 확장도 원할하게 진행된 느낌이에요.
바로 approve해도 괜찮은 코드이지만, 그래도 소소하게 첨언을 드려 보았습니다.
마지막 단계인 만큼 조금만 더 욕심 내어 부탁드리겠습니다. 화이팅입니다! 🙇‍♂️

2021-11-05 17:36 UTC, na-mul commented on src/main/java/lotto/domain/lotto/LottoNumber.java
> +        return lottoNumber.orElseThrow(() -> new IllegalArgumentException("로또 번호는 1 ~ 45 까지 입니다."));
캐쉬를 적절히 잘 적용해주셨네요. 특히 `Optional`을 활용한 부분도 눈에 띕니다. 👍
개인적으로도 `Optional`은 좋아해서 자주 사용하고 있네요!

다만 `Optional`의 목적은 객체 간 메시지를 주고 받을 때, `NullPointException`에 안전한 로직을 구축하기 위함인 것 같아요.
한 메소드 내에서 생성과 사용을 둘 다 하는 경우에는 오버엔지니어링일 수 있는 점 참고 부탁드립니다.

2021-11-05 17:36 UTC, na-mul commented on src/main/java/lotto/domain/lotto/LottoRank.java
> +    private final WinningStrategy<Integer, Boolean> winningStrategy;
이미 정의된 `BiPredicate` 같은 함수형 인터페이스가 존재함에도 인터페이스를 따로 정의하여 사용하게 된다면, 아무래도 도메인끼리 협력할 때 서로에게 특별한 역할을 부여하기 위함이겠지요.
하지만 지금으로서는 `WinningStrategy`는 `LottoRank`에서만 활용되며, 장기적으로도 `lotto`도메인이 `winning` 도메인으로의 불필요한 의존성을 갖게 됩니다.
- 그래서 개인적으로 수정을 권해드리는 편이 좋을 거라는 판단이 듭니다.

아무래도 희진님께서 `purchase`, `lotto`, `winning`으로 도메인을 정말 잘 나눠주신만큼,
저도 함께 도메인 간 의존성에 대해 더 깊게 고민하게 된 것 같아요.
이 점은 저 역시도 감사드립니다.

2021-11-05 17:36 UTC, na-mul commented on src/main/java/lotto/domain/lotto/LottoTicketVendingMachine.java
> +    }
Stream을 통한 깔끔한 처리 좋습니다! 👏

2021-11-05 18:00 UTC, pageprologue commented on src/main/java/lotto/domain/lotto/LottoNumber.java
> +        return lottoNumber.orElseThrow(() -> new IllegalArgumentException("로또 번호는 1 ~ 45 까지 입니다."));
앗 그렇군요. 지금과 같은 경우에도 오버엔지니어링이라고 할 수 있는 걸까요?
이 메소드를 사용하는 곳이 여러군데 있기도 해서, 리턴 타입을 ``Optional<LottoNumber>``로 주기보다 이 메소드 안에서 validation 체크도 하면서 바로 로또 번호를 리턴해 주는 것이 낫다고 생각을 했습니다..!

2021-11-05 18:01 UTC, pageprologue commented on src/main/java/lotto/domain/lotto/LottoRank.java
> +    private final WinningStrategy<Integer, Boolean> winningStrategy;
넵 이 부분 수정하겠습니다~!🙂

2021-11-05 18:48 UTC, na-mul commented on src/main/java/lotto/domain/lotto/LottoNumber.java
> +        return lottoNumber.orElseThrow(() -> new IllegalArgumentException("로또 번호는 1 ~ 45 까지 입니다."));
이 메소드 안에서 리턴하기 전에 validation 체크를 하는 것은 권장드리는 좋은 아이디어입니다. 👍

다만, 한 라인으로 validation 체크도 하고 바로 로또 번호를 리턴하는 것은 조금 더 고민해볼 수 있을 것 같아 말씀드리게 되었습니다.
코드가 약간 더 늘어나기는 하지만 아래 예시 코드 등과 같이한다면, 
굳이 `Optional`으로 한번 더 래핑하고 바로 풀어버리는 일 없이도 충분히 유효성 체크를 할 수 있을 것 같아요.

```
    public static LottoNumber from(int number) {
        LottoNumber lottoNumber = LOTTO_NUMBER_BOX.get(number);
        if(lottoNumber == null) {
            throw new IllegalArgumentException("로또 번호는 1 ~ 45 까지 입니다.");
        }
        return lottoNumber;
    }
```

코드에 정답은 없습니다! 이런 견해도 있을 수 있다는 의미로 가볍게 받아들여주세요~ 🙇‍♂️

2021-11-06 00:43 UTC, pageprologue commented on src/main/java/lotto/domain/lotto/LottoNumber.java
> +        return lottoNumber.orElseThrow(() -> new IllegalArgumentException("로또 번호는 1 ~ 45 까지 입니다."));
아하 저도 이렇게 쓰는 방향 좋다고 생각합니다..! 수정하였습니다 :)
정답은 없겠지만, 제가 작성하는 코드 스타일에 대해서도 더 고민해 보도록 하겠습니다~! 의견 주셔서 감사합니다🙂

2021-11-06 01:45 UTC, na-mul approved these changes
수정해주신 내용 모두 잘 봤습니다. Approve하도록 할게요!
깔끔하게 로또 미션을 마무리하신 것 같아요. 
정말 축하드립니다!
첫 발을 잘 내딛으신만큼 앞으로 남은 미션들도 잘 해주시리라 믿습니다. 😊
화이팅입니다!! 🔥

2021-11-06 01:45 UTC, merged