3단계 - 로또(자동)
next-step/java-lotto-pro pull request #149
Opened 2021-11-05 12:11 UTC by jerry92k

안녕하세요!
3단계 구현 제출 합니다.

프로그램을 설계하며 클래스를 분리하고 역할을 어떻게 나눌지 고민을 많이 한 결과물인데..
제대로 역할 분리를 잘 한 것인지 확신은 안듭니다.

고견 부탁드립니다..!

2021-11-05 15:35 UTC, minsungryu requested changes
지희님 문자열 계산기도 수정하고 로또 미션도 구현하시느라 너무 고생이 많으셨습니다.
코멘트를 좀 남겼는데요 어렵게 느껴지는 부분이 있을 수 있습니다.
(남기고 보니 너무 많은..)
한 번 고민해보시고 다음 리뷰까지 모든 수정사항을 반영하지 않아도 되니 부담은 가지지 않으셨으면 좋겠습니다.
어려움이 있으면 언제든 편하게 DM 주세요

2021-11-05 15:35 UTC, minsungryu commented on src/main/java/lottoservice/LottoMain.java
> +		return InputView.readLine();
InputView, ResultView의 구현이 콘솔에 의존적인데요,
만약 요구사항이 바뀌어서 이 로또 게임을 웹 서비스로 제공해야할 경우 수정할 부분이 많아질 것 같습니다.

이처럼 관심사 밖의 변동사항에 휘둘리지 않기 위해 DIP(의존성 역전 원칙)를 활용할 수 있는데요,
InputView, ResultView는 행위 중심의 인터페이스로 선언한다면 로또 게임에서는 단순히 외부로부터 입력을 받고 결과를 출력해주는 추상적인 행위에만 의존하게 되며 실제로 그 일은 구현체가 담당하게 됩니다.
이를테면 현재 코드를 ConsoleInputView, ConsoleResultView와 같은 구현체로 만들 수 있겠네요.

2021-11-05 15:35 UTC, minsungryu commented on src/main/java/lottoservice/LottoMain.java
> +	private static String GUIDE_MESSAGE_ENTER_INPUT_AMOUNT = "구매금액을 입력해주세요.";
꼼꼼하게 상수를 선언해주셨네요 👍

2021-11-05 15:35 UTC, minsungryu commented on src/main/java/lottoservice/exception/UnexpectedMatchException.java
> +public class UnexpectedMatchException extends RuntimeException{
저번에 제가 구체적인 예외를 던지면 좋겠다고 코멘트를 남겼었는데
그래서인지 예외 클래스를 꼼꼼하게 잘 나눠주셨네요. 힘들지 않으셨나 모르겠네요 ㅎㅎ

현실적으로는 예외 클래스가 많이 생기면 관리하기 힘들기 때문에
이미 자바에서 제공하는 많은 예외 클래스 중 적합한 것을 선택하고 메시지를 잘 전달하는 것만으로도 충분할 수 있습니다.(IllegalArgumentException, IllegalStateException 등)

물론 도메인에서 중요한 부분은 예외를 재정의하는 것도 좋습니다.
이런 것들은 칼로 무 썰듯 그 선을 정하기가 어렵기 때문에 그때 그때 상황을 고려해서 구현하면 될 것 같습니다 :)

2021-11-05 15:35 UTC, minsungryu commented on src/main/java/lottoservice/lottonumber/LottoNumber.java
> +public class LottoNumber {
값 객체 잘 구현해주셨네요 👍 
여유가 되신다면 final 키워드를 활용해서 불변 객체로 만들어보시는 것도 좋을 것 같습니다 :)
Comparable 인터페이스를 구현해봐도 재미있을 것 같네요.

2021-11-05 15:35 UTC, minsungryu commented on src/main/java/lottoservice/lottonumber/LottoNumbersMaker.java
> +				, (pickedNumbers1, pickedNumbers2) -> pickedNumbers1.addAll(pickedNumbers2));
지금도 괜찮긴한데요, 자주 쓰는 패턴은 아니라서 아래와 같이 변경해보시면 어떨까 싶습니다.

```java
.mapToObj(number -> new LottoNumber(number))
.collect(Collectors.toList();
```

2021-11-05 15:35 UTC, minsungryu commented on src/main/java/lottoservice/lottonumber/LottoNumbersMaker.java
> +			(lottoNumberPre, lottoNumberPost) -> lottoNumberPre.getNumber() - lottoNumberPost.getNumber());
아래 방법으로 코드의 가독성과 의도를 개선해보면 어떨까요?
1. LottoNumber가 Comparable 인터페이스를 구현
2. LottoNumber에서 getNumber()한 결과로 Comparator.comparingInt

2021-11-05 15:35 UTC, minsungryu commented on src/main/java/lottoservice/lottoticket/LottoTicket.java
> +	public int getNumOfNumbersInGroup() {
아마도 테스트 관점에서 작성된 코드가 아닐까 싶은데요,
LottoTicket이 가진 숫자의 개수를 가져와서 6개인지 확인하는 것보다는

생성자에서 불변식을 통해 6개의 숫자가 아니면 객체가 생성될 수 없도록 구현해보면 어떨까요?

2021-11-05 15:35 UTC, minsungryu commented on src/main/java/lottoservice/lottoticket/LottoTicket.java
> +		this.lottoNumbers = lottoNumber;
LottoNumber가 6개인지, 중복되지는 않는지에 대한 검사는 생성자에서 이루어지면 좋을 것 같습니다.

2021-11-05 15:35 UTC, minsungryu commented on src/main/java/lottoservice/lottoticket/LottoTicket.java
> +		return lottoTicketToStrMaker.toString();
잘 구현해주셨는데요 이렇게라도 가능할거에요~(지금 코딩을 못하는 상황이라 확인이..)
https://docs.oracle.com/javase/8/docs/api/java/util/stream/Collectors.html#joining-java.lang.CharSequence-java.lang.CharSequence-java.lang.CharSequence-

```java
lottoNumbers.stream()
	.map(lottoNumber -> lottoNumber.toString())
	.collect(Collectors.joining(", ", "[", "]"));
```

2021-11-05 15:35 UTC, minsungryu commented on src/main/java/lottoservice/lottoticket/LottoTicketIssuer.java
> +				(tickets1, tickets2) -> tickets1.addAll(tickets2));
이 부분도 위에서 언급했던 것처럼 더 쉽게 바꿔볼 수 있을 것 같아요.

2021-11-05 15:35 UTC, minsungryu commented on src/main/java/lottoservice/lottoticket/LottoTicketIssuer.java
> +	}
코드가 위에서 아래로 자연스럽게 읽히면 더 좋을 것 같습니다.
그런 의미에서 getNumOfTicketsToBuy 메서드도 buyTickets 아래 위치하는게 어떨까요?

2021-11-05 15:35 UTC, minsungryu commented on src/main/java/lottoservice/lottoticket/LottoTicket.java
> +		this(LottoNumbersMaker.makeLottoNumbers());
LottoTicket은 단순히 값 객체라고 볼 수 있는데 값을 생성하는 로직이 담겨있는 LottoNumbersMaker에 강하게 의존하는 코드인 것 같아요.
빈 생성자는 private으로 닫고 인자를 받아서만 초기화할 수 있도록 하면 좋을 것 같습니다.

2021-11-05 15:35 UTC, minsungryu commented on src/main/java/lottoservice/matcher/LottoMatchResult.java
> +			(matches1, matches2) -> matches1.putAll(matches2));
Collectors.toMap에 대해 알아보시면 더 짧게 코드를 구현해볼 수 있을거에요
(의도하신거라면 못본척해주세요..ㅎㅎ)

2021-11-05 15:35 UTC, minsungryu commented on src/main/java/lottoservice/matcher/LottoMatchResult.java
> +			.map(rank -> rank.getKey().getWinningMoney() * rank.getValue())
람다 인자가 rank인줄 알고 순간 헷갈렸네요.
entry가 더 적합한 이름이지 않을까 싶습니다. 아니면 요즘은 it도 많이 사용하는 것 같아요(이터레이터의 의미)

그리고 아래 mapToLong 대신 여기서 mapToLong 해도 되지 않을까요?

2021-11-05 15:35 UTC, minsungryu commented on src/main/java/lottoservice/matcher/LottoMatchResult.java
> +			.map(matchResult -> matchResult.getValue())
여기도 한 번에 mapToInt가 가능해보여요

2021-11-05 15:35 UTC, minsungryu commented on src/main/java/lottoservice/matcher/LottoMatcher.java
> +		return lottoMatchResult;
객체 외부에서 값을 set해주는 대신(add를 해주시긴 했지만요) 생성자에 lottoTickets와 lottoWinningNumbers를 넘기는 건 어떨까 싶습니다.
그렇게 되면 LottoMatcher와 LottoMatchResult의 역할이 중복되서 하나는 사라질 수도 있겠네요

2021-11-05 15:35 UTC, minsungryu commented on src/main/java/lottoservice/matcher/LottoWinningNumbers.java
> +		validateSizeOfLotto(numbers);
이런 불변식은 정적 팩토리 메서드보다는 생성자 내부에 있는게 더 좋을 것 같습니다.

2021-11-05 15:35 UTC, minsungryu commented on src/main/java/lottoservice/matcher/LottoWinningNumbers.java
> +		if (lottoNumbers.size() < LottoNumbersMaker.SIZE_OF_LOTTERY_NUMBERS) {
이 조건문은 lottoNumbers가 7개 되는 오류는 못잡을 것 같아요.

2021-11-05 15:35 UTC, minsungryu commented on src/main/java/lottoservice/matcher/LottoWinningNumbers.java
> +			matchCount += isMatchNumber(number) ? 1 : 0;
for-each 문 내부에서 부수효과를 일으키는 것보다 Stream API를 활용해보면 좋을 것 같습니다.

2021-11-05 15:35 UTC, minsungryu commented on src/main/java/textcalculation/StringDelimiterParser.java
> +		// Pattern 클래스의 인스턴스 생성 비용이 크기 때문에 매번 생성하는 대신 클래스 변수로 선언하고 재사용
👍

2021-11-05 15:35 UTC, minsungryu commented on src/main/java/textcalculation/StringDelimiterParser.java
> +		if (m.find()) {
바로 `return m.find()` 해도 되겠는데요?

2021-11-05 15:35 UTC, minsungryu commented on src/main/java/textcalculation/StringDelimiterParser.java
> +	protected static String[] splitText(String text) {
protected로 선언하신 이유가 있을까요?

2021-11-05 15:35 UTC, minsungryu commented on src/main/java/lottoservice/lottonumber/LottoNumber.java
> +	public LottoNumber(int number) {
값 객체는 그 수가 많아지면 메모리에 부담이 갈 수도 있을 것 같아요.
private으로 생성자를 막고 정적 팩토리 메서드를 통해 캐시된 객체를 반환하는 방법도 있습니다.
(IntegerCache 참고해보시면 좋을 것 같아요.)

이건 여유가 된다면 고려해보시는 것도 좋을 것 같습니다.

2021-11-05 15:35 UTC, minsungryu commented on src/test/java/lottoservice/lottonumber/LottoNumbersMakerTest.java
> +	public void makeLottoNumbers_1에서45사이_6개의_숫자생성() {
제어할 수 없는 부분에 대해서 테스트하기 힘들지 않으신가요?
사실 위에서 많은 부분이 static으로 되어있어서 언급하려다가 적합한 테스트를 찾기 위해 보고 있었습니다.

랜덤, 시간 등 제어할 수 없는 부분에 대해서는 의존성 주입을 통해 해결하거나 인자로 받아서 해결할 수 있습니다.
따라서 NumberGenerator 또는 NumberSupplier와 같이 숫자를 제공하는 인터페이스를 통해 
프로덕션 코드에는 랜덤 생성을 하고 테스트 코드에서는 매뉴얼하게 생성해서 테스트를 진행할 수 있습니다.

LottoNumberMaker가 static 클래스가 아닌 외부 의존성을 주입받아서 로또 번호를 생성할 수 있도록 변경해보면 좋을 것 같습니다.

2021-11-05 15:35 UTC, minsungryu commented on src/test/java/lottoservice/lottoticket/LottoTicketTest.java
> +		LottoTicket lottoTicket = new LottoTicket();
위에서 언급했듯이 LottoTicket이 값을 만드는 로직에 강하게 의존하고 있어서 발생하는 문제입니다.
테스트하기 어렵게 느껴지지 않으셨나요?

LottoTicket과 로직을 분리해보는걸 추천해드립니다.
사실 이런 테스트를 보면 프로덕션 코드 먼저 개발을 하고 테스트를 작성했다는 것도 알 수 있게 됩니다 🤣

2021-11-05 15:35 UTC, minsungryu commented on src/test/java/lottoservice/matcher/LottoMatchResultTest.java
> +		Assertions.assertThat(lottoMatchResult.getResult().get(LottoMatchRank.SIX_POINT)).isEqualTo(0);
`get(...).get(...)` 보다는 `getResult(LottoMatchRank.SIX_POINT)`처럼 객체에 메시지를 보내는 것은 어떨까요?

2021-11-05 15:35 UTC, minsungryu commented on src/test/java/lottoservice/matcher/LottoMatcherTest.java
> +	private List<LottoNumber> getLottoNumbers(List<Integer> numbers) {
테스트 코드에서 로또 번호를 생성하기 위한 로직이 있는 것보다
LottoTicket 자체가 `List<Integer>`를 받아서 객체를 생성할 수 있도록 정적 팩토리 메서드를 제공하는 것은 어떨까요?

2021-11-05 15:35 UTC, minsungryu commented on src/test/java/lottoservice/matcher/LottoWinningNumbersTest.java
> +		LottoWinningNumbers lottoWinningNumbers = LottoWinningNumbers.makeLottoWinningNumbers(numbers);
makeLottoWinningNumbers처럼 String을 받는 정적 팩토리 메서드를 구현해보는 것은 어떨까요?

2021-11-05 15:35 UTC, minsungryu commented on src/test/java/lottoservice/matcher/LottoWinningNumbersTest.java
> +			assertThat(lottoWinningNumbers.getWinningNumbers().contains(lottoNumber)).isTrue();
`get(...).conatins(...)` 보다는 `hasNumber()`와 같이 객체에 메서드를 보내는 것이 어떨까요?

2021-11-06 00:39 UTC, jerry92k commented on src/main/java/textcalculation/StringDelimiterParser.java
> +		// Pattern 클래스의 인스턴스 생성 비용이 크기 때문에 매번 생성하는 대신 클래스 변수로 선언하고 재사용
메일에는 말씀해주신 부분이 github에는 안보여서.. 동일 메서드인 여기에 답글 남깁니다!

(관련 comment : ```protected로 선언하신 이유가 있을까요?```)

**StringDelimiterParser.splitText protected를 접근제어자로 사용한 이유** 
: StringDelimiterParser 클래스에서 사용하는 dlimiter 패턴들이 StringAddCalculator에 논리적으로 종속적이여서, 해당 패키지 내에서만 사용될것이니 public으로 하기 보다는 protected로 조금 더 제한해야겠다는 생각으로 사용하였습니다. 
=> 제가 맞게 생각한 걸까요~? 

그리고 관련해서 조금 더 생각해보니 CUSTOM_DELIMIERS_PATTERN와 BASIC_DELIMITERS를 상수 선언안하고 DI로 받아서 사용하게 되면 좀 더 유연하게 활용가능해서 public이 되어도 괜찮을것 같이 생각들었습니다.

그래서 이렇게 수정을 해보다가.. 이렇게 할 경우에는 Pattern을 인스턴스 멤버 변수로 관리하게 되면서 StringDelimiterParser를 생성할 때 마다 Pattern 객체 생성 비용을 치르게 되어 다시 돌아왔습니다^^;

더 좋은 방법이 있을까요?

그리고... 어제 늦은시간까지 리뷰해주신 것에 정말 감사합니다. 
덕분에 정말 많이 배우고 있습니다.

다른 comment 주신 것들도 고민해보며 보완해보겠습니다.

감사합니다!

2021-11-06 01:38 UTC, jerry92k commented on src/main/java/lottoservice/lottoticket/LottoTicket.java
> +		return lottoTicketToStrMaker.toString();
오.. joining에 앞 뒤로도 붙일 수 있는 걸 확인을 안 해봤었네요. 감사합니다!

추가적으로 한가지 궁금한점이.. 
stream에서 String으로 형변환 하는 과정에서 String 객체 생성비용(lottoNumber.toString())이 조금 신경 쓰입니다.

이걸 줄이고자 collect 안에서 StringBuilder를 supplier로 주고,
lottoNumber를 char 형으로 변환하여 StringBuilder에 하나씩 append할까 생각도 해보았는데 구분자도 같이 들어가다 보니 코드가 좀 복잡해지더라구요..
이렇게 StringBuilder로 하는게 성능상 의미가 있을까요? 

지금은 데이터가 적기 때문에 String이나 StringBuilder가 큰 차이가 없지만, 
대용량 데이터를 이런식의 문자열로 만드는 경우라면 StringBuilder 하나로 만드는게 나을까요?

2021-11-06 08:24 UTC, jerry92k commented on src/test/java/lottoservice/matcher/LottoMatcherTest.java
> +	private List<LottoNumber> getLottoNumbers(List<Integer> numbers) {
조언해주신 부분을 참고하여 LottoTicket이 값 생성에 직접 관여하지 않고 값을 주입받도록 변경해보았습니다.
(설계를 하면서 무언가 찜찜한 부분들이 있었는데 디테일하게 달아주신 리뷰들 보고 많이 배우고 개선했습니다! 감사합니다!)

한가지 궁금한것은, 개선한 LottoTicket 코드에서 생성자 타입으로 List<LottoNumber>를 구현하였는데, List<Integer>를 인자로 받는 생성자나 정적 팩토리를 만들어도 될까요?
 
LottoTicket은 LottoNumber 리스트를 주입 받아서만 사용하고, Int 타입 List를 받아 LottoNumber 타입 리스트로 변환하는 일은 하지 않는 것이 도메인의 관심사를 분리해주지 않을까 생각했습니다. (List<LottoNumber> 생성 역할은 LottoNumbersMaker)

 (개선 전 코드 기준으로 조언해주신것 이어서, 지금 기준으로 여쭤보는 것이 또 다르긴 하지만 여쭤봅니다!)

2021-11-07 01:50 UTC, minsungryu approved these changes
지희님, 로또 3단계 미션 수행하느라 고생많으셨습니다.
피드백도 잘 반영해주셨고 수많은 고민의 흔적이 느껴졌습니다.
바로 merge하겠습니다. 4단계도 화이팅입니다~

2021-11-07 01:50 UTC, minsungryu commented on src/main/java/lottoservice/LottoMain.java
> +		LottoMain lottoMain = new LottoMain(userInputView, resultView);
👍

2021-11-07 01:50 UTC, minsungryu commented on src/main/java/lottoservice/lottonumber/LottoNumber.java
> +	}
와 캐싱도 적용해보셨군요 멋지네요

2021-11-07 01:50 UTC, minsungryu commented on src/main/java/lottoservice/lottoticket/LottoTicketIssuer.java
> +			.mapToObj((it) -> new LottoTicket(LottoNumbersMaker.makeLottoNumbers()))
`LottoNumbersMaker`의 제어 불가능한 부분(Collections.shuffle)에 의존하는 코드를 의존성 주입을 통해 해결해보면 좋을 것 같아요 :)

2021-11-07 01:50 UTC, minsungryu commented on src/main/java/textcalculation/StringDelimiterParser.java
> +		// Pattern 클래스의 인스턴스 생성 비용이 크기 때문에 매번 생성하는 대신 클래스 변수로 선언하고 재사용
1. 네, 의도를 가지고 설계하셨다면 충분히 괜찮습니다 👍 
2. Pattern객체를 넘겨받는다기보다는 특정 전략을 수행하는 인터페이스에 의존하면 괜찮을 것 같아요. 어떤 구현체는 Pattern 객체를 내부적으로 활용할 수도 있는거고, 다른 구현체는 또 다른 방식으로 Parsing을 수행할 수도 있는거구요. 계산기 입장에서는 Parser가 어떻게 동작하는지보다는 결과값을 잘 넘겨주는 것에만 관심이 있을 것 같습니다.

2021-11-07 01:50 UTC, merged