3단계 - 로또(자동)
next-step/java-lotto-pro pull request #167
Opened 2021-11-06 07:46 UTC by lights93

안녕하세요 강현구 리뷰어님!

개발을 완료했는데, 몇가지 문의사항이 있습니다.

1. 프린트하는 클래스에 Printable 인터페이스
프린트하는 클래스에 Printable 인터페이스를 도입했습니다.
그런데, 프린트하는 문자형식들이 각 클래스 안에 존재하고 있는데요, 이렇게 되면 문자 형식이 같이 있어서 제대로 분리되지 않았다고 볼 수도 있는 걸까요??
해당 클래스 내부의 데이터를 사용하여 출력 메시지를 생성하기 때문에 각 클래스 안에 문자형식을 넣긴 했습니다.
2. LottoResult의 getLottoMoney
LottoResult 클래스에서 getter 없이 최대한 하려고 했지만, LottoMoney에 대한 getter 없이 개발하려고 하니, 구조가 더 이상해지는 것 같아 getter를 사용했는데요.
혹시 getter없이 사용하는 좋은 방법이 있을까요??

이 외에도 도움이 될 만한 것이 있으면 말씀해주세요~
감사합니다.

2021-11-07 07:51 UTC, kang-hyungu commented
> 1. 프린트하는 클래스에 Printable 인터페이스
>    프린트하는 클래스에 Printable 인터페이스를 도입했습니다.
>    그런데, 프린트하는 문자형식들이 각 클래스 안에 존재하고 있는데요, 이렇게 되면 문자 형식이 같이 있어서 제대로 분리되지 않았다고 볼 수도 있는 걸까요??
>    해당 클래스 내부의 데이터를 사용하여 출력 메시지를 생성하기 때문에 각 클래스 안에 문자형식을 넣긴 했습니다.

도메인 객체에서 Printable 의존성을 제거하셔야 합니다.
도메인 객체가 콘솔 화면에 어떻게 문자열로 값을 뿌려줄지 신경 쓸 필요가 없습니다.
지금은 콘솔 상황만 한정해서 개발하고 있지만 모바일, 웹으로 확장하게 된다면 Printable 를 구현한 메서드는 재사용하지 못합니다.
도메인은 값만 제대로 뷰 객체에게 전달하면 됩니다.


> 2. LottoResult의 getLottoMoney
>    LottoResult 클래스에서 getter 없이 최대한 하려고 했지만, LottoMoney에 대한 getter 없이 개발하려고 하니, 구조가 더 이상해지는 것 같아 getter를 사용했는데요.
>    혹시 getter없이 사용하는 좋은 방법이 있을까요??

getter가 필요한 경우에는 사용해야겠죠. 
getter를 쓰지 않기 위해 LottoResult 에서 직접 합계를 계산하도록 만들어 보면 어떨까요?

2021-11-07 07:51 UTC, kang-hyungu requested changes
민호님 몇 가지 피드백 남겼습니다.
참고하셔서 코드 수정해보시고 리뷰 재요청주세요.

2021-11-07 07:51 UTC, kang-hyungu commented on src/main/java/lotto/domain/EarningRate.java
> +public class EarningRate implements Printable {
모든 도메인 객체에서 Printable를 제거해주세요.
도메인 객체에서는 뷰에서 필요로 하는 값만 반환하면 됩니다.
굳이 문자열로 변환해줄 필요는 없습니다.
뷰에서 알아서 처리해야될 일입니다. 도메인이 신경쓰면 안됩니다.

2021-11-07 07:51 UTC, kang-hyungu commented on src/main/java/lotto/domain/LottoCount.java
> +    public LottoCount(long count) {
로또 카운터는 -1도 허용되는 건가요?

2021-11-07 07:51 UTC, kang-hyungu commented on src/main/java/lotto/domain/LottoMoney.java
> +    private static final String WON = "원";
뷰에서 원으로 출력할지 다른 화폐 단위로 출력할지 결정하면 됩니다.
도메인에서 맡을 역할은 아닙니다.

2021-11-07 07:51 UTC, kang-hyungu commented on src/main/java/lotto/domain/LottoMoney.java
> +    public LottoMoney(String moneyText) {
변수명에 Text를 붙일 필요가 있나요?
String 타입을 보면 문자열인 것을 충분히 인지할 수 있지 않을까요

2021-11-07 07:51 UTC, kang-hyungu commented on src/main/java/lotto/domain/LottoMoney.java
> +    public LottoMoney(long money) {
생성자는 상단에 배치해주세요.
중간에 다른 메서드랑 생성자는 구분해주는게 좋습니다.

2021-11-07 07:51 UTC, kang-hyungu commented on src/main/java/lotto/domain/LottoMoney.java
> +    public static EarningRate calculateEarningRate(List<LottoMoney> lottoMoneyList) {
타입이 List 인데 변수명에 또 표현해줄 필요가 있을까요?

2021-11-07 07:51 UTC, kang-hyungu commented on src/main/java/lotto/domain/LottoResults.java
> +    private static final String NEW_LINE = "\n";
화면 출력에 쓰이는 변수들은 view 클래스로 옮겨주세요.
지금은 콘솔 환경이지만 웹, 모바일로 확장하다고 했을 때 이 값들은 재사용하지 못합니다.
특정 뷰에서만 쓰이는 값입니다.

2021-11-07 07:51 UTC, kang-hyungu commented on src/main/java/lotto/domain/LottoTicket.java
> +    private List<Integer> numbers;
로또 번호를 관리하는 도메인 객체를 추가해보면 어떨까요?

2021-11-07 07:51 UTC, kang-hyungu commented on src/main/java/lotto/domain/LottoTicket.java
> +        String[] split = removeAllSpaces(text).split(COMMA);
입력 받은 문자열을 그대로 전달하지 말고 뷰에서 split과 int로 변환해서 전달해줘도 되지 않을까요?
지금 구조면 콘솔이 아닌 다른 환경에서도 "1, 2, 3, 4, 5, 6" 같은 형태로 전달하거나 새로운 생성자를 추가해야겠네요.

2021-11-07 13:24 UTC, lights93 commented on src/main/java/lotto/domain/LottoResults.java
> +    private static final String NEW_LINE = "\n";
메시지 출력을 위한 부분을 view 클래스로 옮기게 된다면 LottoResults 클래스의 내부 노출은 불가피하다고 생각합니다.
LottoResults 내부의 List<LottoResult>를 view 클래스에서는 모르기 때문에 getter메서드가 필요하게 되는데요.
내부를 노출하게 되더라도 view 클래스에서 출력하는 것이 좋을까요??

현재 구조에서 toString()으로 출력되는 내용을 생성하는 것은 어떤가요??
toString()으로 하게되면 웹, 모바일로 확장한다고 했을 때 이 값들을 재사용하지 못해 좋지 않을까요??

1. toString()으로 LottoResults 클래스 내부에서 구현
2. LottoResults의 내부를 노출하더라도 view 클래스에서 구현

리뷰어님 생각은 어떤지 궁금합니다!
확인 부탁드립니다.

2021-11-07 14:26 UTC, lights93 commented on src/main/java/lotto/domain/EarningRate.java
> +public class EarningRate implements Printable {
문자열로 바꾸는 것을 클래스 외부(ex. view 클래스)에서 처리하려면 클래스 내부를 노출해야합니다.
내부를 노출하기 싫어서 프린트에 필요한 객체를 Printable 인터페이스를 구현하여 처리했었습니다.
하지만, 리뷰어님의 말씀처럼 프린트하는 부분을 도메인에서 만드는 것은 뷰에서 처리해야 하는 것이 맞는 것 같습니다.

피드백 반영하여 수정하도록 하겠습니다.

2021-11-07 14:28 UTC, lights93 commented on src/main/java/lotto/domain/LottoCount.java
> +    public LottoCount(long count) {
로또 카운트는 로또금액을 입력받아 계산합니다.
로또금액에서 0 이상의 금액만 받도록 했기 때문에 따로 구현하지는 않았었습니다.

그래도 로또카운트에도 validation이 있는 것이 좋을 것 같아 구현하도록 하겠습니다.
감사합니다.

2021-11-07 14:28 UTC, lights93 commented on src/main/java/lotto/domain/LottoMoney.java
> +    private static final String WON = "원";
넵 수정하겠습니다~
감사합니다.

2021-11-07 14:28 UTC, lights93 commented on src/main/java/lotto/domain/LottoMoney.java
> +    public LottoMoney(String moneyText) {
넵 수정하겠습니다~
감사합니다.

2021-11-07 14:29 UTC, lights93 commented on src/main/java/lotto/domain/LottoMoney.java
> +    public LottoMoney(long money) {
넵 수정하겠습니다~
감사합니다.

2021-11-07 14:29 UTC, lights93 commented on src/main/java/lotto/domain/LottoMoney.java
> +    public static EarningRate calculateEarningRate(List<LottoMoney> lottoMoneyList) {
넵 수정하겠습니다~
감사합니다.

2021-11-07 14:29 UTC, lights93 commented on src/main/java/lotto/domain/LottoTicket.java
> +    private List<Integer> numbers;
넵 확실히 있는 편이 더 좋다고 생각되네요.

반영하겠습니다.
감사합니다.

2021-11-07 14:32 UTC, lights93 commented on src/main/java/lotto/domain/LottoTicket.java
> +        String[] split = removeAllSpaces(text).split(COMMA);
현재 list로 받는 생성자도 있고, string으로 받는 생성자도 있습니다.
저는 뷰에서 validation을 하는 것이 맞지 않다고 생각하여 여기서 구현했었는데요.

기본적으로 잘못된 타입으로 들어오는 것에 대해서는 뷰에서 해도 괜찮을까요??
아니면 validatior 클래스를 생성하는 것은 어떨까요??

2021-11-10 09:49 UTC, kang-hyungu commented on src/main/java/lotto/domain/LottoResults.java
> +    private static final String NEW_LINE = "\n";
toString은 콘솔 뷰를 출력하는 용도가 아닙니다.
getter 메서드를 아예 쓰지 말라는게 아닙니다. 출력에 필요한 값을 반환할 때는 사용해야 합니다.

2021-11-10 09:55 UTC, kang-hyungu commented on src/main/java/lotto/domain/LottoTicket.java
> +        String[] split = removeAllSpaces(text).split(COMMA);
잘못된 타입 체크가 어떤걸 말씀하시는 걸까요?
string으로 받았을 때 숫자가 아닌 문자를 입력한 경우를 말씀하시는 건가요?
도메인에서 허용하는 타입만 받도록 만들고 입력에서 잘못된 타입은 예외를 발생하도록 만들어도 문제는 없어보이네요.

2021-11-14 08:12 UTC, kang-hyungu approved these changes
민호님 피드백 반영 잘 해주셨네요
pr은 머지 처리하겠습니다. 수고하셨어요

2021-11-14 08:12 UTC, kang-hyungu commented on src/main/java/lotto/LottoMachine.java
> +    private String removeAllSpaces(String numbers) {
이 메서드와 parseInt 메서드는 뷰에서 처리해야되지 않을까요?

2021-11-14 08:12 UTC, kang-hyungu commented on src/main/java/lotto/domain/LottoMoney.java
> +    private long parseToValidMoney(String moneyText) {
```suggestion
    private long parseToValidMoney(String money) {
```

문자열 타입이니 text 표시는 필요 없어보이네요.

2021-11-14 08:13 UTC, merged