Step5 - 로또(수동)
next-step/java-lotto-pro pull request #192
Opened 2021-11-07 06:36 UTC by ungseokchoi

## 안녕하세요. 1주차 로또-TDD 미션 참여자 최웅석입니다. 😊

> 5단계 학습 로또(수동) 미션 리뷰 요청 드립니다.

## ⚡ 미션 간략한 느낀점

> Enum 클래스의 필드를 포장해본게 처음이라 구현이 제대로 된건지? 모르겠네요😭

## ⭐  4단계 학습하며 궁금한 점
- 평소 현업에서도 일할때 항상 궁금했었는데 Exception 처리는 컨트롤러 단에서 하는게 좋은 방향인지
아니면 서비스 단에서 하는게 좋은 방향인지 궁금합니다.

##
**그리고 벌써 마지막 단계가 되었네요😲 
정말 짧은시간 동안 요한님의 세심한 리뷰 덕분에 많은것을 배웠습니다. 감사합니다.👍👍👍
항상 신경 써주신 코드 리뷰에 감사합니다. :) 👍**

2021-11-07 09:17 UTC, leeyohan93 requested changes
정말 벌써 마지막 단계이네요 ! 
끝까지 힘내주시는 모습이 보기 좋습니다 😄 
이번에도 몇가지 코멘트들을 남겨드렸으니 마지막까지 힘내주세요! 🔥

2021-11-07 09:17 UTC, leeyohan93 commented on src/main/java/lotto/controller/LottoMachineController.java
> +    private final OutputView outputView;
실무에 관한 코멘트를 더해보자면 저희는 실무에서 스프링 MVC에서 Controller를 많이 접하는데요.
스프링의 Controller는 View에 출력에 대한 책임을 가지지 않습니다.
해당 책임을 외부로 꺼내볼 수도 있을 것 같아요, 참고만 해주셔도 괜찮습니다 :)

Controller라는 네이밍을 사용하셨기에 한번 개선에 도전해볼만한 부분을 코멘트 드린것이니 참고만 해주셔도 괜찮습니다. :)

2021-11-07 09:17 UTC, leeyohan93 commented on src/main/java/lotto/controller/LottoMachineController.java
> +            System.out.println(lpae.getMessage());
> 평소 현업에서도 일할때 항상 궁금했었는데 Exception 처리는 컨트롤러 단에서 하는게 좋은 방향인지
아니면 서비스 단에서 하는게 좋은 방향인지 궁금합니다.

예외에 대한 최종적인 처리는 컨트롤러가 좋은 방향이라고 생각합니다 :)
아래 문서에서 `Using @ControllerAdvice Classes` 챕터가 좋은 예시가 될 수 있을 것 같아요 :) 
https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc


추가적으로 아래에 대한 사항들도 도움이 될 것 같아요 👍 
> [이펙티브자바 아이템 75. 예외의 상세 메시지에 실패 관련 정보를 담으라](https://github.com/bingbingpa/dev-book/blob/master/effective-java-3e/README.md#%EC%95%84%EC%9D%B4%ED%85%9C75-%EC%98%88%EC%99%B8%EC%9D%98-%EC%83%81%EC%84%B8-%EB%A9%94%EC%8B%9C%EC%A7%80%EC%97%90-%EC%8B%A4%ED%8C%A8-%EA%B4%80%EB%A0%A8-%EC%A0%95%EB%B3%B4%EB%A5%BC-%EB%8B%B4%EC%9C%BC%EB%9D%BC-1)
[이펙티브자바 아이템 77. 예외를 무시하지말라](https://github.com/bingbingpa/dev-book/blob/master/effective-java-3e/README.md#%EC%95%84%EC%9D%B4%ED%85%9C77-%EC%98%88%EC%99%B8%EB%A5%BC-%EB%AC%B4%EC%8B%9C%ED%95%98%EC%A7%80-%EB%A7%90%EB%9D%BC-1)

2021-11-07 09:17 UTC, leeyohan93 commented on src/main/java/lotto/domain/Money.java
>      }
BigDecimal 반영 👍 👍 

로또 금액보다 적은 금액일 시에 예외 처리하도록 구현해주셨는데,
로또 금액보다 적을때, 예외처리가 아닌 로또를 0장 구매하도록 해볼 수도 있지 않을까요 ? :)

Money 객체 입장에서 보면 로또 금액에 대한 검증을 하는 것은 어울리지 않는 책임일 수도 있지 않을까요 ?

2021-11-07 09:17 UTC, leeyohan93 commented on src/main/java/lotto/domain/LottoMachine.java
> +    public LottoMachine(Money money, List<List<Number>> activeNumberList) {
로또 번호를 의미하는 Number 또한 LottoMachine 외부에서 만들어지는 것보다는 내부에서 만들어지는 것이
더욱 적합해보이는 것 같습니다 :)

2021-11-07 09:17 UTC, leeyohan93 commented on src/main/java/lotto/domain/LottoMachine.java
>                  .forEach(f -> lottoNumbers.add(new LottoNumber()));
로또 번호를 생성하는 책임을 가진 LottoMachine 클래스가 있음에도 LottoNumber 내부에서 랜덤으로 로또를 생성하는 책임을 가지고 있는데요. 로또 생성에 대한 책임을 이전해온다면 LottoNumber는 랜덤에 의존하지 않는 테스트하기 더욱 좋은 코드가 되고 좀 더 적합한 책임만 남을 것 같은데 어떻게 생각하시나요 ?

2021-11-07 09:17 UTC, leeyohan93 commented on src/main/java/lotto/domain/LottoNumber.java
> +    public final static BigDecimal GAME_PRICE = BigDecimal.valueOf(1000);
가격에 대한 부분이니 Money를 이용해볼 수 도 있지 않을까요 ? :)

```suggestion
    public final static Money GAME_PRICE = new Money(BigDecimal.valueOf(1000));
```

2021-11-07 09:17 UTC, leeyohan93 commented on src/main/java/lotto/domain/LottoResult.java
>      }
여기도 BigDecimal 대신 Money를 사용해볼 수 있을 것 같아요
도메인 내부에서 모두 Money를 사용하도록 하고 출력 시에만 값을 꺼내주는건 어떨까요? :)

2021-11-07 09:17 UTC, leeyohan93 commented on src/main/java/lotto/domain/Rank.java
>      private final MatchStrategy expression;
제가 기대했던 Money 클래스의 사용은 이렇습니다!
WinningCondition은 현재 아무런 책임이 없기 때문에 오버엔지니어링 처럼 보이는 것 같아요 😢 

```suggestion
    NONE(2, new Money(BigDecimal.valueOf(0)), (count, match) -> count <= 2),
    FIVE(3, new Money(BigDecimal.valueOf(5_000)), (count, match) -> count == 3),
    FOUR(4, new Money(BigDecimal.valueOf(50_000)), (count, match) -> count == 4),
    THIRD(5, new Money(BigDecimal.valueOf(1_500_000)), (count, match) -> (count == 5 && !match)),
    SECOND(5, new Money(BigDecimal.valueOf(30_000_000)), (count, match) -> (count == 5 && match)),
    FIRST(6, new Money(BigDecimal.valueOf(2_000_000_000)), (count, match) -> count == 6);

    private final int matchCount;
    private final Money prizeMoney;
    private final MatchStrategy expression;
```

2021-11-07 09:17 UTC, leeyohan93 commented on src/main/java/lotto/domain/WinningLotto.java
> +        EnumMap<Rank, Integer> result = new EnumMap<Rank, Integer>(Rank.class);
사소하지만 구체적인 클래스보다는 추상적인 인터페이스에 의존해주시는 것이 좋습니다 ! :)

```suggestion
        Map<Rank, Integer> result = new EnumMap<>(Rank.class);
```

2021-11-07 09:17 UTC, leeyohan93 commented on src/main/java/lotto/exception/LottoActiveNumberException.java
> +public class LottoActiveNumberException extends IllegalArgumentException {
커스텀 익셉션을 활용해주셨네요 ! 💯

2021-11-07 09:17 UTC, leeyohan93 commented on src/main/java/lotto/domain/WinningLotto.java
>  public class WinningLotto {
WinningLotto 내부의 matchNumber도 LottoNumber클래스로 다루는 것이 좀 더 적합하지 않을까요 ? :)

2021-11-07 09:17 UTC, leeyohan93 commented on src/test/java/lotto/domain/LottoResultTest.java
> +    static Stream<Arguments> listProvide3() {
1, 2, 3과 같은 인덱스를 포함한 메서드는 어디에 사용되는 메서드일지 유추하기가 어렵습니다 
좀 더 의미있는 메서드 네이밍을 써주시면 어떨까요..! :)

2021-11-07 09:17 UTC, leeyohan93 commented on src/test/java/lotto/domain/RankTest.java
> +    }
ParameterizedTest를 활용해보는 건 어떨까요 ? :)

2021-11-07 13:37 UTC, ungseokchoi commented on src/main/java/lotto/domain/LottoMachine.java
> +    public LottoMachine(Money money, List<List<Number>> activeNumberList) {
저는 생성자에 매개변수의 자료형을 지정하는게 더 안전하다고 생각했는데
요한님의 피드백을 보니 각각의 호출부에서 변수에 대한 파싱 코드가 생겨 지저분해질거라고 예상도 됩니다. 😱 
내부에서 매개변수 의 다양한 자료형에 대한 paser를 제공해야하는게 더 좋은 방향인가요??

2021-11-07 13:42 UTC, leeyohan93 commented on src/main/java/lotto/domain/LottoMachine.java
> +    public LottoMachine(Money money, List<List<Number>> activeNumberList) {
제가 로또 번호를 의미하는 Number를 내부에서 만들어지는 것이 좋을 것 같다고 피드백 드린 이유는
이미 로또 한줄이나, 로또의 도메인 모델을 내부에서 만들기 때문인데요.

생성자를 제공할 때 다양한 자료형을 제공하는 여러 생성자를 만드는 것은 좋습니다. (포비 강의에서도 이야기해주셨죠)

2021-11-07 14:22 UTC, ungseokchoi commented on src/main/java/lotto/domain/Money.java
>      }
로또 한줄에 1000원인데 구입 금액을 1500원을 입력했을때 예외처리 입니다!!😄
그리고 피드백 주신 내용처럼 Money 클래스에게 로또 비즈니스 책임을 지지 않도록 변경했습니다

2021-11-07 14:34 UTC, ungseokchoi commented on src/main/java/lotto/domain/LottoMachine.java
>                  .forEach(f -> lottoNumbers.add(new LottoNumber()));
좋은 의견 감사합니다👍

2021-11-08 03:53 UTC, leeyohan93 approved these changes
안녕하세요 웅석님 😄 

마지막 단계 피드백 까지 잘 반영해주셨습니다 👍 
저도 리뷰와 답변을 드리는 과정에서 많이 배웠던 것 같습니다 😄 
마지막으로 아쉬워 몇가지 코멘트를 더 남겨두었으니 생각해보시면 좋을 것 같아요 :)

함께하는 이번 미션은 종료되었지만 이제 또 다른 시작이시니 
더욱 열심히 잘해내가실 것이라 생각이 듭니다 🔥  👍 

로또 미션 하시느라 정말 고생 많으셨습니다 🙏

2021-11-08 03:53 UTC, leeyohan93 commented on src/main/java/lotto/LottoApplication.java
> +        }
해당 부분에 대한 처리는 다음 미션들에서 진행하실 수도 있으니 그때 제가 드린 피드백이 도움이 되었으면 합니다 😄

2021-11-08 03:53 UTC, leeyohan93 commented on src/main/java/lotto/domain/LottoMachine.java
> +        return purchaseAmount.getMoney().divide(gamePrice.getMoney()).intValue();
Money 객체에서 데이터를 꺼내 계산하시는 부분은 Money 클래스를 객체가 아닌 데이터의 저장소로 바라보는 것입니다 😢 
디미터 법칙에 대해 알아보시면 좋을 것 같아요

https://johngrib.github.io/wiki/law-of-demeter/

```suggestion
        return purchaseAmount.divide(gamePrice);
```

2021-11-08 03:53 UTC, leeyohan93 commented on src/main/java/lotto/domain/LottoMachine.java
> +                .collect(Collectors.toList());
stream을 사용하지 않아도 될 것 같아요 :)
```suggestion
        return new ArrayList<>(generateAutoLotto(autoCount));
```

2021-11-08 03:53 UTC, leeyohan93 commented on src/test/java/lotto/domain/LottoMachineTest.java
> +    public void getLottoListTest2(List<Integer> lottoNumber) {
DisplayName을 사용하다보면 테스트 메서드 명은 대충 짓게 되는 것은 저 또한 그런데요 😢 
그래도 어느정도 의미 있는 메서드명을 써주시면 좋을 것 같아요

2021-11-08 03:53 UTC, leeyohan93 commented on src/main/java/lotto/domain/LottoMachine.java
> +                .map(m -> getLottoNumber(m))
메서드 참조를 사용해보면 어떨까요?
```suggestion
                .map(this::getLottoNumber)
```

2021-11-08 03:53 UTC, leeyohan93 commented on src/main/java/lotto/domain/LottoMachine.java
> +        return lottoNumber;
코드를 인라인해서 사용해보면 어떨까요 ?
```suggestion
        return getLottoNumber(new ArrayList<>(numbers));
```

2021-11-08 03:53 UTC, merged