Step4 - 로또(2등)
next-step/java-lotto-pro pull request #198
Opened 2021-11-07 09:00 UTC by Kelicia91

2021-11-07 12:24 UTC, minsungryu requested changes
지우님 4단계 미션 빠르게 잘 진행해주셨네요 👍 
일부 테스트 코드와 객체 설계 관련해서 약간의 코멘트를 남겼으니 확인 부탁드립니다!

2021-11-07 12:24 UTC, minsungryu commented on src/main/java/LottoNumber.java
> +		validate(trimmed);
String이 `null`일 위험도 있어서 검사해주시면 좋을 것 같습니다

2021-11-07 12:24 UTC, minsungryu commented on src/main/java/LottoWinningRank.java
> +	private final String extraMessage;
개인적으로 보너스 관련 속성이 아니라 메시지로 관리되다보니 클래스가 어색하게 느껴지는 부분이 있는 것 같습니다.
`if (...)`와 같은 로직이 추가될 수 있겠지만 보너스 일치 여부를 속성으로 관리하고 메시지는 View단(또는 관련된 코드)에서 제어해보는 것도 괜찮을 것 같습니다(?)

2021-11-07 12:24 UTC, minsungryu commented on src/test/java/LottoWinningRankTest.java
> +	}
보너스 매치 여부도 `@ParameterizedTest`로 통합해보는 것은 어떨까요?
`"5:true:SECOND", "5:false:THIRD"`로 가능하지 않을까 싶습니다 ㅎㅎ

2021-11-07 12:24 UTC, minsungryu commented on src/main/java/WinningLottoBuilder.java
> +public final class WinningLottoBuilder {
빌더 클래스를 직접 구현해주셨네요 👍 
제 개인적인 생각이지만 멤버 변수의 수가 적을 때는 Builder 클래스를 만드는 공수가 더 크지 않을까(?) 걱정되는 부분도 있습니다.
물론 실무에서는 `@Lombok`이 어느정도 귀찮은 부분을 해결해주긴 하지만요..

또한 `WinningLotto`에서 `bonusNumer`에 대한 `null check`가 없다보니
불완전한 객체 생성이 될 여지도 있는 것 같습니다.

`WinningLotto` 생성자에서 `null check`도 필요해보이고, 간단하게 정적 팩토리 메서드를 제공해보시는 건 어떨까 의견 드려봅니다.
물론 제 의견이 100% 정답은 아니기 때문에 고민해보시고 결정하시면 될 것 같습니다 :)

2021-11-07 12:24 UTC, minsungryu commented on src/test/java/WinningLottoTest.java
>  		assertThat(winningLotto.countMatching(Lotto.from(lotto))).isEqualTo(numOfMatching);
보너스 번호 일치 여부에 대한 검증도 있으면 더 좋을 것 같습니다 😄

2021-11-07 12:24 UTC, minsungryu commented on src/test/java/LottoWinningStatisticsTest.java
>  	@Test
개인적인 생각이지만 계산식을 검증하는 테스트에 로직이 있다면 자기 자신의 복사된 코드를 검증하는 모양(?)이 되어서 의도를 파악하기 어려운 면이 있는 것 같습니다.
expect 부분에 정확한 숫자를 대입해서 로직보다는 기대값을(의도를) 표현하는건 어떨까 생각해봤습니다 :)

2021-11-07 12:24 UTC, minsungryu commented on src/test/java/LottoWinningStatisticsTest.java
> +		assertThat(statistics.countLottos(rank)).isEqualTo(1L);
등수마다 테스트를 만드는 것을 주로 봐왔는데 이렇게도 검증해볼 수도 있겠군요~

테스트를 보다가 소소한 의견이 있어서 코멘트 드려봅니다.
테스트 메서드에 단언문이 하나만 있다보니 어떤 문맥인지 이해하기 살짝 어렵게 느껴졌는데요
(다행히 테스트 코드가 적어서 바로 위를 보면 되긴 하지만요)

최근에 아래 포스트를 읽고 공감이 많이 되었는데 한 번 보시고 고민해보시는 것도 좋을 것 같아서 공유드려요.
https://jojoldu.tistory.com/611?category=1011740

2021-11-07 12:24 UTC, minsungryu commented on src/main/java/Lotto.java
>  	private static List<LottoNumber> generate() {
리뷰 타이밍이 조금 이상하지만(?) 지나친 부분이 있는 것 같아서 남겨봅니다 😭 

개인적으로 `Lotto` 클래스는 데이터 클래스 역할을 한다고 보는데요
객체 내부에서 생성 로직을 가지고 있다보니 책임 범위가 넓은 것 같다는 생각이 들었습니다.
기회가 된다면 `LottoFactory`와 같은 별도 팩토리를 만들어서 데이터와 생성 로직을 분리해볼 수 있지 않을까요?

2021-11-08 09:17 UTC, Kelicia91 commented on src/main/java/LottoNumber.java
> +		validate(trimmed);
웁스 `null` 체크를 여기저기 빼먹엇네요 😵  수정햇어요~

2021-11-08 09:18 UTC, Kelicia91 commented on src/main/java/LottoWinningRank.java
> +	private final String extraMessage;
view에서 처리되게끔 수정햇고 더 깔끔하네요 :-)

2021-11-08 09:19 UTC, Kelicia91 commented on src/test/java/LottoWinningRankTest.java
> +	}
통합햇고 `assert` 하나로 해결됏네요 😃

2021-11-08 09:26 UTC, Kelicia91 commented on src/main/java/WinningLottoBuilder.java
> +public final class WinningLottoBuilder {
1. `WinningLotto` 에서 누락된 `null` 체크 추가햇어요!
2. 원래는 builder 없이 정적 팩토리 메소드로 구현했었는데요. 하다보니 `from(String bonus, String lotto)` 로 구현햇던 부분을 `from(String lotto, String bonus)`로 바꾸고 싶더라구요.(bonus가 나중에 추가된 요소라 순서변경 의도) 그런데 인자순서를 바꾸면서 호출하는 쪽도 수정해줘야 하는데 컴파일 에러 없이 하나씩 찾아야한다는 사실에 builder 를 추가하게 되더라구요;

2021-11-08 09:27 UTC, Kelicia91 commented on src/test/java/WinningLottoTest.java
>  		assertThat(winningLotto.countMatching(Lotto.from(lotto))).isEqualTo(numOfMatching);
아 그거슨 `Lotto.hasBonus(WinningLotto winningLotto)` 테스트에 잇습니다요~

2021-11-08 09:30 UTC, Kelicia91 commented on src/test/java/LottoWinningStatisticsTest.java
>  	@Test
아 요거 저도 약간 부자연스러운 느낌적느낌이 잇엇는데, 저만 그런게 아니엇군요! 기대값을 상수로 처리하니 깔끔해졋네요 👍

2021-11-08 09:34 UTC, Kelicia91 commented on src/test/java/LottoWinningStatisticsTest.java
> +		assertThat(statistics.countLottos(rank)).isEqualTo(1L);
테스트 픽스처에 대한 글 공유 감사합니다 🙇‍♀️ 
읽어보니 아래 문장이 가장 와닿앗네요
> 절대 테스트 메소드를 이해하기 위해 다른 부분을 찾아보게 만들어선 안된다.
테스트 하나하나가 독립적으로 수행될 수 잇게끔 `private final` 멤버변수들 삭제하고 
각 테스트별 의도에 맞게 변수 설정이 되도록 수정햇어요. 감사합니다 👍

2021-11-08 09:36 UTC, Kelicia91 commented on src/main/java/Lotto.java
>  	private static List<LottoNumber> generate() {
`LottoFactory`로 분리해보앗는데 훨씬 깔끔해지네요! 😃

2021-11-08 11:19 UTC, minsungryu approved these changes
지우님 4단계 구현하시느라 고생많으셨습니다!
추가로 피드백 드릴게 없네요 👍 
다음 단계도 화이팅입니다.

2021-11-08 11:21 UTC, minsungryu commented on src/main/java/WinningLottoBuilder.java
> +public final class WinningLottoBuilder {
아하 그러셨군요.
참고로 인텔리제이에서 `Refactor -> Change signature` 기능이 있는데 
요놈이 그런 일을 대신해줘서 편리합니다!

2021-11-08 11:21 UTC, merged