Step4 : 로또(2등)
next-step/java-lotto-pro pull request #217
Opened 2021-11-08 05:51 UTC by moonjuhyeon

요한님 안녕하세요.
지난번 주셨던 코멘트 너무 감사합니다.
이번 4단계는 주셨던 코멘트 내용 복기하며 리팩토링하는 것에 시간을  많이 소요 했던 것 같습니다.
이번 4단계도 따끔한 코멘트 부탁드리며, 리뷰요청 드립니다.

감사합니다.

2021-11-08 15:00 UTC, leeyohan93 requested changes
로또 4단계 미션도 잘 진행해 주셨네요 👍 
이전 단계보다 많이 개선된 부분에서 노력의 흔적이 보입니다 ! 💯 
이번 에도 몇가지 코멘트들을 남겼으니 확인 부탁드릴게요 :)

2021-11-08 15:00 UTC, leeyohan93 commented on src/main/java/lotto/README.md
> +### STEP 4
구현해주신 도메인 모델에 비해 요구사항 정리는 조금 아쉬운 부분이 있는 것 같아요 :)
개인적으로는 요구사항 정리가 명확하게 잘 될 때 좀 더 좋은 설게가 나올 수 있다고 생각합니다 😄

2021-11-08 15:00 UTC, leeyohan93 commented on src/main/java/lotto/model/LottoGenerator.java
> +	private List<String> inputNumberList;
https://github.com/next-step/java-lotto-pro/pull/144#discussion_r743704612
저번에 드렸던 코멘트에 대해 어떻게 생각하시나요 ? :)

2021-11-08 15:00 UTC, leeyohan93 commented on src/main/java/lotto/model/Lottos.java
> +	}
Lottos 클래스가 LottoGenerator 클래스를 알아야(의존해야)할까요 ? 
LottoGenerator라는 로또의 생성의 책임을 가지는 클래스로 분리하였는데, 다시 내부에 들어오게 된 것 같아요.
그렇게 생각하는 이유는 해당 생성자를 사용하는 테스트는 랜덤에 의존하고 있기 때문에 테스트하기 어려운 코드입니다.
Lottos에서 랜덤에 대한 의존성(LottoGenerator 에 대한 의존성)을 제거해보는 건 어떨까요? 🤔

2021-11-08 15:00 UTC, leeyohan93 commented on src/main/java/lotto/model/LottoNumbers.java
>  	private List<LottoNumber> generateLottoNumberList(String inputNumber) {
https://github.com/next-step/java-lotto-pro/pull/144#discussion_r743731840
위 피드백에서 이야기드린 부분을 반영해보는 건 어떨까요?

2021-11-08 15:00 UTC, leeyohan93 commented on src/main/java/lotto/model/LottoGenerator.java
>  	}
금액을 나누는 부분은 이전에 만들었던 Money 클래스에서 하는것이 더욱 적합해보이기도 하는데 어떻게 생각하시나요 :)

2021-11-08 15:00 UTC, leeyohan93 commented on src/main/java/lotto/model/LottoGenerator.java
>  	public static final int LOTTO_PRICE = 1000;
```suggestion
	public static final Money LOTTO_PRICE = new Money(1000);
```

금액을 의미하는 LOTTO_PRICE 상수도 Money 클래스를 사용해볼 수 있을 것 같아요 !

2021-11-08 15:00 UTC, leeyohan93 commented on src/main/java/lotto/model/LottoRank.java
> +		Map<LottoRank, Integer> rankCodeMap = new HashMap<>();
```suggestion
		Map<LottoRank, Integer> rankCodeMap = new EnumMap<>(LottoRank.class);
```

EnumMap을 사용하면 성능을 더욱 향상시킬 수 있습니다 :)

2021-11-08 15:00 UTC, leeyohan93 commented on src/main/java/lotto/model/LottoResult.java
> +	public Map<LottoRank, Integer> getRankCodeMapUsingContainsMap() {
개인적으로 생성자를 제외한 테스트를 위한 로직, 메서드는 지양해야한다고 생각합니다 :)

외부에 제공되는 public 메서드는 항상 신중하게 만들어져야하며 테스트를 위한 메서드의 추가는 해당 클래스에 대한 사용성과 가독성을 떨어뜨린다고 생각해요. 주현님 의견은 어떠신가요?

2021-11-08 15:00 UTC, leeyohan93 commented on src/main/java/lotto/model/LottoResult.java
> +	public int containsWinningLottoNumbers(WinningLottoNumbers winningLottoNumbers, LottoNumbers lottoNumbers) {
클래스 내부에서 사용되는 메서드들의 접근제어자는 private으로 변경해주세요 :)

2021-11-08 15:00 UTC, leeyohan93 commented on src/main/java/lotto/model/LottoRank.java
> +	}
```suggestion
	FIRST(6, 0, new Money(2_000_000_000),
	SECOND(5, 1, new Money(30_000_000),
	THIRD(5, 0, new Money(1_500_000),
	FORTH(4, 0, new Money(50_000),
	FIFTH(3, 0, new Money(5_000),
	NOTHING(0, 0, new Money(0);

	private int containsCount;
	private int bonusCount;
	private Money money;

	LottoRank(int containsCount, int bonusCount, Money money) {
		this.containsCount = containsCount;
		this.bonusCount = bonusCount;
		this.money = money;
	}
```

Money 클래스를 도출하셨으니 다음과 같이 원시 값을 포장해보는건 어떨까요?

2021-11-08 15:00 UTC, leeyohan93 commented on src/main/java/lotto/model/LottoResult.java
> +	public double calculateYield() {
수익률을 계산하거나, 금액을 계산하는 로직은 Money 클래스가 담당하도록 해보는건 어떨까요? 😄 
현재의 Money 클래스는 어떤 책임도 할당 받지 못하고 그저 데이터를 담고있는 클래스가 되어있는 상태인 것 같아요.

클래스를 작게 분리하는 것은 중요하지만, 적절한 책임에의해 만들어져야합니다.

2021-11-09 04:31 UTC, moonjuhyeon commented on src/main/java/lotto/README.md
> +### STEP 4
확인했습니다! 더 자세히 적어보도록 하겠습니다 😭

2021-11-09 04:31 UTC, moonjuhyeon commented on src/main/java/lotto/model/LottoGenerator.java
> +	private List<String> inputNumberList;
넵.. 생성자에 로직을 사용하지 않도록 전체적인 리팩토링 진행했습니다 👍

2021-11-09 04:32 UTC, moonjuhyeon commented on src/main/java/lotto/model/Lottos.java
> +	}
좋은 코멘트 감사합니다. 👍

2021-11-09 04:33 UTC, moonjuhyeon commented on src/main/java/lotto/model/LottoGenerator.java
>  	}
Money 클래스에게 돈에 대한 더 많은 책임을 부여하는 것이 맞다고 생각합니다 👍 👍 👍

2021-11-09 04:33 UTC, moonjuhyeon commented on src/main/java/lotto/model/LottoGenerator.java
>  	public static final int LOTTO_PRICE = 1000;
반영했습니다 👍

2021-11-09 04:33 UTC, moonjuhyeon commented on src/main/java/lotto/model/LottoRank.java
> +		Map<LottoRank, Integer> rankCodeMap = new HashMap<>();
꿀팁 감사합니다 ! 반영했습니다. 👍 _

2021-11-09 04:34 UTC, moonjuhyeon commented on src/main/java/lotto/model/LottoResult.java
> +	public Map<LottoRank, Integer> getRankCodeMapUsingContainsMap() {
요한님 말씀에 동의합니다.
테스트를 하기 위한 public 메소드를 private 메소드로 리팩토링 하였습니다.

2021-11-09 04:34 UTC, moonjuhyeon commented on src/main/java/lotto/model/LottoRank.java
> +	}
👍 👍

2021-11-09 04:35 UTC, moonjuhyeon commented on src/main/java/lotto/model/LottoResult.java
> +	public double calculateYield() {
제 나름대로 Money에 책임을 주기 위하여 리팩토링 해보았는데, 요한님께서 한번 확인해 주시면 감사하겠습니다 👍!

2021-11-09 14:01 UTC, leeyohan93 approved these changes
피드백 잘 반영해주셨습니다 👍 
다음 단계 진행을 위해서 머지하도록 할게요 😄 
이제 로또도 마지막 단계네요! 
끝까지 화이팅입니다 🔥

2021-11-09 14:01 UTC, leeyohan93 commented on src/main/java/lotto/model/LottoGenerator.java
> +	private final List<String> inputNumberList;
https://github.com/next-step/java-lotto-pro/pull/217#discussion_r744775075

제가 코멘트에 대한 설명이 모자랐던 것 같네요 😢 
코멘트에 대한 의도는 LottoGenerator의 멤버 변수인 Money와 List<String>을 제거해보자는 이야기였습니다 :)

2021-11-09 14:01 UTC, leeyohan93 commented on src/main/java/lotto/model/LottoNumbers.java
> +				LottoNumber.from(RandomUtil.pickNumber(LottoNumber.MIN_LOTTO_NUMBER, LottoNumber.MAX_LOTTO_NUMBER)));
랜덤에 대한 의존성이 LottoNumbers 객체 내부에 있는데요.
랜덤은 테스트 하기 어려운 로직이고, 결과적으로는 LottoNumbers 클래스를 테스트하기 어렵게 만듭니다.
외부로 분리해보는 건 어떨까요?

2021-11-09 14:01 UTC, leeyohan93 commented on src/main/java/lotto/model/Money.java
> +	private final int money;
소소한 코멘트를 드려보면 실무에서는 Money 클래스를 사용할 때 
정밀한 사용을 위한 BigDecimal을 사용합니다
참고만 해주세요 :)

https://jsonobject.tistory.com/466

2021-11-09 14:01 UTC, merged