Step5 로또(수동) :)
next-step/java-lotto-pro pull request #239
Opened 2021-11-08 17:04 UTC by koola97620

어느덧 마지막 step5 를 pr 날리는 날이 왔네요 :)
이번에는 기능구현하다 놓친 부분을 우연히 발견하기도 하고ㅎㅎ 
지금까지도 유익했지만 테스트 코드의 중요성을 체감할 수 있는 더 유익한 step 이었어요 ㅎㅎ 
피드백 감사합니다!!

2021-11-09 13:25 UTC, jhhj424 requested changes
안녕하세요 재용님~ 🙇🏻‍♂️
TDD 로또 마지막 미션 구현 잘 해주셨습니다~
미션 진행하면서 점점 더 많이 고민하시면서 구현하신게 느껴지네요 👍
이대로 끝내기 조금 아쉬워서 마지막 코멘트 조금 남겼는데 확인부탁드릴게요 :)
고민해보시고 다시 리뷰 요청 주세요~ 화이팅입니다 👊

2021-11-09 13:25 UTC, jhhj424 commented on src/main/java/lotto/controller/LottoGameController.java
> +        LottoGame lottoGame = LottoStore.sell(manualNumbersStrings,money);
사소하지만 컨벤션 관련해서 습관적으로 체크해주시는것도 도움이 될 것 같습니다 👍 
인텔리제이 + mac 을 사용하신다면 option + command + L 로 전체 소스코드를 정리할 수 있습니다 ~

```suggestion
        LottoGame lottoGame = LottoStore.sell(manualNumbersStrings, money);
```

2021-11-09 13:25 UTC, jhhj424 commented on src/main/java/lotto/domain/LottoBallFactory.java
> +        return Collections.unmodifiableList(ballsDraw);
👍

2021-11-09 13:25 UTC, jhhj424 commented on src/main/java/lotto/domain/LottoBalls.java
>      private String[] splitNumberString(String numbersString) {
저번에 저도 그냥 넘어간 것 같은데 죄송합니다 🙏

splitNumberString 이 LottoBalls 의 책임 및 역할이 맞는지 생각이 조금 드네요 :)

2021-11-09 13:25 UTC, jhhj424 commented on src/main/java/lotto/domain/LottoStore.java
> +        return manualLottoBalls;
해당 `createManualLottoBalls` 메서드의 로직을 stream 을 활용한다면

```java
return manualNumbersStrings.stream()
                .map(LottoBalls::new)
                .collect(Collectors.toList());
```
이렇게도 작성해볼 수 있겠네요~

`Collections.unmodifiableList` 로 감싸주셔도 됩니당 👍

2021-11-09 13:25 UTC, jhhj424 commented on src/main/java/lotto/domain/LottoStore.java
> +                Stream.concat(manualLottoBalls.stream(), autoLottoBalls.stream()).collect(Collectors.toList())
stream 과 같은 체이닝 메서드를 활용할 때 

객체지향 생활 체조 원칙
규칙 4: 한 줄에 점을 하나만 찍는다.
을 생각해보셔도 좋을 것 같아요 !
가독성 측면입니다~

2021-11-09 13:25 UTC, jhhj424 commented on src/main/java/lotto/view/ResultView.java
> +        builder.append(TRY_COUNT_MANUAL_MESSAGE).append(lottoGame.getManualTryCount()).append(TRY_COUNT_MIDDLE_MESSAGE);
이런 builder 의 경우도
규칙 4: 한 줄에 점을 하나만 찍는다.
을 생각해볼 수 있겠네요~

2021-11-09 13:25 UTC, jhhj424 commented on src/test/java/lotto/domain/LottoBallsTest.java
> +                .withMessageContaining("로또 공 개수가 6개가 아닙니다.");
exception 의 의미가 조금 다른 것 같습니다 ~


서로 다른 6개의 숫자로만 로또볼 생성이 가능하다 <> 로또 공 개수가 6개가 아닙니다.

2021-11-09 13:27 UTC, jhhj424 commented
ㅎㅎ 적당히 리팩터링 할 부분이 있는지 마지막으로 체크 해주세요~!
이정도면 됐다! 라고 생각이 드시면 언제든 다시 리뷰 요청 부탁 드립니다 🙏

2021-11-09 16:18 UTC, koola97620 commented on src/main/java/lotto/domain/LottoBalls.java
>      private String[] splitNumberString(String numbersString) {
괜찮습니다 ㅎㅎ :)
LottoBalls 의 생성자를 여러개 만들어도 괜찮겠다는 생각이 들어서 지금과 같은 방식으로 코딩을 시도 했어요!

그런데 말씀 듣고보니 splitNumberString 이 LottoBalls 에 있는게 어색해 보이긴 하네요.
LottoBalls 는 LottoBall 의 일급컬렉션인데 List<LottoBall> 을 직접 생성할 책임을 가질 필요는 없어보여요!
 그래서 생성로직을 LottoBallFactory 클래스로 이동시켜봤습니다!

2021-11-09 16:22 UTC, koola97620 commented on src/main/java/lotto/controller/LottoGameController.java
> +        LottoGame lottoGame = LottoStore.sell(manualNumbersStrings,money);
감사합니다!

2021-11-09 16:25 UTC, koola97620 commented on src/main/java/lotto/domain/LottoStore.java
> +        return manualLottoBalls;
감사합니다!! ㅎㅎ

2021-11-10 14:42 UTC, jhhj424 approved these changes
안녕하세요 재용님~ 🙇🏻‍♂️
마지막 미션 피드백까지 완벽하게 반영해주셨네요 :)
일주일간 정말 고생하셨습니다 👍 
미션을 리뷰 하면서 적극적으로 해주셔서 저도 열심히 했던 것 같습니다 ~!
저랑 함께하는 미션은 끝이났지만 언제든 고민거리 있으면 DM 주셔도 됩니다 😁
앞으로의 미션도 화이팅입니다 👊

2021-11-10 14:42 UTC, jhhj424 commented on src/main/java/lotto/domain/LottoBallFactory.java
> +        return lottoBallList;
해당 메서드도 이번 미션에서 사용했었던 stream 구문으로 한번에 작성할 수 있겠네요 :)

2021-11-10 14:42 UTC, jhhj424 commented on src/main/java/lotto/exception/DuplicateNumberException.java
> +public class DuplicateNumberException extends RuntimeException {
👍

2021-11-10 14:42 UTC, merged