4단계 - 로또(2등)
next-step/java-lotto-pro pull request #254
Opened 2021-11-09 15:04 UTC by minseokLim

1. 3단계 마지막 PR 코멘트에서 '해피 케이스 외에도 유효성 체크, 예외가 발생하는 경우'에 대한 테스트를 추가해달라고 하셨는데, 저는 아무리 찾아도 더는 추가할 게 없어보입니다^^;;; 기본적으로 유효성 검사를 모두 객체 생성 시 진행하고 있기 때문에, 객체 생성시 유효성 검사를 하는 테스트 케이스는 추가되어있습니다. 억지로 예외 케이스를 만들어보려고 해도 그 객체에 주입하는 객체에서 이미 유효성 검사를 진행하고 있기 때문에 의미가 없다고 생각했습니다. 예를 들면, LottoNumbers 클래스 안에 1~45 이외에 숫자가 들어가는 경우를 테스트 하려고 하지만 이미 그 클래스에 주입하는 Number 클래스에서 해당 유효성 검사를 진행하고 있고 NumberTest에서 이를 진행하고 있습니다. 혹시 제가 빠뜨린 부분이 어떤 게 있을지 한 가지만 예를 들어주신다면 감사하겠습니다. 메서드에도 추가할 부분을 저는 찾을 수가 없습니다ㅠㅠ 혹시 모든 매개변수에서 Objects.requireNonNull()를 해야하는 걸까요?;;
2. DM으로 여쭤봤던 부분에서 MatchResult 클래스의 rateOfReturn필드는 포장을 진행하였습니다. rankToCount 필드의 경우, 객체 외부로 노출될 필요가 없어서 진행하지 않았습니다.

잘 부탁드립니다! :)

2021-11-10 11:54 UTC, kang-hyungu requested changes
민석님 몇 가지 피드백 남겼습니다.
수정해보시고 리뷰 재요청 주세요.
궁금한 점 생기면 dm 주시거나 코멘트 남겨주세요

2021-11-10 11:54 UTC, kang-hyungu commented on src/main/java/lotto/LottoGame.java
>          Collection<LottoNumbers> lottoNumbersCollection =
```suggestion
        Collection<LottoNumbers> lottoNumbers =
```
변수명에 컬렉션을 써줘야 하는 이유가 있나요?

2021-11-10 11:54 UTC, kang-hyungu commented on src/main/java/lotto/model/LottoMatcher.java
> +    public LottoMatcher(Number bonusNumber, LottoNumbers winningNumbers) {
파라미터는 null 허용인가요?
테스트 코드도 같이 추가해보아요

2021-11-10 11:54 UTC, kang-hyungu commented on src/main/java/lotto/model/LottoMatcher.java
> +            ranks.add(Rank.valueOf(countOfMatch, matchBonus));
LottoNumbers에게 랭크를 구해달라고 메시지를 보내보면 어떨까요?

```java
// 적절한 메서드명을 정해보아요
Rank rank = lottoNumbers.rank(winningNumbers, bonusNumber);
ranks.add(rank);
```

2021-11-10 11:54 UTC, kang-hyungu commented on src/main/java/lotto/model/LottoNumberGenerator.java
>      public Collection<LottoNumbers> generateLottoNumbersCollection() {
```suggestion
    public Collection<LottoNumbers> generate() {
```

클래스명에도 이미 로또 번호라는 이름이 있으니 어떤 메서드인지만 잘 표현해도 충분하겠네요
메서드 이름은 간결한게 좋습니다.
다른 사람이 작성한 코드를 읽을 때 긴 단어, 문장보다 짤막하지만 뜻이 분명한 문장, 단어가 잘 읽히는 것을 비교해보아요

2021-11-10 11:54 UTC, kang-hyungu commented on src/main/java/lotto/model/LottoNumbers.java
> +    public int getCountOfMatch(LottoNumbers winningNumbers) {
LottoMatcher에 남긴 코멘트를 적용하면 이 메서드를 제거할 수 있겠네요.
코드를 간결하게 만들어보아요

2021-11-10 11:54 UTC, kang-hyungu commented on src/main/java/lotto/model/LottoNumbers.java
> +        return (int)others.stream().filter(this.numbers::contains).count();
stream 한 줄 쓰기 금지입니다.
코드 읽기 힘들게 만듭니다.

```java
        return (int) others.stream()
                .filter(this.numbers::contains)
                .count();
```

2021-11-10 11:54 UTC, kang-hyungu commented on src/main/java/lotto/model/Payment.java
>          return payment / LOTTO_PRICE;
메서드명을 countLotto()로 하면 get을 안써도 되니 더 간결해지겠네요

2021-11-10 11:54 UTC, kang-hyungu commented on src/main/java/lotto/model/Payment.java
> +    public RateOfReturn getRateOfReturn(int prizeMoney) {
get이라는 메서드명이 적절한가요?

2021-11-10 11:54 UTC, kang-hyungu commented on src/main/java/lotto/view/InputView.java
>  public class InputView {
InputView를 테스트 할 방법은 없을까요?
InputView의 메서드들을 살펴보니 분기문이 간혹 보이네요.
InputView는 따로 테스트할 필요는 없을까요? 어떻게 보시나요?

2021-11-10 11:54 UTC, kang-hyungu commented on src/test/java/lotto/model/LottoMatcherTest.java
> +        assertThat(new LottoMatcher(7, 1, 2, 3, 4, 5, 6).match(
테스트 코드도 유지보수 대상입니다.
읽기 좋게 작성해주세요.

```java
    void match() {
        // given
        final List<LottoNumbers> lottoNumbers = Arrays.asList(
                new LottoNumbers(1, 2, 3, 7, 8, 9),
                new LottoNumbers(1, 2, 3, 4, 5, 11),
                new LottoNumbers(1, 2, 3, 4, 5, 6),
                new LottoNumbers(1, 2, 3, 4, 5, 7),
                new LottoNumbers(1, 2, 9, 10, 11, 12)
        );

        // when
        final MatchResult actual = new LottoMatcher(7, 1, 2, 3, 4, 5, 6).match(PAYMENT, lottoNumbers);

        // then
        assertThat(actual).isEqualTo(new MatchResult(PAYMENT, Rank.FIFTH, Rank.THIRD, Rank.FIRST, Rank.SECOND, Rank.MISS));
    }
```

2021-11-10 11:54 UTC, kang-hyungu commented on src/test/java/lotto/model/LottoNumbersTest.java
> +    void getCountOfMatch(int[] numbers, int countOfMatch) {
이건 무슨 테스트일까요?
다른 테스트처럼 설명을 추가해서 일관성을 유지해주세요

2021-11-10 11:54 UTC, kang-hyungu commented on src/test/java/lotto/model/MatchResultTest.java
>  public class MatchResultTest {
1. MatchResult 생성자 테스트를 추가해보아요
2. null 예외도 추가해보아요

2021-11-10 11:54 UTC, kang-hyungu commented on src/test/java/lotto/model/NumberTest.java
> +        assertThat(Number.valueOf(1)).isEqualTo(Number.valueOf(1));
아래 코드도 문제 없는지 테스트 추가해보아요

```java
Number.valueOf(1) == Number.valueOf(1)
```

2021-11-10 11:54 UTC, kang-hyungu commented on src/test/java/lotto/model/NumberTest.java
> +            Number.valueOf(input)
```suggestion
            Number.of(input)
```

2021-11-10 11:54 UTC, kang-hyungu commented on src/test/java/lotto/model/LottoMatcherTest.java
> +        assertThat(new LottoMatcher(7, 1, 2, 3, 4, 5, 6).match(
다른 테스트 코드도 같이 정리해주세요.
assertThat 한줄에 다 작성하면 코드 파악이 어려워집니다.

2021-11-10 12:22 UTC, minseokLim commented on src/main/java/lotto/LottoGame.java
>          Collection<LottoNumbers> lottoNumbersCollection =
lottoNumbers를 여러 개 모아놓은 것이라 저렇게 표현했습니다. lottoNumberss 처럼 ss를 2개 붙힐 수도 없고 그렇다고 lottoNumbers라고만 쓰면 LottoNumbers 객체 한 개만 있는 것과 구분이 되지 않을 것 같습니다.

2021-11-10 15:19 UTC, minseokLim commented on src/main/java/lotto/view/InputView.java
>  public class InputView {
유효성 검사가 InputView에 일부 포함되어있기 때문에 테스트가 필요하겠네요. 그런데, InputView에 있는 유효성 검사까지 도메인 객체 내부로 옮기는 게 올바를까요, 아니면 InputView에 대한 테스트를 추가하는 게 더 올바른 방법일까요? 일단 InputView에 대한 테스트 코드를 추가해보도록 하겠습니다.

2021-11-11 10:46 UTC, kang-hyungu commented on src/main/java/lotto/LottoGame.java
>          Collection<LottoNumbers> lottoNumbersCollection =
lottoNumbers 라는 클래스이름을 바꿔볼 수 있지 않을까요?
의미 있는 클래스명 없을까요? 로또번호 묶음을 뭐라 부를 수 있을까요?

2021-11-11 10:48 UTC, kang-hyungu commented on src/main/java/lotto/view/InputView.java
>  public class InputView {
입력에서 담당해야 될 유효성 검사가 있고 도메인에서 체크해야될 부분을 분리하시면 됩니다.

2021-11-11 10:58 UTC, kang-hyungu approved these changes
민석님 피드백 반영 잘해주셨네요
코드도 전체적으로 많이 깔끔해졌습니다.
pr은 머지 처리하겠습니다. 다음 미션 진행해주세요

2021-11-11 10:58 UTC, kang-hyungu commented on src/main/java/lotto/model/LottoMatcher.java
> +        Objects.requireNonNull(bonusNumber);
```suggestion
        this.bonusNumber = Objects.requireNonNull(bonusNumber);
        this.winningNumbers = Objects.requireNonNull(winningNumbers);
```

이렇게 줄여쓰는 방법도 있겠네요

2021-11-11 10:58 UTC, kang-hyungu commented on src/test/java/lotto/view/InputViewTest.java
> +        System.setIn(new ByteArrayInputStream(inputBytes));
setIn 이라는 메서드도 있군요.
Reader 처럼 테스트하기 힘든 객체들은 mock을 활용하는 방법도 있습니다.

2021-11-11 10:58 UTC, kang-hyungu commented on src/test/java/lotto/view/InputViewTest.java
> +        InputView.bufferedReader = new BufferedReader(new InputStreamReader(System.in));
인스턴스 변수를 강제로 갈아끼우지 말고 아래와 같이 생성자를 추가해서 테스트 객체를 주입해줄수도 있겠네요.
mockito를 사용하실수도 있겠지만 이런 방법이 있구나 정도로 이번 코멘트는 패스하셔도 좋습니다.

```java
// InputView
public InputView(BufferedReader bufferedReader) {
    this.bufferedReader = bufferedReader;
}

// InputViewTest
// MockReader는 임의로 지은 이름입니다.
// 이런식으로 외부에서 테스트 가능한 객체로 전달해줄 수도 있습니다.
new InputView(new MockReader());
```

2021-11-11 10:58 UTC, merged

2021-11-11 13:38 UTC, minseokLim commented on src/main/java/lotto/LottoGame.java
>          Collection<LottoNumbers> lottoNumbersCollection =
로또가 번호 6개를 갖고 있는거니까 차라리 LottoNumbers를 Lotto라고 변경하고 위에값을 lottos라고 바꾸면 해결될 것 같다는 생각이 드네요^^;