Step 5 : 로또 (수동)
next-step/java-lotto-pro pull request #264
Opened 2021-11-10 08:05 UTC by moonjuhyeon

안녕하세요 요한님 😄 
어느덧 1주차 마지막 5단계 리뷰 요청 드립니다.

질문드렸던사항 반영하려고 노력하였습니다.
`LottoGenerator (로또 생성기) 객체`의 상태 값으로 
생성시에 필요한 금액과 로또 번호 리스트를 제거하는 것이 옳은 것인지 고민이 됩니다 😯 

마지막까지 따끔한 리뷰 부탁드립니다! 👍 👍

2021-11-10 17:43 UTC, leeyohan93 requested changes
5단계 구현을 잘 해주셨네요 👍 
몇가지 코멘트를 남겨 놓았으니 확인 부탁드립니다
이제 얼마 안남았습니다 ! 마지막까지 화이팅입니다 ! 🔥

2021-11-10 17:43 UTC, leeyohan93 commented on src/main/java/lotto/model/LottoResult.java
> +				LottoRank.getRankMoney(rankCodeEntry.getKey(), rankCodeEntry.getValue()));
LottoRank의 getRankMoney에서 Money를 반환하고, 
금액을 더하거나 곱하거나 하는 계산하는 책임을 Money 에게 할당해보면 어떨까요? :)

2021-11-10 17:43 UTC, leeyohan93 commented on src/main/java/lotto/model/Lottos.java
> +	private final List<LottoNumbers> randomLottoNumbersList;
수동 로또와 자동로또는 생성의 방법이 다를 뿐, 모든 면에서 똑같이 동작할 수 있다고 생각하는데요 :)
하나의 리스트로 구현해보는 건 어떨까요 ?

2021-11-10 17:43 UTC, leeyohan93 commented on src/main/java/lotto/model/Money.java
> +	public static final BigDecimal LOTTO_PRICE = new BigDecimal(1000);
금액을 의미하는 상수도 Money 클래스로 래핑해보는건 어떨까요 :)

```suggestion
	public static final Money LOTTO_PRICE = new Money(new BigDecimal(1000));
```

2021-11-10 17:43 UTC, leeyohan93 commented on src/main/java/lotto/model/LottoResult.java
>  	public float getYield() {
flaot 대신 BigDecimal을 소수점 표현 또한 더욱 안전하게 사용할 수 있습니다 :)
https://madplay.github.io/post/the-need-for-bigdecimal-in-java

2021-11-10 17:43 UTC, leeyohan93 commented on src/main/java/lotto/model/Lottos.java
>  	}
해당 메서드도 getter와 같은 기능을하고 있는데요. 
일급 컬렉션에서는 꼭 필요한 getter를 제외하고는 사용을 지양해주시고, 외부에서 메시지를 던져 사용할 수 있도록 해주세요 !

2021-11-10 17:43 UTC, leeyohan93 commented
로또 생성기에 대한 상태 값을 유지하시려는 이유도 함께 이야기해주시면 리뷰에 도움이 될 것 같아요 :)

2021-11-11 04:43 UTC, moonjuhyeon commented
로또 생성기의 상태 값제거에 초점을 맞추어 리팩토링 했습니다.
마지막 단계 리뷰 잘 부탁드립니다 요한님 🙏 🙏

2021-11-11 14:58 UTC, leeyohan93 requested changes
이번 피드백도 반영을 너무 잘해주셨네요 ! 👍 
마지막 단계를 종료하기 전에 조금 더 개선해볼만한 부분에
사소한 코멘트들을 남겨놓았으니 확인 부탁드려요 :)
마지막까지 파이팅입니다! 🔥

2021-11-11 14:58 UTC, leeyohan93 commented on src/main/java/lotto/model/LottoGenerator.java
>  	}
LottoGenerator를 싱글톤으로도 만들어볼 수 있을 것 같아요 :)

2021-11-11 14:58 UTC, leeyohan93 commented on src/main/java/lotto/model/LottoGenerator.java
> +	private static void validInputSize(String input, int inputNumberListSize) {
객체로 사용도록 정의해주셨다면 정적 메서드가 아니어도 괜찮을 것 같아요 :)
내부에 static 메서드들을 제거해주세요 :)

```suggestion
	private void validInputSize(String input, int inputNumberListSize) {
```

2021-11-11 14:58 UTC, leeyohan93 commented on src/main/java/lotto/model/LottoGenerator.java
> +		return generateMixLottoNumbers(money, inputNumberList);
해당 메서드의 성공에 대한 테스트를 깜빡하신 것 같아요 :)

2021-11-11 14:58 UTC, leeyohan93 commented on src/main/java/lotto/model/LottoGenerator.java
>  	}
개인적으로 생성자를 제외한 테스트를 위한 로직, 메서드는 지양해야한다고 생각합니다 :)

외부에 제공되는 public 메서드는 항상 신중하게 만들어져야하며 테스트를 위한 메서드의 추가는 해당 클래스에 대한 사용성과 가독성을 떨어뜨린다고 생각하는데 주현님 생각은 어떠신가요?

2021-11-11 14:58 UTC, leeyohan93 commented on src/main/java/lotto/model/LottoGenerator.java
> +		System.out.println();
로깅으로 사용하시다가 제거하는 것을 놓치신 부분일까요?

2021-11-11 14:58 UTC, leeyohan93 commented on src/main/java/lotto/model/LottoResult.java
>  		return sum;
아래와 같은 변수명을 사용해볼 수도 있을 것 같아요 :) 참고만 해주세요 🙏 
```java
		Money total = Money.from(DEFAULT_VALUE);
		Map<LottoRank, Integer> rankMap = containsWinningLottoGenerator();

		for (Map.Entry<LottoRank, Integer> rankCodeEntry : rankMap.entrySet()) {
			Money rankPrize = LottoRank.getRankPrize(rankCodeEntry.getKey(), rankCodeEntry.getValue());
			total = total.sum(rankPrize);
		}

		return total;
	}
```

2021-11-12 15:00 UTC, leeyohan93 approved these changes
주현님 마지막까지 피드백을 반영하여 미션을 잘 마무리 해주셨네요 💯
여러 이야기를 나눌 수 있어서 정말 즐거운 시간이였습니다. 😄 
로또 미션은 종료되었지만 앞으로도 궁금한점이나, 어려운점 있다면 편하게 연락주세요.
다음 미션도 좋은 모습으로 완주하시기라 믿습니다.🔥
감사합니다.

2021-11-12 15:00 UTC, merged