5단계 - 로또(수동)
next-step/java-lotto-pro pull request #268
Opened 2021-11-10 15:10 UTC by don-key

안녕하세요~! 민호님

4단계 리뷰 요청 드리고 미리 좀 적용해보고 있어서 
좀 일찍 리뷰 요청드리는 느낌이네요~!

항상 리뷰를 꼼꼼하게 해주시고 방향성을 잘 잡아주셔서 좋았습니다 👍 

5단계 리뷰 부탁드립니다~

2021-11-11 12:49 UTC, 5minho requested changes
안녕하세요 동현님!
마지막 미션까지 진행하시느라 고생많으셨습니다!
코멘트를 몇 개 남겼는데 확인해주시면 감사하겠습니다~

2021-11-11 12:49 UTC, 5minho commented on src/main/java/lotto/domain/LottoNumber.java
> +    private LottoNumber(int number) {
로또 숫자 캐시하는 것 좋네요 👍

2021-11-11 12:49 UTC, 5minho commented on src/main/java/lotto/domain/LottoResult.java
>      private final Map<LottoRank, Integer> lottoTicketRankMap;
`Map<LottoRank, Integer>` 을 감싸는 일급컬렉션을 만드는 것도 좋을거 같아요 (예를들면 RankResult, RankCounts)
그 일급컬렉션에서는 사용자가 몇등을 몇개 했는지 다 알고 있기 때문에 아래 `calculateRateOfReturn` 도 그 일급컬렉션에게 물어볼 수도 있겠죠

2021-11-11 12:49 UTC, 5minho commented on src/main/java/lotto/domain/LottoResult.java
>      private final double rateOfReturn;
이번 단계에 모든 원시값을 포장해라! 라는 요구사항이 있는데요
Rate 라는 값객체를 만들어보는 것도 좋을거 같아요!

2021-11-11 12:49 UTC, 5minho commented on src/main/java/lotto/domain/LottoPurchase.java
> +    private int manualPurchaseQuantity;
이런 원시값들도 포장하는 경험을 해보셨으면 좋겠어요!

2021-11-12 02:51 UTC, don-key commented on src/main/java/lotto/domain/LottoResult.java
>      private final Map<LottoRank, Integer> lottoTicketRankMap;
넵~! 감사합니다.

2021-11-12 02:54 UTC, don-key commented on src/main/java/lotto/domain/LottoResult.java
>      private final double rateOfReturn;
넵 구현에만 집중하다보니 옛날 스타일로 짜버렸네요 
다른 부분들도 다시 한번 생각해보고 수정하겠습니다~!

2021-11-14 10:04 UTC, don-key commented
안녕하세요~ 민호님!

저번 리뷰요청때는 미션은 어떻게 구현을 할까에 집중을 너무 한것 같아서 
마음이 급했던 것 같습니다 😢 

요번에는 좀 차분하게 고민하면서 했는데 잘 했는지 모르겠네요..ㅎㅎ

리뷰 요청드립니다~!

2021-11-14 19:20 UTC, 5minho approved these changes
안녕하세요 동현님~
로또 미션 마무리 잘해주셨고요.
피드백 반영해주시느라 고생많으셨습니다!!
마지막 단계까지 화이팅입니다!!

2021-11-14 19:20 UTC, 5minho commented on src/main/java/lotto/controller/LottoController.java
> +        if (lottoPurchase.findPurchaseQuantity(LottoPurchaseType.MANUAL) != 0) {
```
if (lottoPurchase.existsManualQuantity()) {
}
```
이렇게 객체한테 물어보는 것도 좋을거 같아요!

2021-11-14 19:20 UTC, 5minho commented on src/main/java/lotto/controller/LottoController.java
> +        }
List 에 저장해도 될거 같은데 TreeMap 에 저장하신 이유가 궁금하네요~

2021-11-14 19:20 UTC, 5minho commented on src/main/java/lotto/domain/Money.java
> +
값 객체에 equals, hashcode 메서드 오버라이딩을 필수입니다!!

2021-11-14 19:20 UTC, 5minho commented on src/main/java/lotto/domain/LottoPurchase.java
> +        return purchaseAmount.getAmount() / LOTTO_PRICE;
```
purchaseAmount.divide(LOTTO_PRICE);
```
이런식으로 getter 를 사용하지 않고 값객체에게 물어보는 건 어떨까요?

2021-11-14 19:20 UTC, 5minho commented on src/test/java/lotto/domain/LottoPurchaseQuantityTest.java
> +    }
CsvSource 어노테이션을 이용해서 `수량의 타입 마다 수량을 저장할 수 있다.`  라는 테스트로 만들어봐도 좋을거 같아요

2021-11-14 19:20 UTC, 5minho commented on src/test/java/lotto/domain/LottoPurchaseQuantityTest.java
> +}
파일의 끝은 새로운 라인으로 끝나게 해주세요~

2021-11-14 19:21 UTC, merged

2021-11-15 14:31 UTC, don-key commented on src/main/java/lotto/controller/LottoController.java
> +        }
키값이 따로 필요없어서 리스트에 저장해도 됐었는데 이번 미션에서 TreeMap을 쓰다보니 쓴 것 같아요 😢

2021-11-15 14:32 UTC, don-key commented on src/main/java/lotto/domain/Money.java
> +
앗 감사합니다!!

2021-11-15 14:33 UTC, don-key commented on src/main/java/lotto/domain/LottoPurchase.java
> +        return purchaseAmount.getAmount() / LOTTO_PRICE;
더 안전하고 의미있는 것 같아요 감사합니다!!

2021-11-15 14:33 UTC, don-key commented on src/test/java/lotto/domain/LottoPurchaseQuantityTest.java
> +    }
넵~! 감사합니다

2021-11-15 14:33 UTC, don-key commented on src/test/java/lotto/domain/LottoPurchaseQuantityTest.java
> +}
넵!!

2021-11-15 14:35 UTC, don-key commented on src/main/java/lotto/controller/LottoController.java
> +        if (lottoPurchase.findPurchaseQuantity(LottoPurchaseType.MANUAL) != 0) {
객체에게 물어봤어야 했는데 놓쳤네요ㅠ 감사합니다!

2021-11-15 14:37 UTC, don-key commented
늦은 시간에 리뷰해주셔서 놀랐습니다!!
감사합니다 👍 

그리고 민호님 덕분에 객체지향적으로 많이 생각해봤던 것 같습니다~!
다음 미션부터는 더 신경써서 진행해보겠습니다~~!! 👍