로또 5단계 미션
next-step/java-lotto-pro pull request #300
Opened 2021-11-15 01:28 UTC by devhak2

로또 5단계 미션 진행했습니다~ 다른일이 생겨서 좀 늦게 제출하게 되었네요ㅠㅠ 저번에 리뷰 주신 것들도 함께 반영하여 올렸습니다! 잘 부탁드리겠습니다~!

2021-11-15 19:11 UTC, 5minho requested changes
안녕하세요 영학님
5단계 미션까지 진행하시느라 고생하셨습니다.
다만 5단계에 추가된 프로그래밍 요구사항 중 빠진게 있는거 같아요.
확인 후 재요청주시면 감사하겠습니다.

2021-11-15 19:11 UTC, 5minho commented on src/main/java/lotto/model/PurchaseMoney.java
> +	public int purchaseWithoutManual(int numberOfManual) {
결국 자동 숫자를 구하는 메서드 같은데요.
`public int countAutoLottoSize(int numberOfManual)` 정도의 메서드명이 좋지 않을까요?

2021-11-15 19:11 UTC, 5minho commented on src/main/java/lotto/view/InputView.java
>  import java.util.Arrays;
5단계 프로그래밍 요구사항 중에 `예외 처리를 통해 에러가 발생하지 않도록 한다.` 라는 요구사항이 있는데요
해당 요구사항은 반영이 안된거 같네요.

2021-11-15 19:11 UTC, 5minho commented on src/test/java/lotto/PurchaseMoneyTest.java
> +	void purchaseWithoutManual() {
이 테스트 메서드가 검증 하고자 하는 것을 DisplayName 어노테이션을 통해 드러내보면 좋을거 같아요

2021-11-15 19:11 UTC, 5minho commented on README.md
> +
5단계 프로그래밍 요구사항이 반영이 안된거 같습니다.

`규칙 3: 모든 원시값과 문자열을 포장한다.`
`예외 처리를 통해 에러가 발생하지 않도록 한다.`

로또 게임에서 원시값으로 포장해 볼 만한 것들을 고민해주시면 좋을거 같아요.

2021-11-15 19:11 UTC, 5minho commented on src/main/java/lotto/model/Lottos.java
> +		List<Lotto> merged = new LinkedList<>(this.lottos);
list 중간에 데이터를 추가하거나 삭제하거나 할 일이 없을거 같은데 `LinkedList` 보다 `ArrayList` 가 좋지 않을까요

2021-11-16 16:11 UTC, devhak2 commented on src/main/java/lotto/model/PurchaseMoney.java
> +	public int purchaseWithoutManual(int numberOfManual) {
말씀하신대로 return값이 무얼 의미하는지 잘 보여주게되서 좋은 것 같습니다 감사합니다~!

2021-11-16 16:12 UTC, devhak2 commented on src/main/java/lotto/view/InputView.java
>  import java.util.Arrays;
해당 요구사항을 빠트린것 같습니다ㅠㅠ 확인하고 다시 요청드리도록 하겠습니다~!

2021-11-16 16:12 UTC, devhak2 commented on src/test/java/lotto/PurchaseMoneyTest.java
> +	void purchaseWithoutManual() {
DisplayName을 빠트렸군요! 추가하도록 하겠습니다!

2021-11-16 16:13 UTC, devhak2 commented on README.md
> +
해당 요구사항들을 반영하여 더 바꿀것은 없는지 고려해보도록 하겠습니다!

2021-11-16 16:15 UTC, devhak2 commented on src/main/java/lotto/model/Lottos.java
> +		List<Lotto> merged = new LinkedList<>(this.lottos);
혹시나 Lotto 갯수가 많으면 ArrayList의 경우 내부에서 array가 resize되면서 배열 복사가 일어나게 될까봐 LinkedList로 구현 했습니다! ArrayList로 구현해도 문제 없을 것으로 보입니다

2021-11-17 16:09 UTC, 5minho requested changes
안녕하세요 영학님!
몇가지 더 개선해볼점 코멘트로 남겼습니다.
확인부탁드리겠습니다.

2021-11-17 16:09 UTC, 5minho commented on src/main/java/lotto/model/BonusNumber.java
> +public class BonusNumber {
하나의 보너스 숫자를 위한 객체를 만들기보다는, 로또 숫자 하나하나를 래핑하는 LottoNumber 라는 객체를 만들어 보는건 어떤가요? 로또 숫자 하나의 대한 로직을 LottoNumber 에 담으면 현재 Lottos 에 있는 코드량도 줄거 같아요!

2021-11-17 16:09 UTC, 5minho commented on src/main/java/lotto/model/BonusNumber.java
> +	}
값 객체는 equals / hashcode 는 필수입니다.

2021-11-17 16:09 UTC, 5minho commented on src/main/java/lotto/model/Prize.java
>  	public double rateReturn(PurchaseMoney money) {
실수값을 래핑하는 Rate 객체를 만들어 볼 수도 있을거 같아요

2021-11-17 16:09 UTC, 5minho commented on README.md
> +
<img width="412" alt="스크린샷 2021-11-18 오전 1 05 53" src="https://user-images.githubusercontent.com/20471248/142236689-06023bbe-1c55-4d80-bb7c-9711f8181b06.png">

당첨통계 노출되는게 현재 요구사항이랑 다릅니다.

2021-11-18 13:38 UTC, devhak2 commented on src/main/java/lotto/model/BonusNumber.java
> +public class BonusNumber {
BonusNumber도 기본적으로는 LottoNumber이니 재사용이 가능 하겠군요! 변경 해보도록 하겠습니다.

2021-11-18 13:38 UTC, devhak2 commented on src/main/java/lotto/model/BonusNumber.java
> +	}
해당 클래스에 추가하도록 하겠습니다!

2021-11-18 13:39 UTC, devhak2 commented on src/main/java/lotto/model/Prize.java
>  	public double rateReturn(PurchaseMoney money) {
해당 값 객체도 한번 추가해보도록 하겠습니다!

2021-11-19 17:07 UTC, 5minho approved these changes
안녕하세요 영학님!
로또 미션진행하느라 고생 많으셨습니다.
이만 머지하도록 할께요.
마지막까지 화이팅입니다!

2021-11-19 17:07 UTC, 5minho commented on src/main/java/lotto/model/Rate.java
> +		return String.format("%.2f", rate);
소수점 둘째자리 까지 출력하는건 view 영역에 로직에 담는게 좋지 않을까요?
model 영역이 view 로직을 알고 있는건 좋은 설계는 아니라고 생각합니다.

2021-11-19 17:07 UTC, 5minho commented on src/main/java/lotto/model/Lotto.java
> +	public Lotto(int... numbers) {
테스트를 위한 코드 같은데요. 
프로덕션 코드에서 최대한 사용 못하도록 메서드 접근 제한자를 디폴트로 하면 더 좋을거 같습니다.

2021-11-19 17:07 UTC, 5minho commented on src/main/java/lotto/model/Rate.java
> +		this.rate = Math.floor(rate * 100) / 100;
생성자에서 floor 처리를 하고 저장하는 것보다 인자로 온 값을 유효성 체크 후 저장하고
Rate 에서 floor 함수를 따로 제공하는게 더 요구사항 변경에 유연하지 않을까요?

2021-11-19 17:07 UTC, 5minho commented on src/main/java/lotto/view/InputView.java
>  import java.util.Arrays;
수동으로만 로또를 사면 프로그램이 죽어버리네요ㅜ

2021-11-19 17:07 UTC, 5minho commented on src/main/java/lotto/model/WinLotto.java
> +	private final LottoNumber lottoNumber;
당첨 번호안에 보너스 숫자는 포함이 될 수 없는데 지금 포함될 수 있네요.

2021-11-19 17:07 UTC, 5minho commented on src/main/java/lotto/model/Rate.java
> +		this.rate = Math.floor(rate * 100) / 100;
그리고 로직 내에서 값 객체를 믿고 쓸 수 있게 rate 에 대한 유효성 체크를 해주시면 좋을거 같습니다.

2021-11-19 17:07 UTC, 5minho commented on src/main/java/lotto/model/LottoNumber.java
> +	}
인텔리제이에서 자동 생성해준 코드 같은데요.
그래도 변수명 같은건 저희 프로그램 요구사항이나 컨벤션에 맞게 수정해주시면 좋을거 같아요.

2021-11-19 17:07 UTC, merged

2021-11-20 07:05 UTC, devhak2 commented on src/main/java/lotto/model/LottoNumber.java
> +	}
넵 자동 생성이 맞습니다! 다음엔 컨벤션에 맞게 조절하도록 하겠습니다!

2021-11-20 07:07 UTC, devhak2 commented on src/main/java/lotto/model/Rate.java
> +		return String.format("%.2f", rate);
그렇군요. 객체의 표현을 소수 2자리까지로만 제한한다(?) 라는 생각에서 toString에 넣었던건데 다시 밖으로 빼놓도록 하겠습니다!

2021-11-20 07:08 UTC, devhak2 commented on src/main/java/lotto/model/Lotto.java
> +	public Lotto(int... numbers) {
넵 맞습니다! 테스트를 위한 생성자 입니다! 이럴 때는 디폴트가 더 나을수도 있겠군요 감사합니다!

2021-11-20 07:09 UTC, devhak2 commented on src/main/java/lotto/model/Rate.java
> +		this.rate = Math.floor(rate * 100) / 100;
그 생각을 못했군요...! 말씀하신대로 floor 함수를 따로 제공하는게 더 유연하게 될 것 같습니다! 다음에는 유효성 체크도 하도록 하겠습니다!

2021-11-20 07:10 UTC, devhak2 commented on src/main/java/lotto/model/WinLotto.java
> +	private final LottoNumber lottoNumber;
생성시에 유효성 체크 하는 것을 놓쳤네요ㅠㅠ 감사합니다!