2단계 문자열 덧셈 계산기
next-step/java-lotto-pro pull request #366
Opened 2022-05-10 13:40 UTC by SanghoLee-dev

테스트 케이스 처음부터 따라가면서 진행해봤습니다.

2022-05-11 02:36 UTC, seokhongkim requested changes
상호님, 문자열 덧셈 계산기 잘 구현해주셨습니다.
코멘트 몇 개 남겼으니 확인 부탁드려요!
그리고 요구사항을 todo list 로 작성해야 하는 것 같습니다.

궁금하신 점이나 이야기 나누고 싶은 부분이 있다면 깃헙 코멘트, 슬랙 DM 편하게 남겨주세요!

2022-05-11 02:36 UTC, seokhongkim commented on src/main/java/stringaddcalculator/StringAddCalculator.java
> +    public static final String COMMA_AND_COLON = ",|:";
해당 문자열은 어떤 목적으로 사용될까요?
상수의 이름은 값을 서술하는 것도 좋지만, 어떤 목적으로 사용되는지를 이해할  수 있으면 더 좋을 것 같아요.
`ZERO` 에 대해서도 고민해보시면 도움이 될 것 같아요.

2022-05-11 02:36 UTC, seokhongkim commented on src/main/java/stringaddcalculator/StringAddCalculator.java
> +    public static final int ZERO = 0;
반복적으로 사용되는 값, 매직 넘버를 상수로 분리하신 점 좋습니다. 👍
모든 상수가 외부에서 사용될 필요가 있을까요?

2022-05-11 02:36 UTC, seokhongkim commented on src/main/java/stringaddcalculator/StringAddCalculator.java
> +    public static int splitAndSum(final String text) {
메소드 이름은 구현보다는 행위를 서술하도록 작성하는 것이 좋습니다.
외부에서 이 메소드를 호출할 때 기대하는 것은 무엇일까요?

2022-05-11 02:36 UTC, seokhongkim commented on src/main/java/stringaddcalculator/StringAddCalculator.java
> +    private static boolean validateNullOrEmpty(final String text) {
메소드명을 고민해보면 좋겠습니다.
이름에서는 `validate` 를 하는 것으로 기대되나, 실제 역할은 `빈 값인지 여부를 반환`하는 것으로 보이네요.

2022-05-11 02:36 UTC, seokhongkim commented on src/main/java/stringaddcalculator/StringAddCalculator.java
> +    private static void validateNumeric(final String text) {
저는 호출되는 순서를 고려하여 메소드를 배치하는 게 읽고 이해하는 데 도움이 되더라구요.
상호님은 어떤 기준으로 메소드를 배치하시나요?

2022-05-11 02:36 UTC, seokhongkim commented on src/main/java/stringaddcalculator/StringAddCalculator.java
> +        if (text == null) {
꼼꼼한 null check 좋습니다. 👍

2022-05-11 02:36 UTC, seokhongkim commented on src/main/java/stringaddcalculator/StringAddCalculator.java
> +            throw new RuntimeException("숫자가 아닙니다.");
RuntimeException 보다 상황에 맞는 적절한 예외를 사용하는 게 좋을 것 같아요!

2022-05-11 02:36 UTC, seokhongkim commented on src/main/java/stringaddcalculator/StringAddCalculator.java
> +public class StringAddCalculator {
한 클래스에 모든 코드가 구현되어 이해하는데 수월한 반면, 모든 변경은 이 클래스를 수정하는 것으로 이뤄질 것 같아요.

코드를 봤을 때, 아래와 같은 역할이 있는 것 같습니다.
1. 문자열을 분할한다. - 일정한 패턴으로 작성되어 있어야 함
2. 각 문자를 숫자 타입으로 변경한다. - 양의 정수여야 함
3. 모든 숫자를 더한다.

작성하신 코드를 객체지향적으로 설계한다면 어떻게 변경해볼 수 있을까요?

2022-05-11 02:36 UTC, seokhongkim commented on src/test/java/stringaddcalculator/StringAddCalculatorTest.java
> +class StringAddCalculatorTest {
꼼꼼한 테스트 케이스 작성 좋습니다. 👍

2022-05-11 03:14 UTC, SanghoLee-dev commented on src/main/java/stringaddcalculator/StringAddCalculator.java
> +    private static boolean validateNullOrEmpty(final String text) {
메소드 명을 `validateNullOrEmpty` 보다 `isNullOrEmpty` 가 더 잘 어울리는거 같아요.

2022-05-11 03:18 UTC, SanghoLee-dev commented on src/main/java/stringaddcalculator/StringAddCalculator.java
> +    public static final int ZERO = 0;
앗! 내부에서만 사용하는 상수값을 선언할때는 `private` 접근자만 사용했었는데 모든 상수 접근자가 `public` 이였네요.
제가 작업을 할때 우선은 쭉 작성을 하고 IDE 리팩토링 기능을 이용하는데 상수 추출 후에 접근자 확인을 안했었네요.
`private` 접근자로 변경하겠습니다.

2022-05-11 03:20 UTC, SanghoLee-dev commented on src/main/java/stringaddcalculator/StringAddCalculator.java
> +            throw new RuntimeException("숫자가 아닙니다.");
앗 요구사항에 RuntimeException 이라고 되어 있어서 바보처럼 그대로 써버렸어요.
상황에 맞게 `IllegalArgumentException` 으로 변경할게요.

2022-05-11 06:43 UTC, SanghoLee-dev commented on src/test/java/stringaddcalculator/StringAddCalculatorTest.java
> +class StringAddCalculatorTest {
앗! 사실 2단계 테스트 소스코드 를 사용한거 뿐인데요
앞으로도 더 테스트 케이스를 꼼꼼하게 작성해 보겠습니다.

2022-05-11 09:54 UTC, SanghoLee-dev commented on src/main/java/stringaddcalculator/StringAddCalculator.java
> +    public static final String COMMA_AND_COLON = ",|:";
상수 이름을 값보다 목적으로 변경 해보겠습니다. `ZERO` 는 `EMPTY_SUMMARY`, `COMMA_ANMD_COLON` 는 `DEFAULT_DELIMITER` 바꿔 봤는데 전보다 목적성이 나오는 네이밍일까요?

2022-05-11 09:56 UTC, SanghoLee-dev commented on src/main/java/stringaddcalculator/StringAddCalculator.java
> +    private static void validateNumeric(final String text) {
저도 코드를 읽을때 위에서 부터 순차적으로 보는 편이라서 호출되는 순서 대로 배치를 하는게 좋아보이네요. 저는 주로 배치를 할때 연관 있는 메소드 끼리 가까이 배치를 하는데 호출 순서까지 생각해서 배치 하지는 않았던거 같습니다. 기본 컨벤션 내에서 호출순서대로 하면 더 일기 좋을 거 같습니다.

2022-05-11 10:47 UTC, SanghoLee-dev commented on src/main/java/stringaddcalculator/StringAddCalculator.java
> +        if (text == null) {
null 체크는 언제나 잊지 않겠습니다.

2022-05-11 10:50 UTC, SanghoLee-dev commented on src/main/java/stringaddcalculator/StringAddCalculator.java
> +    public static int splitAndSum(final String text) {
사실 테스트 소스코드의 있는 메소드명을 그대로 사용해야하는 줄 알고 네이밍을 생각 못했습니다.
외부에서 이 메소드를 호출 할때는 결국 문자열로 된 숫자를 더하여 합을 구하는걸 기대한다고 생각합니다.
그래서 메소드 명을 `splitAndSum` 보다 `sumNumberText` 로 변경하는건 어떤가요?

2022-05-11 14:56 UTC, SanghoLee-dev commented on src/main/java/stringaddcalculator/StringAddCalculator.java
> +public class StringAddCalculator {
1. 입력 문자열을 관리하는 객체 => 문자열 분할의 역할을 가집니다.
2. 문자로 된 숫자 객체 => 문자로 된 숫자를 입력 받으면 양의 정수 객체로 변경합니다.
3. 양의 정수 객체
로 설계를 변경해서 수정해봤습니다.

2022-05-11 15:04 UTC, SanghoLee-dev commented
2단계 요구사항 todo list 를 STEP2.md 에 작성했는데요.
사실 TO-DO list 를 작성하는게 작성하는게 조금 익숙하지 않더라고요. 이런식으로 작성하는게 맞는걸까요?

2022-05-11 23:31 UTC, seokhongkim commented
> 2단계 요구사항 todo list 를 STEP2.md 에 작성했는데요. 사실 TO-DO list 를 작성하는게 작성하는게 조금 익숙하지 않더라고요. 이런식으로 작성하는게 맞는걸까요?

TO-DO list 를 작성하는 방법에도 정답은 없지만, 프로젝트의 README에 작성하는 TO-DO list 는 기능 요구사항을 작성해놓으면 좋을 것 같아요.
그럼 이 프로그램이 어떤 요구사항을 충족하는지 이해하는 데 도움이 되고, 개발하실 때도 요구사항을 확인하면서 어디까지 기능이 구현됐는지 체크하실 수 있을 것 같아요.
반대로 클래스, 메소드를 구현하기 전에 할 일을 적을 때는 지금처럼 구체적인 구현을 작성한 후 개발하면서 삭제하는 게 도움이 될 것 같네요.

TO-DO list 작성시에는 마크다운 문법 중 체크리스트인 `- [ ]` 와 `- [x]`(처리 완료)를 사용해보셔도 좋을 것 같아요.

2022-05-11 23:46 UTC, seokhongkim approved these changes
2단계 미션 진행하느라 고생하셨습니다.

각자의 역할을 가진 클래스로 분리도 잘 해주셨어요.
다음 단계에서는 클래스의 네이밍, 연관관계에 대해서도 고민해보고, 함께 이야기 나눠보기를 기대합니다.
예를 들면, `문자열을 분할하는 역할을 한 클래스는 다른 곳에서 재사용할 수 있지 않을까? 어떤 클래스는 조합 관계를 유지하고, 어떤 클래스는 사용자가 개별적으로 사용할 수 있도록 분리하면 좋을까?`와 같은 고민을 나눠보고 싶네요. 😁 

피드백은 다음 단계 미션을 진행하실 때 고민해보셔도 될 것 같아서, 이만 PR 머지하도록 하겠습니다.
다음 단계에서 뵙겠습니다!

2022-05-11 23:46 UTC, seokhongkim commented on src/main/java/stringaddcalculator/NumberText.java
> +        return new NumberText(PositiveInteger.valueOf(Integer.parseInt(text)));
`PositiveInteger` 가 문자열을 입력 받는 생성자를 제공해주는 방법도 있을 것 같네요!

2022-05-11 23:46 UTC, merged

2022-05-12 04:27 UTC, SanghoLee-dev commented on src/main/java/stringaddcalculator/NumberText.java
> +        return new NumberText(PositiveInteger.valueOf(Integer.parseInt(text)));
`PositiveInteger` 가 문자열 입력 받게 처리하면 더 간결해질거 같네요.