Step2: 문자열 덧셈 계산기
next-step/java-lotto-pro pull request #367
Opened 2022-05-10 13:54 UTC by EastStar1129

step1의 리뷰 받은 내용을 지키면서 개발
junit5 명령어를 습득에 초점을 두면서 개발
Number 모델 생성

2022-05-10 15:28 UTC, Junhong-Kim requested changes
2단계 미션 잘 구현해주셨습니다 👍
소소한 코멘트 남겼는데 확인해주시면 감사드립니다!

2022-05-10 15:28 UTC, Junhong-Kim commented on src/main/java/util/Calculator.java
> +		return list.stream().mapToInt(i->i.getNumber()).sum();
스트림 사용 좋아요! 👍
다음과 같이 메서드 참조를 사용할 수도 있으니 참고해주세요.
```suggestion
		return list.stream().mapToInt(Number::getNumber).sum();
```

2022-05-10 15:28 UTC, Junhong-Kim commented on src/main/java/util/Calculator.java
> +		    return matcher.group(2).split(customDelimiter);
`matcher.group(1)` 보다는 `1`의 의미를 상수로 추출 후 사용하면 좋을 것 같아요.

2022-05-10 15:28 UTC, Junhong-Kim commented on src/main/java/util/Number.java
> +public class Number {
Number 클래스가 변수 값(number)을 갖는데 util 패키지 하위 클래스로 볼 수 있을까요?
이 부분에 대해 고민해보고 수정해보면 좋을 것 같아요! ☺️

2022-05-10 15:28 UTC, Junhong-Kim commented on src/test/java/util/CalculatorTest.java
> +		);
`assertAll()`을 활용한 검증 좋습니다! 👍

2022-05-10 15:41 UTC, Junhong-Kim reviewed
다음 내용도 함께 확인해주시면 감사드립니다 '◡'

2022-05-10 15:41 UTC, Junhong-Kim commented on src/main/java/util/Calculator.java
> +		Matcher matcher = Pattern.compile(CUSTOM_REGEX).matcher(value);
메서드 내부에서 매번 Pattern.compile()을 호출하여 인스턴스를 생성하고 있습니다.
Pattern 인스턴스 생성 비용이 비싸므로 재사용 할 것을 권장드립니다.

2022-05-11 00:15 UTC, EastStar1129 commented on src/main/java/util/Calculator.java
> +		    return matcher.group(2).split(customDelimiter);
상수 체크 한번 더 체크하겠습니다. 감사합니다.

2022-05-11 00:16 UTC, EastStar1129 commented on src/main/java/util/Calculator.java
> +		return list.stream().mapToInt(i->i.getNumber()).sum();
Number::getNumber 문법 하나 더 배워갑니다. stream 사용법 더 공부하겠습니다.

2022-05-11 00:21 UTC, EastStar1129 commented on src/test/java/util/CalculatorTest.java
> +		);
드디어 칭찬 ㅠ 감사합니다~!

2022-05-11 00:22 UTC, EastStar1129 commented on src/main/java/util/Calculator.java
> +		Matcher matcher = Pattern.compile(CUSTOM_REGEX).matcher(value);
코스트 낭비를 줄일 수 있도록 코드 재검토 하겠습니다. 감사합니다.

2022-05-11 00:35 UTC, EastStar1129 commented
리뷰사항을 반영하였으며, 리뷰에 언급한 비슷한 코드들도 수정하였습니다.

2022-05-11 09:29 UTC, Junhong-Kim approved these changes
2단계 미션 피드백 잘 반영해주셨습니다! 👍
소소한 코멘트 남겼는데 다음 단계 시작 전 확인 부탁드립니다.

2022-05-11 09:29 UTC, Junhong-Kim commented on src/main/java/model/Number.java
> +		return number > MIN_NUMBER;
상수로 추출해서 사용하는 습관 좋습니다! 👍

2022-05-11 09:29 UTC, Junhong-Kim commented on src/main/java/util/Calculator.java
> +	}
`customRegexPattern`이 초기화 되지 않았을 때만 인스턴스 생성! 👍

2022-05-11 09:29 UTC, Junhong-Kim commented on src/main/java/util/StringUtil.java
> +	private static int getLastIndex(String value) {
`value.length() - 1`을 `getLastIndex()` 메서드로 추출해 의미를 부여해주신 점 좋아요! 👏

2022-05-11 09:29 UTC, Junhong-Kim commented on src/main/java/util/StringUtil.java
static 메서드만 갖고 있는 Util 클래스들은 기본 생성자의 접근 제어자를 `private`으로 만드는 것을 권장합니다.
접근 제어자를 `private`으로 만들면 실수로 인스턴스를 생성하는 것을 방지할 수 있습니다. ☺️

```java
private StringUtil() {
    throw new UnsupportedOperationException();
}
```

2022-05-11 09:29 UTC, merged

2022-05-11 11:12 UTC, EastStar1129 commented on src/main/java/util/StringUtil.java
기초적인 실수를 했네요 ㅠ 감사합니다! 더 꼼꼼히 체크하겠습니다.