Step2  2단계 - 문자열 덧셈 계산기 PR입니다.
next-step/java-lotto-pro pull request #376
Opened 2022-05-10 16:42 UTC by kwonyongil

안녕하세요. 2단계 - 문자열 덧셈 계산기 PR 입니다. 
이번 2단계도 미션진행하면서 무척 재밌었습니다!
조금씩 TDD에 익숙해지고 있는 것 같아 기쁩니다.
추가로 신경썼던건 
'이펙티브 자바 아이템 6. 불필요한 객체 생성을 피하라' 
Pattern을 생성 해놓고 재사용하는 부분이였습니다!
리뷰 잘 부탁드리겠습니다! 감사합니다.

2022-05-11 19:15 UTC, chae-yh requested changes
안녕하세요 : ) 
재밌게 미션 진행하고 계시다니 좋네요 👍 
작성하신 코드 관련하여 조금 더 고민해보면 좋을만한 부분에 대해서 코멘트 남겨두었는데 확인부탁드리고, 수정도 해주시면 좋을 것 같습니다!

감사합니다 : )

2022-05-11 19:15 UTC, chae-yh commented on docs/README.md
> +# 로또
요구 사항 작성 잘 해주셨네요! 👍

2022-05-11 19:15 UTC, chae-yh commented on src/test/java/calculator/StringAddCalculatorTest.java
> +        assertAll(
assertAll 사용 좋습니다 👍

2022-05-11 19:15 UTC, chae-yh commented on src/test/java/calculator/StringAddCalculatorTest.java
> +    void splitAndSum_숫자하나(String input, int expect) {
강의에 나온 부분은 예시라고 생각이 듭니다. display name에서 한글로 상황을 잘 설명해주었다면 메소드명은 한글/영어를 혼합해서 사용하기보단 영어로 통일해보면 어떨까요...?

2022-05-11 19:15 UTC, chae-yh commented on src/main/java/calculator/ParseNumber.java
> +            throw new RuntimeException(NEGATIVE_NUMBER_EXCEPTION_MESSAGE);
RuntimeException 은 범위가 너무 큰 익셉션으로 느껴집니다. IllegalArgumentException, IllegalStateException 등으로 익셉션을 구체화하는 것은 어떨까요...?

2022-05-11 19:15 UTC, chae-yh commented on src/main/java/calculator/ParseNumber.java
> +        return number < 0;
0과 같은 매직넘버는 상수로 추출해보면 어떨까요...?

2022-05-11 19:15 UTC, chae-yh commented on src/main/java/calculator/ParseNumber.java
> +        } catch (NumberFormatException e) {
"999999999999999999999" 혹은 "1.1"을 입력해도 NumberFormatException 익셉션이 발생합니다. 해당의 경우 익셉션 메시지가 안 맞지 않을까요...?

2022-05-11 19:15 UTC, chae-yh commented on src/main/java/calculator/ParseNumber.java
> +    public static ParseNumber parseNotNegativeNumber(String input) {
이펙티브 자바 아이템1 : 생성자 대신 정적 팩터리 메서드를 고려하라 👍

2022-05-11 19:15 UTC, chae-yh commented on src/main/java/calculator/StringAddCalculator.java
> +public class StringAddCalculator {
이 클래스에서 숫자를 자르고 더하는 역할을 해주고 있네요. 역할을 조금 더 분리해보면 어떨까요...?

2022-05-11 19:15 UTC, chae-yh commented on src/main/java/calculator/StringAddCalculator.java
> +    private static final Set<String> DELIMITER_GROUP = Collections.unmodifiableSet(
불변객체 👍

2022-05-11 19:15 UTC, chae-yh commented on src/main/java/calculator/StringAddCalculator.java
> +    private static int getSum(String[] splits) {
미션 진행 중에는 가능한 stream을 사용하지 않고 진행해봅시다!

2022-05-11 19:15 UTC, chae-yh commented on src/main/java/calculator/ParseNumber.java
> +public class ParseNumber {
동사 + 명사의 형태라서 클래스명보다는 메서드명에 어울리는 것 처럼 느껴집니다. Number로 명확하게 표현하는 것은 어떨까요...?

2022-05-12 01:17 UTC, kwonyongil commented on src/main/java/calculator/ParseNumber.java
> +public class ParseNumber {
네 그렇네요. 수정하겠습니다!

2022-05-12 01:18 UTC, kwonyongil commented on src/main/java/calculator/ParseNumber.java
> +    public static ParseNumber parseNotNegativeNumber(String input) {
감사합니다!

2022-05-12 01:20 UTC, kwonyongil commented on src/main/java/calculator/ParseNumber.java
> +        return number < 0;
아아 다른 부분에서는 매직넘버 상수 추출을 하였는데, 이부분은 상수로 추출을 할지말지 고민했었던거 같습니다. 해당 코드도 상수화 하도록 하겠습니다!

2022-05-12 01:22 UTC, kwonyongil commented on src/main/java/calculator/ParseNumber.java
> +            throw new RuntimeException(NEGATIVE_NUMBER_EXCEPTION_MESSAGE);
RuntimeException 으로 던지는게 요구사항이라고 생각했었는데 RuntimeException 종류였나보군요! 제가 잘못이해한거같아요! 구체적인 익셉션으로  변경하겠습니다! 감사합니다 :)

2022-05-12 09:09 UTC, kwonyongil commented on src/test/java/calculator/StringAddCalculatorTest.java
> +    void splitAndSum_숫자하나(String input, int expect) {
네넵 동의합니다! 감사합니다!

2022-05-12 10:15 UTC, kwonyongil commented on src/main/java/calculator/StringAddCalculator.java
> +    private static int getSum(String[] splits) {
네넵 알겠습니다!

2022-05-12 10:16 UTC, kwonyongil commented on src/main/java/calculator/StringAddCalculator.java
> +public class StringAddCalculator {
네 역할이 많았던거 같습니다. 리뷰반영하겠습니다! 감사합니다.

2022-05-12 11:25 UTC, chae-yh approved these changes
피드백 드린 내용 잘 반영해주셨습니다! 추가 수정하신 부분 관련해서 소소하게 코멘트 달아보았습니다. 간단히 읽으시고, 다음단계 미션 진행하시면 될 것 같습니다 : ) 그리고, PR 은 merge하겠습니다!

이제 본격적으로 로또 미션 시작이네요. 파이팅 입니다 : )

2022-05-12 11:25 UTC, chae-yh commented on src/main/java/calculator/PositiveNumber.java
> +public class PositiveNumber {
원시값 포장 좋습니다 👍 
해당 숫자는 0을 포함한 양수인데 PositiveNumber로 표현하신 이유는 여쭤보고 싶습니다 : )

2022-05-12 11:25 UTC, chae-yh commented on src/main/java/calculator/PositiveNumbers.java
> +public class PositiveNumbers {
1급 콜렉션 좋습니다 👍

2022-05-12 11:25 UTC, chae-yh commented on src/main/java/calculator/StringUtils.java
> +public class StringUtils {
split 역할 분리 좋습니다 👍

2022-05-12 11:26 UTC, merged