Step3: 로또(자동) 기능 구현
next-step/java-lotto-pro pull request #401
Opened 2022-05-11 13:53 UTC by EastStar1129

Step 1, 2에 받은 피드백을 최대한 반영하면서 기능 구현
적절한 위치에 클래스와 메소드를 구현하는 것에 초점을 맞췄습니다.
도메인로직을 최대한 UI로직과 분리하는 것에 초점을 맞췄습니다.

2022-05-11 15:20 UTC, Junhong-Kim requested changes
3단계 미션 코멘트 남겼습니다!
확인 후 재요청 부탁드립니다.

그리고 전체적으로 코드 포맷팅이 맞지 않는 부분이 많은데요.
IDE의 자동 포맷팅을 사용하면 좋을 것 같아요. 🥲

2022-05-11 15:20 UTC, Junhong-Kim commented on src/main/java/lotto/Lotto.java
> +public class Lotto {
`Lotto` 클래스는 애플리케이션 `main` 클래스인데 도메인 역할을 할 것은 이름이네요.
다른 이름을 사용하는게 적절해 보입니다.

2022-05-11 15:20 UTC, Junhong-Kim commented on src/main/java/lotto/Lotto.java
> +		List<LottoNumber> lottoNumbers = new ArrayList<LottoNumber>();
타입 아규먼트는 생략할 수 있습니다.
```suggestion
		List<LottoNumber> lottoNumbers = new ArrayList<>();
```

2022-05-11 15:20 UTC, Junhong-Kim commented on src/main/java/lotto/Lotto.java
> +		for (String lottoNumber: lastLottoNumbers.split(", ")) {
`,`에 띄어쓰기가 없으면 에러가 발생하네요.

2022-05-11 15:20 UTC, Junhong-Kim commented on src/main/java/lotto/Lotto.java
> +	}
UI 로직들은 `InputView`, `ResultView`와 같은 클래스로 분리해서 사용해주세요.

2022-05-11 15:20 UTC, Junhong-Kim commented on src/main/java/lotto/Lotto.java
> +	}
로또 번호 개수가 변경될 경우도 고려되면 좋을 것 같아요.

2022-05-11 15:20 UTC, Junhong-Kim commented on src/main/java/lotto/LottoMachine.java
> +	private model.Number money;
`Number` 클래스보다는 구입금액을 의미하는 클래스를 사용하는게 좋아보여요.

2022-05-11 15:20 UTC, Junhong-Kim commented on src/main/java/lotto/LottoMachine.java
> +		this.money = new model.Number(money);
`LottoMachine`이 `money`를 갖는게 어색해보입니다.
`LottoMachine`은 입력받은 구입금액 만큼 로또를 반환하도록 수정해보면 좋을 것 같아요.

2022-05-11 15:20 UTC, Junhong-Kim commented on src/main/java/lotto/LottoMachine.java
> +		lottos = new ArrayList<LottoNumbers>();
로또를 구매할 때마다 `lottos`를 재정의하는 것보다는 인스턴스 생성 후 반환하면 될 것 같습니다.

2022-05-11 15:20 UTC, Junhong-Kim commented on src/main/java/lotto/LottoMachine.java
> +	}
`LottoMachine`의 역할보다는 로또 결과를 관리하는 클래스의 역할로 적절해보여요.

2022-05-11 15:20 UTC, Junhong-Kim commented on src/main/java/lotto/LottoUtil.java
> +	public static final int[] WIN_MONEYS = {0, 0, 0, 5000, 50000, 1500000, 2000000000};
`WIN_MONEYS` 값들이 어떤 것을 의미하는지 알기 어렵네요.
`enum` 클래스를 사용해보면 좋을 것 같아요.

2022-05-11 15:20 UTC, Junhong-Kim commented on src/main/java/lotto/LottoUtil.java
> +	public static List<LottoNumber> randomLottoNumbers() {
로또를 만드는 것은 `LottoMachine`의 역할로 보입니다.
`LottoUtil` 클래스가 불필요한 클래스는 아닐지 고민해보면 좋을 것 같아요

2022-05-11 15:20 UTC, Junhong-Kim commented on src/main/java/lotto/model/LottoNumber.java
> +	private boolean isNumber(String lottoNumber) {
숫자와 관련된 기능을 수행하는 util 클래스에서 처리하면 좋을 것 같아요.

2022-05-11 15:20 UTC, Junhong-Kim commented on src/main/java/lotto/model/LottoNumber.java
> +		validationRange(getLottoNumber());
유효성 검증 후 `lottoNumber`를 초기화하는 부분이 없는데 맞는걸까요?

2022-05-11 15:20 UTC, Junhong-Kim commented on src/test/java/lotto/LottoMachineTest.java
> +		);
`given-when-then` 패턴을 사용하면 테스트 코드 가독성이 좋아집니다.

2022-05-11 15:20 UTC, Junhong-Kim commented on src/test/java/lotto/LottoTest.java
> +
테스트가 비어있네요 😅
확인 부탁드립니다.

2022-05-11 15:20 UTC, Junhong-Kim commented on src/test/java/lotto/LottoUtilTest.java
> +        assertEquals(LottoUtil.LOTTO_PRICE, 1000);
들여쓰기가 안되어 있습니다.

2022-05-11 15:20 UTC, Junhong-Kim commented on src/main/java/lotto/model/LottoNumber.java
> +			throw new IllegalArgumentException("nubmer: " + lottoNumber + " 1~45 범의의 숫자만 입력이 가능합니다.");
로또 번호 범위가 바뀌면 수정이 필요해보이네요.
하드코딩된 부분은 수정해주세요.

2022-05-11 15:20 UTC, Junhong-Kim commented on src/main/java/lotto/model/LottoNumbers.java
> +		validationCount(lottoNumbers);
항상 모두 검증되어야한다면 `validate`와 같은 메서드로 합쳐두는게 좋을 것 같아요.

2022-05-12 09:54 UTC, EastStar1129 commented on src/main/java/lotto/Lotto.java
> +		for (String lottoNumber: lastLottoNumbers.split(", ")) {
공백을 생각을 못했습니다. 감사합니다!

2022-05-12 10:01 UTC, EastStar1129 commented on src/main/java/lotto/Lotto.java
> +	}
확장성을 고려하는 코드로 변경하겠습니다. 감사합니다!

2022-05-14 10:41 UTC, Junhong-Kim requested changes
추가로 고민해볼 만한 내용 코멘트 남겼습니다 ☺️

피드백을 반영하시면서 `LottoMachine` 클래스가 사라졌는데요.
**로또 기계에서 구입한 로또를 당첨 번호와 비교해서 결과를 반환한다.**
라는 관점으로 다음 단계를 위해 수정해보면 좋을 것 같아요!

화이팅입니다! 🙌

2022-05-14 10:41 UTC, Junhong-Kim commented on src/main/java/view/InputView.java
> +	private static final String inputLastWinLottoMessage = "\n지난 주 당첨 번호를 입력해 주세요.";
자바 구글 코드 컨벤션에 의하면 상수명은 `UPPER_SNAKE_CASE` 사용해야합니다.
https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

2022-05-14 10:41 UTC, Junhong-Kim commented on src/main/java/lotto/model/UserMoney.java
> +	private static final int LOTTO_PRICE = 1000;
`LOTTO_PRICE`를 `UserMoney` 클래스가 갖고있는게 어색합니다.
로또 금액을 입력받아 로또를 반환하는 클래스의 역할로 적절해보여요.

2022-05-14 10:41 UTC, Junhong-Kim commented on src/main/java/lotto/model/UserMoney.java
> +	private int money;
`final` 선언해서 `UserMoney`를 불변으로 만들 수 있습니다.

2022-05-14 10:41 UTC, Junhong-Kim commented on src/main/java/lotto/model/UserMoney.java
> +		this.money = Integer.valueOf(money);
다음 구문이 적절해보입니다.
```suggestion
		this.money = Integer.parseInt(money);
```

2022-05-14 10:41 UTC, Junhong-Kim commented on src/main/java/lotto/Lotto.java
> +		return lottoResult.buyAutoLottos(userMoney);
`LottoResult`에게 로또 구매를 구매해달라는 메시지를 보내고 있네요.
`LottoResult` 클래스명을 봤을 때는 구매한 로또와 당첨 로또를 비교해서 결과를 반환하도록 수정하면 좋을 것 같아요.
그럼 로또 구매는 어떤 클래스에게 역할을 할당해야할지 함께 고민해볼 수 있을 것 같아요.

2022-05-14 10:41 UTC, Junhong-Kim commented on src/main/java/view/ResultView.java
> +public class ResultView {
`ResultView`는 static 메서드로만 구성되어있네요.
인스턴스를 생성할 수 없도록 기본 생성자 접근제어자를 `private`으로 수정하면 좋을 것 같아요.

2022-05-14 10:41 UTC, Junhong-Kim commented on src/main/java/lotto/Lotto.java
> +		return lottoResult.winningList(new LottoNumbers(lottoNumbers));
`Lotto` 클래스로 로또를 구매할 수 있고, 당첨 로또도 만들어낼 수 있네요.
당첨 로또에 대한 기능을 클래스로 분리하고 이를 구매한 로또와 비교해 결과를 반환하도록 수정해보면 좋을 것 같아요.

2022-05-14 10:41 UTC, Junhong-Kim commented on src/main/java/lotto/model/WinningMoney.java
> +	SIX(6, 2000000000);
다음과 같이 자릿수에 `_`를 사용하면 가독성을 높일 수 있어요.
```suggestion
	OTHER(0, 0), 
	THREE(3, 5_000), 
	FOUR(4, 50_000), 
	FIVE(5, 1_500_000), 
	SIX(6, 2_000_000_000);
```

2022-05-14 10:41 UTC, Junhong-Kim commented on src/main/java/lotto/model/WinningList.java
> +		sum = 0;
지역 변수로 선언해 반환하도록 수정해보세요.

2022-05-15 11:06 UTC, Junhong-Kim approved these changes
피드백 잘 반영해주셨네요 👍
소소한 코멘트 남겼는데 다음 단계 시작 전 반영해보면 좋을 것 같아요.
이번 단계는 이만 merge 하겠습니다. 😁

리뷰 내용이 적지 않았는데 반영하시느랴 정말 고생 많으셨습니다.
훨씬 읽기 좋은 코드가 된 것 같아요.
다음 단계도 화이팅입니다! ☺️

2022-05-15 11:06 UTC, Junhong-Kim commented on src/main/java/util/NumberUtil.java
> +public class NumberUtil {
util 클래스는 기본 생성자 접근 제어자를 private으로 선언해서 불필요한 인스턴스 생성을 방지할 수 있습니다.
```java
private NumberUtil() {
    throw new UnsupportedOperationException();
}
```

2022-05-15 11:06 UTC, Junhong-Kim commented on src/main/java/lotto/model/Lottos.java
> +public final class Lottos {
클래스에 `final` 선언을 한 이유가 있을까요?

2022-05-15 11:06 UTC, Junhong-Kim commented on src/main/java/lotto/LottoMachine.java
> +		for (int i = LottoNumber.minLottoNumber(); i <= LottoNumber.maxLottoNumber(); ++i) {
로또를 생성할 때마다 최소번호와 최대번호 사이의 로또 인스턴스를 만들고 있네요.
`lottoNumbersCount` 만큼만 랜덤으로 `LottoNumber` 인스턴스를 생성하면 좋을 것 같아요.

2022-05-15 11:06 UTC, Junhong-Kim commented on src/main/java/lotto/model/LottoNumber.java
> +	private int lottoNumber;
`final` 선언해서 불변으로 만들면 좋을 것 같아요.

2022-05-15 11:06 UTC, Junhong-Kim commented on src/main/java/lotto/model/LottoNumber.java
> +	public boolean equals(Object o) {
`equals()`와 `hashCode()` 재정의! 👍

2022-05-15 11:06 UTC, Junhong-Kim commented on src/main/java/lotto/LottoMachine.java
> +	public Lottos buyAutoLottos(UserMoney userMoney) {
`LottoMachine`에 적절한 역할을 나누었네요 👍

2022-05-15 11:06 UTC, Junhong-Kim commented on src/main/java/lotto/LottoResult.java
> +		sum = 0;
이전 리뷰에 남겨드린 것 처럼 `sum`을 지역변수로 선언해서 사용하도록 수정해보면 좋을 것 같아요.

2022-05-15 11:06 UTC, Junhong-Kim commented on src/main/java/lotto/model/UserMoney.java
> +public final class UserMoney {
멤버 변수 `money`에 `final` 선언하는 것으로 리뷰 드렸는데 클래스에 `final` 선언을 해주셨네요. 😅
`final` 선언 위치(변수, 메서드, 클래스)에 따른 차이점에 대해 알아보면 좋을 것 같아요.

2022-05-15 11:07 UTC, merged