Step3 - 로또(자동)
next-step/java-lotto-pro pull request #420
Opened 2022-05-11 18:13 UTC by KangSeongHyo

안녕하세요~

Step3 로또(자동) 리뷰 부탁드립니다.

감사합니다.

2022-05-13 12:22 UTC, dhmin5693 requested changes
안녕하세요 성효님.
미션 진행해주시느라 굉장히 수고 많으셨어요.

몇 가지 개선점을 남겨보았습니다.
남겨드린 개선점의 대부분은 `객체의 책임` 과 관련되어 있어요.
TDD 미션은 객체를 더욱 객체답게 설계하는 것을 목표로 하고 있거든요.

코드 스타일을 보면 자바와 스프링 프레임워크에 친숙하신 것처럼 보입니다.
MVC 구조로 변경해보자는 의미는 스프링에서 주로 사용되는 레이어드 아키텍처 기반의 코드 구조로 작성하기보다는 각 객체의 역할을 최소한으로 쪼개보자는 의미에 더 가깝습니다.

기분좋은 주말에 너무 많은 과제를 남겨드린 것 같아 마음이 무겁네요.
미션 진행하다가 어렵다고 생각되는 점 있으시다면 바로 DM 주세요.
언제든지 도와드리겠습니다.
저희는 그걸 위해 이 일을 하고 있으니까요 :)

2022-05-13 12:22 UTC, dhmin5693 commented on README.md
> +## FeatureList
정리하고 시작하는 습관 매우 좋아요! 👍

2022-05-13 12:22 UTC, dhmin5693 commented on src/main/java/lotto/model/LottoGeneratorService.java
> +    public Lotto generateLotto() {
`RandomNumberUtils` 에 너무 강하게 의존이 된 상태입니다.
의존의 방향까지는 별 문제 없습니다만 의존한 코드의 결과가 멱등하지 않아요.
특정 로직 수행 결과가 멱등하지 않으면 개발자가 코드를 정확하게 제어할 수가 없습니다.
이 때문에 예상하지 못한 문제가 발생할 수도 있고 테스트 코드도 정확하게 짜기 어려워지게 됩니다.

실제로 테스트 코드를 보면 어떤가요?
기대하는 결과가 1 ~ 45 사이의 6개 숫자임은 알 수 있지만 정확하게 어떤 값을 가지는지는 테스트로 확인하기 어렵습니다.

멱등성 문제를 가진 대표적인 예시로는 `LocalDateTime.now()`, `Random.nextInt()` 정도가 있습니다.
현재 시간을 LocalDateTime.now() 로 데이터베이스에 저장하는 코드가 있다고 해보겠습니다.
`현재 시간이 데이터베이스에 정확하게 저장된다` 라는 결과를 테스트 코드로 작성할 수 있을까요?
혹은 `2022년 5월 13일 00시 00분에 저장을 시도하면 그 시간이 정확히 기록된다`는 어떨까요?

이런 코드를 사용할 때에는 가급적이면 **외부에서 주입**받아 사용하는 형태를 추천드립니다.
사용하는 부분에서 제어할 수 있도록요.

2022-05-13 12:22 UTC, dhmin5693 commented on src/main/java/lotto/utils/RandomNumberUtils.java
> +        List<Integer> numberList = createNumberList(low, max);
메모리를 조금 더 아낄 수 있는 방법이 있지 않을까요?

2022-05-13 12:22 UTC, dhmin5693 commented on src/main/java/lotto/model/LottoGeneratorService.java
> +    public Lotto generateLotto() {
jojoldu 님의 블로그에 멱등성을 해치는 코드의 문제점을 다룬 글이 있어 첨부합니다.
https://jojoldu.tistory.com/451

2022-05-13 12:22 UTC, dhmin5693 commented on src/main/java/lotto/view/InputView.java
> +public class InputView {
인스턴스로 생성할 필요가 없어보이는데 어떻게 생각하시나요?
클래스명이 `InputView` 이지만 사실상 `InputMessage` 의 역할을 수행하고 있는 것으로 보입니다.
`ResultView`가 `Lottos` 를 받아 출력을 수행하듯 적절한 역할을 더 할당해보시는걸 추천드립니다.

테스트가 어려운 코드 중에는 `Scanner` 등의 표준 입력도 있는데요,
`Application` 에서 해당 코드를 분리해서 여기로 책임을 이동하는건 어떤가요?
UI는 테스트 대상에서 제외니까요.

System.out.println 도 테스트 대상으로 삼기는 조금 미묘한데 `InputView`나 `ResultView`로 옮겨봅시다.
그렇게 되면 메소드 하나로 "입력해주세요" 문구와 입력을 동시에 수행할 수 있을 것 같아요.

2022-05-13 12:22 UTC, dhmin5693 commented on src/main/java/lotto/model/LottoPlayService.java
> +        LottoGameValidateUtils.validateWinningNumberList(winningNumberList);
로또 번호는 `Lottos` 에서 관리하게 만드셨더라구요.
당첨 번호도 **하나의 객체**에 책임을 할당할 수 있지 않을까요?
그럼 이 validation 로직도 이동시킬 수 있을 것 같아요.

2022-05-13 12:22 UTC, dhmin5693 commented on src/main/java/lotto/constant/LottoMatchNumber.java
> +    public static Set<LottoMatchNumber> allMatchNumber() {
LottoMatchNumber.values() 로도 대체할 수 있는데 혹시 EnumSet으로 만들어 둔 특별한 이유가 있을까요?

2022-05-13 12:22 UTC, dhmin5693 commented on src/main/java/lotto/vo/Lottos.java
> +        this.resultProfitRate = resultProfitRate;
setter는 제거해주세요.
`Lottos` 가 책임을 너무 많이 가진게 근본적인 원인같아 보입니다.
적절하게 분배해보는건 어떨까요?

2022-05-13 12:22 UTC, dhmin5693 commented on src/main/java/lotto/controller/LottoGameController.java
> +        return new LottoGameDTO(null, inputView.inputMoneyView(), false);
메소드 명으로 동작을 유추하기가 힘들어보여요.
실제로 하는 동작은 dto에 메시지를 넣어서 생성하는건데 메소드명은 금액 입력이거든요.

금액 자체의 역할을 별도로 분리해봐도 좋겠네요.

2022-05-13 12:22 UTC, dhmin5693 commented on src/main/java/lotto/dto/LottoGameDTO.java
> +public class LottoGameDTO {
dto로 데이터를 이동시키는건 각 레이어 간 직접 연결을 줄여주는 아주 좋은 수단입니다 👍 
하지만 dto 하나를 너무 많은 곳에서 사용하고 있어서 불필요한 필드가 많이 생기는 것 같아요.

실제로 `new LottoGameDTO` 로 인스턴스를 생성하는 곳은 8군데인데 그 중 5군데에서 `Lottos` 를 null로 넣고 있습니다.

2022-05-14 06:07 UTC, KangSeongHyo commented on src/main/java/lotto/dto/LottoGameDTO.java
> +public class LottoGameDTO {
이부분은 객체의 책임을 분리하기 시작하니 DTO가 사용이 두군데로 줄어서
 Application으로 예외 전달에 필요하니 생성자를 새로 추가해서 처리해보았는데
 혹시 Application과 Controller를 더 나누는게 좋은지 질문드립니다.

2022-05-14 06:10 UTC, KangSeongHyo commented on src/main/java/lotto/model/LottoGeneratorService.java
> +    public Lotto generateLotto() {
이부분이 조금 어렵게 느껴졌는데요
랜덤넘버를 생성하는 부분을 Controller로 올려서 처리를 하니
클래스에 책임이 애매해지는 부분 있는 것 같은데 어떻게 하면 좋을지
이부분은 한번더 리뷰를 받아보고 싶습니다~

2022-05-14 06:10 UTC, KangSeongHyo commented on src/main/java/lotto/utils/RandomNumberUtils.java
> +        List<Integer> numberList = createNumberList(low, max);
Map을 통해 캐시할수 있도록 처리해보았습니다.

2022-05-14 06:11 UTC, KangSeongHyo commented on src/main/java/lotto/view/InputView.java
> +public class InputView {
피드백 반영하여 입력과 출력에 대한 책임을 분리해보았습니다.

2022-05-14 06:11 UTC, KangSeongHyo commented on src/main/java/lotto/model/LottoPlayService.java
> +        LottoGameValidateUtils.validateWinningNumberList(winningNumberList);
``WinningLotto`` 객체로 분리해 보았습니다.

2022-05-14 06:11 UTC, KangSeongHyo commented on src/main/java/lotto/constant/LottoMatchNumber.java
> +    public static Set<LottoMatchNumber> allMatchNumber() {
이부분 확인하여 수정했습니다.

2022-05-14 13:37 UTC, dhmin5693 commented on src/main/java/lotto/model/LottoGeneratorService.java
> +    public Lotto generateLotto() {
조금 직접적으로 말씀드리자면 `LottoGeneratorService` 는 번호 생성 로직을 알지 않아도 됩니다.
만약 `NumberCreator` 라는 이름의 인터페이스에 의존하여 번호를 생성하고 있다면 어떨까요?
메인 로직에서는 랜덤값을 생성하는 로직을 그대로 사용해도 되고 테스트에서는 내멋대로 값을 주입하여 조금 더 정확한 테스트를 만들어 낼 수 있습니다.

2022-05-14 15:06 UTC, dhmin5693 approved these changes
하루만에 늘어난 커밋의 개수를 보고 성효님이 얼마나 미션을 열심히 진행해주셨는지
그 열기가 잘 느껴지네요 👍

코드를 전체적으로 한번 뒤엎는 과정을 거치면서 이번 미션의 목적을 충분히 달성하셨다고 생각합니다.
간단한 코멘트 몇 개 남겼는데요, 큰 건 아니니 잠깐 확인 정도만 해보시길 바랍니다.

다음 미션 진행해주세요.
정말 고생 많으셨습니다.

2022-05-14 15:06 UTC, dhmin5693 commented on src/main/java/lotto/utils/RandomNumberUtils.java
> +        List<Integer> numberList = createNumberList(low, max);
현재 상황에서는 1 ~ 45 리스트 하나만 생성해도 되는데
아무래도 유틸성 클래스이다 보니 다른 곳에서 활용할 가능성까지 염두에 두신 점 너무 좋네요 :)

여담이지만 변수명에선 `List` 등 가급적이면 Java Collection 명을 사용하지 않으시는걸 추천드려요.
https://tecoble.techcourse.co.kr/post/2020-04-24-variable_naming

2022-05-14 15:06 UTC, dhmin5693 commented on src/main/java/lotto/utils/RandomNumberUtils.java
> +        List<Integer> randomNumberList = new ArrayList<>();
이 부분은 특별한 로직 없이 한 줄로 끝내도 괜찮습니다.
```
return new ArrayList<>(shuffleNumberList);
```

2022-05-14 15:06 UTC, dhmin5693 commented on src/main/java/lotto/dto/LottoGameDTO.java
> +public class LottoGameDTO {
`Application` 과 `Controller` 는 지금으로도 충분한 듯 합니다.
피드백을 잘 반영해주셔서 dto 의존도가 매우 많이 낮아졌네요 👍 

별도의 `Service` 가 없어지면서 `LottoGameDTO` 자체도 최종적으론 삭제할 수 있을 것 같긴 한데,
지금으로선 충분하니 고민 정도만 한번 해보셔도 좋을 것 같아요!

2022-05-14 15:06 UTC, dhmin5693 commented on src/main/java/lotto/vo/Lotto.java
> +    public int[] numberListToArray() {
public 메소드에 대한 테스트는 반드시 작성해주세요!

2022-05-14 15:06 UTC, dhmin5693 commented on src/test/java/lotto/vo/LottoTest.java
> +        assertAll(
한 번에 검증하여 테스트 대상을 정확히 구분하시는 모습 매우 좋습니다 👍

2022-05-14 15:07 UTC, merged

2022-05-15 06:43 UTC, KangSeongHyo commented on src/main/java/lotto/utils/RandomNumberUtils.java
> +        List<Integer> randomNumberList = new ArrayList<>();
아 이부분은 count 개수 만큼만 추가하고 있습니다.