3단계 - 로또(자동)
next-step/java-lotto-pro pull request #437
Opened 2022-05-13 03:53 UTC by iamjunsulee

3단계 로또(자동) PR 입니다.
이전에 피드백 주신 부분과 보완해야할 점을 먼저 반영하고 3단계 미션 진행했습니다 !
어제 교육을 듣고, 생성자를 추가하는 방법에 대해서 고민해보고 적용시켜보았는데요...
우승 로또를 따로 도메인으로 설계하는게 더 나은 방법 같기도 하고 어렵네요..ㅠㅠ
리뷰 부탁드립니다. 감사합니다.

2022-05-14 07:14 UTC, joojimin requested changes
안녕하세요~ 준수님!
리뷰가 늦어서 정말 죄송합니다 ㅠㅠ

로또 4단계 미션에 들어가기전 생각해보셧으면 좋을 리뷰 몇가지 남겨봤어요!
무조건적인 정답은 없으니 생각해보시고 더 좋다고 판단되는 방법을 사용하시면 될 것 같습니다 ㅎㅎ

클래스 분리, 다양한 메서드를 활용해서 테스트하는 방법 잘 활용해주신 것 같습니다 👍 👍

2022-05-14 07:14 UTC, joojimin commented on README.md
> +* 사용자가 입력한 값에 대한 실행 결과를 구한다.
요구사항정리 👍 👍 👍 👍

2022-05-14 07:14 UTC, joojimin commented on src/main/java/calculator/Number.java
> +}
숫자를 따로 객체로 관리하는 부분 훌륭하십니다! 👍 👍 👍

2022-05-14 07:14 UTC, joojimin commented on src/main/java/calculator/Number.java
> +public class Number {
Number 객체안에서도 validate하는 로직이 많은거같아요! 이부분도 테스트가 작성되면 좋을것같습니다!

2022-05-14 07:14 UTC, joojimin commented on src/main/java/calculator/Numbers.java
> +    public Numbers(String[] values) {
Numbers 객체도 테스트가 작성되면 좋을거같아요!
또한 생성자의 String array를 받아서 처리하게끔되어있는데 Numbers 객체가 String array를 Number로 변환하는 책임까지 가지고있는지 생각해볼 문제인거같아요!! 

또한 String을 Number로 변환하여 Numbers에 포함시키려는 행위를 의도한다면 기본 생성자보다 static factory method를 이용한 생성자는 어떨까 싶어요!

2022-05-14 07:14 UTC, joojimin commented on src/main/java/calculator/Numbers.java
> +public class Numbers {
일급컬렉션  👍 👍 👍

2022-05-14 07:14 UTC, joojimin commented on src/main/java/calculator/SplitGenerator.java
> +    private static final int DELIMITER = 1;
피드백반영 👍 👍 👍

2022-05-14 07:14 UTC, joojimin commented on src/main/java/lotto/domain/Lotto.java
> +    private static final String SIZE_ERROR_MESSAGE = "로또 번호는 6개만 가능합니다.";
정의되는 static final (상수)가 많거나 같은 성격으로 묶이는 경우에는 따로 Enum 클래스는 만드는 것이 후에 확장을 하거나 해당 부분을 찾을때도 도움되는 것 같아요! 이부분도 한번 생각해주시면 좋을거같습니다!

2022-05-14 07:14 UTC, joojimin commented on src/main/java/lotto/domain/Lotto.java
> +    public Lotto(String winLottoNumbers) {
파라미터를 다르게하며 생성자를 여러개 두는 것은 사용자가 단박에 알아보기 힘들것 같아요! 이부분도 정적 팩토리 메서드 생성자를 통해 네이밍을 지어줌으로써 의도를 명확하게 해보는건 어떨까요~?

2022-05-14 15:04 UTC, iamjunsulee commented on src/main/java/calculator/Number.java
> +public class Number {
처음에 StringAddCalculator 클래스로만 작성하여 테스트를 다 진행했다고 생각하여 리팩토링하면서 테스트를 진행안했네요 ㅠㅠ 반성합니다.

2022-05-14 15:15 UTC, iamjunsulee commented on src/main/java/calculator/Numbers.java
> +    public Numbers(String[] values) {
테스트 추가하겠습니다.!
정적 팩토리 메서드를 활용해서 의도를 분명히 하고, 내부 구현을 숨길 수도 있겠네요..!
좋은 방법인 것 같습니다.

2022-05-14 15:59 UTC, iamjunsulee commented on src/main/java/lotto/domain/Lotto.java
> +    private static final String SIZE_ERROR_MESSAGE = "로또 번호는 6개만 가능합니다.";
에러 메세지들을 위한 enum 클래스를 작성하는 것이 추후 확장을 위해서 더 나은 방법이 될 것 같네요 !!

2022-05-14 17:04 UTC, iamjunsulee commented on src/main/java/lotto/domain/Lotto.java
> +    public Lotto(String winLottoNumbers) {
의미를 분명히 전달하는데 있어서 정적 팩토리 메서드 사용이 더 나은 방법 같네요 !!

2022-05-14 17:14 UTC, iamjunsulee commented on src/main/java/lotto/domain/Lotto.java
> +    public Lotto(String winLottoNumbers) {
로또번호를 클래스로 분리를 해도 좋을 것 같아 분리해보았습니다 !
해당 클래스 안에서 로또 번호를 생성할때, String 파라미터에 관해서는 정적 팩토리 메서드를 적용시켜보았습니다.

2022-05-15 00:43 UTC, joojimin approved these changes
안녕하세요~ 준수님!
피드백 고민하고 반영하시느냐고 고생하셧습니다 👍 👍 
이번 미션은 여기서 머지하고 다음 미션에서 같이 고민하는 걸로 해볼께요!!
고생많으셧습니다! 💯

2022-05-15 00:43 UTC, merged