Step3
next-step/java-lotto-pro pull request #487
Opened 2022-05-15 09:09 UTC by jiyeonghwang

안녕하세요. 황지영입니다. 

step2에서 피드백 받았던 내용도 함께 PR요청 드립니다.
추가로 궁금한 사항이 있어 질문드립니다.

1. `Lotto` 객체를 collection으로 가지고 있는 `Lottos` 객체가 있습니다.
이 때 Lottos가 일급컬렉션이 되는데요, 제가 구현하다보니 Lotto도 일급 콜렉션으로 구현하였습니다.. 
이렇게 구현해도 되는지 의문이 들어서 질문드립니다.

2. Lotto 자동 생성 시 Test를 어떻게 구현해야 할 지 애매해서요.
이렇게 자동으로 생성되는 객체나 메소드인 경우 어떤식으로 테스트 케이스를 생성해야하는지 궁금합니다! 

step3 리뷰도 잘 부탁드리겠습니다.

2022-05-15 15:25 UTC, enemfk777 requested changes
안녕하세요 지영님 :)
일요일에도 미션 진행하시느라 고생 많으셨습니다 🙇‍♂️
몇가지 아쉬운 부분이 보여 코멘트 드렸습니다..!
domain - controller - view 의 역할에 대해 한 번 더 고민 해 보시면 좋을 것 같습니다 :)
고민해보신 후 다시 한번 요청 부탁드립니다 !!

2022-05-15 15:25 UTC, enemfk777 commented on src/main/java/lotto/domain/Lotto.java
> +    }
> Lotto 자동 생성 시 Test를 어떻게 구현해야 할 지 애매해서요.
> 이렇게 자동으로 생성되는 객체나 메소드인 경우 어떤식으로 테스트 케이스를 생성해야하는지 궁금합니다!

이질문의 답은 여기서 드릴 수 있을 것 같네요 :)

테스트가 용이한 코드를 만들기 위해서는 코드에서 개발자가 제어할 수 없는 부분을 분리해 내는 것이 중요합니다.
- Instant.now()
- Random
- shuffle
위와 같은 기능의 실행 결과는 매번 다르게 되고 , 이는 개발자가 제어할 수 없음을 의미합니다

그렇다면 Lotto를 개발자가 제어할 수 있는 코드로 만들기위해서는 어떻게 해야할까요?
Lotto가 랜덤하게 생성할 책임을 질 필요가 있을까요?
Lotto의 책임은 6개의 중복되지 않은 숫자를 담고 있다는 책임만지고,
랜덤한 6개의 숫자를 생성해내는 책임은 Generator 와 같은 클래스를 분리해서 그 클래스가 지게 하는것은 어떨까요?

2022-05-15 15:25 UTC, enemfk777 commented on src/main/java/lotto/domain/Lotto.java
> +    private final List<Integer> lottoNumber;
로또의 중요한 특성은 "중복되지 않은 숫자" 일 것 같은데요.
List 외에 "중복되지 않은 숫자" 에 알맞은 자료구조가 무엇이 있을까요?

2022-05-15 15:25 UTC, enemfk777 commented on src/main/java/lotto/domain/Lotto.java
> +    private final List<Integer> lottoNumber;
Step2 에서 Number 클래스를 분리해서 양의 정수임을 보장할 수 있는 책임을 부여해주셨던 것 처럼
1 - 45 범위를 갖는 것을 보장 할 수 있는 클래스는 LottoNumber 와 같은 형태로 분리될 수 있지 않을까요? :)

2022-05-15 15:25 UTC, enemfk777 commented on src/main/java/lotto/domain/LottoStatistic.java
> +public class LottoStatistic {
이 클래스는 enum이 어울릴 것 같은데요, enum을 활용해보시는건 어떨까요?

참고 : https://techblog.woowahan.com/2527/

2022-05-15 15:25 UTC, enemfk777 commented on src/main/java/lotto/domain/Lottos.java
> +    private List<Lotto> lottoList;
> Lotto 객체를 collection으로 가지고 있는 Lottos 객체가 있습니다.
> 이 때 Lottos가 일급컬렉션이 되는데요, 제가 구현하다보니 Lotto도 일급 콜렉션으로 구현하였습니다..
> 이렇게 구현해도 되는지 의문이 들어서 질문드립니다.

넵 구현해 주신대로 일급컬렉션의 일급컬렉션도 아무 문제가 없습니다.

Lotto라는 일큽 컬렉션은 로또 숫자들의 모음을 나타내는 일급컬렉션이고
Lottos는 Lotto들의 모음을 나타내는 일급컬렉션이니 의미상 전혀 다른 클래스로 볼 수 있으니까요 :)

단 현재 Lottos가 갖는 역할이 좀 부족해보이는데요,
Lottos에서 로또 들의 정보를 모두 가지고 있으니, 
당첨 로또 번호만 전달받으면 스스로 당첨 결과를 생성해 내는 역할을 맡을 수 있지 않을까요?? :)

2022-05-15 15:25 UTC, enemfk777 commented on src/main/java/lotto/domain/Lottos.java
> +        return list;
1 ~ 45 의 숫자를 만들어 내는 것이 Lottos의 책임일까요?
테스트 용이한 코드 관련 코멘트에서 언급해 드렸던 생성을 맡는 클래스의 책임일 것 같아요 :)
또, 1 ~ 45는 고정되어있는 요구사항인데요, 매번 호출할 때 마다 생성하지않고 캐싱이 가능하지 않을까요? :)

2022-05-15 15:25 UTC, enemfk777 commented on src/main/java/lotto/view/InputView.java
> +        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
Scanner를 사용하면 정수형을 바로 입력 받을 수 있을 것 같아요 :)

2022-05-15 15:25 UTC, enemfk777 commented on src/main/java/lotto/view/OutputView.java
> +        System.out.println(lottoStatistic.toResultString());
출력 메세지는 OutputView의 책임일 것 같아요 :)
출력 메세지는 형태가 늘 바뀔 수 있는 부분인데
lottoStatistic이라는 중요 도메인클래스에서 직접 메세지를 반환하게 되면,
출력메세지가 바뀔때마다 lottoStatistic가 영향을 받게되고, OutputView가 나뉘어 있는 이유가 없어 질것 같습니다 :)

2022-05-15 15:25 UTC, enemfk777 commented on src/main/java/lotto/domain/TotalLotto.java
> +public class TotalLotto {
이클래스가 너무 많은 책임을 지고있는 것으로 보입니다.
입력한 금액, 살수있는 로또 게임 갯수, 당첨결과 확인등 모두 이 클래스에서 책임지고 있네요

- 음수 금액이 입력되지 않았는지
- 최소 게임 금액 (1000원)이 얼마인지
- 구매 가능 게임 수 계산

위 책임을 갖는 클래스는 어떤 이름으로 분리될 수 있을 까요?

또 getter로 값을 꺼내와서 당첨여부를 확인하기보다는
당첨 정보를 가지고 있는 클래스에게 확인 대상 게임들을 전달해서 직접 당첨 결과를 반환받게 하는건 어떨까요?
객체의 책임과 역할을 나눌 때 가장 판별하기 쉬운 기준은
객체가 어떤 기능을 하기에 스스로 충분한 정보를 가지고 있는가 입니다.
당첨번호를 가지고 있는 클래스가 당첨 확인 기능을 갖는건 자연스러운 일이겠죠?

위 기준에 따라 이 클래스의 과도한 책임을 다른 클래스들로 쪼개어 볼까요 ? :)

2022-05-15 15:25 UTC, enemfk777 commented on src/main/java/lotto/domain/TotalLotto.java
> +    public int MatchesLottoNumber(Lotto lotto) {
메서드명은 카멜케이스로 쓰는게 원칙입니다!

2022-05-15 15:25 UTC, enemfk777 commented on src/main/java/lotto/utils/LottoGame.java
> +public class LottoGame {
전체적인 클래스 분리에 관한 내용이라 이곳에 적겠습니다 :)
도메인 클래스와 dto 클래스의 경계가 잘 나뉘어 지지 않은 것 같습니다

도메인 클래스 : 어플리케이션의 핵심 비즈니스 로직을 갖는 클래스 Lotto, Lottos, LottoRank 등
dto 클래스 : 값 전달을 위한 클래스 도메인 클래스가 view 클래스에 직접 노출되지 않게 view에 맞는 값을 전달

도메인클래스를 view에 직접 노출시키지 않는 것이 좋은 이유는 view에서 도메인클래스를 값 노출에 직접 사용하게 될 경우 view에서 보여주는 방식만 바뀌는 변화에도 도메인클래스가 직접 영향 받게 되기 때문입니다.

비즈니스의 핵심을 담고있는 도메인클래스가 자주 변경에 노출되면 그만큼 버그, 오류가 발생할 여지가 많아지게 되죠 :)
때문에 도메인클래스에서 핵심 로직을 다 수행하고 난 결과물만 dto 클래스를 통해 view로 전달하게 해서
만약 view에서 보여주는 값에 변화가 생겨도, dto 클래스까지만 영향 받게 하고, 도메인클래스를 보호하는 것입니다.

위 사항을 잘 고민하셔서 도메인 클래스와 dto 성격의 클래스가 잘 나뉘면 좋을 것 같습니다.
패키지로 나누어 보시는것도 좋을 것 같아요 :)

로또 미션 목차에 있는 domain - view - controller에 관한 글도 참고해 보시면 도움이 될 것 같습니다 
https://edu.nextstep.camp/s/X02BsEA0/ls/PBl6en4H

2022-05-17 14:48 UTC, jiyeonghwang commented on src/main/java/lotto/domain/Lotto.java
> +    }
LottoNumber에서 생성되도록 개선하였습니다!

2022-05-17 14:55 UTC, jiyeonghwang commented on src/main/java/lotto/domain/Lotto.java
> +    private final List<Integer> lottoNumber;
출력 시 정렬하려면 다시 List로 변환해야하는 점과  `1~45`까지의 수를 가지고 있는 list를 상수화하여 사용중이여서 Set 자료형을 사용하지 않았었는데, 다시 생각해보니 랜덤한 범위의 수에서 특정 개수의 수를 추출하는 경우 Set 자료형을 사용하는게 좋을 것 같습니다!

2022-05-17 14:56 UTC, jiyeonghwang commented on src/main/java/lotto/domain/Lotto.java
> +    private final List<Integer> lottoNumber;
양의 정수임과 `1~45`를 확인할 수 있도록 LottoNumber 클래스를 별도로 분리하였습니다!

2022-05-17 15:00 UTC, jiyeonghwang commented on src/main/java/lotto/domain/LottoStatistic.java
> +public class LottoStatistic {
enum형식으로 변경하였습니다! 
개인적으로 enum은 개념적으로 알고 있지만, 적용하는 사례에 대해서 애매모호한 점이 있었는데,
직접 구현해보니 유용하였습니다! 좋은 피드백 감사드립니다😊

2022-05-17 15:01 UTC, jiyeonghwang commented on src/main/java/lotto/domain/Lottos.java
> +    private List<Lotto> lottoList;
Lottos에서 당첨 결과를 생성해내도록 개선하였습니다.
제가 질문하였던 내용에 대한 자세한 답변도 감사드립니다!

2022-05-17 15:02 UTC, jiyeonghwang commented on src/main/java/lotto/domain/TotalLotto.java
> +    public int MatchesLottoNumber(Lotto lotto) {
앗.. ㅠㅠ 오타 발견 감사드립니다

2022-05-17 15:03 UTC, jiyeonghwang commented on src/main/java/lotto/domain/TotalLotto.java
> +public class TotalLotto {
피드백 주신 내용을 참고하여 객체를 쪼갠다고 쪼개보았는데,
좀 더 좋은 방향으로 쪼갤 수 있지 않았을까 하는 아쉬움이 남네요..

2022-05-17 15:03 UTC, jiyeonghwang commented on src/main/java/lotto/view/InputView.java
> +        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
Scanner로 변경하였습니다!

2022-05-17 15:16 UTC, jiyeonghwang commented on src/main/java/lotto/utils/LottoGame.java
> +public class LottoGame {
1차 피드백 이후 클래스에 toString() 메소드 오버라이딩 또는 String을 반환하는 메소드를 구현하였습니다. 
이런 부분을 도메인 클래스를 가지고 있는 클래스에서 구현한다면. 
제가 올바른 방향으로 도메인 클래스와 dto클래스를 분리하는건지 궁금합니다.

<hr>

자세한 피드백 감사드립니다.
domain-view-controller에 대해 다시 한 번 생각해보는 계기가 되었습니다!
ㅠㅠ 2차 피드백도 모쪼록 잘 부탁드리겠습니다.😂

2022-05-17 16:24 UTC, enemfk777 requested changes
안녕하세요 지영님 :)

피드백 열심히 반영해 주셔서 감사합니다 👍
피드백을 잘 적용해 주셨지만, 아직 객체간 책임 분리가 조금 아쉬운 부분이 있어
한 번 더 request change 드리겠습니다 🙇‍♂️
이미 피드백 반영을 하면서 클래스 분리를 수행해 보셔서 어렵지 않게 분리하 실수 있을 거예요 :)
그럼 반영 후 다시 한 번 요청 부탁드립니다..!

2022-05-17 16:24 UTC, enemfk777 commented on src/main/java/lotto/domain/TotalLotto.java
> +    public TotalLotto(int count) {
프로덕션 코드에 테스트 코드만을 위한 코드는 없어야 합니다.
테스트코드는 말그대로 프로덕션 코드를 검증 하기 위한 용도로
테스트코드가 프로덕션 코드를 오염시켜서는 안됩니다 :)

테스트하기가 어렵다면 클래스 분리가 잘못된건 아닌지 의심해보세요 :)

2022-05-17 16:24 UTC, enemfk777 commented on src/main/java/lotto/utils/LottoGame.java
> +        totalLotto.of(amount);
of 는 보통 두개 이상의 인자로 객체를 생성하는 정적 팩토리 메서드의 명칭으로 쓰는 것이 관례입니다 :)
TotalLotto를 생성자로 먼저 초기화 할 필요가 없어보이는데요, 정적 팩토리 메서드로 바꿔보시면 어떨까요

2022-05-17 16:24 UTC, enemfk777 commented on src/main/java/lotto/domain/TotalLotto.java
> +    private static final int LOTTO_PRICE = 1000;
LottoNumber 클래스가 분리된것 처럼
입력받는 금액도 클래스 분리가 이루어지면 어떨까요?
금액 클래스의 인스턴스는 어플리케이션 내에서 1000원 이상이어야 의미가 있을 테니
위 상수는 여기보단 그쪽에 어울릴 것 같아요

또 이렇게 Money 클래스가 분리된다면, 구매 가능 수량은 어느 클래스가 스스로 만들어낼 수 있게 될까요?

2022-05-17 16:24 UTC, enemfk777 commented on src/main/java/lotto/domain/TotalLotto.java
> +    }
객체는 가능한 불변인 상태가 좋습니다.
처음 초기화 한 후 내부의 값을 그대로 유지시키는 것을 말하는데요
외부 메서드로 인해 객체 내부의 상태가 바뀌면 객체 내부의 상태를 따라가는데 어려움이 있습니다.
개발자가 코드를 읽는 타이밍에 객체 내부의 상태가 어떨지 추측하기 어려워 지는 것이지요.

새로운 상태로 갱신이 필요한 경우 새로운 객체를 만들어 내는 편이 훨씬 좋습니다.

2022-05-17 16:24 UTC, enemfk777 commented on src/main/java/lotto/domain/LottoNumber.java
> +            .collect(Collectors.toList());
LottoNumber 목록을 만들어내는건 LottoNumber의 책임이라고 보기 힘들 것 같아요

이렇게 책임을 질 클래스가 애매할땐

LottoNumberGenerator와 같이 생성을 책임지는 클래스를 분리해주시는건 어떨까요?
해당 클래스는 자동뿐만아니라 앞으로 추가될 수동 생성책임도 함께 책임 질 수 있을 것 같아요 :)

2022-05-18 15:37 UTC, jiyeonghwang commented on src/main/java/lotto/domain/TotalLotto.java
> +    private static final int LOTTO_PRICE = 1000;
Money 객체로 대체하였습니다!

2022-05-18 15:55 UTC, yeongever0 commented on src/main/java/lotto/domain/LottoNumber.java
> +            .collect(Collectors.toList());
LottoFactory를 따로 구현하여 LottoNumber목록을 생성하도록 구현하였습니다!

2022-05-18 15:58 UTC, jiyeonghwang commented on src/main/java/lotto/domain/TotalLotto.java
> +    }
`of` 메소드를 삭제하고, 새로운 객체로 반환하는 `from` 메소드로 대체하였습니다!

2022-05-18 16:01 UTC, jiyeonghwang commented on src/main/java/lotto/utils/LottoGame.java
> +        totalLotto.of(amount);
정적 팩토리 메소드 컨벤션이 있는줄 몰랐습니다.. 
좋은 정보 감사드립니다🥰

`of`대신 `from`으로 변경하였습니다!

2022-05-18 16:08 UTC, jiyeonghwang commented on src/main/java/lotto/domain/TotalLotto.java
> +    public TotalLotto(int count) {
1차 피드백 받기 전, 테스트 코드 작성 시 실제론 사용하지 않는 메소드가 왜 계속 추가되는지 막막했는데,
피드백 과정을 거치며 어떤 부분이 잘못되었는지 깨닫게 되었습니다. 감사합니다😁
이번 피드백도 잘 부탁드립니다!

2022-05-19 15:56 UTC, enemfk777 approved these changes
안녕하세요 지영님:)

바쁘게 피드백을 반영해주셨는지 피드백 반영 후 제거되어야할 코드들이 그대로 남아있는 부분이 있네요 😅
해당 부분 피드백 드렸고, 그외에 소소한 피드백 드렸으니
다음 단계에서 함께 반영 부탁드립니다 🙇‍♂️

이번단계에서 리뷰 핑퐁이 많았는데, 반영해주시느라 고생많으셨습니다!
그럼 다음 단계를 위해 이만 머지하겠습니다..!💪

2022-05-19 15:56 UTC, enemfk777 commented on src/main/java/lotto/domain/LottoFactory.java
> +    private static List<LottoNumber> lottoNumberList;
불필요한 변수는 제거해주세요 :)

2022-05-19 15:56 UTC, enemfk777 commented on src/main/java/lotto/domain/LottoFactory.java
> +            OutputView.printErrorMessage();
도메인객체가 View를 의존하고 있는 어색한 상황이네요.
이곳 말고도 많은 도메인 객체에서 View를 의존하고 있는데요,
MVC 패턴에 대해서 다시 한번 학습해보시면 좋을것 같습니다 :)
실무에서도 컨트롤러 보다 안쪽에 있는 클래스들이 프론트엔드를 직접 사용하진 않는걸 떠올려보세요 :)

2022-05-19 15:56 UTC, enemfk777 commented on src/main/java/lotto/domain/Lotto.java
> +        Collections.sort(lottoNumbers);
생성자에 로직이 들어가는건 지양하는 편이 좋습니다.
특히 파라미터 변조는 더욱 지양하시는 편이 좋습니다.
참고 : https://jackjeong.tistory.com/149

2022-05-19 15:56 UTC, enemfk777 commented on src/main/java/lotto/domain/LottoNumber.java
> +    }
미사용 메서드는 제거해주세요 :)

2022-05-19 15:56 UTC, enemfk777 commented on src/main/java/lotto/domain/LottoNumber.java
> +    private static final List<LottoNumber> LOTTO_NUMBERS = IntStream.rangeClosed(LOTTO_MIN_NUMBER, LOTTO_MAX_NUMBER)
미사용 변수는 제거해주세요 :)

2022-05-19 15:56 UTC, enemfk777 commented on src/main/java/lotto/domain/TotalLotto.java
> +        totalLotto.lottoList.autoGenerator(totalLotto.money.getCount());
로또 생성 책임이분리 되었는데 이전코드가 그대로 님아 쓰이고 있네요 :)

2022-05-19 15:56 UTC, enemfk777 commented on src/main/java/lotto/domain/Money.java
> +    private int isValidCount(int amount) {
is 로 시작하는 메서드명은 boolean 값을 반환하는것이 관례입니다.
그리고 하나의 메서드가 너무 많은 책임을 지고 있네요
https://edu.nextstep.camp/s/X02BsEA0/ls/PBl6en4H
위 아티클의 맨아래 리팩토링 규칙을 지키는 형태로 메서드 분리가 필요합니다 :)

2022-05-19 15:56 UTC, merged