3단계 - 로또(자동) PR입니다.
next-step/java-lotto-pro pull request #489
Opened 2022-05-15 10:59 UTC by tj3828

안녕하세요!
3단계 - 로또(자동) PR입니다.

원시값 포장, 일급컬렉션사용 등을 많이 고려해서 설계해보려고 노력하였으나
초반에는 잘되다가 뒤로 갈수록 설계도 많이 꼬이고, TDD도 잘 못했던 것 같습니다 ㅠ

특히, PurchasedInfo 클래스의 winningLotto를 테스트하기 위해 도중에 많이 바꾸었는데요.
테스트 시 mock을 사용하지 않고 깔끔하게 테스트하기 위해 여러가지 생각해보았으나 잘 떠오르지가 않았습니다.

수동기능이 포함된 로또였다면 그나마 테스트 할 수 있었을 것 같은데,, 자동기능만 있다는 가정하에 테스트하려니 막막하더라구요..
설계자체가 잘못된건지 감이 잘오지 않아서 피드백 부탁드립니다!

2022-05-15 16:01 UTC, oper912 requested changes
안녕하세요 탁종님 
로또 step3 잘 구현해주셨네요 주말에 고생 많으셨습니다 🙂

로또 번호 자동 생성과 테스트 관련해서 고민을 많이 하신거같아요 👍
현재는 구현체에 의존하다보니 전체적인 구조가 조금 복잡해진 느낌도 있는데요 

질문주신 부분에 대해서 힌트가 될만한 코멘트 남겨드렸는데 확인부탁드리구 
이번에 구조를 잘 잡고 가신다면 다음 단계를 진행하시기 수월하실 거 같아서 Request changes 하였습니다 🙏
고민해보신 후 다시 한번 리뷰 재요청 부탁드립니다

2022-05-15 16:01 UTC, oper912 commented on src/main/java/lotto/model/factory/LottoAutoFactory.java
> +            .forEach(i -> rangeLottoNumbers.add(new LottoNumber(i)));
```suggestion
        IntStream.rangeClosed(LOTTO_NUMBER_RANGE_MIN, LOTTO_NUMBER_RANGE_MAX)
            .forEach(i -> rangeLottoNumbers.add(new LottoNumber(i)));
```
rangeClosed 를 활용해볼 수도 있겠네요 :)

2022-05-15 16:01 UTC, oper912 commented on src/main/java/lotto/model/number/LottoNumbers.java
> +        validateDuplicate(lottoNumbers);
메서드명만봐도 어떤 유효성 검증을 하려고 했는지 의도를 바로 알 수 있었던 것 같습니다 🙂

2022-05-15 16:01 UTC, oper912 commented on src/main/java/lotto/model/number/LottoNumbers.java
> +    private List<LottoNumber> lottoNumbers;
중복이 불가능한 자료구조를 활용해보면 어떨까요??
관련해서 validateDuplicate도 조금 더 단순해질 수 있을거같아요 🤔

2022-05-15 16:01 UTC, oper912 commented on src/test/java/lotto/model/purchased/PurchasedLottoTest.java
> +    }
아마 이 부분에서 굉장히 오래 고민하셨던거 같은데요 관련해서 테스트가 가능하도록 해야해서 구조도 조금 복잡해진 것 같습니다 😱
[해당 블로그](https://velog.io/@lxxjn0/%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4%EB%A5%BC-%EB%B6%84%EB%A6%AC%ED%95%98%EC%97%AC-%ED%85%8C%EC%8A%A4%ED%8A%B8%ED%95%98%EA%B8%B0-%EC%A2%8B%EC%9D%80-%EB%A9%94%EC%84%9C%EB%93%9C%EB%A1%9C-%EB%A7%8C%EB%93%A4%EA%B8%B0) 내용을 참고하시면 감이 오실 수도 있는데요 
로또 번호 생성시 `구현체`에 의존하지않고 `인터페이스`에 의존하도록하면 별도로 일정한 번호를 생성해주는 테스트용 클래스를 정의해서 활용해볼 수 있을 것 같아요

이번 기회에 스프링에서 DI시 생성자 주입 방식을 추천하는 점, solid에서 DIP(의존 역전 원칙) 도 관련해서 생각해보면 좋을 것 같아요

2022-05-15 16:01 UTC, oper912 commented on src/main/java/lotto/util/LottoUtil.java
> +public class LottoUtil {
LottoUtil에 있는 메서드들이 정말 utility성 메서드인지 한번 더 고민해보면 좋을 것 같아요 🤔
개인적으로는 애매한 코드를 모아두는 곳이 생기다보면 처음에는 편한데 나중에 관리가 잘 되지않는거같더라구요

무조건 제 의견을 반영하실 필요는 없구 다른 의견이 있으시면 자유롭게 말씀해주세요! 
이런 부분에서 제가 생각하지 못했던 의견들을 듣다보면 저도 깨닫는 부분이 있을 것 같아요 🙏  함께 성장하는 우테캠Pro

2022-05-15 18:44 UTC, tj3828 commented on src/main/java/lotto/model/factory/LottoAutoFactory.java
> +            .forEach(i -> rangeLottoNumbers.add(new LottoNumber(i)));
생각지도 못한 꿀팁 감사합니다 👍

2022-05-15 18:46 UTC, tj3828 commented on src/main/java/lotto/model/number/LottoNumbers.java
> +    private List<LottoNumber> lottoNumbers;
해당 유효성 검사 자체가 필요없는거 였네용 ㅎㅎ

2022-05-15 18:55 UTC, tj3828 commented on src/test/java/lotto/model/purchased/PurchasedLottoTest.java
> +    }
다시 리뷰요청 올린 것에 일단 말씀해주신 인터페이스 까지는 만들어봤습니다..
근데.. 테스트 시에 어떻게 활용할 수 있는지가 의문입니다.🤔

랜덤로또 번호 생성은 로또번호 한줄 만을 생성해줄 수 있는데, 테스트 시에는 이러한 수동번호를 여러개 생성해야 하기 때문에
말씀해주신 테스트 코드 부분에 어떻게 활용할 수 있을까요...? 😭

로또번호 한줄마다 인터페이스 구현체를 만들어 로또번호를 생성하는 것은 너무 비효율 적이라 생각하고,, 
그렇다고 인터페이스와 구현체 내에서 파라미터를 추가하여 풀기에는 실제 비지니스 로직에서 generate()에서는 파라미터를 사용하지 않기때문에 불가능하다고 생각했습니다.

일단 객체관계에서 각 객체를 생성하는 로직을 변경하여 전체적으로 테스트 커버리지를 올릴 수 있도록 변경하긴 하였는데,,
의견 부탁드립니다..! 🙏

2022-05-15 18:57 UTC, tj3828 commented on src/main/java/lotto/util/LottoUtil.java
> +public class LottoUtil {
피드백 듣고 돌이켜 보니,
model에만 집중하고 util은 보지도 않았던거 같습니다.😢

애매하다 싶은건 다 util에 넣었던 것 같은데,, util보다는 각 객체의 검사(?) 부분과 어울린다 생각하여 model 객체에서 처리할 수 있도록 변경하였습니다!

2022-05-16 15:02 UTC, oper912 requested changes
안녕하세요 탁종님 🙂
랜덤한 값을 검증하는 부분에서 고민을 많이 하신 것 같아요 
이전의 제 설명이 조금 부족했던 것 같기도 해서 추가적으로 코멘트 남겼는데 확인 부탁드립니다 🙏

나머지 피드백은 잘 반영해주셔서 개선해나갈 점들은 다음 단계 진행하시면서 수정해주셔도 될 것 같아서 이만 `merge`하도록 하겠습니다
고생 많으셨습니다~

2022-05-16 15:02 UTC, oper912 commented on src/main/java/lotto/model/factory/LottoAutoTestFactory.java
> +        return null;
음 제가 설명이 조금 부족했을 수도 있는데요 🤔 
이전에 제가 링크 드린 블로그에서도 보면  랜덤하게 얻을 수 있는 값을 테스트하는게 아니라 랜덤하게 숫자를 얻었다고 가정하고 그 이후에 로직이 정상적으로 수행되는지 테스트를 하고 있어요

![스크린샷 2022-05-16 오후 10 51 28](https://user-images.githubusercontent.com/31276206/168608221-55e66192-a37f-4053-b487-b4b8f333df4a.png)

테스트코드는 일관성이 중요한데 랜덤한 값은 경우에 따라서 실패하거나 성공이 가능하기 때문에 
`랜덤하게 생성되는 값이 필요해!` 보다는 랜덤하게 숫자가 생성되었다고 가정하고 이후에 로직들이 의도한대로 수행되는지 검증하면 실제 운영코드에서도 랜덤한 값들이 오더라도 이후 로직들은 정상적으로 수행되는걸 보장할 수 있을 것 같아요!

2022-05-16 15:02 UTC, oper912 commented on src/test/java/lotto/model/purchased/PurchasedLottoTest.java
> +            generateLottoNumberList(new int[]{1, 2, 3, 4, 5, 6}));
LottoAutoTestFactory 에서 랜덤한 번호라고 가정하고 1 ~ 6 의 로또 번호를 생성하게 해준다면
각 테스트클래스에 있는 `generateLottoNumberList()` 메서드도 제거될 수 있겠네요

2022-05-16 15:02 UTC, oper912 commented on src/main/java/lotto/model/factory/LottoAutoTestFactory.java
> +        return null;
너무 어렵게 고민하지마시구 LottoAutoTestFactory 에서 숫자가 랜덤하게 뽑혔다고 가정하고 1 ~ 6의 로또번호를 생성해줘도 될 것 같습니다 🙂

2022-05-16 15:02 UTC, oper912 commented on src/main/java/lotto/model/factory/LottoAutoTestFactory.java
> +public class LottoAutoTestFactory implements ILottoFactory{
테스트를 위한 클래스니 test/java/lotto 하위 패키지로 위치를 옮겨주시면 좋을 것 같습니다 🙂

2022-05-16 15:02 UTC, merged

2022-05-16 15:16 UTC, tj3828 commented on src/main/java/lotto/model/factory/LottoAutoTestFactory.java
> +        return null;
아하 아닙니다ㅠㅠ 보내주신 링크는 완벽했는데 제가 활용를 이상하게 한 것 같아요..!

제가 여쭤봤던건 말씀해주신 1 ~ 6의 로또번호를 생성한다고 했을 때,
수익률에 대한 테스트를 진행한다고 하면 (로또10개 번호 수동 생성 -> 당첨번호 수동입력 -> 수익률계산) 로직을 한번에 테스트안에서 객체를 생성하여 수익률을 계산하려고 했었습니다.
그렇기에 로또번호 10개가 수동생성되는데 1 ~ 6번으로 동일하게 생성된다면 의미가 없지않나? 생각했던 것이구요..

애초에 수익률을 계산하는 로직에 대한 메소드를 분리를 잘했다면, 로또 번호 생성이나 당첨번호 수동입력과 같은 행위가 없어도 수익률계산에 대한 로직이 검증될 수 있었어야 했을 것 같습니다..!

단위테스트를 생각했어야 했는데, 마치 제가 하려했던건 통합테스트를 하려고 했었네요 ㅠ_ㅠ

단계적으로 차근차근 리팩토링하는 것이 아니라 처음부터 완벽하게 하려고 이것저것 하다보니 많이 꼬인 것 같습니다..!

지금보니 몇몇 메소드가 꼭 해당 클래스에 있어야하나 싶은 것도 보이네요.

꼼꼼한 피드백 감사드리고, 다음 PR때 좀 더 개선해보겠습니다!