3단계 - 로또(자동)
next-step/java-lotto-pro pull request #501
Opened 2022-05-15 17:16 UTC by mukeunzi

리뷰어님 안녕하세요! 

3단계 PR요청 드립니다~! :)

2022-05-16 14:44 UTC, chae-yh requested changes
은지님 안녕하세요! 로또 미션 잘 구현해주셨습니다 👍 
커밋도 잘 작성해주셨지만, 커밋 범위가 조금 큰 경우가 있어서 조금 더 쪼개서 커밋하면 좋지 않을까 생각해봅니다! 그리고, 조금 생각해보면 좋을 만한 내용들이 있어 코멘트 작성하였는데 확인 부탁드립니다!

끈질기게 답을 알아가려는 열정에 저도 배우고 있습니다.
감사합니다 : )

2022-05-16 14:44 UTC, chae-yh commented on src/main/java/lotto/domain/LottoStore.java
> +public class LottoStore {
이 클래스는 테스트 클래스가 없네요! 중요한 클래스인데 테스트 코드 작성되면 좋을 것 같습니다 : )

2022-05-16 14:44 UTC, chae-yh commented on src/main/java/lotto/domain/LottoNumber.java
> +    private final String LOTTO_NUMBER_REGEX = "^[1-9]{1}$|^[1-3]{1}[0-9]{1}$|^4{1}[0-5]{1}$";
테스트 코드를 보니 정상동작하지만, 정합성 체크를 정규식으로 하다보니 읽는 입장에서 어렵게 느껴지기도 합니다. 결국 특정 범위안에 들어가면 정상 동작하는 셈인데, 부등호를 이용하면 어떨까요...?

2022-05-16 14:44 UTC, chae-yh commented on src/main/java/lotto/domain/LottoNumbers.java
> +    private final List<Integer> lottoNumbers;
이 부분은 의견이 갈릴 수 있다고 생각하지만, 저는 Set 자료 구조를 써서 중복이 허용되지 않는 다는 것을 보여주는 것도 좋을 것 같습니다!
그리고, 일급컬렉션인데 LottoNumber를 가지고 있으면 더 좋을 것 같습니다 : )

2022-05-16 14:44 UTC, chae-yh commented on src/main/java/lotto/domain/LottoStore.java
> +    private HashMap<Integer, Integer> lottoCashPrize = initializeLottoCashPrize();
이 클래스의 역할이 너무 많고 큽니다. 한 클래스에서 많아도 2개 이상의 필드는 갖지 않게 분리해보는 것은 어떨까요...?

2022-05-16 14:44 UTC, chae-yh commented on src/main/java/lotto/domain/LottoNumbers.java
> +public class LottoNumbers {
물론 LottoNumber로 이루어진 일급객체이긴 하지만, lotto라고 명명해주면 조금 더 이해하기 쉽지 않을까요..?

2022-05-16 14:44 UTC, chae-yh commented on src/main/java/lotto/domain/LottoNumbers.java
> +    public static final int LOTTO_DIGITS = 6;
상수명이 직관적이지 않은 것 같습니다! SIZE 정도는 어떨까요..?

2022-05-16 14:44 UTC, chae-yh commented on src/main/java/lotto/domain/LottoStore.java
> +        if (matchCount == MATCH_THREE) {
if 절을 이렇게 나열하기 보다는 더 간단하게 표현하는 방법은 없을까요...?

2022-05-16 14:44 UTC, chae-yh commented on src/main/java/lotto/domain/Money.java
> +    public static final int MINIMUM_MONEY = 1000;
해당 값은 LOTTO_PRICE로 대체할 수 있지 않을까요...?

2022-05-16 14:44 UTC, chae-yh commented on src/main/java/lotto/constant/LottoWinningConstant.java
> +public class LottoWinningConstant {
랭킹 정보를 상수로 추출한 것 좋네요 👍 
이런 형식의 데이터는 Enum으로 추출해 주면 더 좋을 것 같습니다 : )

2022-05-16 14:44 UTC, chae-yh commented on src/main/java/lotto/domain/LottoAutoGenerator.java
> +    private static List<Integer> initializeNumbers() {
미리 캐쉬해두는 것 좋네요 👍

2022-05-16 14:44 UTC, chae-yh commented on src/main/java/lotto/domain/LottoStore.java
> +            lottoAutoNumbers.add(new LottoNumbers(LottoAutoGenerator.makeNumbers()));
랜덤으로 숫자를 만드는 것을 외부로 잘 추출해 내었습니다 👍

2022-05-16 14:44 UTC, chae-yh commented on src/main/java/lotto/domain/LottoNumbers.java
> +        return lottoNumbers;
일급 컬렉션은 단순히 필드를 final로 선언하였다고 하여 불변객체가 되지 않습니다. lottoNumbers의 list를 재할당하는 것만을 막아줍니다. 해당 메소드에서 로또를 가져다가 사용자가 임의로 숫자를 넣어줄 수 있습니다. 이 부분을 막을 수 있도록 작성해보는 것도 좋을 것 같습니다. 다음과 같은 키워드로 공부해보시면 좋을 것 같아요!
`Collections.unmodifiableList()`

2022-05-16 14:44 UTC, chae-yh commented on src/main/java/lotto/view/OutputView.java
> +    public static void printLottoResult(LottoStore lottoStore, HashMap<Integer, Integer> lottoResult) {
하나의 메서드가 너무 기네요. 역할 분리하여 10줄 이하로 줄이는 것은 어떨까요...?

2022-05-16 14:44 UTC, chae-yh commented on src/test/java/lotto/domain/LottoNumbersTest.java
> +    @ValueSource(strings = {"1", "1,2,3", "1,2,3,4,5,6,7"})
적절한 @annotaion 사용 좋습니다 👍

2022-05-16 14:44 UTC, chae-yh commented on src/test/java/lotto/domain/LottoNumbersTest.java
> +public class LottoNumbersTest {
calculateMatchCount 테스트도 추가할 수 있지 않을까요...?

2022-05-16 14:44 UTC, chae-yh commented on src/main/java/lotto/domain/LottoAutoGenerator.java
> +
static 메소드밖에 없다면 private LottoAutoGenerator(){} 로, 생성자를 막아주는 것도 좋을 것 같습니다!

2022-05-16 14:44 UTC, chae-yh commented on src/main/java/lotto/domain/LottoNumbers.java
> +        validate();
validate를 먼저하고 initializeLottoNumbers 를 하면 어떨까요...?

2022-05-17 14:42 UTC, mukeunzi commented on src/main/java/lotto/domain/LottoNumber.java
> +    private final String LOTTO_NUMBER_REGEX = "^[1-9]{1}$|^[1-3]{1}[0-9]{1}$|^4{1}[0-5]{1}$";
넵! 저도 동의합니다.ㅠㅠ

기존에는 LottoNumber 생성 시 값을 string으로 받았기 때문에 부등호로 값을 판단할 수 없어 정규표현식을 사용했던 것이었는데요. LottoNumber를 생성할 때 형변환(string to int)을 외부에서 하는 것이 맞다고 판단하여 관련 생성자함수를 수정할 예정입니다. 따라서 값이 int으로 주어지기 때문에 위 정규표현식도 부등호로 변경하려고 합니다!

2022-05-17 14:43 UTC, mukeunzi commented on src/main/java/lotto/domain/LottoStore.java
> +    private HashMap<Integer, Integer> lottoCashPrize = initializeLottoCashPrize();
반영해보도록 하겠습니다!

2022-05-17 14:43 UTC, mukeunzi commented on src/main/java/lotto/domain/LottoNumbers.java
> +    public static final int LOTTO_DIGITS = 6;
동의합니다!

2022-05-17 14:44 UTC, mukeunzi commented on src/main/java/lotto/domain/LottoNumbers.java
> +        validate();
넵 동의합니다!

2022-05-18 01:06 UTC, mukeunzi commented
영훈님 안녕하세요! 
리뷰주신 내용 반영 및 리팩토링 완료되어 PR요청 드립니다 :) 

커밋을 쪼개어 작업하려고 했는데, 연관성 있는 코드들이 많고 시간에 쫓기다보니 한번에.. 커밋을 하게 되었습니다. 다음 리뷰부터는 작게 쪼개도록 하겠습니다 ( __ )

수정사항이 많은데 커밋을 나누지 못해 클래스와 관련된 부분 추가 설명 남깁니다.

1. LottoStore 클래스 역할 축소
  - 이 클래스는 상점이라는 개념을 두고 있습니다. 하지만 기존에는 너무 많은 역할(ex. 로또 가격, 사용자의 로또 구매 개수 관리, 사용자의 자동 번호 관리, 로또 결과값 생성 등)이 있어 역할을 축소시켰습니다. 그중, (사용자의)로또 번호는 별도의 클래스에서 관리하는 것이 맞다고 판단하여 이 클래스에서 관련 역할을 제거하고 LottoTicket 클래스로 이동시켰습니다. 
  - 상점의 개념으로 봤을 때 이 클래스에서는 `로또 가격, 사용자가 금액을 넣을 경우 자동번호 생성` 만 담당하도록 수정했습니다. 
3. LottoNumbers 클래스 역할 변경
 - 기존에는 이 클래스가 로또 한줄(6개)을 Collection으로 관리하는 일급컬렉션이었는데요. 이 클래스는 로또 번호(1~45)를 관리하는 용도로 변경하였습니다. 
5. LottoTicket 클래스 생성
 - 신규로 생성된 클래스입니다. 이 클래스는 로또 한줄(6개)을 관리에 필요한 검증, 자동 번호 생성 등의 기능이 있습니다. 
7. LottoController 실행 로직 변경
 - 기존에는 Controller내에서 LottoStore객체를 생성할 때 파라미터로 money를 넣었는데요. money는 구매하는 행위를 할 때 전달하는 것이 맞다고 판단하여 이를 변경했습니다.
 - 로또를 구매하는 buy() 를 호출할 때에도, 호출하는 측에서 구매 결과인 로또 목록을 리턴받을 수 있도록 수정했습니다. 


전체 구조를 리팩토링 하느라 테스트코드 수정을 못한 상태입니다. 리팩토링 시에는 TDD를 하지 못했네요..ㅠ 리뷰해주시는 동안 테스트코드 추가해두겠습니다. 매번 꼼꼼한 리뷰 감사합니다! 🙇

2022-05-18 14:15 UTC, mukeunzi commented on src/main/java/lotto/domain/LottoStore.java
> +public class LottoStore {
작성했습니다!

2022-05-18 14:17 UTC, mukeunzi commented on src/main/java/lotto/domain/LottoNumbers.java
> +    private final List<Integer> lottoNumbers;
자료구조로 의도를 나타내는 것도 좋은 방법이네요! 다음부터 구현 시 참고하겠습니다 :)

2022-05-18 14:18 UTC, mukeunzi commented on src/main/java/lotto/domain/LottoStore.java
> +        if (matchCount == MATCH_THREE) {
Enum을 적용하여 해당 코드 수정했습니다!

2022-05-18 14:18 UTC, mukeunzi commented on src/main/java/lotto/domain/LottoNumbers.java
> +        return lottoNumbers;
넵! 적용했습니다 :)

2022-05-18 14:18 UTC, mukeunzi commented on src/main/java/lotto/view/OutputView.java
> +    public static void printLottoResult(LottoStore lottoStore, HashMap<Integer, Integer> lottoResult) {
수정했습니다!

2022-05-18 14:19 UTC, mukeunzi commented
테스트코드 작성도 완료되었습니다!

2022-05-19 13:25 UTC, chae-yh requested changes
은지님 안녕하세요! 리뷰가 조금 늦었네요..ㅠ 
피드백 잘 반영해주셨습니다 👍 코드가 상당히 깔끔해지고 이해하기 쉽게 변경되었습니다 ㅎㅎ 지금도 merge 해도 괜찮을 것 같지만 조금 만 더 생각해보면 좋을만한 내용이 있어 Request changes 하겠습니다!

한 번만 더 확인 부탁드립니다 감사합니다!

2022-05-19 13:25 UTC, chae-yh commented on README.md
> +### 기능 요구사항
기능 요구 사항 작성 좋습니다 👍

2022-05-19 13:25 UTC, chae-yh commented on src/main/java/lotto/domain/LottoNumber.java
> +    public static final int LOTTO_MIN_NUMBER = 1;
public 으로 열린 상수이니 외부에서 사용할 땐 MIN_NUMBER 정도로도 괜찮지 않을까요...?
LottoNumber.LOTTO_MIN_NUMBER VS LottoNumber.MIN_NUMBER

2022-05-19 13:25 UTC, chae-yh commented on src/main/java/lotto/domain/LottoRank.java
> +public enum LottoRank {
Enum으로 잘 빼내어 주셨네요 👍 
테스트 코드도 추가되면 좋을 것 같아요!

2022-05-19 13:25 UTC, chae-yh commented on src/main/java/lotto/domain/LottoStore.java
> +        for (int i = 0; i < money.getMoney() / LOTTO_PRICE; i++) {
money.getMoney() / LOTTO_PRICE 
이 부분을 메소드로 추출하고 의미를 부여해도 좋을 것 같습니다 : )

2022-05-19 13:25 UTC, chae-yh commented on src/main/java/lotto/domain/LottoTicket.java
> +    private final List<LottoNumber> lottoTicket;
중복된 값이 아니라는 의미의 자료구조를 사용할 수 있을 것 같습니다!

2022-05-19 13:25 UTC, chae-yh commented on src/main/java/lotto/domain/LottoTicket.java
> +        copyLottoTicket.retainAll(target.lottoTicket);
재밌는 방법이네요 ㅎㅎ

2022-05-19 13:25 UTC, chae-yh commented on src/main/java/lotto/domain/LottoTicket.java
> +    public static LottoTicket makeAuto() {
이 랜덤으로 만들어주는 로직을 한단계 위(LottoStore)로 올리는 것은 어떨까요...? 
강의에서도 나왔듯 이런 랜덤으로 숫자를 만드는 것은 테스트가 어렵고, 이 부분이 LottoTicket이 영향을 받기보다는 한단계 위의 layer에서 만들어주면 해당 값의 리스트를 LottoTicket가 받아서 만들어주는 방향도 좋을 것 같습니다!

2022-05-19 13:25 UTC, chae-yh commented on src/main/java/lotto/view/OutputView.java
> +    private static int matchCount(List<Integer> matchList, LottoRank lottoRank) {
이 부분의 로직처럼 실제 값계산이 들어가는 부분은 view에서 해주기보다는 domain에서 해주는 것이 좋을 것 같아요!
LottoStatistics 비슷한 클래스로 해당 데이터를 표현하면 어떨까요...?

2022-05-19 13:25 UTC, chae-yh commented on src/main/java/lotto/view/OutputView.java
> +    private static int lottoProfit(List<Integer> matchList, List<LottoRank> lottoRanks) {
이 부분도 domain 로직으로 보입니다!

2022-05-19 13:25 UTC, chae-yh commented on src/test/java/lotto/domain/LottoTicketTest.java
> +                    System.out.println(lottoNumbers.toString());
테스트 코드 내 System 함수는 가능한 사용하지 않는 것이 좋습니다!

2022-05-19 13:25 UTC, chae-yh commented on src/test/java/lotto/domain/LottoTicketTest.java
> +    }
match 메소드에 대한 테스트도 추가하면 좋을 것 같아요!

2022-05-19 13:50 UTC, mukeunzi commented on src/main/java/lotto/domain/LottoNumber.java
> +    public static final int LOTTO_MIN_NUMBER = 1;
넵 동의합니다~!

2022-05-19 13:58 UTC, mukeunzi commented on src/main/java/lotto/domain/LottoTicket.java
> +    private final List<LottoNumber> lottoTicket;
넵, 이전에도 코멘트주신 부분이었는데요. 
이번 구현에서는 List로 선언 후 별도의 validation 로직을 구현했고, match() 와 같은 메서드에서 List 구조로 값이 사용되기 때문에 그대로 두려고 합니다! 

다음 미션부터 참고해서 작업하도록 하겠습니다 :)

2022-05-19 15:09 UTC, mukeunzi commented on src/main/java/lotto/view/OutputView.java
> +    private static int matchCount(List<Integer> matchList, LottoRank lottoRank) {
앗 넵 이부분 수정하고 싶었는데 결과값 생성하는 별도의 클래스가 필요했던거군요! 반영하겠습니다 :)

2022-05-19 15:09 UTC, mukeunzi commented on src/test/java/lotto/domain/LottoTicketTest.java
> +                    System.out.println(lottoNumbers.toString());
앗 넵! 이부분은 잘못 커밋된 부분이네요 삭제했습니다~

2022-05-19 15:32 UTC, mukeunzi commented on src/test/java/lotto/domain/LottoTicketTest.java
> +    }
추가했습니다!

2022-05-19 15:41 UTC, mukeunzi commented on src/main/java/lotto/domain/LottoTicket.java
> +    public static LottoTicket makeAuto() {
반영했습니다! 한가지 궁금한 것이 있는데요, 

저도 이 방법을 고민했는데, 위 메소드를 한 레이어 위로 올리면 LottoStore에 옮겨지는데, 이때 리턴 값이 LottoTicket(즉 다른 일급컬렉션)인 것이 어색하다고 여겨졌는데, 그건 상관없을까요? 

자동생성을 역할 관점에서 바라봤을 때, LottoStore에서 구현하는 것에는 저도 동의하지만, LottoStore의 메소드 응답값이 다른 일급컬렉션(LottoTicket)을 응답하는 것이 어색하다고 생각되어 이를 LottoTicket에 구현한 것이었습니다. 

의견이 듣고싶습니다!

2022-05-19 16:31 UTC, chae-yh approved these changes
은지님 안녕하세요 : ) 피드백 잘 반영해주셨습니다 👍 
조금 확인해보면 좋을 부분은 코멘트 남겨드렸습니다만, 이 정도면 미션의 목적을 달성했다고 생각되어 merge하겠습니다!

빠르게 피드백 반영해주시는게 인상적입니다 ㅎㅎ 다음 미션 진행 부탁드립니다!

2022-05-19 16:31 UTC, chae-yh commented on src/main/java/lotto/domain/LottoStore.java
> +    private int ticketCount(int money) {
이 부분의 책임을 Money로 옮길 수 있지 않을까요...?

2022-05-19 16:31 UTC, chae-yh commented on src/main/java/lotto/domain/LottoStatistics.java
> +public class LottoStatistics {
이 클래스의 테스트가 있어도 좋을 것 같아요!

2022-05-19 16:31 UTC, chae-yh commented on src/main/java/lotto/view/OutputView.java
> +        float rateOfReturn = profit / (matchList.size() * LOTTO_PRICE);
부동 소수점은 정확한 값이 나오지 않을 수 있습니다 BigDecimal을 써보는 건 어떨까요...?

2022-05-19 16:31 UTC, chae-yh commented on src/main/java/lotto/view/OutputView.java
> +        for (LottoRank lottoRank : lottoRanks) {
이런 로직은 domain 쪽으로 옮기는 건 어떨까요....? 단순히 데이터를 보여주는 view 에 있기에는 로직이 복잡해보입니다!

2022-05-19 16:31 UTC, chae-yh commented on src/main/java/lotto/domain/LottoTicket.java
> +    public static LottoTicket makeAuto() {
이렇게 서로 다른 도메인이 메시지를 전달하고 받으면서 기능의 목적을 달성하는 것이 객체지향의 중요한 점이라고 생각하기 때문에 오히려 좋은 방법이라고 생각합니다! 도메인 객체들은 다른 도메인과 메시지를 전달하고 전달 받을텐데, 이 리턴 값이 일급 컬렉션일 경우 단순히 리스트로 된 데이터보다 개발자의 의도를 명확히 할 수 있고, 데이터 캡슐화도 잘 되어 있다고 할 수 있으므로 오히려 좋다고 생각합니다!

2022-05-19 16:31 UTC, chae-yh commented on src/main/java/lotto/domain/LottoTicket.java
> +    public int match(LottoTicket target) {
해당 클래스에서만 쓰는데 private 로 바꿔도 되지 않을까요...? 밑의 matchList의 테스트코드를 추가하는게 더 좋아보입니다 : )

2022-05-19 16:31 UTC, chae-yh commented on src/main/java/lotto/view/InputView.java
> +        List<LottoNumber> numbers = new ArrayList<>();
LottoTickets 같은 일급 컬렉션을 만들어서 해당 역할을 줄 수 있지 않을까요...?

2022-05-19 16:31 UTC, merged

2022-05-21 07:18 UTC, mukeunzi commented on src/main/java/lotto/domain/LottoTicket.java
> +    public static LottoTicket makeAuto() {
아.. 넵 답변 이해했습니다 ㅠㅠ 👍 
객체지향의 개념을 아는 것과 개념을 코드에 녹여내는 건 또 다른 연습이 필요한 것 같네요 
미션에서 연습해볼 수 있어 너무 좋은 것 같습니다! 다음 미션부터 이부분 잘 고려해보도록 하겠습니다!

2022-05-22 15:49 UTC, mukeunzi commented on src/main/java/lotto/domain/LottoStore.java
> +    private int ticketCount(int money) {
넵, Money가 더 적절해보이네요! 다음 PR에 적용하도록 하겠습니다!

한가지 궁금한 것은, 위 코드와 같이 2개 이상의 클래스를 사용해서 값을 생성할 때 책임을 어디에 둘지가 고민이 되는데, Money가 더 적절하다고 생각하시는 기준이 있을까요? 아직 익숙치 않다보니 저도 Money가 적절한 것 같다 생각은 들지만 이유를 명확히 말하지는 못하겠습니다 😢

2022-05-22 16:00 UTC, mukeunzi commented on src/main/java/lotto/view/InputView.java
> +        List<LottoNumber> numbers = new ArrayList<>();
[다음 PR](https://github.com/next-step/java-lotto-pro/pull/601)에서 관련 의견 남기겠습니다!