Step3 - 로또(자동)
next-step/java-lotto-pro pull request #506
Opened 2022-05-16 02:46 UTC by tasklet1579

안녕하세요~
기능은 구현했는데 테스트 하면서 진행하다보니 시간이 너무 오래 걸리네요.. 
중반부터는 기능만 만들고 완성 후에 테스트 케이스 코드만 작성했습니다..
테스트 코드를 잘 작성하면 그것을 기반으로 클래스만 잘 조립하면 되는 것 같은데 아직 제게는 어려운 부분 같습니다.
이런 것도 테스트 코드를 작성해야 하는가 의문이 드는 것은 빈 파일로 커밋했습니다.
indent depth는 1단계를 초과하지 않으려고 했는데 LotteryStatistics result 에서 또 메서드로 나눠야하는지 모르겠습니다..

2022-05-16 15:01 UTC, chae-yh requested changes
성우님 안녕하세요 : ) 로또 미션 본격적으로 시작했는데 잘 작성해주신 것 같습니다 👍 
TDD는 습관이 되지 않으면 어려운 것에 매우 동감합니다. 저도 처음 TDD 접했을 때 속도도 안나고 힘들었던 기억이 있네요. 하지만 손에 익혀두면 매우 좋은 것 또한 의심의 여지가 없다고 생각합니다!

작성해주신 코드 관련해서는 조금 생각해보면 좋을만한 내용들을 코멘트로 작성해두었습니다! 참고 부탁드립니다 : )

열정 잃지 마시고 계속 파이팅입니다 : )

2022-05-16 15:01 UTC, chae-yh commented on docs/로또.md
> +### 4. 로또 기능 정의
기능 정의 잘 작성해주셨습니다 👍 
pr 주실 때마다 개선되는 모습이 인상적입니다!

2022-05-16 15:01 UTC, chae-yh commented on src/main/java/lotto/view/Console.java
> +    private static boolean isClosed() {
혹시 이 메서드의 역할은 무엇일까요...?

2022-05-16 15:01 UTC, chae-yh commented on src/main/java/lotto/vo/Lottery.java
> +    public final static int LOTTERY_SIZE = 6;
public으로 열린 상수이기 때문에 외부에서 사용시에 Lottery.LOTTERY_SIZE 로 쓰게 될텐데 이보다는 Lottery.SIZE 의 형태로도 좋을 것 같습니다!

2022-05-16 15:01 UTC, chae-yh commented on src/main/java/lotto/vo/Lottery.java
> +    public Lottery() {
이 생성자는 어떤 용도로 있는 걸까요...?

2022-05-16 15:01 UTC, chae-yh commented on src/main/java/lotto/LotteryGame.java
> +    private static Winning result;
해당 변수들을 전역 변수로 선언한 이유가 있을까요...?

2022-05-16 15:01 UTC, chae-yh commented on src/main/java/lotto/LotteryGame.java
> +    public static void main(String[] args) {
main 메소드이긴 하지만 해당 메소드도 너무 긴 것 같습니다. 의미를 나눠서 10줄 이내로 줄이면 어떨까요..?

2022-05-16 15:01 UTC, chae-yh commented on src/main/java/lotto/vo/Coupon.java
> +public class Coupon {
쿠폰이라고 하면 뭔가를 할인해주는 형태가 먼저 생각나는데 Unit같은 것으로 변경하는 것은 어떨까요...?

2022-05-16 15:01 UTC, chae-yh commented on src/main/java/lotto/vo/Lottery.java
> +    public Lottery(List<Number> numbers) {
랜덤으로 값을 만드는 부분을 해당 Lottery를 사용하는 부분으로 잘 올려주셨습니다 👍

2022-05-16 15:01 UTC, chae-yh commented on src/main/java/lotto/LotteryUtils.java
> +public class LotteryUtils {
클래스는 책임과 역할을 나타내는 적당한 이름을 정해야 한다고 생각합니다. 그에 반해 Util은 너무 범위가 넓은 이름인 것 같습니다. LottryClerk도 어떻게 보면 LotteryUtils로 생각할 수도 있다고 생각합니다. 
여기는 로또 번호를 만들어주므로 해당 의미를 살리는 이름으로 바꾸는 것은 어떨까요...?

2022-05-16 15:01 UTC, chae-yh commented on src/main/java/lotto/LotteryUtils.java
> +    public LotteryUtils(int number, int creationCount) {
여기도 메서드길이가 10줄 정도 되네요 validation 해주는 부분은 extract 해줄 수 있을 것 같습니다!

2022-05-16 15:01 UTC, chae-yh commented on src/main/java/lotto/LotteryUtils.java
> +            numbers.add(new Number(number++));
여기는 해당 객체가 만들어질 때마다 똑같이 45개의 숫자를 넣어주네요. static 초기화를 해서 한번만 초기화해주면 어떨까요...?

2022-05-16 15:01 UTC, chae-yh commented on src/main/java/lotto/vo/Lotteries.java
> +        return lotteries;
vo는 불변 객체로 만들어 주는 것이 좋습니다. 해당 값을 불변으로 만들려면 어떻게 하면 될까요...?
단순 final 선언만 한다면 재할당은 불가하지만, 해당 list에 값을 추가하거나 제거하는 것은 가능합니다.

2022-05-16 15:01 UTC, chae-yh commented on src/main/java/lotto/vo/Lottery.java
> +        }
여기도 메서드 길이가 10줄을 넘네요. validatation 등을 메서드 추출하면 좋을 것 같습니다!

2022-05-16 15:01 UTC, chae-yh commented on src/main/java/lotto/vo/Lottery.java
> +        while (!result && idx < size) {
이 부분은 for문 쓰면 간단히 구현 가능할 것 같은데 혹시 while문을 쓰는 이유가 있을까요...?
현재 코드는 종료가 명확하기 때문에 크게 이슈가 없지만, 실무 코드 작성 시 while문은 무한 루프에 빠지거나 할 경우 장애가 발생할 수 있어 개인적으로는 해당 작성을 피하고, for문을 사용하는 편입니다. 그래서 혹시 while문의 장점이 있는지 궁금하여 여쭤봅니다!

2022-05-16 15:01 UTC, chae-yh commented on src/main/java/lotto/vo/Lottery.java
> +    public String customToString() {
이 부분은 데이터를 표현하는 방법에 대한 부분으로, view로 옮겨도 되지 않을까요...?

2022-05-16 15:01 UTC, chae-yh commented on src/main/java/lotto/vo/Money.java
> +    private final static String NEGATIVE_AMOUNTS_OR_ZERO_CANNOT_BE_ENTERED = "1원 보다 작은 금액은 입력할 수 없습니다.";
minimum 제약 조건이 있다면, maximum 제약 조건도 주면 좋지 않을까요...?

2022-05-16 15:01 UTC, chae-yh commented on src/main/java/lotto/vo/Number.java
> +        if (number < 1) {
Lottery의 로또 범위를 이용한 validation이 이쪽에 들어가면 좋지 않을까요..?

2022-05-16 15:01 UTC, chae-yh commented on src/main/java/lotto/LotteryClerk.java
> +public class LotteryClerk {
로또 상점, 점원 등을 구별했네요 ㅎㅎ 재밌는 방법인 것 같습니다 : )
그런데 LotteryClerk와 LotteryStroe의 차이는 어떤 것인가요..?

2022-05-16 15:01 UTC, chae-yh commented on src/test/java/lotto/LotteryGameTest.java
> +class LotteryGameTest {
여기는 view 부분이라 테스트가 필요 없을 것 같습니다! 삭제해도 될 것 같아요 : )

2022-05-16 15:01 UTC, chae-yh commented on src/main/java/lotto/vo/Result.java
> +public class Result {
결과 값은 등수, 금액 등이 전부 정해져있습니다. 미리 Enum으로 선언해서 사용해보는 것은 어떨까요...?

2022-05-16 15:01 UTC, chae-yh commented on src/test/java/lotto/vo/CouponTest.java
> +    @MethodSource("천원_미만_금액")
적절한 @annotaion 사용 좋습니다 👍

2022-05-16 15:01 UTC, chae-yh commented on src/test/java/lotto/vo/LotteryTest.java
> +            new Lottery(lotteryUtils.pickRandomNumbers(6));
Lottery가 받는 값이 꼭 랜덤일 필요는 없을 것 같습니다!

2022-05-16 15:01 UTC, chae-yh commented on src/test/java/lotto/vo/ResultTest.java
> +class ResultTest {
필요 없는 테스트 클래스는 지워도 될 것 같습니다!

2022-05-16 15:01 UTC, chae-yh commented on src/test/java/lotto/vo/WinningTest.java
> +class WinningTest {
sum 메서드를 테스트 해 볼 수 있지 않을까요...?

2022-05-16 15:01 UTC, chae-yh commented on src/main/java/lotto/LotteryStatistics.java
> +            if (entry.getKey() >= 3) {
indent 2depth관련 부분이, 이 부분 말씀이시군요! 
이 부분은 if 절만 method extract 하시면 될 것 같습니다만.... 가끔씩 if 절에 return 이나 break를 쓰는 경우가 있습니다. 이 경우는 저도 경험상 1 depth로 만들기 어렵더라구요... 이런 경우에는 stream 씁니다...ㅎ.ㅎ;;

2022-05-16 15:01 UTC, chae-yh commented on src/main/java/lotto/LotteryStatistics.java
> +        for (int idx = 3; idx <= 6; idx++) {
3과 6은 무엇을 의미할까요...? 상수로 추출해보면 어떨까요...?

2022-05-16 15:01 UTC, chae-yh commented on src/main/java/lotto/LotteryStatistics.java
> +    private LotteryStatistics() {
보통 클래스 내 메소드 및 필드 순서는
1. 정적 변수 : public -> protected -> private 
2. 인스턴스 변수 : public -> protected -> private 
3. 생성자 
4. 정적 메소드
5. 메소드
6. 스탠다드 메소드 : toString, equals, hashcode 와 같은 메소드
7. getter, setter 메소드 : 클래스의 밑 부분에 위치 

로 작성해줍니다. 해당 생성자는 인스턴스 변수 밑으로 가면 좋을 것 같습니다 : )

참조 : https://www.oracle.com/java/technologies/javase/codeconventions-fileorganization.html

2022-05-18 02:02 UTC, tasklet1579 commented on src/main/java/lotto/view/Console.java
> +    private static boolean isClosed() {
Console 소스코드는 [mission-utils](https://github.com/tasklet1579/mission-utils/blob/main/src/main/java/camp/nextstep/edu/missionutils/Console.java)를 참고했습니다

자바의 리플렉션은 클래스의 구조를 분석하여 동적 로딩을 할 수 있습니다
new 키워드를 사용하지 않아도 인스턴스를 생성할 수 있고 프로그램 재실행없이 소스 코드를 교체할 수 있는 데다가 탐색을 통해서 외부에서 인스턴스를 할당할 수 있습니다
단, 탐색을 하는데 상당한 비용이 들어가고 이미 메모리에 로드가 되었는데 소스 코드가 교체된다면 에러가 발생할 수 있습니다

리플렉션의 활용적인 측면을 놓고 봤을 때 동적으로 할당된 클래스를 Object에 넣게 되면 Object의 기본 메서드뿐만 아니라 해당 클래스의 구조를 분석해서 메서드를 검색하고 실행할 수 있습니다
getMethod를 사용하면 같은 이름의 메서드라도 파라미터의 설정에 따라서 호출을 다르게 할 수고 생성자 역시 다양하게 획득할 수 있습니다
getMethod 이외에도 아래의 메서드를 사용할 수 있습니다
- getMethods : Object에서부터 해당 클래스까지 있는 모든 메서드를 찾습니다
- getDeclaredMethods : 해당 클래스에 있는 메서드만을 찾습니다

이 기능을 잘 활용하면 private이나 protected처럼 접근이 제한되어 있는 메서드도 실행할 수 있기 때문에 테스트에서 메서드의 결과를 확인할 수 있습니다

Console에서는 Scanner는 정적으로 선언하였고 getDeclaredField로 sourceClosed 변수에 접근을 가능하게 하였습니다
이렇게 프로그램 실행 도중 클래스의 멤버 변수에 접근해서 값을 확인하면 실제로 Scanner가 close 되었는지 알 수 있습니다

제가 알고 있는 것은 여기까집니다

2022-05-18 02:03 UTC, tasklet1579 commented on src/main/java/lotto/LotteryGame.java
> +    private static Winning result;
프로그램 실행 제어를 편리하게 하기 위해서 전역으로 선언했습니다
지금은 모두 지역 변수로 변경했는데 전역 변수는 상수를 제외하고는 사용하면 안될까요?

2022-05-18 02:08 UTC, tasklet1579 commented on src/main/java/lotto/vo/Lotteries.java
> +        return lotteries;
인스턴스를 생성할 때 방어적 복사를 통해서 외부와 내부의 관계를 끊어주고 get과 같은 값을 반환하는 메서드를 호출할 때는 Collections.unmodifiableList 처리하면 될까요?

2022-05-18 02:17 UTC, tasklet1579 commented on src/main/java/lotto/vo/Lottery.java
> +        while (!result && idx < size) {
조건이 증가할 때 (인덱스, 사이즈)는 for문을 사용하고 감소할 때는 while문을 사용합니다
지금 여기서는 인덱스를 증가시켰는데.. 알고리즘 문제를 풀 때 while (size-- >0) 이런식으로 썻던 것 같습니다
반복문의 반복 횟수를 가변적으로 제어 가능하다는 장점 말고는 다른 것은 생각이 나질 않네요

2022-05-18 02:24 UTC, tasklet1579 commented on src/main/java/lotto/LotteryClerk.java
> +public class LotteryClerk {
로또 발행은 LotteryStore에서 이루어지는데 로또 최소 구입 금액과 단위 금액을 확인해야 했습니다
LotteryStore에 확인하는 역할을 부여할 수도 있지만 실제 세계의 개념?을 떠올려 보았을 때 그 둘의 역할이 다르다고 생각해서 별도의 클래스로 분리해보았습니다
- LotteryClerk : 로또를 구입할 수 있는지 확인함
- LotteryStore : 로또를 발행함

2022-05-18 23:17 UTC, chae-yh requested changes
성우님 안녕하세요 피드백 잘 반영해주셨습니다 👍 
그런데 바로 merge하기에는 조금만 더 수정하면 좋을 것 같은 부분이 있습니다 관련해서는 코멘트 남겨 드렸는데 확인 부탁드립니다.

마지막까지 파이팅 입니다 : )

2022-05-18 23:17 UTC, chae-yh commented on src/main/java/lotto/LotteryProducer.java
> +        return Collections.unmodifiableList(new LinkedList<>(numbers));
방어적 복사 좋습니다 👍

2022-05-18 23:17 UTC, chae-yh commented on src/main/java/lotto/LotteryProducer.java
> +    public LotteryProducer() {
이 부분은 객체가 만들어질 때마다 numbers를 새로 만들어주네요. static block 등으로 캐시하여 반복적으로 사용할 수 있지 않을까요....?

2022-05-18 23:17 UTC, chae-yh commented on src/main/java/lotto/LotteryStatistics.java
> +    private static List<Result> results;
여기도 필드가 너무 많네요 조금 분리해볼 수 있을 것 같습니다!

2022-05-18 23:17 UTC, chae-yh commented on src/main/java/lotto/LotteryStatistics.java
> +    private static void initRewards() {
Enum으로 정의된 Reward를 사용해보면 어떨까요...?

2022-05-18 23:17 UTC, chae-yh commented on src/main/java/lotto/LotteryStatistics.java
> +    private static void match(Lottery winning, Number number) {
compare 나 match 같은 메소드는 Lotteries 혹은 Lottery에 있어야 할 것 같은 메소드인데 통계값을 내주는 현재 클래스에 있으니 어색하게 느껴집니다. 
LotteryStatistics의 역할이 너무 큰 건 아닐까요...?

2022-05-18 23:17 UTC, chae-yh commented on src/main/java/lotto/constant/Reward.java
> +package lotto.constant;
도메인 로직과 관련되어 있으니 패키지를 domain으로 보내면 어떨까요..?

2022-05-18 23:17 UTC, chae-yh commented on src/main/java/lotto/vo/Lotteries.java
> +package lotto.vo;
단순히 값을 가지고 있다기 보다는, 도메인 로직을 처리하고 있으니 domain 으로 바꾸면 어떨까요...?

2022-05-18 23:17 UTC, chae-yh commented on src/main/java/lotto/constant/Reward.java
> +    public static int find(int match) {
findReward 같이 메소드를 구체적으로 쓰는 것은 어떨까요...?

2022-05-18 23:17 UTC, chae-yh commented on src/main/java/lotto/vo/Lotteries.java
> +    private List<Lottery> lotteries;
밑에서 방어적 복사를 해주는데 여기도 final로 바꾸면 좋을 것 같습니다!

2022-05-18 23:17 UTC, chae-yh commented on src/main/java/lotto/vo/Result.java
> +    public Result(int matches, int count, int reward) {
이 부분은 Rewrad Enum을 쓰면 파라미터를 줄일 수 있거나, 아니면 해당 클래스를 없앨 수 있지 않을까요...? 단순히 값만 가지고 있는 객체의 필요성을 현재는 못느끼고 있습니다....ㅎ.ㅎ;;;

2022-05-18 23:17 UTC, chae-yh commented on src/test/java/lotto/vo/SummaryTest.java
> +        assertThat(new Summary(new LinkedList<>()).sum()).isEqualTo(0);
이 부분은 테스트를 분리해볼 수 있을 것 같습니다!

2022-05-18 23:17 UTC, chae-yh commented on src/test/java/lotto/vo/SummaryTest.java
> +        assertThat(summary.sum()).isEqualTo(2004605000);
테스트 코드는 이런식으로도 많이 쓰고, Arrays.asList 사용하시면 더 깔끔할 것 같습니다 : )
```
// given
Result result1 = new Result(3, 1, 5000);
Result result2 = new Result(4, 2, 50000);
Result result3 = new Result(5, 3, 1500000);
Result result4 = new Result(6, 1, 2000000000);
List<Result> results = Arrays.asList(result1, result2, result3, result4)

// when
Summary summary = new Summary(results);

// then
assertThat(summary.sum()).isEqualTo(2004605000);
```

2022-05-18 23:17 UTC, chae-yh commented on src/main/java/lotto/LotteryGame.java
> +    private static Winning result;
저희가 계속 불변 객체를 만드는 등의 작업을 해주는 이유는 값이 중간에 바뀌는 변수 혹은 객체들은 다루기가 어렵기 때문입니다. 전역 변수도 클래스 내에서 어디에서나 접근이 가능하기 때문에 값이 변경될 수 있고 그런 경우 해당 변수는 사용하는 입장에서는 해당 값이 자신이 원하는 값인지 확인하는 작업을 추가로 해주어야 합니다.

지금의 경우는 성우님이 작성하신 코드이고, 코드량도 많아봐야 100 line 내외라서 전역변수의 영향이 잘 느껴지지 않습니다만, 다른 사람이 작성한 코드이고 코드량이 몇만줄 정도 될 경우(실제 실무의 레거시 코드는 이런 경우가 종종 있습니다 ㅎ.ㅎ;;) 전역변수는 사용하기 정말 어려운 값이 됩니다. 반대로 안쓰자니 안쓰는 값을 필드로 가지고 있는 것도 이상하구요... 그래서 전역변수는 가능한 쓰지 않는 편이 좋을 것 같고, 마지막으로 저희들의 선배분이 말씀하신 내용으로 코멘트 마치도록 하겠습니다 : )

```
전역 데이터를 주의해야 한다는 말은 우리가 소프트웨어 개발을 시작한 초창기부터 귀가 따갑게 들었다.
심지어 전역 데이터는 이를 함부로 사용한 프로그래머들에게 벌을 주는 지옥 4층에 사는 악마들이 만들었다는 말이 돌 정도였다.
 - 마틴 파울러, 리펙토링 -
```

참고로, 리펙토링 책도 좋은 내용이 많아서 참고하셔도 좋을 것 같습니다!

2022-05-19 02:19 UTC, tasklet1579 commented on src/main/java/lotto/vo/Lotteries.java
> +    private List<Lottery> lotteries;
복사를 할 때 Arrays.asList를 사용하게 되면 Arrays의 이너 클래스인 ArrayList를 반환하게 되네요
해당 클래스는 AbstractList를 상속하고 있고 add와 같은 메서드를 호출하면 UnsupportedOperationException 에러가 발생합니다 
불변 처리한 객체에 add와 같은 메서드를 만들지는 않겠지만.. 그런 경우가 발생할 수도 있을까요?

2022-05-19 05:50 UTC, tasklet1579 commented on src/main/java/lotto/vo/Result.java
> +    public Result(int matches, int count, int reward) {
생성자 파라미터를 줄이는 것은 알겠는데 왜 클래스를 없애야하나요??

2022-05-19 05:52 UTC, tasklet1579 commented
안녕하세요
Result 클래스 관련해서 추가적인 설명 부탁드려도 될까요? 어떤 이유때문에 삭제해야될까요?

2022-05-19 14:23 UTC, chae-yh approved these changes
성우님 피드백 반영 잘해주셨습니다! 👍 
이 정도면 해당 미션의 목적은 달성한 것으로 생각되어 merge 하겠습니다! 질문 주신 내용 및 몇가지 고민해보면 좋을만한 내용은 코멘트로 남겨드리니 한 번 확인 부탁드리겠습니다 : )

고생 많으셨습니다! 다음 미션 진행 부탁드립니다!

2022-05-19 14:23 UTC, chae-yh commented on src/main/java/lotto/domain/Money.java
> +    private final static int STORE_LIMIT_AMOUNT = 100000;
피드백 반영 좋습니다 👍

2022-05-19 14:23 UTC, chae-yh commented on src/main/java/lotto/vo/Lotteries.java
> +    private List<Lottery> lotteries;
그런 경우가 발생할 수 있겠지만, 해당 객체를 사용하는 사람에게 해당 객체가 불변이라는 알람을 줄 수 있을 것 같습니다!

2022-05-19 14:23 UTC, chae-yh commented on src/main/java/lotto/vo/Result.java
> +    public Result(int matches, int count, int reward) {
질문 주신 내용은 여기서 답변 드리겠습니다!
`Result 클래스 관련해서 추가적인 설명 부탁드려도 될까요? 어떤 이유때문에 삭제해야될까요?`

우선 제가 해당 클래스의 필요성에 대해서 말씀드린 이유는 아래와 같습니다.
1. domain 내의 클래스인데, 로직 처리는 거의 하지 않고 데이터를 전달해주는 dto의 역할이 더 커 보입니다.
2. 많은 부분에서 Reward로 대체가 가능해보입니다.

제 생각에는 LotterySummary, Summary, Result가 굉장히 밀접한 관계가 있고, 조금 더 나아가면 하나의 클래스로 합칠 수 있을 것 같습니다. 예를 들어 LotterySummary에서 Map<Reward, Integer> 형태로 등수별 카운트를 가지고 있다면 굳이 Result가 없어도 되지 않을까요...?

위의 이유로 Result는 없어도 되지 않을까... 라고 생각했는데 성우님은 어떻게 생각하시는지 궁금합니다!

2022-05-19 14:23 UTC, chae-yh commented on src/main/java/lotto/LotteryProducer.java
> +public class LotteryProducer {
수정 요청은 아니지만 개인적인 의견 하나 드립니다.
제 생각에 어느 패키지에도 들어 있지 않은 클래스는 아래와 같이 분류 가능할 것 같습니다.
domain : LotteryClerk, LotteryProducer, LotteryStore, LotterySummary, TieldCalculator -> 도메인 로직을 처리하는데 너무 상위 패키지에 있음
현재위치 : LotteryGame -> main 함수가 있으므로 가장 상단에 위치
그리고, 추가로 해당 클래스들이 domain 클래스 이므로 각각에 대해 테스트 클래스는 있는 것이 좋을 것 같다는 의견도 추가로 드립니다!

혹시 관련해서는 어떻게 생각하시는지 궁금합니다!

2022-05-19 14:23 UTC, chae-yh commented on src/main/java/lotto/domain/Ticket.java
> +    private static final String LOTTERY_PURCHASE_AMOUNT_IS_IN_UNITS_OF_1000_WON = "로또 구입 금액은 1,000원 단위입니다.";
이 부분을 1000원 단위가 아닌 구입 가능한 최대 개수로 구입하게 변경해도 좋지 않을까요...? 예를 들어 1500원이 입력되었다면 1장 구입, 2000원일 경우 2장 구입 같은 형태도 좋다고 생각됩니다!

2022-05-19 14:23 UTC, chae-yh commented on src/main/java/lotto/domain/Reward.java
> +public enum Reward {
이 클래스도 테스트 코드가 있으면 좋을 것 같습니다!

2022-05-19 14:24 UTC, merged