5단계 - 로또(수동)
next-step/java-lotto-pro pull request #518
Opened 2022-05-16 14:19 UTC by wenodev

안녕하세요 리뷰어님😀 로또 5단계 요청드립니다🙏

항상 좋은 리뷰 작성해주셔서 감사드립니다!!

월요일이라 힘드셨을텐데 하루 마무리 잘 하세요👏

2022-05-16 14:55 UTC, jhhj424 commented
현재 작성된 코드는 구조도 잘 잡아주셨고, 로직도 깔끔한 것 같습니다.
그렇지만 이번 미션의 목적은 로또 구현이 아닌 TDD 연습이기 때문에, 모든 로직에 대한 테스트가 이루어지면 좋겠습니다 :)
빠진 테스트도 체크해서 다시 요청 주시면 바로 확인해보겠습니다 :)

2022-05-16 14:58 UTC, jhhj424 requested changes
안녕하세요 주원님~🙇🏻‍♂️
TDD 로또 미션의 마지막 단계까지 잘 작성해주셨네요 💯 
전체적으로 앞선 단계에서 구조를 잘 가져가주셔서 큰 무리 없이 요구사항을 만족해주셨습니다 👍 
조금 더 진행해봤으면 좋을 만한 점 코멘트 드렸는데, 확인 부탁드립니다 !
월요일이라서 더 힘드셨을텐데, 미션 진행하시느라 고생 많으셨습니다 ㅎㅎ 금방 하실 것 같으니, 바로 반영해주시고 PR 주세요 ~

2022-05-16 14:58 UTC, jhhj424 commented on src/main/java/lotto/model/PassiveQuantity.java
> +    private static void validateNumber(String price) {
해당 메서드를 `static` 으로 하신 이유가 있을까요?

---
`PassiveQuantity` 생성자에서 `quantity` 검증을 위한 메서드로 사용되고 있는데, 해당 메서드 시그니처에서 인수는 `String price` 로 되어있네요

2022-05-17 02:32 UTC, wenodev commented on src/main/java/lotto/model/PassiveQuantity.java
> +    private static void validateNumber(String price) {
static을 사용한 것과 price를 사용한건 단순 실수 같네요ㅜㅜ 꼼꼼하게 봐주셔서 감사합니다🙏

2022-05-17 09:22 UTC, jhhj424 approved these changes
안녕하세요 주원님~
마지막 미션까지 꼼꼼하게 진행해주셨네요 💯 
이번 미션동안 같이 고민한 것들이 앞으로의 미션에도 도움이 되길 바라며 마지막 단계 머지하도록 하겠습니다 ㅎㅎ
언제든 추가적으로 궁금한 점 있으시면 DM 환영하겠습니다 :)
정말 고생 많으셨습니다~ 👍

2022-05-17 09:22 UTC, jhhj424 commented on src/test/java/lotto/LottoGeneratorTest.java
> +    @DisplayName("문자가 숫자형이 아니라면 예외를 던진다")
추가적으로 꼼꼼하게 테스트 해주셨네요 💯

2022-05-17 09:22 UTC, merged

2022-05-17 09:22 UTC, jhhj424 commented on src/main/java/lotto/model/PassiveQuantity.java
> +    private static void validateNumber(String price) {
ㅎㅎ 넵 정말 고생 많으셨습니다~
저도 덕분에 더 고민해볼 수 있었네요, 감사합니다 !
앞으로의 미션도 화이팅입니다~