4단계 로또(2등)
next-step/java-lotto-pro pull request #530
Opened 2022-05-16 19:02 UTC by SanghoLee-dev

3단계 마지막 피드백 해주셨던 부분 수정해봤습니다. `Round` 가 필요 없어져서 제거 하였고 통계정보에서도 의존을 제거했습니다.
4단계 작업을 하면서 약간의 리팩토링을 해봤습니다. domain 패키지를 추가랑 메시지 객체를 추가하였습니다.
다음 당첨번호를 추가 하였습니다. `WinningNumbers` 객체로 기존 당첨번호 6개와 보너스번호를 관리하는 역할 입니다.
2등 로직이 추가되면서 여러 코드의 리팩토링을 진행하였고 그에따라 테스트코드도 변경했습니다.

2022-05-16 23:47 UTC, seokhongkim requested changes
상호님, 4단계 빠르게 구현해주셨네요. 👍 

3단계에서 클래스 역할을 잘 나누고, 구조도 잘 잡아주셔서 코드 수정이 많지 않았던 것 같아요.
4단계 진행하시면서 패키지 분리하신 것도 좋았습니다.

코멘트 조금 남겼으니, 확인 부탁드립니다. 🙏

2022-05-16 23:47 UTC, seokhongkim commented on src/main/java/lotto/domain/LottoWinResult.java
> +    public static LottoWinResult confirm(final int count, final boolean bonusCorrect) {
`BiPredicate` 라는 것을 학습해보신 후, 등수를 검증하는 `filter` 로직에 적용해서 리팩토링 해보시면 좋을 것 같아요!

2022-05-16 23:47 UTC, seokhongkim commented on src/main/java/lotto/domain/Lotto.java
> +package lotto.domain;
도메인을 별도 패키지로 분리하셔서 코드 구조 파악이 더 용이하네요 👍

2022-05-16 23:47 UTC, seokhongkim commented on src/main/java/lotto/ResultView.java
> +        System.out.printf(PRINT_LOTTO_NUMBERS, lotto.toStringPickNumbers());
`lotto` 의 `toStringPickNumbers` 는 도메인보다는 UI에 보여주기 위한 것으로 보이네요!
코드 의존의 방향은 `ResultView` -> `Lotto` 이지만, `Lotto` 가 화면이 어떻게 보여질 지 알고 있어야 하는 것 같습니다.
화면에 보여주기 위한 값 정리를 뷰로 분리하면 도메인 로직을 더 단순하게 만들  수 있을 것 같아요!

2022-05-17 15:28 UTC, SanghoLee-dev commented on src/main/java/lotto/ResultView.java
> +        System.out.printf(PRINT_LOTTO_NUMBERS, lotto.toStringPickNumbers());
메시지를 전달한다 라는 개념에만 매몰되어 있었던거 같습니다. 그래서 UI 로직이 `Lotto` 도메인 로직에 포함된거 같아요.
번호를 로또 번호를 반환하여 UI 로직에서 출력 문자열을 만들도록 변경 하겠습니다.

2022-05-17 15:28 UTC, SanghoLee-dev commented on src/main/java/lotto/domain/Lotto.java
> +package lotto.domain;
앞으로 단계를 더 진행하면서 코드 구조 파악에 용이하도록 패키지를 더 추가하겠습니다.

2022-05-17 16:07 UTC, SanghoLee-dev commented on src/main/java/lotto/domain/LottoWinResult.java
> +    public static LottoWinResult confirm(final int count, final boolean bonusCorrect) {
`BiPredicate` 를 이용해서 판별식 자체를 enum 에 매핑 시킬수가 있네요. 말씀해주신대로 리팩토링 해봤습니다.

2022-05-18 00:25 UTC, seokhongkim approved these changes
상호님, 로또 미션 4단계 잘 마무리 해주셨어요! 💯 
피드백 드린 내용도 잘 반영해주셨습니다.

4단계 PR은 여기서 머지하도록 하겠습니다.
5단계 미션도 잘 부탁드립니다. 🙏

2022-05-18 00:25 UTC, merged