Step4 - 로또 (2등)
next-step/java-lotto-pro pull request #538
Opened 2022-05-17 11:30 UTC by bestsilver

안녕하세요 태엽님!  : - )
로또4단계 구현해보았습니다!
3단계에서 말씀해주셨던 부분도 같이 수정해보았습니다.

태엽님께서 책임 분리에 대해 자세히 알려주신 덕분에 많이 배운 것 같습니다!
감사합니다!

2022-05-17 16:53 UTC, enemfk777 requested changes
안녕하세요 고은님 :)
3단계에서 잘 구현해주신덕에 4단계는 비교적 손쉽게 진행하신 것 같네요 👍
몇가지 소소한 코멘트 드렸으니 금방 반영해 주실 수 있을 것 같습니다!
그럼 반영후 다시 요청 부탁드립니다!

2022-05-17 16:53 UTC, enemfk777 commented on src/main/java/lotto_auto/model/LottoRank.java
> +        LottoRank resultRank = rank.orElse(NOTHING);
두 덩어리로 나뉘지 않고 합쳐질 수 있을것 같아요 :)

2022-05-17 16:53 UTC, enemfk777 commented on src/main/java/lotto_auto/model/LottoRank.java
> +        return resultRank.isSecondRank(matchedBonusBall) ? SECOND : THIRD;
stream에서 findFirst()를 한뒤
조건문에서 SECOND 여부와 matchedBonusBall 여부면 THRID를 반환하고 나머지는 그대로 반환하는 편이 가독성이 더 좋을 것같아요

2022-05-17 16:53 UTC, enemfk777 commented on src/main/java/lotto_auto/model/Lotto.java
> +        return lottoNumbers.getLottoNumberSet().contains(number);
아마 강의에서 포비가 "메세지를 보내라" 라는 말씀을 하셨을지 모르겠는데요 😁
getter로 꺼내는 습관을 버리고
객체 스스로 해결할 수 있게 계속 의식적으로 연습해보시는건 어떨까요?
lottoNumbers에게 number를 전달하면 스스로 포함 여부를 반환할 수 있을 것 같아요

2022-05-17 16:53 UTC, enemfk777 commented on src/main/java/lotto_auto/model/WinningLotto.java
> +        if (this.getLottoNumbers().getLottoNumberSet().contains(bonusBall)) {
이부분도 위에서 말씀드린것 처럼 :) 메세지를 보내보세요!!

2022-05-17 16:53 UTC, enemfk777 commented on src/main/java/lotto_auto/model/WinningLotto.java
> +public class WinningLotto extends Lotto {
상속은 부모 - 자식 관계가 "is a" 관계일 때 사용하는 편이 좋습니다.
"당첨 조건" 과 "로또" 가 과연 "is a" 관계로 볼 수 있을까요? 
대부분의 경우에는 "is a" 관계보단 "has a" 관계 인 경우가 많습니다.
그렇다면 조합을 사용해 보시는건 어떨까요?
아래는 관련 아티클입니다.
https://tecoble.techcourse.co.kr/post/2020-05-18-inheritance-vs-composition/

2022-05-18 09:57 UTC, bestsilver commented
말씀하신 수정사항 변경해보았습니다!

2022-05-18 15:41 UTC, enemfk777 approved these changes
안녕하세요 고은님:)

피드백 잘 반영해주셨습니다 🙇‍♂️
어느새 다음 단계가 이번 미션의 마지막 단계네요..!
이번단계는 이만 머지하겠습니다.
다음 단계도 화이팅입니다 💪

2022-05-18 15:41 UTC, enemfk777 commented on src/main/java/lotto_auto/model/WinningLotto.java
> +        if (lotto.getLottoNumbers().isContain(bonusBall)) {
메세지를 Lotto에 직접 보낼수 있을것 같아요 :)

2022-05-18 15:42 UTC, merged