Step3 - 로또(자동) 리뷰 요청드립니다
next-step/java-lotto-pro pull request #550
Opened 2022-05-17 18:18 UTC by millennion-jin

빨리빨리 진행을 하고 싶었는데 일이 너무 바빠서 과제가 늦어지고 있습니다 ㅠ
뭔가 질문 드리고 싶었던 것들이 좀 있었는데
지금 머리 속이 멍해서 생각이 안 나네요
수정 사항 반영이나 Step4 때 질문 드리겠습니다 ㅠ
리뷰 잘 부탁 드립니다

2022-05-18 12:29 UTC, seokhongkim requested changes
진웅님, 업무로 바쁘신 와중에도 과제 잘 진행해주셨어요! 👍 
여러 클래스를 만들고, 각 클래스에 책임을 나눠서 구현하려는 노력을 해주신 게 보입니다.
4단계 요구사항에 있는 내용도 일부 구현을 해주신 것 같네요.

피드백 조금 남겼으니 확인 부탁드립니다.
궁금하신 내용은 언제든 깃헙 코멘트나 슬랙 DM 남겨주시면 확인하는대로 답변 드리겠습니다. 😀

2022-05-18 12:29 UTC, seokhongkim commented on src/main/java/lotto/constants/LottoConstants.java
> +    public static final int MIN_LOTTO_NUMBER = 1;
로또 최솟값, 최댓값은 어느 도메인에서 관리할 수 있는 규칙일까요? 로또 사이즈도 관리할 수 있는 도메인이 있을까요?
별도의 상수 클래스를 놓는 것이 유용할 때도 있지만, 특정 도메인에서 관리할 수 있는 값을 상수 클래스로 옮기는 경우 상수 클래스가 비대해지고, 도메인과 거리가 멀어지는 단점도 있을 것 같아요!

2022-05-18 12:29 UTC, seokhongkim commented on src/main/java/lotto/domain/Lotto.java
> +    private final List<LottoNumber> numberList;
로또 번호를 관리하는 컬렉션을 List 로 정하신 이유가 있을까요?

2022-05-18 12:29 UTC, seokhongkim commented on src/main/java/lotto/domain/Lotto.java
> +        numberList.sort(Comparator.comparing(LottoNumber::getNumber));
숫자를 정렬하는 것을 도메인에서 관리해야 할 필요가 있을까요?

2022-05-18 12:29 UTC, seokhongkim commented on src/main/java/lotto/domain/LottoMatchingResult.java
> +    private boolean isBonusMatched;
4단계 기능 요구사항인데 먼저 구현하신 것 같네요!

2022-05-18 12:29 UTC, seokhongkim commented on src/main/java/lotto/domain/LottoNumber.java
> +    private final Integer number;
`LottoNumber` 에 number 가 없을 수 있을까요? 반드시 있어야 한다면, primitive type 을 사용하시지 않은 이유는 무엇일까요?

2022-05-18 12:29 UTC, seokhongkim commented on src/main/java/lotto/domain/LottoNumber.java
> +public class LottoNumber {
`LottoNumber` 가 1~45 사이의 값만 가질 수 있다면 미리 객체를 만들어서 재사용해도 좋을 것 같아요!

2022-05-18 12:29 UTC, seokhongkim commented on src/main/java/lotto/domain/LottoNumberPool.java
> +public class LottoNumberPool {
`LottoNumberPool` 에서 자동으로 로또 번호를 추첨하는 역할을 해주는 것 같네요!
클래스의 역할을 더 잘 나타내줄 수 있는 이름이 있을까요?

2022-05-18 12:29 UTC, seokhongkim commented on src/main/java/lotto/enums/LottoRank.java
> +                .filter(lottoRank -> lottoRank.countOfMatch == countOfMatch)
`BiPredicate` 를 학습해보신 후, 이 부분을 리팩토링 해보시면 좋을 것 같아요!

2022-05-18 12:29 UTC, seokhongkim commented on src/main/java/lotto/domain/LottoMatchingResult.java
> +    public void addCountOfMatch() {
`LottoMatchingResult` 를 `countOfMatch` 계산이 끝난 후 생성한다면 불변 객체로 만들 수 있지 않을까요?
불변 객체로 만들었을 때의 장점과 함께 생각해보시면 좋을 것 같아요!

2022-05-18 12:29 UTC, seokhongkim commented on src/main/java/lotto/domain/LottoNumberPool.java
> +        shuffleLottoNumberList();
`generateLotto` 가 호출 될 때마다 필드의 `numberList` 가 바뀌겠네요.
`numberList` 가 변경되도록 공유할 필요가 있을까요?

2022-05-18 14:21 UTC, millennion-jin commented on src/main/java/lotto/domain/Lotto.java
> +        numberList.sort(Comparator.comparing(LottoNumber::getNumber));
화면 출력시에만 정렬이 되어도 상관이 없는데 쓸데없이 넣은 것 같습니다
해당 부분은 옮겨두도록 하겠습니다

2022-05-18 14:22 UTC, millennion-jin commented on src/main/java/lotto/domain/LottoMatchingResult.java
> +    private boolean isBonusMatched;
4단계 항목을 미리 봐둬서 만들다가 약간 반영이 되었습니다 ㄷㄷ

2022-05-18 14:33 UTC, millennion-jin commented on src/main/java/lotto/domain/Lotto.java
> +    private final List<LottoNumber> numberList;
딱히 List로 정할 필요는 없었지만 아래의 코드와 같이 도메인 내에서 쓸데없는 정렬을 하고 있었고
1~45의 로또번호들을 List로 관리하고 subList를 가져다 사용하고 있어 List로 정하게 되었습니다
다른 컬렉션으로 변경시 더 나아지는 점이 있을까요?

2022-05-18 14:36 UTC, millennion-jin commented on src/main/java/lotto/domain/LottoNumberPool.java
> +public class LottoNumberPool {
저도 이름이 좀 미묘한 것 같다고 생각했었습니다
LottoGenerator로 클래스명을 변경하고자 합니다

2022-05-18 14:45 UTC, millennion-jin commented on src/main/java/lotto/domain/LottoNumberPool.java
> +        shuffleLottoNumberList();
요구사항 내용 중

힌트
로또 자동 생성은 Collections.shuffle() 메소드 활용한다.

를 사용하게 될 경우 뒤섞인 list를 리턴하는게 아니라 현재 객체 내에서 순서를 뒤섞게 되는데
이미 뒤섞인 list를 다시 섞어도 랜덤은 랜덤이니
계속해서 list를 다시 생성해줄 필요 없이 생성해둔 객체를 계속해서 사용하는 것이 효율적이라 판단했습니다

2022-05-18 15:03 UTC, millennion-jin commented on src/main/java/lotto/domain/LottoMatchingResult.java
> +    public void addCountOfMatch() {
최초에는 불변 객체로 만드려고 했었지만 indent depth 1 제한 조건으로 인해 
별 생각 없이 객체 내에서 카운트를 증가시키는 구조로 선회가 되었었습니다.
하지만 아무래도 불변 객체로 사용하는 것이 차후 데이터가 변경되는 문제가 없을테니 불변 객체 형태로 변경하도록 하겠습니다

2022-05-18 18:10 UTC, millennion-jin commented on src/main/java/lotto/constants/LottoConstants.java
> +    public static final int MIN_LOTTO_NUMBER = 1;
로또 숫자의 최소값, 최대값은 LottoNumber 에서 관리가 될 것 같고
로또 사이즈의 경우 Lotto 에서 관리가 될 것 같습니다
이전에는 2개 클래스 이상에서 사용되는 상수를 상수 클래스에서 관리하는 습관이 있었는데
확실히 도메인과 멀어지는 문제가 있을 것 같아 상수 선언 시 좀 더 고민을 해봐야겠습니다

2022-05-18 18:31 UTC, millennion-jin commented on src/main/java/lotto/domain/LottoNumber.java
> +    private final Integer number;
Integer를 사용한 것은 LottoNumber의 equals 를 overriding 하면서 두 LottoNumber 간의 숫자 비교를 할 때 Integer의 equals를 사용하는 것이 더 깔끔하지 않을까 하는 생각으로 사용을 했었습니다.
현재 int로 변경을 진행하였습니다
LottoNumber에 number 변수가 없이 어떻게 구현이 되어야 하는지 까지는 생각이 닿지 않아 이 부분은 문의를 드립니다.

2022-05-18 18:34 UTC, millennion-jin commented on src/main/java/lotto/domain/LottoNumber.java
> +public class LottoNumber {
현재 상태로는 LottoNumberPool, 수정 될 클래스 명으로는 LottoGenerator에서 1-45 까지의 LottoNumber 객체들을 미리 만들어 놓고 Collections.shuffle 을 사용해 LottoNumber 리스트를 뒤섞은 후 앞의 6개 객체의 sublist를 가져다 사용하는 방식으로 구현이 되어있습니다

2022-05-18 18:34 UTC, millennion-jin commented on src/main/java/lotto/enums/LottoRank.java
> +                .filter(lottoRank -> lottoRank.countOfMatch == countOfMatch)
해당 내용 학습 후 리팩토링을 진행해 보겠습니다

2022-05-19 17:12 UTC, millennion-jin commented on src/main/java/lotto/enums/LottoRank.java
> +                .filter(lottoRank -> lottoRank.countOfMatch == countOfMatch)
BiPredicate 를 계속해서 메서드 처럼 사용하려고 하다보니
사용해도 개선이 된 것 같지가 않아 이 부분을 개선하기 위해 많은 시간을 들였습니다.
그러다 인터넷에서 실제 적용된 사례들을 확인해본 결과
BiPredicate 의 강점은 함수형 언어처럼 변수로 사용이 가능하다는 것이었음을 깨닫게 되서
그 방향으로 수정을 진행하였습니다.

처음엔 이런 걸 왜 사용하라고 하셨나 했는데
기존의 올드한 상식을 조금이나마 깰 수 있는 좋은 경험이었습니다
감사합니다.

2022-05-20 00:15 UTC, seokhongkim commented on src/main/java/lotto/domain/Lotto.java
> +    private final List<LottoNumber> numberList;
`Lotto` 당첨 번호를 추첨할 때 컬렉션에 데이터가 존재하는지 확인할텐데, 다른 컬렉션을 사용하면 성능상의 이점을 얻을 수 있을 것 같아요.
또한, 로또 번호가 중복이 될 수 없다는 점을 코드에서 명시적으로 나타낼 수 있는 컬렉션도 있을 것 같네요.

tip: `HashSet`, `TreeSet` 과 `List` 를 비교했을 때 어떤 차이점이 있는지 학습해보시면 좋을 것 같습니다. 😀

2022-05-20 00:17 UTC, seokhongkim commented on src/main/java/lotto/domain/LottoNumber.java
> +    private final Integer number;
`number` 변수는 필요해요. 제가 질문을 잘 못 드렸네요. 😅 
`number` 의 값이 필수라면, nullable 한 wrapper type 을 사용하신 이유가 무엇일까? 궁금했어요.
`int` 로 변경하여 해결하신 것 같습니다!

2022-05-20 00:25 UTC, seokhongkim approved these changes
진웅님, 로또 미션 3단계 잘 진행해주셨어요. 👍 

코멘트 남긴 부분은 4단계에서 고민해보셔도 충분할 것 같아서, 3단계 PR은 여기서 머지하도록 하겠습니다.
4단계에서 뵙겠습니다!

2022-05-20 00:25 UTC, seokhongkim commented on src/main/java/lotto/domain/Lotto.java
> +            countOfMatch += hasNumber(lotto.get(index)) ? 1 : 0;
3항 연산자 사용은 지양해주세요!
indent 를 피하기 위해 if 문 대신 3항 연산자를 사용하신 것으로 생각되는데, 맞을까요?
3항 연산자도 if 문과 동일한 역할이므로 indent 가 있는 것으로 보입니다.

tip: `hasNumber` 의 이름이 변경되면, 일치하는 데이터가 존재할 때 카운트를 증가시키거나 1을 반환하는 역할로도 써볼 수 있지 않을까요?

2022-05-20 00:25 UTC, seokhongkim commented on src/main/java/lotto/enums/LottoRank.java
> +                .filter(lottoRank -> lottoRank.matchingBiPredicate.test(countOfMatch, isBonusMatched))
`BiPredicate` 를 잘 이용해 주셨네요! 💯

2022-05-20 00:25 UTC, seokhongkim commented on src/test/java/lotto/domain/LottoGeneratorTest.java
> +}
파일 마지막에 newline 이 없네요.
파일 마지막에 newline 이 있다면 어떤 장점이 있을까요? 왜 깃헙에서는 파일 마지막에 newline 이 없다는 경고를 띄워줄까요?

2022-05-20 00:25 UTC, merged

2022-05-20 00:58 UTC, millennion-jin commented on src/main/java/lotto/domain/Lotto.java
> +    private final List<LottoNumber> numberList;
현재는 validate 메서드 내에서 HashSet을 하나 더 생성해서 중복 건수가 있는지를 체크했었는데
subList를 가지고 ArrayList를 한 번 만들었다가 HashSet을 또 생성해서 중복체크를 하는 것 보다는
subList에서 바로 HashSet을 생성해서 Set 구조로 사용하는게 나을 것 같네요
이 부분은 변경하도록 하겠습니다

2022-05-20 01:02 UTC, millennion-jin commented on src/main/java/lotto/domain/Lotto.java
> +            countOfMatch += hasNumber(lotto.get(index)) ? 1 : 0;
넵 맞습니다 indent를 피해보고자 꼼수를 썼지만 역시 좀 그런 것 같습니다
이 부분은 수정하도록 하겠습니다