Step5 - 로또(수동)
next-step/java-lotto-pro pull request #581
Opened 2022-05-20 07:12 UTC by yulmucha

안녕하세요.
드디어 마지막 단계네요.
그동안 감사했습니다.

2022-05-21 11:48 UTC, joojimin requested changes
안녕하세요~ 전율님!
리뷰가 많이늦어서 죄송합니다 ㅠㅠ
수익률 계산하는 부분에 버그가있는것같아요 
나올수있는 숫자와 형이 맞는지 확인부탁드립니다!!

2022-05-21 11:48 UTC, joojimin commented on src/main/java/lotto/GameManager.java
> +            return null;
Null을 반환하기보다 Exception을 던져서 그걸 트라이하는 방식으로 후처리하면 어떨까요~? 
에러핸들링을 위한 null처리는 다른문제를 야기할수 있을 것 같습니다!

2022-05-21 11:48 UTC, joojimin commented on src/main/java/lotto/GameManager.java
> +            return null;
동일한 처리가 몇부분보이는데 다같이한번 생각해주시면 좋을거같아요!

2022-05-21 11:48 UTC, joojimin commented on src/main/java/lotto/domain/ExceptionMessage.java
> +public enum ExceptionMessage {
메세지 Enum 정의 👍 👍

2022-05-21 12:06 UTC, yulmucha commented
> 안녕하세요~ 전율님! 리뷰가 많이늦어서 죄송합니다 ㅠㅠ 수익률 계산하는 부분에 버그가있는것같아요 나올수있는 숫자와 형이 맞는지 확인부탁드립니다!!

음.. 확인해 보았지만 특별히 이상한 점은 찾지 못했습니다.
등수별 (당첨금 x 당첨 개수)의 총합을 구입 금액(실제 구입에 사용된 금액. 14700원이면 14000원)으로 나눈 후 소수점 셋째 자리에서 반올림해서 보여주고 있습니다.

2022-05-21 12:18 UTC, yulmucha commented
아 0으로 나누는 경우가 있네요

2022-05-21 12:59 UTC, yulmucha commented on src/main/java/lotto/GameManager.java
> +            return null;
혹시 아래와 같은 방식을 말씀하시는 것인가요?
아래와 같이 하고 싶었지만 indent depth가 2가 되어서 부득이 함수를 추출하고 null을 반환하는 방식으로 했습니다.
아니라면 조언 부탁드립니다.
```java
private NumberOfGames numberOfManualLottoGames() {
    while (true) {
        try {
            return new NumberOfGames(InputView.readNumberOfManualLottoGames());
         } catch (IllegalArgumentException e) {
            ResultView.printExceptionMessage(e.getMessage());
         }
     }
}
```

2022-05-22 10:58 UTC, joojimin requested changes
안녕하세요 승훈님!

당첨금 x 당첨 개수 << 이부분을 계산하는 타입이 int여서 overflow가 나는데요!
최고당첨금액이 여러개인 케이스를 확인해보시면될것같습니다!

2022-05-22 10:58 UTC, joojimin commented on src/main/java/lotto/GameManager.java
> +            return null;
넵 제가생각한방식은 이렇게입니다~! 
indent depth가 2여서 문제가된다면 try-catch부분을 다시 메서드로 분리하면될거같아요~

2022-05-22 12:59 UTC, yulmucha commented on src/main/java/lotto/GameManager.java
> +            return null;
try-catch 부분을 메서드로 분리하더라도, 분리한 메서드에서 null을 반환하지 않고 exception을 던지면 while문 안에는 try-catch가 없기 때문에 잘못된 입력이 들어오면 에러와 함께 프로그램이 그냥 종료됩니다.(에러를 발생시키지 않고 다시 입력받는 것이 목적)

아래처럼 재귀를 사용하는 방법도 되긴 되겠지만, 꼬리재귀 최적화가 되지 않고 입력자가 마음만 먹으면 스택오버플로를 낼 수 있기 때문에 안전하지 않아 보입니다.
```java
private NumberOfGames numberOfManualLottoGames() {
    try {
        return new NumberOfGames(InputView.readNumberOfManualLottoGames());
    } catch (IllegalArgumentException e) {
        ResultView.printExceptionMessage(e.getMessage());
        return numberOfManualLottoGames();
    }
}
```

2022-05-22 14:33 UTC, yulmucha commented
총 당첨금 계산 시 오버플로가 날 수 있는 부분 고쳤습니다.
또한, 수동 개수가 총 구입 개수를 초과할 수 있는 버그를 발견하여 수정했습니다.
입력 받는 부분은 일단 indent depth가 2이더라도 null을 반환하지 않게 했습니다.

2022-05-22 15:08 UTC, joojimin approved these changes
안녕하세요~ 피드백반영해주시고 고민하시느냐고 고생하셧습니다!
피드백의 목적은 단순히 그걸따르라는 수정의목적이아닌 해당부분을 다른방식으로 생각해보라는 의미이므로 고민해보시고 맞는부분으로 수정해주시면됩니다 ㅎㅎ
로또미션 고생하셧습니다!

2022-05-22 15:08 UTC, merged