로또 (2등) 기능 구현
next-step/java-lotto-pro pull request #584
Opened 2022-05-20 14:26 UTC by rockpro87

저번 과제 피드백을 반영한 후 기능 구현을 하니 생각보다 쉽게 구현이 되었습니다.
그리고 테스트가 있으니 정말 코드 수정하는게 좋네요 👍 

과제 속도는 느려서 불안한 감도 있지만 남은기간 노력해야겠습니다 ㅠㅠ
좋은 피드백 주셔서 감사합니다.

2022-05-21 04:26 UTC, wooobo requested changes
안녕하세요 형록님!

코드속에서 많은 고민이 느껴집니다 :+1: 

몇가지 코멘트 남겨 드렸는데, 확인해보시고 
재요청 부탁드려요~ :pray:

2022-05-21 04:26 UTC, wooobo commented on src/main/java/lotto/controller/LottoController.java
> +        Store store = new Store(cashier.buyCount());
`Store`의 역할이 다소 모호한것 같아요 :thinking: 
`Store` 가 하는 역할이 `Lottos`를 생성하는 것만 있다면 꼭 필요할까요?

2022-05-21 04:26 UTC, wooobo commented on src/main/java/lotto/model/Cashier.java
> 클래스의 이름은 객체가 노출하고 있는 기능에 기반해서는 안됩니다!. 클래스의 이름은 무엇을 하는지가 아니라 무엇인지에 기본해야합니다. - 엘레강트 오브젝트 발췌 

`Cashier`는 다른 클래스들이 보았을때 다소 모호한 의미를 가지고 있지 않을까 생각해봤어요.
그렇다면, 좀 더 분명한 이름이 없을까요?

2022-05-21 04:26 UTC, wooobo commented on src/main/java/lotto/model/Lotto.java
>      private List<Integer> createNumbers() {
인스턴스 변수에서 
`private final List<Integer> numbers;` 가 있는데 `Integer`가 아닌 1-45까지의 숫자를 가질수 있는 객체가 있으면 어떨까요?

2022-05-21 04:26 UTC, wooobo commented on src/main/java/lotto/model/Organizer.java
>          }
`"당첨 번호는 6개 입력해야합니다."`
`"당첨 번호는 슷자만 입력가능합니다."`
`"중복된 숫자는 입력 불가합니다."`
해당 책임을 가져야할 클래스가 있고 그러한 클래스들에서 직접 책임을 가지게 하면 어떨까요?
`Organizer`가 다소 많은 검증을 하고 있는것 같아요!

> `String numbersText` 인자가 아닌 특정 클래스로 받아볼수 있을것 같기도해요.
그렇다면 이미 검증된 타입을 받을수 있을테니까요.

2022-05-21 04:27 UTC, wooobo commented
아래 사항에 대해서 한번더 고민해 보시면 좋을것 같아요 :pray:

```
규칙 3: 모든 원시값과 문자열을 포장한다.
규칙 8: 일급 콜렉션을 쓴다.
클래스를 작은 단위 나누어 본다

```

예시를 들어본다면,

- `Number` : 1~45까지의 숫자 하나를 가지는 클래스
- `Lotto` : `Number`를 6개 가지는 일급콜렉션
- `Lottos` : `Lotto` 목록을 가지는 일급콜렉션

2022-05-22 14:51 UTC, rockpro87 commented on src/main/java/lotto/controller/LottoController.java
> +        Store store = new Store(cashier.buyCount());
고민끝에 제거하기로 했습니다.

2022-05-22 14:55 UTC, rockpro87 commented on src/main/java/lotto/model/Cashier.java
모호한 기준이 좀 모호하네요 ㅠㅠ Counter로 바꾸어봤습니다. 그런데 어떤 이름이 좋을까요? 리뷰어 님의 의견도 듣고 싶습니다.
엘레강트 오브젝트에서 발췌하신 내용은 이해가 가는데... 모호함의 기준이 조금 궁금하긴해요~!

2022-05-22 15:00 UTC, rockpro87 commented
수정하다보니 많은 부분을 고치게 되었네요. 피드백은 적었지만 많은 생각을 하게해주었습니다.
무언가...정답을 자꾸 찾으려는 제 모습이 보여 걱정이긴 하네요..

2022-05-23 13:33 UTC, wooobo requested changes
피드백에 대해 고민해주셔서 감사합니다 :bow: 

추가적으로, 저의 관점과 코멘트 작성해 두었습니다.!

정답을 찾기보다는 이런 관점도 있구나 생각해주시면 좋을것 같습니다 :pray: 
다양한 방법을 시도해보시는것을 추천드립니다.

궁금한 사항있으시면 DM 주세요!

화이팅입니다!

2022-05-23 13:33 UTC, wooobo commented on src/main/java/lotto/model/Counter.java
> +public class Counter {
네이밍에 관해서는 주관적인 부분이 많이 작용하므로 조심스럽습니다 :sweat_smile:
`Cashier`처럼 `-er`로 끝나는 클래스들은, 행동에 집중하고 필요한 데이터를 바인딩한다고 볼수 있을것같습니다.

반면에, `Money` 라고 짓는다면 데이터를 만들고 행동을 바인딩한다고 볼수 있을것 같습니다.(바라보는 관점에 따라 아니게 보일수도 있습니다!)

- `cashier.mod(1000)` 캐셔가 어떤 데이터에 1000을 나눈 나머지를 준다. 
  -  `캐셔를 나눈다`? 다소 어색합니다.
- `money.mod(1000)` `money`를 1000을 나눈 나머지를 준다.
  -  `머니를 나눈다`는 개인적으로는 납득이 됩니다.
 
그렇다면, 다시 `엘레강트 오브젝트`의 내용으로 돌아가 생각해보겠습니다.
`Cashier`는 무엇을 하는지에 중점을 가지고 있다고 생각합니다. _돈을 계산한다_
`Money`는 돈 그 자체입니다. 무엇인지를 표현하고 있습니다.
`Cashier`는 수동적이고 `Money`는 능동적이라는 느낌이 들었으면 좋겠습니다!

이것은 객체지향 프로그래밍 사고방식? 이라고 볼수 있을것 같아요.
하나의 객체를 만들었다는건 데이터가 있고 그 데이터 기반으로 메서드들이 만들어 지므로써,
클래스 내부의 데이터와 메소드의 응집도가 높아지고, 가독성, 유지보수성도 향상 될 수 있다고 생각해요!

정리하자면,
`Cashier`는 아주 다양한 메서드(행동)을 가질수 있다는 측면에서 모호하다고 말씀드렸다고 볼수 있을것같아요. 이것을 다르게 표현하자면 시간이 갈수록 클래스의 책임에 부합하지 않는 메서들의 집합소가 될 수 있다고 표현 할 수 있을것 같아요.

모호하다고 표현한 저의 관점을 최대한 공유하기 위해 길게 작성한 부분 양해 부탁드립니다 :pray: 
정답은 없습니다! ^^

형록님의 생각도 궁금하네요 :smile: 

추가적으로 궁금하신 부분이 있다면 슬랙 DM 환영합니다!


(내용추가)
'er'로 끝나는 객체를 만들지 마십시오.`에 대해 검색해보셔도 좋을것같아요!

2022-05-23 13:33 UTC, wooobo commented on src/main/java/lotto/model/BonusNumber.java
> +public class BonusNumber {
`BonusNumber` 또한 1~45까지의 숫자를 가져야 하는 조건이 있을것같아요.
그러한, 객체가 `LottoNo`와 똑같다고 볼수 있지 않을까요?

그렇다면, `checkBonusNumber` 메서드가 애매할 것같은데요.
보너스번호와 이번주 로또번호를 가지는 `Organizer`에게 위임 할 수도 있을것 같아요 :thinking: 

저의 관점일 뿐이며, 정답은 없습니다!

2022-05-23 13:33 UTC, wooobo commented on src/main/java/lotto/model/LottoNo.java
> +    public static List<LottoNo> toLottoNoList(List<Integer> numbers) {
인스턴스 변수 `lottoNo`를 사용하고 있지 않다면, `LottoNo` 객체가 해당 메서드를 가지고 있을 필요가 있을까요? :thinking:

2022-05-23 13:33 UTC, wooobo commented on src/main/java/lotto/model/LottoNumbersInput.java
> +        }
```
6개 입력해야합니다.
중복된 숫자는 입력이 불가합니다.
```
`Lotto`가 직접 검증해야 하지 않을까요?

---

`숫자만 입력가능합니다.` 
`LottoNo`가 직접 검증해야 하지 않을까요?

2022-05-23 13:33 UTC, wooobo commented on src/main/java/lotto/model/Organizer.java
> +    private final WinningNumber winnerNumbers;
`WinningNumber`,`BonusNumber`를 같은 객체에 넣는 아이디어 좋은것 같아요! :+1:

2022-05-23 13:33 UTC, wooobo commented on src/main/java/lotto/model/WinningNumber.java
> +    private final List<Integer> numbers;
`WinningNumber` 또한 1~45사이의  숫자 이면서 중복되지 않는 6개의 로또번호를 가져야 하지 않을까요?

2022-05-24 14:40 UTC, rockpro87 commented on src/main/java/lotto/model/Counter.java
> +public class Counter {
객체 지향에 대해 아직 모르는 지식이 많네요.
부족한 배경 지식으로는 부족한 질문밖에 나오지 않겠군요 ㅠㅠ 
객체에 대한 지식을 더 습득해야 함을 느끼네요. 좋은 답변 감사합니다.

2022-05-24 14:40 UTC, rockpro87 commented on src/main/java/lotto/model/BonusNumber.java
> +public class BonusNumber {
두 값을 가지고 있는 곳에서 하는게 좋겠네요 수정해보았습니다~!

2022-05-24 14:41 UTC, rockpro87 commented on src/main/java/lotto/model/LottoNo.java
> +    public static List<LottoNo> toLottoNoList(List<Integer> numbers) {
그러네요 필요 없는 것으로 판단되어 제거했습니다!

2022-05-24 14:44 UTC, rockpro87 commented on src/main/java/lotto/model/LottoNumbersInput.java
> +        }
처음부터 숫자만 입력 가능하도록 LottoNo 객체가 설계되었을 경우 검증 주체는 어디가 되어야 할까요?
다른 부분은 Lotto 객체에서 검증을 하도록 변경을 해보았는데... LottoNo는 조금 애매하네요.
클래스 생성에서부터 문자열 입력 자체가 되지 않아 컴파일이 불가능한데.. 별도로 문자열을 받는 생성자를 추가하여 검증해야 할지 고민이 됩니다. 
일단 제 의견은 객체 설계가 숫자만 받도록 되었다면 검증이 되었다고 생각하는데... 어떻게 진행하는게 좋을지 리뷰어님 의견도 듣고싶네요~!

2022-05-24 14:51 UTC, rockpro87 commented
리뷰어님의 의견을 보고 전체적으로 리팩토링을 진행해보았습니다.
많은 부분을 제거하게 된 것 같네요. 코드상으로는 간소화 되었지만 좋은 방향인지는 좀 애매하네요.
특히 WinningNumber, BonusNumber 를 각각 개체 생성했던 것을 리팩토링 하니 단순히 동일한 객체를 생성하는 데 그치지 않아,
기존 Lotto, LottoNo를 활용해서 변수명으로 구분했는데요.
별다른 추가 기능이 없는 객체를 무조건 생성하는 것 보다 기존 객체를 활용하고 변수명으로 전달하는 것으로 충분하다고 생각되는데 어떨까요?

그리고 LottoNo의 숫자검증에 대한 댓글도 하나 남겼는데 답변 가능하면 부탁드릴게요!

바쁜 와중에도 꼼꼼하고 자세히 봐주셔서 여러가지 생각하고 좋은 방향으로 개선할 수 있는 것 같아요. 잘 하고 있는 건지 모르겠지만 ㅎㅎ..
감사합니다.

2022-05-25 03:35 UTC, wooobo approved these changes
피드백 적용하신다고 정말정말 수고 많으셨어요 💯 

적용과 함께 고민한 내용을 공유 해주셔서 리뷰하는게 더욱 즐겁네요 :)

다음 단계 진행하시면서 고민해보시면 좋을 것 같은 내용을 코멘트 달아 드렸어요!
확인부탁드려요! 🙇 

이만 `merge`를 진행하도록 하겠습니다.

2022-05-25 03:35 UTC, wooobo commented on src/main/java/lotto/controller/LottoController.java
> +        Lotto winningLotto = new Lotto(InputView.inputWinningNumbers());
좋은데요! :+1:

2022-05-25 03:35 UTC, wooobo commented on src/main/java/lotto/controller/LottoController.java
> +        Lotto winningLotto = new Lotto(InputView.inputWinningNumbers());
> 코드상으로는 간소화 되었지만 좋은 방향인지는 좀 애매하네요.

간소화도 맞는 표현이고, 중복개념을 정리했다고도 볼 수 있을것 같아요!
처음 코드를 보는 입장에서는 `WinningNumber`는 어떠한 객체이고 `BonusNumber`는 어떠한 객체이지? `LottoNo`와 비슷한것 같은데 특별한 무언가가 있는건가? 생각의 꼬리를 물게되고 코드를 이해하는데 어려움이 있을것 같아요.
 `Lotto`, `LottoNo`로 리팩터링 된부분에서는 개념이 간소화됨으로써 `봐야하는 코드의 영역이 작아지고`  `코드의 응집력`이 생겼다고도 볼 수 있을것 같아요

---
>별다른 추가 기능이 없는 객체를 무조건 생성하는 것 보다 기존 객체를 활용하고 변수명으로 전달하는 것으로 충분하다고 생각되는데 어떨까요? 

기존객체를 활용하는 것이 좋다고 생각해요. **같은 개념을 가진 객체라면요!**
(물론 비지니스가 커질수록 하나의 객체가 점점 비대해질수 있습니다. 그럴때 적절하게 리팩터링을 통해 객체를 또 잘게 분리해야겠죠^^)

모든 부분을 설명할수 있는 예시는 아니겠지만 예시를 들어보겠습니다.
1.`Number` => 그것은 번호입니다.
2.`BonusNumber` => 보너스 번호입니다.
3.`LottoNumber` => 로또 번호입니다.
차이점이 보이시나요? 중요한 것은 `그것`입니다. `Number`는 보너스번호가 될수도 있고 로또번호가 될수도 있습니다.
그것은 정의 내리는 곳에서 무언가가 될 수 있습니다. 중요한것은 `번호(숫자)` 데이터를 기반으로 개념이 움직이고 있다라는 것입니다.

어떤 사람의 이름이 `민수`입니다. 그사람의 아내는 `여보`라고 부릅니다. 영어이름은 `Bob`입니다.
다른 사람일까요? 결국 똑같은 사람이겠죠 부르는 곳에서 다르게 부를뿐이죠 다소 추상적이고 철학적으로 보일 수 있지만
네이밍이란게 그런것 같습니다 ㅠㅠ

2022-05-25 03:35 UTC, wooobo commented on src/main/java/lotto/model/LottoNumbers.java
>      public static List<Integer> PREPARED_NUMBERS;
> 처음부터 숫자만 입력 가능하도록 LottoNo 객체가 설계되었을 경우 검증 주체는 어디가 되어야 할까요?
다른 부분은 Lotto 객체에서 검증을 하도록 변경을 해보았는데... LottoNo는 조금 애매하네요.
클래스 생성에서부터 문자열 입력 자체가 되지 않아 컴파일이 불가능한데.. 별도로 문자열을 받는 생성자를 추가하여 검증해야 할지 고민이 됩니다.
일단 제 의견은 객체 설계가 숫자만 받도록 되었다면 검증이 되었다고 생각하는데... 어떻게 진행하는게 좋을지 리뷰어님 의견도 듣고싶네요~!


`1~45`의 숫자를 가지는거라면
`List<LottoNo> PREPARED_NUMBERS;`가 될수있겠죠?

그렇게 되면 `1~45`이외 의 숫자를 입력했을때 예외를 발생하는 검증을 담당할수 있을것같아요.
그런김에 `100`을 입력했을때 예외를 발생시키는 테스트를 만들어 보는것도 좋을것같아요!

2022-05-25 03:35 UTC, wooobo commented on src/main/java/lotto/model/Lotto.java
> +        List<Integer> numbers = LottoNumbers.PREPARED_NUMBERS;
생성자에 대해 인사이트가 있는 블로그 공유해드립니다 [블로그](https://cozzin.tistory.com/71)

2022-05-25 03:35 UTC, wooobo commented on src/main/java/lotto/model/Lotto.java
> +    private List<LottoNo> createNumbers(List<Integer> numbers) {
리턴이 `List<LottoNo>` 인데 이것은 `Lotto`객체라고 봐도 되지 않을까요?

2022-05-25 03:35 UTC, wooobo commented on src/main/java/lotto/model/Organizer.java
>      private long totalWinningMoney;
`private Money totalWinningMoney;` 로 될수 있을지는 잘모르겠지만 고려해봐주세요! :)
(적절하지 않다고 생각하신다면 넘어가셔도 됩니다!)

2022-05-25 03:35 UTC, wooobo commented on src/main/java/lotto/model/Organizer.java
> +        return lotto.contain(this.bonusLottoNo.value());
`모든 원시값과 문자열을 포장한다` 포장한 객체를 다시 풀어서 던진다면 포장한 이유가 없어진다고 볼수 있을것 같은데 어떻게 생각하시나요? 🤔

2022-05-25 03:35 UTC, wooobo commented on src/main/java/lotto/model/Organizer.java
>      private int compare(LottoNo number) {
리턴을 `boolean` 타입으로 한다면 어떨까요? 
`return this.winningLotto.contain(number);`

그리고 `userNumberSameCount`를 좀 더 리팩터링 해본다면
```
private int userNumberSameCount(Lotto lotto) {
    return (int) lotto.seeNumbers().stream()
        .filter(this::compare)
        .count();
}
```
이렇게 변경해도 될지는 모르겠지만, 이런관점이 있구나라고만 봐주세면 좋을것같아요!

제가 보기엔 다소 복잡하게 구현된것 같아서 공유해드립니다.

2022-05-25 03:36 UTC, merged