Step5 로또(수동)
next-step/java-lotto-pro pull request #587
Opened 2022-05-20 19:09 UTC by piopoi

5단계 PR 드립니다.
주말에 리뷰요청드려 죄송합니다. 😢

2022-05-21 15:00 UTC, parkeeseul requested changes
마지막 단계 잘 진행해 주셨녜요! 👍 
몇 가지 코멘트 남겨두었으니 확인 부탁드립니다! 😄 
화이팅 이에요! 🔥

2022-05-21 15:00 UTC, parkeeseul commented on src/main/java/step3/domain/Money.java
> +        if (money < 0) {
매직 넘버를 사용하기 보다는 상수화를 통해 값에 의미를 부여해 주면 어떨까요 ? 😄

2022-05-21 15:00 UTC, parkeeseul commented on src/main/java/step3/domain/Yield.java
> +        this.element = element;
Yield 는 getter 만 있을 뿐 아무런 책임이 없는데요,
어떠한 목적으로 설계해 주신 걸까요? 😄

2022-05-21 15:00 UTC, parkeeseul commented on src/main/java/step3/domain/LottoCount.java
> +        if(lottoCount < 0) {
@_@ 매의 눈! 😄 
```suggestion
        if (lottoCount < 0) {
```

2022-05-21 15:00 UTC, parkeeseul commented on src/main/java/step3/domain/Money.java
> +    }
Money가 LottoCount 에 의존적인 것 같은데 의도하신 설계가 맞으실까요? 😄

2022-05-21 15:00 UTC, parkeeseul commented on src/test/java/step3/domain/LottoCountTest.java
> +    @DisplayName("LottoCount는 0 이상이어야 한다.")
테스트 설명이 동일하네요 🤔

2022-05-21 15:00 UTC, parkeeseul commented on src/test/java/step3/domain/MoneyTest.java
> +    }
해당 테스트로 Money가 0이상이여야만 한다는 것을 알 수 있을까요? 😄

2022-05-21 16:25 UTC, piopoi commented on src/main/java/step3/domain/Money.java
> +        if (money < 0) {
좋은 의견 감사합니다. 전체 소스 확인하여 수정하였습니다. 😄

2022-05-21 16:29 UTC, piopoi commented on src/main/java/step3/domain/Yield.java
> +        this.element = element;
저도 고민을 했던 부분이었지만, 모든 원시값을 포장하라는 요구사항이 있어서 생성하게 되었습니다. 
수익률을 계산하는 로직과 화면에 출력하는 UI 로직이 분리되어 있어 계산된 수익률을 전달해줘야 하는데, 원시값으로 전달하기에는 요구사항을 충족시키지 못해서 별도 클래스로 생성하게 되었습니다. 😄

2022-05-21 16:33 UTC, piopoi commented on src/main/java/step3/domain/LottoCount.java
> +        if(lottoCount < 0) {
formatting 놓친 부분이 있었네요.. 😢 
수정하겠습니다! 👍

2022-05-21 16:36 UTC, piopoi commented on src/test/java/step3/domain/LottoCountTest.java
> +    @DisplayName("LottoCount는 0 이상이어야 한다.")
create()의 DisplayName을 변경하였습니다. 감사합니다! 😄

2022-05-21 16:40 UTC, piopoi commented on src/test/java/step3/domain/MoneyTest.java
> +    }
`금액_생성()` 의 DisplayName을 변경하고, 바로 아래에 위치한 `invalid_금액_생성()`의 테스트 값을 경계값(-1)로 변경하였습니다. 😄

2022-05-21 17:02 UTC, piopoi commented on src/main/java/step3/domain/Money.java
> +    }
의도하지 않은 부분이었습니다 😢 
Money의 LottoCount에 대한 의존성은 모두 제거하겠습니다.
감사합니다! 😄

2022-05-22 11:56 UTC, parkeeseul approved these changes
피드백 잘 반영해 주셨네요! 👍 
몇 가지 소소한 코멘트 남겨두었으니 확인 부탁드리고
이만 머지 하도록 하겠습니다 😄 

그동안 많은 피드백 반영해 주시느라 정말 고생 많으셨습니다!
남은 미션들도 꼭 완주하시어 많은 인사이트 얻어 가시길 바랄게요!
마지막까지 화이팅 입니다 🔥

2022-05-22 11:56 UTC, parkeeseul commented on src/main/java/step3/domain/LottoCount.java
> +    public static final int MIN_LOTTO_COUNT = 0;
[해당 피드백](https://github.com/next-step/java-lotto-pro/pull/480#discussion_r873165611) 을 확인해 주세요 😄

2022-05-22 11:56 UTC, parkeeseul commented on src/main/java/step3/domain/Money.java
> +        return element / lottoPrice;
개인적으로 Money 가 로또 카운트를 계산(Money.lottoCount())하는 것 보다는
Moeny.divide() 와 같이 사용하는게 Money 에게 자연스럽지 않나 생각되는데 석원님의 생각은 어떠신가요? 😄 
Moeny.divide() 와 같이 사용하게 되면 로또 카운트를 구하는 것 뿐만 아니라 조금 더 넓은 범위에서 사용할 수 있을 것 같아요

2022-05-22 11:56 UTC, merged

2022-05-22 12:12 UTC, piopoi commented on src/main/java/step3/domain/LottoCount.java
> +    public static final int MIN_LOTTO_COUNT = 0;
집어주신 부분 말고도 Lotto 클래스에서도 같은 문제가 있었네요 😢 
항상 말씀해주신 부분 고려하도록 하겠습니다 😄

2022-05-22 12:19 UTC, piopoi commented on src/main/java/step3/domain/Money.java
> +        return element / lottoPrice;
단순하게 목적을 표현하기 위해서 `lottoCount()`라고 작명했었는데, 다시 생각해보니 말씀하신대로 애매한 부분이 있네요.
이설님께서 말씀하신 `divide()`가 확실히 더 자연스러워 보입니다. 작명이 참 어려운 것 같습니다. 😢 
조언 감사드립니다! 😄