Step4 리뷰 요청 드립니다.
next-step/java-lotto-pro pull request #609
Opened 2022-05-22 17:22 UTC by jiyeonghwang

안녕하세요. 황지영 입니다. 😀
Lotto 4단계 리뷰 요청 드립니다!

2022-05-23 15:48 UTC, enemfk777 requested changes
안녕하세요 지영님 :)
4단계 미션을 잘 구현해 주셨네요!
이전 단계의 피드백도 잘 반영해주셔서 감사합니다..! 🙇‍♂️
몇 가지 피드백을 드렸으니 반영 후 다시 한 번 요청 부탁드려요..!

2022-05-23 15:48 UTC, enemfk777 commented on src/main/java/lotto/domain/TotalLotto.java
> +        totalLotto.lottoList = LottoShop.generateLottos(totalLotto.money.getCount());
정적 팩토리 메서드인 from내부에서
empty constructor로 객체를 생성후 빈객체의 상태를 바꿔가며 초기화 하기보단
money 와 lottoList를 인자로 받는 private 생성자를 하나 만들어 두시는건 어떨까요?

2022-05-23 15:48 UTC, enemfk777 commented on src/main/java/lotto/domain/LottoFactory.java
>          if (set.size() != 6) {
상수가 있음에도 매직넘버가 쓰이고있네요 :)

2022-05-23 15:48 UTC, enemfk777 commented on src/main/java/lotto/domain/WinningLotto.java
> +                .count();
lotto에서 getLottoNumbers로 내부의 번호를 노출시키기 보다는
lotto에게 LottoNumber를 전달해서 스스로 count 반환하도록 할 수 있을 것 같아요 :)

아니 아예 contains 여부(boolean)을 반환하게 할 수 있겠네요 :)

2022-05-23 15:48 UTC, enemfk777 commented on src/main/java/lotto/constants/Message.java
> +}
메세지만 따로 클래스로 빼두신 이유는 무엇일까요?
메세지가 사용되는 클래스에 있는 것과 
여러군데서 쓰이는 메세지가 한 클래스에 있는 것 중
응집도가 높은 케이스는 어떤 케이스일까요? :)

2022-05-23 15:48 UTC, enemfk777 commented on src/main/java/lotto/domain/LottoFactory.java
> +    private LottoFactory() {
상태를 갖지않는 클래스의 생성자를 private 접근제한자로 설정 👍

2022-05-23 15:48 UTC, enemfk777 commented on src/main/java/lotto/utils/LottoGame.java
> +        LottoScore lottoScore = new LottoScore(totalLotto.getLottoList().matchLottoStaticToString(winningLotto));
totallLotto의 리스트를 노출시키기 보다
totalLotto에 winningLotto를 전달해서 반환 값으로 LottoScore 반환하는 메서드를 작성해보는 건 어떨까요? (메시지를 전달해라)

어떤 행위를 하는 메서드의 위치를 정하는게 애매할 때는 필요한 데이터를 갖고있는 클래스 안에 위치시키는게 자연스러운 책임 분리가 될 확률이 높다는 걸 기억해주세요 :)

2022-05-23 15:48 UTC, enemfk777 commented on src/main/java/lotto/view/InputView.java
> +    public static int printRequestAmount() {
inputView의 메서드 명칭이 print* 인데요
print라는 명칭은 단지 출력만 책임지는 것 같습니다.
InputView의 메서드들은 입력 책임을 지고있는데요,
메서드 명칭을 바꿔주시는건 어떨까요?

2022-05-24 08:35 UTC, jiyeonghwang commented on src/main/java/lotto/domain/TotalLotto.java
> +        totalLotto.lottoList = LottoShop.generateLottos(totalLotto.money.getCount());
money 와 lottoList를 인자로 받는 private 생성자를 생성하였습니다!

2022-05-24 08:35 UTC, jiyeonghwang commented on src/main/java/lotto/domain/LottoFactory.java
>          if (set.size() != 6) {
앗... 상수로 치환하였습니다!..ㅠㅠ

2022-05-24 08:43 UTC, yeongever0 commented on src/main/java/lotto/constants/Message.java
> +}
겹치는 메시지가 있어서 따로 분리하였는데, 
다시 보니 겹치지 않는 메시지가 더 많아서 다시 원복하였습니다! 

응집도가 높은 케이스를 구분하면서 사용해야겠네요. 감사합니다 😊

2022-05-24 08:44 UTC, jiyeonghwang commented on src/main/java/lotto/utils/LottoGame.java
> +        LottoScore lottoScore = new LottoScore(totalLotto.getLottoList().matchLottoStaticToString(winningLotto));
>필요한 데이터를 갖고있는 클래스 안에 위치시키는게 자연스러운 책임 분리가 될 확률이 높다

이 부분이 제가 항상 고민하던 부분인데, 피드백 감사드립니다! 😁

2022-05-24 08:45 UTC, jiyeonghwang commented on src/main/java/lotto/view/InputView.java
> +    public static int printRequestAmount() {
값을 return한다는 점에서 전체적으로 get*Print 형식으로 변경하였습니다!

2022-05-24 08:46 UTC, jiyeonghwang commented
안녕하세요, 태엽님! 이번에도 자세한 피드백 감사드립니다! 💐
피드백 적용하였습니다. 다시 확인 부탁드리겠습니다! 
감사합니다. 🥰

2022-05-24 16:03 UTC, enemfk777 approved these changes
안녕하세요 지영님 :) 
4단계 피드백까지 잘  반영해 주셨습니다.
피드백을 반영하다 보니 다시 개발자가 제어할 수 없게 된 부분이 있어
코멘트 드렸으니 다음 단계에서 함께 반영 부탁드려요!!
그럼 이만 머지하겠습니다! 로또 미션의 마지막 단계로 가보시죠 💪

2022-05-24 16:03 UTC, enemfk777 commented on src/main/java/lotto/domain/Lotto.java
> +        return result;
this.lottoNumbers.contains(lottoNumber) 가 이미 boolean을 반환 하는 코드여서
나머지 조건절및 result 변수는 필요 없을 것 같아요 :)

2022-05-24 16:03 UTC, enemfk777 commented on src/main/java/lotto/domain/TotalLotto.java
> +        return new TotalLotto(money, lottoList);
[이전 단계에서 코멘트 드렸던](https://github.com/next-step/java-lotto-pro/pull/487#discussion_r873180116) 개발자가 제어할 수 없는 코드가 되어 버렸네요 :)
이 부분때문에 getLottoScore도 테스트가 어려워 테스트코드가 작성되어 있지 않은 것 같은데요,
랜덤성을 갖는 부분은 외부로 분리하고, 작성하지 못했던 테스트 코드도 작성해 보시겠어요..?

2022-05-24 16:03 UTC, enemfk777 commented on src/main/java/lotto/domain/Rank.java
> +public enum Rank {
Rank enum 내에 사용하지 않는 메서드가 있네요 :) 사용하지 않는 메서드는 제거해주세요 :)

2022-05-24 16:03 UTC, merged