Step5 - 로또(수동)
next-step/java-lotto-pro pull request #611
Opened 2022-05-23 13:35 UTC by songsimo

안녕하세요, 드디어 마지막 단계 제출이네요.

꼼꼼하게 봐주시고 리뷰 주셔서 감사합니다.

덕분에 많은 걸 얻어 갔어요 = )

이번 리뷰도 잘 부탁드립니다 🙇‍♂️🙇‍♂️.

2022-05-23 16:28 UTC, enemfk777 requested changes
안녕하세요 철현님 :)

마지막 단계 미션 잘 구현해 주셨습니다..!
마지막 단계를 진행하면서 이전 단계에서 LottoMachine에게 나누어 주었던 생성 책임이
다시 Controller로 돌아 온 것 같아 관련 피드백을 드렸으니
고민 해 보신 후 다시 한 번 요청 부탁드립니다..!

로또 미션 완수라는 고지가 얼마 남지 않았네요..! 화이팅입니다!! 💪

2022-05-23 16:28 UTC, enemfk777 commented on src/main/java/lotto/controller/LottoController.java
> +		LottoTickets lottoTickets = getLottoTicketsByManual(lottoPrice, manualCount);
지난 단계까지 열심히 로또 생성 책임을 LottoMachine 클래스로 옮겨주었는데
수동 로또 때문에 다시 controller에서 생성 책임을 지게 되었네요 :)
lottoPrice 와 수동으로 구입할 로또 번호들을 를 멤버변수로 갖는 클래스를 하나 정의하고
LottoMachine 에 해당 클래스를 넘겨주면 자동 수동 모두 생성책임을 분리해낼 수 있을 것 같아요 :)

2022-05-23 16:28 UTC, enemfk777 commented on src/main/java/lotto/controller/LottoController.java
> +		OutputView.printPurchaseCount(manualCount, autoCount);
위에서 말씀드린 "lottoPrice 와 수동으로 구입할 로또 번호들을 를 멤버변수로 갖는 클래스" 가 있다면 수동, 자동 갯수 출력도 문제 없을 것 같아요 :)

2022-05-23 16:28 UTC, enemfk777 commented on src/main/java/lotto/controller/LottoController.java
> +		lottoTickets.sum(automaticallyBuyLotto(autoCount));
LottoMachine에서 자동, 수동이 모두 생성된 결과를 한번에 반환하면 어떨까요?

2022-05-23 16:28 UTC, enemfk777 commented on src/main/java/lotto/controller/LottoController.java
> +		Lotto winningLotto = Lotto.getInstanceByString(InputView.inputWinningNumbers());
LottoMachine 이 있으니 입력값으로 Lotto를 반환하는 책임도 함께 질 수 있을 것 같아요 :)

2022-05-23 16:28 UTC, enemfk777 commented on src/main/java/lotto/controller/LottoController.java
>  		RankResult result = lottoTickets.getResult(winningLotto, number);
LottoTickets 클래스의 getResult 내부 구현에 관한 피드백입니다 :)
스트림을 사용해주셨으니
```
List<Rank> rankList = new ArrayList<>();
for(Lotto lotto: lottoTickets) {
	rankList.add(lotto.match(winningLotto, number));
}
```
이 부분도 스트림을 사용해서 더 깔끔하게 작성이 가능할 것 같아요 :)

2022-05-23 16:28 UTC, enemfk777 commented on src/main/java/lotto/controller/LottoController.java
> +		OutputView.printRate(result.compileStatistics(lottoPrice.expenses()));
출력 책임을 지는 OutputView가 지녀야할 책임이 controller에게 옮은 것 같아요 :)

2022-05-25 18:42 UTC, songsimo commented on src/main/java/lotto/controller/LottoController.java
> +		OutputView.printRate(result.compileStatistics(lottoPrice.expenses()));
음...어떤 부분이 OutputView 책임이 controller에 옮은 건가요? 😅😅

2022-05-25 19:14 UTC, songsimo commented on src/main/java/lotto/controller/LottoController.java
> +		lottoTickets.sum(automaticallyBuyLotto(autoCount));
음... 자동 생성된 로또 번호들을 출력해야해서 일부러 분리했어요. 🤔🤔

2022-05-26 15:01 UTC, enemfk777 commented on src/main/java/lotto/controller/LottoController.java
> +		OutputView.printRate(result.compileStatistics(lottoPrice.expenses()));
reportLottoResult 라는 메서드 자체가 OutpuView의 public 메서드여야 한다고 생각했어요 :)
Controller는 LottoResult를 출력하는데
prizeResult를 먼저 출력하고, Rate를 출력해야한다는 세부 구현 자체를 알 필요가 없다고 생각했거든요 :)

2022-05-26 15:03 UTC, enemfk777 approved these changes
안녕하세요 철현님 :)

피드백 반영해주시느라 고생하셨습니다.
제가 마지막 단계까지 피드백을 많이 드렸던 것 같은데 잘 반영해주셨네요 :)

저와 진행했던 미션의 경험이 앞으로 남은 미션을 진행하시는데 도음이 되셨으면 좋겠습니다.
이번 단계는 이만 머지 하겠습니다..!

그 동안 로또 미션 함께 수행하시느라 고생 많으셨습니다!
이 후 미션도 화이팅입니다..! 💪

2022-05-26 15:03 UTC, merged

2022-05-26 20:21 UTC, songsimo commented
> 안녕하세요 철현님 :)
> 
> 피드백 반영해주시느라 고생하셨습니다. 제가 마지막 단계까지 피드백을 많이 드렸던 것 같은데 잘 반영해주셨네요 :)
> 
> 저와 진행했던 미션의 경험이 앞으로 남은 미션을 진행하시는데 도음이 되셨으면 좋겠습니다. 이번 단계는 이만 머지 하겠습니다..!
> 
> 그 동안 로또 미션 함께 수행하시느라 고생 많으셨습니다! 이 후 미션도 화이팅입니다..! 💪

감사합니다! 잘 반영된 거겠죠!?!? = ) 덕분에 많은 걸 배우고 가요!

그 동안 리뷰 봐주시느라 고생하셨어요!