Step5 - 로또(수동) 리뷰 요청 드립니다
next-step/java-lotto-pro pull request #619
Opened 2022-05-25 16:33 UTC by millennion-jin

드디어 마지막 Step이네요
그 동안 정말 상세히 리뷰 해주셔서 감사드립니다.

이번 기능 구현에 있어서
망설이게 되는 부분이 있었는데

우선 로또 숫자들의 문자열에 대한 validation 체크를 어디서 할까 하다가
그래도 Lotto를 생성하기 위한 문자열인데
Lotto 에서 관리가 되어야 하지 않을까 해서
Lotto에 문자열을 사용하는 생성자를 추가하고 해당 부분에서 validation 체크를 했는데
이게 제대로 된 선택 일지 망설여졌습니다.

이 것을 다른 곳에서 체크를 했어야 했을까요?

2022-05-26 10:12 UTC, seokhongkim requested changes
진웅님, 5단계 미션 잘 구현해주셨어요.

문의주신 내용에 제 생각을 먼저 공유 드립니다.
> 우선 로또 숫자들의 문자열에 대한 validation 체크를 어디서 할까 하다가
그래도 Lotto를 생성하기 위한 문자열인데 Lotto 에서 관리가 되어야 하지 않을까 해서
Lotto에 문자열을 사용하는 생성자를 추가하고 해당 부분에서 validation 체크를 했는데
이게 제대로 된 선택 일지 망설여졌습니다.
이 것을 다른 곳에서 체크를 했어야 했을까요?

`Lotto` 에서 검증하는 것도 괜찮은 방법인 것 같습니다. `Lotto` 도메인에서 숫자의 개수를 검증하는 책임도 있기 때문에요.
개인적으로는 `InputView` 에서 6개의 숫자만 넘어오는지 검증하는 것도 하나의 방법일 것 같은데요.
이렇게 생각한 이유는 `InputView` 를 추상화해서 UI 라고 생각했을 때, 로또의 UI 에서는 숫자 6개만 입력할 수 있도록 제한하는 책임을 가지고 있다고 생각했습니다.

전체적으로 밸리데이션을 꼼꼼하게 하기 위해 노력하신 모습과 입력값을 받을 때 예외 케이스로 프로그램이 중지되지 않도록 잘 처리해주신 것 같아요.
위 과정에서 중복으로 발생하는 코드를 리팩토링 해보시는 것도 도움이 될 것 같습니다. 😀 
위 내용을 포함하여 피드백을 조금 남겼으니 확인 부탁드립니다. 🙏

2022-05-26 10:12 UTC, seokhongkim commented on src/main/java/lotto/domain/Lotto.java
> +    private void validateString(String numbersString) {
추가된 메소드가 호출되는 곳이 생성자인데, 너무 멀리 떨어지게 배치된 것 같아요.
메소드 배치 순서를 고민해보시면 좋을 것 같아요!

2022-05-26 10:12 UTC, seokhongkim commented on src/main/java/lotto/domain/WinningLotto.java
> +        validateBonusNumber(winningLotto, bonusNumber);
똑같은 `validateBonusNumber` 메소드인데 인자에 따라 구현이 달라지는군요.
메소드를 사용하는 다른 개발자가 쉽게 구현이 다르다는 것을 인지할 수 있는 방법이 있을까요?

2022-05-26 10:12 UTC, seokhongkim commented on src/main/java/lotto/domain/LottoGenerator.java
>      public Lottos generateLottos(int size) {
기존에 로또를 생성하던 메소드는 사용하지 않을 것 같아요. 코드를 삭제하는 게 어떨까요?

2022-05-26 10:12 UTC, seokhongkim commented on src/main/java/lotto/domain/LottoPlay.java
> +        try {
예외가 발생하지 않을 때까지 재시도하는 기능을 공통 기능으로 추출하면 중복 코드를 많이 줄일 수 있겠네요!

아마도 이런 형태로 제공할 수 있을 것 같군요.
```java
public T retryOnThrow(Supplier<T> supplier, Consumer exceptionHandler) {
    T value = null;
    while (value == null) {
        try {
            T = supplier.get();
        } catch (Exception e) {
            // handle exception
        }
    }
}
```

2022-05-26 10:12 UTC, seokhongkim commented on src/main/java/lotto/domain/LottoGenerator.java
> +    private Lottos generateLottosWithList(List<Lotto> lottoList, int size) {
이 메소드의 역할은 `자동 로또` 를 발행하는 것일까요?
메소드가 하는 일을 구체적으로 설명할 수 있는 이름을 사용해주시면 좋을 것 같아요!

2022-05-26 10:12 UTC, seokhongkim commented on src/main/java/lotto/domain/LottoGenerator.java
> +    public Lottos generateLottos(List<Lotto> manualLottoList, int autoSize) {
`수동 로또` 와 `자동 로또` 의 데이터 생성 시점이 다르다보니 데이터 흐름을 이해하는 게 더 어렵게 느껴지네요.
`LottoGenerator` 에서 `돈` 과 `수동 로또 번호` 를 받아서 모두 발급해주는 형태로 진행하는 것에 대해서는 어떻게 생각하시나요?

2022-05-26 10:12 UTC, seokhongkim commented on src/main/java/lotto/domain/WinningLotto.java
>      private void validateWinningLotto(Lotto winningLotto) {
`validation` 메소드 네이밍도 고민해보시면 좋을 것 같아요.
null 체크를 하는 밸리데이션도 `validateNull`, `validateWinningLotto` 와 같이 이름이 달라서 메소드명만 봤을 때 무슨 밸리데이션인지 인지하기 어려운 것 같습니다.
추가로, 대부분의 밸리데이션 로직이 아래와 같은데, 공통 메소드를 제공할 수 있는 방법도 고민해보시면 좋겠네요!

```java
if (condition) {  // 혹은 condition == false
    throw new IllegalArgumentException(message);
}
```

2022-05-26 10:12 UTC, seokhongkim commented on src/main/java/lotto/domain/PurchaseQuantity.java
> +    private void validate(PurchaseMoney purchaseMoney, int manualQuantity) {
밸리데이션을 꼼꼼하게 해주신 것 좋습니다. 👍

2022-05-26 10:12 UTC, seokhongkim commented on src/test/java/lotto/domain/LottoTest.java
>      void lottoSize() {
테스트 이름도 변경이 필요해 보이네요~

2022-05-26 16:32 UTC, millennion-jin commented on src/main/java/lotto/domain/LottoGenerator.java
>      public Lottos generateLottos(int size) {
넵 해당 메서드는 제거하겠습니다

2022-05-26 16:56 UTC, millennion-jin commented on src/main/java/lotto/domain/LottoPlay.java
> +        try {
Supplier 에 대해 알려주셔서 감사합니다
이건 정말 앞으로 개발 할 때에도 중복 코드들을 줄이는데 잘 사용될 수 있을 것 같습니다.

2022-05-26 17:44 UTC, millennion-jin commented on src/main/java/lotto/domain/LottoGenerator.java
> +    public Lottos generateLottos(List<Lotto> manualLottoList, int autoSize) {
수동 로또 생성도 로또 생성의 일종이니
입력 값만 전달해 주고 LottoGenerator에서 생성이 되는 것이 개념적으로 더 맞는 것 같습니다
해당 방향으로 수정을 하겠습니다

2022-05-26 17:45 UTC, millennion-jin commented on src/main/java/lotto/domain/LottoGenerator.java
> +    private Lottos generateLottosWithList(List<Lotto> lottoList, int size) {
이 부분은 수동 로또 생성 기능을 LottoGenerator로 이동시키면서 메서드명을 정리하였습니다

2022-05-26 18:37 UTC, millennion-jin commented on src/main/java/lotto/domain/WinningLotto.java
>      private void validateWinningLotto(Lotto winningLotto) {
validation 메서드 명을 줄여서 쓰지 않고 정확한 의미를 포함하도록 수정하였고
Predicate 혹은 BiPredicate 를 사용하는 공통 Validation 메서드를 작성하여 반영했습니다

2022-05-26 18:40 UTC, millennion-jin commented on src/test/java/lotto/domain/LottoTest.java
>      void lottoSize() {
ㄷㄷ 테스트 메서드명을 생각하지 않고
테스트 내용만 바꿨던 것 같습니다 수정하겠습니다

2022-05-26 18:42 UTC, millennion-jin commented on src/main/java/lotto/domain/Lotto.java
> +    private void validateString(String numbersString) {
항상 고민하는 문제 중 하나인게 메서드 배치 순서인데
혹시 석홍님께서는 메서드 배치 순서를 어떻게 사용하고 계신가요?

2022-05-26 18:43 UTC, millennion-jin commented on src/main/java/lotto/domain/WinningLotto.java
> +        validateBonusNumber(winningLotto, bonusNumber);
이건 밤늦게 작업하다 졸려서 동일한 메서드명이 들어간 것 같습니다 ㄷ
앞으로는 좀 더 명확하게 의미를 담을 수 있는 메서드 명을 사용하겠습니다

2022-05-27 15:41 UTC, seokhongkim commented on src/main/java/lotto/domain/Lotto.java
> +    private void validateString(String numbersString) {
저는 생성자 - 메소드 - getter/setter - equals/hashcode/toString 순서로 작성하는 편입니다.
또한, 메소드는 그룹핑을 해놓는 편인데요. 예를 들면 아래와 같습니다.

```java
public void A() {
    B();
}

private void B() { // 메소드를 사용하는 A와 가까운 곳에 배치
}

public void C(int i) {
    D();
}

public void E(String s) {
    D();
}

private void D() { // C, E 가 동일한 역할을 하는 오버로딩된 메소드이므로, 둘을 그룹핑하고 두 곳에서 호출되는 D를 이어서 배치
}
```

아래 가이드를 참고해서 진웅님의 메소드 배치 순서를 고민해보시는 게 좋을 것 같아요!
https://www.oracle.com/java/technologies/javase/codeconventions-fileorganization.html

2022-05-27 15:48 UTC, seokhongkim requested changes
진웅님, 피드백 반영 잘 해주셨습니다! 👍 
공통으로 사용할 수 있는 기능을 리팩토링해서 코드 양이 줄고 이해하기도 좀 더 수월해진 것 같습니다.

질문주신 부분에 대해 답변과 함께 피드백 조금 남겼으니 확인 부탁드립니다. 🙏

2022-05-27 15:48 UTC, seokhongkim commented on src/main/java/util/ValidationUtil.java
> +    public static <T> void validatePredicate(Predicate<T> predicate, T target, String exceptionMessage) {
boolean 값을 받지 않고 `Predicate`, `BiPreciate` 를 사용하신 이유가 있을까요?

2022-05-27 15:48 UTC, seokhongkim commented on src/main/java/util/ValidationUtil.java
> +    public static <T> void validatePredicate(Predicate<T> predicate, T target, String exceptionMessage) {
조금 더 메소드의 의도를 드러낼 수 있는 네이밍을 고민해보시면 좋을 것 같아요!
`validatePredicate` 라는 이름으로는 메소드가 무엇을 밸리데이션 하는데 사용할 수 있을지 알려줄 수 있는 정보가 적은 것 같습니다.
밸리데이션에 실패하는 경우 `IllegalArgumentException` 을 발생시킨다는 것은, 아마도 이 밸리데이션은 `argument` 를 검증하기 위한 목적인 것 같아요.
현재 객체의 상태를 검증한다면 아마도 `IllegalStateException` 을 발생시킬 것 같아요.

2022-05-27 17:17 UTC, millennion-jin commented on src/main/java/util/ValidationUtil.java
> +    public static <T> void validatePredicate(Predicate<T> predicate, T target, String exceptionMessage) {
뭔가 새벽까지 하다가 졸린데다가 이전 Step에서 BiPredicate 를 알게 되어 한번 써봐야겠다는 생각이 합쳐져 만들어진 이상한 코드인 것 같습니다 ㅠ
해당 부분은 condition 값을 사용하여 동작되도록 수정했습니다

2022-05-27 17:18 UTC, millennion-jin commented on src/main/java/util/ValidationUtil.java
> +    public static <T> void validatePredicate(Predicate<T> predicate, T target, String exceptionMessage) {
네 확실히 Exception의 타입이 정해진 상태에서 validatePredicate 라는 광범위한 메서드명은 문제가 있을 것 같습니다
해당 부분은 수정을 진행하겠습니다

2022-05-28 08:45 UTC, seokhongkim approved these changes
진웅님, 로또 5단계 미션 잘 마무리 해주셨습니다. 👍 
피드백 반영도 끝나서 PR은 이만 머지하도록 하겠습니다.

앞으로 남은 교육 기간동안 진웅님이 많이 학습하고 성장하시기를 응원하겠습니다. 💪 
로또 미션 진행하느라 고생하셨습니다! 😀

2022-05-28 08:45 UTC, merged