Step5 pr 요청합니다.
next-step/java-lotto-pro pull request #626
Opened 2022-05-28 07:02 UTC by hyunhyun

안녕하세요~ step 5 로또 수동 구매 리뷰 요청드립니다~
이전 리뷰에서 코멘트 해주신 내용들도 반영하였습니다.
감사합니다!

2022-05-28 14:17 UTC, jaeyeonling requested changes
마지막 단계 미션을 잘 구현해주셨어요 👍 
추가적인 코멘트 남겨두었으니 확인 부탁드려요!!

2022-05-28 14:17 UTC, jaeyeonling commented on src/main/java/lotto/LottoPlay.java
> +    static LottoNo bonusNumber;
해당 값들을 static으로 선언하지 않고 구현해 볼 수 있을 것 같은데요.
static으로 구현하는 것과 인스턴스 변수로 구현하는 것은 어떠한 차이가 있을지도 고민해보아요.

2022-05-28 14:17 UTC, jaeyeonling commented on src/main/java/lotto/domain/Lotto.java
> +    public boolean checkBonusMatch(LottoNo bonusNumber) {
매개변수로 넘어오는 값이 bonusNumber가 아니어도 동작할 것 같은데요.
그렇다면 메서드의 이름이나 매개변수의 이름이 변경돼야 하지 않을까요?

2022-05-28 14:17 UTC, jaeyeonling commented on src/main/java/lotto/domain/Lotto.java
> +    public int checkMatchCount(Lotto checkLotto) {
check-라는 이름은 일반적으로 boolean 값을 응답할 때 사용하는데요.
해당 메서드의 기능을 나타낼 수 있는 이름이 없을지 고민해보아요.

2022-05-28 14:17 UTC, jaeyeonling commented on src/main/java/lotto/domain/Lotto.java
> +            lotto.getLottoNumbers().add(new LottoNo(lottoNumber));
getter를 사용하지 않고 메시지를 던지는 방식으로 구현해보면 좋겠네요~

2022-05-28 14:17 UTC, jaeyeonling commented on src/main/java/lotto/domain/LottoNo.java
> +        this.lottoNumber = validateNumberRange(checkLottoNoInput);
주생성자를 정하여 인스턴스 변수는 주생성자를 통해서만 초기화하도록 수정해보면 좋겠어요~

2022-05-28 14:17 UTC, jaeyeonling commented on src/main/java/lotto/domain/LottoNo.java
> +    public LottoNo validateBonus(Lotto winningLotto) {
```
class A {
    상수(static final) 또는 클래스 변수
    인스턴스 변수
    생성자
    팩토리 메소드
    메소드
    기본 메소드 (equals, hashCode, toString)
}
```

클래스 구현 순서는 위와 같습니다!

2022-05-28 14:17 UTC, jaeyeonling commented on src/main/java/lotto/domain/WinRanks.java
> +        Optional<Rank> rank = Rank.matchedRank(checkMatchCount, bonusMatch);
rank가 없을 경우 어떻게 동작하는게 맞을까요?
예외처리를 한다면 어디서 하는게 좋을지도 고민해보아요.

2022-05-28 14:17 UTC, jaeyeonling commented on src/main/java/lotto/domain/WinRanks.java
> +        if(rank.isPresent()){
```suggestion
        if (rank.isPresent()) {
```

컨벤션을 확인해주세요~

2022-05-28 14:17 UTC, jaeyeonling commented on src/test/java/lotto/domain/LottoTest.java
> +    static class TestLotto extends Lotto {
TestLotto를 따로 만들어주신 이유가 있을까요?

2022-05-28 14:17 UTC, jaeyeonling commented on src/main/java/lotto/domain/LottoConst.java
> +public class LottoConst {
상수들을 따로 분리해주신 이유가 있을까요?

2022-05-29 08:04 UTC, hyunhyun commented on src/main/java/lotto/LottoPlay.java
> +    static LottoNo bonusNumber;
main 메소드가 너무 길어져서 분리하는데만 신경을 쓰단보니 static으로 계속 저장될 필요가 없는 변수들까지 static으로 처리가 되서 메모리 낭비가 발생했네요. 메소드를 더 분리해서 파라미터로 필요한 값 넘기도록 수정했습니다.

2022-05-29 08:05 UTC, hyunhyun commented on src/main/java/lotto/domain/Lotto.java
> +    public boolean checkBonusMatch(LottoNo bonusNumber) {
네 범용적으로 사용할수 있도록 변경하겠습니다.

2022-05-29 08:11 UTC, hyunhyun commented on src/main/java/lotto/domain/Lotto.java
> +            lotto.getLottoNumbers().add(new LottoNo(lottoNumber));
아래 addLottoNumber 함수를 활용 하도록 변경했습니다. 그리고 createRandomLotto로 명을 지어서 랜덤으로 생성된 값으로 로또 사용할때만 사용했었는데 일반 생성자로 만들어서 테스트코드에서 List<Integer> 타입으로도 로또를 생성할 수 있도록 하였습니다.

2022-05-29 08:11 UTC, hyunhyun commented on src/main/java/lotto/domain/LottoNo.java
> +        this.lottoNumber = validateNumberRange(checkLottoNoInput);
넵 감사합니다~

2022-05-29 08:12 UTC, hyunhyun commented on src/main/java/lotto/domain/WinRanks.java
> +        Optional<Rank> rank = Rank.matchedRank(checkMatchCount, bonusMatch);
stream을 잘 활용하지 못했던 거 같습니다. 수정하였습니다!

2022-05-29 08:13 UTC, hyunhyun commented on src/main/java/lotto/domain/WinRanks.java
> +        if(rank.isPresent()){
넵! 개발 후에 reformat하는거 자꾸 놓치네요..

2022-05-29 08:19 UTC, hyunhyun commented on src/test/java/lotto/domain/LottoTest.java
> +    static class TestLotto extends Lotto {
생성자가 List<Integer> 가 별도로 있었는데 테스트코드에서만 사용하고 있어서 지웠더니 소스코드에 String[] 타입 생성자 밖에 없었는데, 테스트 코드 작성이 너무 불편하여 테스트 내부 클래스를 만들었었는데
[코멘트](https://github.com/next-step/java-lotto-pro/pull/626#discussion_r884139291) 에서 답변해주신거 메소드를 생성자변경하도록해서 테스트코드에서 이를 활용하였습니다.

2022-05-29 08:23 UTC, hyunhyun commented on src/main/java/lotto/domain/LottoConst.java
> +public class LottoConst {
Lotto와 관련된 값들이 중복되어서 상수로 처리하려고 빼었는데, 일급컬렉션인 Lotto에 다른 변수는 없어야되는줄 알고 별도로 분리하였ㅡ는데 일급컬렉션에는 다른 멤버변수만 없으면 되고 클래스변수는 괜찮은 거였네요. Lotto안으로 변경하였습니다.

2022-05-30 07:12 UTC, jaeyeonling approved these changes
미션을 잘 진행해주셨어요!!
수 많은 코멘트 반영하시느라 정말 고생 많으셨습니다~
해당 요청은 머지하도록 하겠습니다 마지막까지 화이팅입니다 😄

2022-05-30 07:12 UTC, jaeyeonling commented on src/main/java/lotto/domain/Lotto.java
> +    public boolean containsLottoNo(LottoNo bonusNumber) {
아직도 bonusNumber라는 이름이 남아있네요 ㅎㅎ

2022-05-30 07:12 UTC, merged