2단계 - 문자열 덧셈 계산기 실습 PR 요청드립니다!
next-step/java-lotto-pro pull request #686
Opened 2022-10-25 13:54 UTC by taewonh

2022-10-25 14:30 UTC, heowc requested changes
안녕하세요 태원님! 🙇 
문자열 덧셈 계산기 잘 구현해주셨습니다. 👍 

코멘트 몇 개 남겼으니 확인 부탁드려요!

궁금하신 점이나 이야기 나누고 싶은 부분이 있다면 깃헙 코멘트, 슬랙 DM 편하게 남겨주세요!

2022-10-25 14:30 UTC, heowc commented on src/main/java/StringAddCalculator.java
> +        if (isEmpty(text)) {
꼼꼼한 문자열 체크 좋습니다 👍

2022-10-25 14:30 UTC, heowc commented on src/main/java/StringAddCalculator.java
> +        String delimiter = generateDelimiter(delimiterMatcher);
메소드 순서를 호출 순서대로 나열해보는 것은 어떨까요? 🤔

2022-10-25 14:30 UTC, heowc commented on src/main/java/StringAddCalculator.java
> +                .peek(StringAddCalculator::checkMinus)
`peek(...)`으로 구현한 것은 처음 보는 것 같습니다. 좋네요 👍

2022-10-25 14:30 UTC, heowc commented on src/main/java/StringAddCalculator.java
> +            throw new RuntimeException();
파싱하는 부분과 음수인지 체크하는 부분 잘 나눠주셨습니다 👍 

다만, `RuntimeException`으로만 예외를 던지기 보다는 상황에 맞는 예외를 만들어 던지는 것은 어떨까요? 🤔 
추가로 해당 라인에 대한 테스트도 추가해주시면 좋을 것 같아요 🙇

2022-10-26 08:08 UTC, taewonh commented on src/main/java/StringAddCalculator.java
> +        String delimiter = generateDelimiter(delimiterMatcher);
@heowc 메소드 선언 순서와 동일하게 호출 순서를 변경하였습니다!

2022-10-26 08:10 UTC, taewonh commented on src/main/java/StringAddCalculator.java
> +            throw new RuntimeException();
@heowc RuntimeException Throw 로 적용된 메소드 2가지 (parseInt, checkMinus) 모두 의미상 좀더 부합하도록 IllegalArgumentException으로 지정하고, 오류 메세지도 구분해서 입력하도록 처리했습니다! 추가로 두 가지 케이스 모두 검증가능하도록 기존 테스트 코드 역시 2가지로 분리했습니다!

2022-10-26 08:11 UTC, taewonh commented on src/main/java/StringAddCalculator.java
> +        String delimiter = generateDelimiter(delimiterMatcher);
@heowc 별개로 커밋하다보니 커밋 메시지에 fix로 입력 했는데 의미상 refactoring이 좀더 맞을까요..?

2022-10-26 09:15 UTC, heowc commented on src/main/java/StringAddCalculator.java
> +        String delimiter = generateDelimiter(delimiterMatcher);
리팩토링이 더 적절해보이긴 하네요.
https://gist.github.com/stephenparish/9941e89d80e2bc58a153를 참고하시면 더 도움이 될 것 같습니다 👍

2022-10-26 09:25 UTC, heowc approved these changes
크게 피드벡 드릴게 없어보이네요.
다음 단계를 진행해주세요 🙇 

다음 미션부터 본격적인 미션이 시작되니 화이팅 입니다 👍

2022-10-26 09:25 UTC, merged