Step2 문자열 계산기 PR 요청 드립니다.
next-step/java-lotto-pro pull request #691
Opened 2022-10-25 15:15 UTC by giraffelim

안녕하세요. 학습 테스트에 이어 문자열 계산기 리뷰 요청 드립니다.
감사합니다 :)

2022-10-26 05:59 UTC, mskangg requested changes
안녕하세요, 태양님! 
이번 로또미션에 리뷰어를 맡게된 강민수라고 합니다.
잘부탁드려요 👐

전체적으로 꼼꼼하게 테스트코드 작성해주셨네요 💯 
몇가지 피드백 드렸는데 확인해보시고 재요청 부탁드립니다 🙇‍♂️

2022-10-26 05:59 UTC, mskangg commented on src/test/java/learn/SetTest.java
> +        assertThat(numbers).contains(element);
1단계에서 받은 피드백 적용하셨군요 💯

2022-10-26 05:59 UTC, mskangg commented on src/main/java/step2/StringAddCalculator.java
> +    private static final Pattern CUSTOM_DELIMITER_PATTERN = Pattern.compile("//(.)\n(.*)");
Pattern.compile은 매번 새로운 인스턴스를 생성하는데 static 변수로 잘 만드셨습니다 💯

2022-10-26 05:59 UTC, mskangg commented on src/main/java/step2/StringAddCalculator.java
> +    public static final int NUMBER_OF_TEXT_GROUP = 2;
내부적으로만 사용하는 상수는 private으로 설정하는게 좋아보입니다 :)

2022-10-26 05:59 UTC, mskangg commented on src/test/java/step2/StringAddCalculatorTest.java
> +    }
@DisplayName에서 명시한 의도가 테스트 코드와 맞지 않습니다

2022-10-26 05:59 UTC, mskangg commented on src/test/java/step2/StringAddCalculatorTest.java
> +    public void splitAndSum_쉼표_또는_콜론_구분자() {
또는 <- 의 조건이니 쉼표와 클론 테스트코드를 분리하는게 좋아보입니다

2022-10-26 05:59 UTC, mskangg commented on src/test/java/step2/StringAddCalculatorTest.java
> +                .isInstanceOf(RuntimeException.class);
에러테스트 잘하셨는데, 예외에 메세지를 설정하셨더라구요
```
.hasMessage("")
```
로 추가 검증한다면 더욱더 정확한 테스트코드가 될것 같습니다 :)

위에 숫자가 아닌 문자도 동일하게 추가하면 좋을것 같아용

2022-10-26 05:59 UTC, mskangg commented on src/main/java/step2/StringAddCalculator.java
> +            throw new RuntimeException("Is Not a Integer Format");
현재 요구사항에선 `RuntimeException` 예외만 발생시키라고만 되어있지만, 프로덕트에선 비즈니스 로직 예외가 아닌 특정한 예외를 캐치하여 `RuntimeException`으로 돌리는 경우엔 예외 콜스택을 부모객체에 전달해줘야합니다.
왜그럴까요?

2022-10-26 05:59 UTC, mskangg commented on src/main/java/step2/StringAddCalculator.java
> +            throw new RuntimeException("Can not Convert NegativeNumber To Int");
메제지도 상수화하는것도 좋아보입니다 :)

2022-10-26 12:47 UTC, giraffelim commented on src/main/java/step2/StringAddCalculator.java
> +    public static final int NUMBER_OF_TEXT_GROUP = 2;
추가적으로 상수를 선언하면서 단축키를 활용한 뒤 visibility를 수정하지 못한 채 올린 것 같습니다 😢 
말씀해주신대로 수정하였습니다!.
[b89b0cf](https://github.com/next-step/java-lotto-pro/pull/691/commits/b89b0cf025ab9fbbc100711a0554878078c07d60)

2022-10-26 12:47 UTC, giraffelim commented on src/test/java/step2/StringAddCalculatorTest.java
> +    }
올바른 DisplayName으로 수정하였습니다!
[1200e31](https://github.com/next-step/java-lotto-pro/pull/691/commits/1200e31f34ce9f9802de7bb0172aec1da4ade131)

2022-10-26 12:48 UTC, giraffelim commented on src/test/java/step2/StringAddCalculatorTest.java
> +    public void splitAndSum_쉼표_또는_콜론_구분자() {
기존에 쉼표 테스트가 존재했기 때문에 해당 테스트를 콜론인 경우를 테스트하도록 변경하였습니다!
[cab2bf5](https://github.com/next-step/java-lotto-pro/pull/691/commits/cab2bf570bc3351d69a43df86b6b6485f99c46ca)

2022-10-26 12:48 UTC, giraffelim commented on src/test/java/step2/StringAddCalculatorTest.java
> +                .isInstanceOf(RuntimeException.class);
말씀해주신대로 예외 테스트 시 메시지도 함께 테스트할 수 있도록 변경하였습니다!.
[9b9a0be](https://github.com/next-step/java-lotto-pro/pull/691/commits/9b9a0be995ea312b7afba23d95ae7d3165267486)

2022-10-26 12:49 UTC, giraffelim commented on src/main/java/step2/StringAddCalculator.java
> +            throw new RuntimeException("Can not Convert NegativeNumber To Int");
말씀해주신대로 에러메시지도 상수 처리하였습니다!
[d748625](https://github.com/next-step/java-lotto-pro/pull/691/commits/d7486255012ce2ed06065fe2d20028ace824420f)

2022-10-26 13:14 UTC, giraffelim commented on src/main/java/step2/StringAddCalculator.java
> +            throw new RuntimeException("Is Not a Integer Format");
말씀해주신 내용에 대해 제가 이해하기로는 비즈니스 예외가 아닌 특정한 예외를 캐치하여 rethrow 하는 경우 cause에 해당 Exception을 전달해야 한다는 말씀으로 이해했습니다. [abf1e9d](https://github.com/next-step/java-lotto-pro/pull/691/commits/abf1e9dcb52092ed2c8ecf33c2240801123a97be)

`비즈니스 로직 예외가 아닌 특정한 예외를 캐치하여 RuntimeException으로 돌리는 경우엔 예외 콜스택을 부모객체에 전달해줘야합니다. 왜그럴까요?`
=> 프로덕트에서 예외를 처리할 때 여러가지 예외를 하나의 큰 분류의 예외로 묶어서 ControllerAdvice 등을 통해 핸들링을 진행하는데, 비즈니스 로직 예외가 아닌 특정 예외를 캐치하여 다른 Exception으로 돌릴 경우 근본이 되는 예외를 전달함으로써 스택 트레이스 출력 시 해당 내용을 출력하거나 디버깅 시 확인할 수 있기 때문에 빠르게 문제의 원인을 파악하거나 해당 Exception의 cause를 통해 부가적인 처리를 진행할 수 있기 때문에 전달해주어야 된다고 생각하였습니다. 혹 제가 놓치고 있거나 잘못된 부분이 있다면 알려주시면 감사하겠습니다!

2022-10-26 13:18 UTC, giraffelim commented
@mskangg 
안녕하세요 민수님! 제 코드를 꼼꼼하게 리뷰 진행해주셔서 정말 감사합니다 💯 
코멘트로 남겨주신 피드백에 대한 내용을 확인한 뒤, 작업을 진행하였습니다.
추가로 String.split의 경우 내부에서 Pattern.compile을 통해 split을 진행하고 있다는 것을 알게 되어 해당 부분도 미리 선언해놓고 재사용될 수 있도록 변경해보았습니다. [da5d4e0](https://github.com/next-step/java-lotto-pro/pull/691/commits/da5d4e0e5bdf5ca99e347d4a935e5f93217c8e7b)
감사합니다! 👍 👍 👍

2022-10-27 00:46 UTC, mskangg commented on src/main/java/step2/StringAddCalculator.java
> +            throw new RuntimeException("Is Not a Integer Format");
https://ojt90902.tistory.com/887
넵~~ 예외를 던지는데에 있어 의미를 알고 계신것 같습니다! 🤙🏻

2022-10-27 00:51 UTC, mskangg approved these changes
피드백에 대한 커밋 링크도 남겨주시니, 편하게 리뷰하였습니다~ 👍👍👍 
2단계 잘 마무리하셨고, 로또 미션 화이팅입니다! 🚀

2022-10-27 00:51 UTC, merged