Step2
next-step/java-lotto-pro pull request #759
Opened 2022-10-28 03:17 UTC by yeojiin

메서드를 분리하는 부분이 어려웠던 거 같아요.
특히, 특수문자를 delimiter로 넘겼을 경우가 추가되니 if문이 지저분하게 많아진 것 같네요.😥
어느 단위까지 쪼개는 게 좋을지 고민이 됩니다.🤔
리뷰 잘 부탁드립니다

2022-10-29 08:26 UTC, joojimin requested changes
안녕하세요~ 정연님! 리뷰어 주지민입니다!
몇가지 궁금한 점과 요구사항을 충족못시킨 부분이 있어서 RC드렸습니다!
코멘트 확인부탁드려요!

2022-10-29 08:26 UTC, joojimin commented on src/main/java/step2/StringAddCalculator.java
> +    private static String delimiter = "";
상수 정의가 완벽히 안된 것 같아요!! **변하지 않고, 항상 일정한 값을 갖는 수** 인데요! 변하지 않게하려면 어떤 키워드가 추가되야할까요?

2022-10-29 08:26 UTC, joojimin commented on src/main/java/step2/StringAddCalculator.java
> +    private static void init() {
초기화 로직을 메서드로 빼신 이유가 있을까요~? 
매번 로직이 추가될때마다 init() 메서드를 수행해야할 거 같은데 
클래스 생성시 초기화로는 부족했을까요?

2022-10-29 08:26 UTC, joojimin commented on src/main/java/step2/StringAddCalculator.java
> +            throw new RuntimeException("negative Exception");
Exception에 들어가는 메시지도 상수로 정의해보면 어떨까요?!

2022-10-29 08:26 UTC, joojimin commented on src/main/java/step2/StringAddCalculator.java
> +            delimiter = m.group(1);
매처에서 뽑아내는 그룹값도 상수로 정의되면 의미가 명확해 질 것 같습니다!

2022-10-29 11:13 UTC, yeojiin commented on src/main/java/step2/StringAddCalculator.java
> +    private static String delimiter = "";
항상 일정한 값을 가진다는 부분을 제가 놓쳤습니다!😅 final을 추가하면 될 것 같습니다.

2022-10-29 11:14 UTC, yeojiin commented on src/main/java/step2/StringAddCalculator.java
> +            throw new RuntimeException("negative Exception");
그럼 훨씬 직관적일 것 같네요~ 해당 부분도 상수 처리 했습니다!

2022-10-29 11:29 UTC, yeojiin commented on src/main/java/step2/StringAddCalculator.java
> +    private static void init() {
수정하면서 이 부분을 제일 많이 고민했는데 명확한 답을 찾지 못한 것 같습니다.
테스트를 한번에 돌렸을 때 sum이 0으로 초기화 되지 않고 
이전 테스트 결과를 반영해 누적되는 현상이 생겨 해당 메서드를 호출할 때마다 sum과  delimiter 상수를 초기화 해주려는 의도였는데
클래스 생성시 초기화는 어떤 방식으로 진행하면 좋을까요?

StringAddCalculatorTest 부분에 @BeforeEach를 선언 후 StingAddCalculator에 생성자를 만들어도 봤는데
 @Test
    public void splitAndSum_custom_다양한_구분자() throws Exception {
        int result = StringAddCalculator.splitAndSum("//*\n3*3*3");
        assertThat(result).isEqualTo(9);

        result = StringAddCalculator.splitAndSum("//$\n1$2$3");
        assertThat(result).isEqualTo(6);

        result = StringAddCalculator.splitAndSum("//0\n10203");
        assertThat(result).isEqualTo(6);
    }
위와 같은 테스트의 경우 같은 테스트 케이스의 경우 StringAddCalculator 클래스의 sum이 계속해서 누적되어 

결국
public static int splitAndSum(String target) {
        sum = 0;
        delimiter = basicSplitRegex;
  ...
}
과 같이 추가했는데 그렇다면 init()메서드와 달라지는 부분이 없어지는 거 같아서요😥
제가 TDD에 익숙하지 않고, 아직 공부해야 할 게 많은 단계라 너무 기본적인 질문을 드리는 거 같아 죄송하네요.
답답하실 수 있겠지만 열심히 하는 모습을 좋게 봐주셨으면 합니다! 
꼼꼼한 리뷰 정말 감사합니다!

2022-10-30 04:50 UTC, joojimin commented on src/main/java/step2/StringAddCalculator.java
> +    private static void init() {
StringAddCalculator 클래스에서 두가지를 분리해볼수 있을 것 같아요!
현재 sum, 즉 결과를 수집하는 기능과 String을 split하여 변환하는 기능 두가지가 해당 클래스에 관심사로 잡혀 고민이 되시는게 아닌가 싶습니다!
결과를 수집할 수 있는 클래스를 만들어 StringAddCalculator.splitAndSum에서 반환하게 하면 어떨까요~?
sum의 초기화도 걱정할 필요없고, delimiter도 상수로 가져갈 수 있지 않을까 생각됩니다!

2022-10-30 04:51 UTC, joojimin commented
안녕하세여 정연님~!!
작은 부분도 놓치지않고 고민하시는 모습 정말 감명깊었습니다!
질문 남겨주신 내용에 코멘트 달았는데 다음 미션 진행하시면서 같이 한번 고민해보면 좋을 것 같아요!
이번 미션은 머지하도록 하겠습니다~
고생하셨습니다!

2022-10-30 04:51 UTC, merged

2022-10-30 04:52 UTC, joojimin approved these changes
에고 어프로치를 늦게했습니다~!