3단계 - 로또(자동) 리뷰 요청
next-step/java-lotto-pro pull request #762
Opened 2022-10-28 12:54 UTC by cwJohnPark

안녕하세요. 원철님 😃 

자동 로또 프로그램을 구현하였습니다.

리뷰 부탁드립니다!
감사합니다.

2022-10-28 16:38 UTC, heowc requested changes
안녕하세요. 창원님 🙇 

빠르게 3단계를 진행해주셨네요 👍 
전체적으로 잘 진행해주셨지만, 조금 더 고민해보시면 좋을 것 같은 내용이 있어 코멘트를 남겼습니다. 🙏 

코멘트 보시고 궁금하신 점이나 함께 이야기해보면 좋을 내용이 있다면 깃헙 코멘트 또는 슬랙 DM으로 편하게 말씀 부탁드립니다 🙇

2022-10-28 16:38 UTC, heowc commented on src/main/java/lotto/LottoNumberGenerator.java
> +public interface LottoNumberGenerator {
인터페이스를 만듬으로써, 상세 구현을 숨길 수 있겠네요 👍 
다만, `LottoTicket`를 생성한다면, `LottoTicketGenerator`라는 네이밍이 더 적절하지 않을까 싶습니다.
어떻게 생각하시나요? 🤔

2022-10-28 16:38 UTC, heowc commented on src/main/java/lotto/AutoLottoNumberGenerator.java
> +			LottoNumber.MIN_NUMBER, LottoNumber.MAX_NUMBER, LottoTicket.NUMBER_COUNT);
로또번호는 1 ~ 45 사이에 숫자로 이루어지는 걸로 알고 있는데요.
`Randoms#generateUniqueNumbers`에 구현된 코드를 보면 1 ~ 44 사이의 로또번호만 생성될 것 같습니다. 😱

2022-10-28 16:38 UTC, heowc commented on src/main/java/lotto/LottoMatchResult.java
> +	private final List<Integer> equalNumbersCount;
`~~~Count` 라는 변수명이라면 `Number` 타입의 값이라고 추측되지만,  `List<Integer>` 타입을 갖습니다.
보다 적절한 변수명으로 바꿔보는 건 어떨까요? 🤔

2022-10-28 16:38 UTC, heowc commented on src/main/java/lotto/LottoNumber.java
> +public class LottoNumber {
일급객체 활용 좋습니다 👍 

추가로 고민해볼 만한 점이 있다면, `로또 번호`는 1 ~ 45 사이에 번호로 이루어지기 때문에 인스턴스 캐싱을 해볼 수 있지 않을까 싶습니다. 👍  인스턴스 캐싱은 [Integer](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/lang/Integer.java#L1012)에도 비슷한 전략을 사용하고 있으니, 궁금하시면 링크를 참고해주세요 😄

2022-10-28 16:38 UTC, heowc commented on src/main/java/lotto/LottoNumber.java
> +	public boolean isEqualTo(int number) {
해당 코드는 테스트를 위한 코드로 보이는데요. 
`equals`로도 충분히 테스트를 작성해볼 수 있을 것 같습니다.

어떻게 생각하시나요? 🤔

2022-10-28 16:38 UTC, heowc commented on src/main/java/lotto/LottoVendor.java
> +	public LottoTickets purchase(Money amount) {
`로또 판매기(LottoVendor)`에 구매한다 라는 메소드가 있는 점이 다소 어색합니다.
해당 메소드는 어디로 옮길 수 있을까요? 혹은 어떻게 변경해야 할까요? 🤔

2022-10-28 16:38 UTC, heowc commented on src/main/java/lotto/LottoTicket.java
> +	public static LottoTicket of(int... numbers) {
정적 팩토리 메소드을 사용하셨군요 👍

2022-10-28 16:38 UTC, heowc commented on src/main/java/money/Money.java
> +		return Money.wons(subtractedAmount);
금액을 차감했는데 보다 많은 금액을 차감할 때는 0원을 주는 것이 다소 어색한 것 같습니다.
오히려 예외를 던지는 것이 더 좋지 않을까요 ? 🤔

2022-10-28 16:38 UTC, heowc commented on src/main/java/utils/CollectionUtils.java
> +public class CollectionUtils {
유틸 클래스 작성 좋습니다 👍 

유틸 클래스의 경우는 생성자가 필요하지 않으므로 다양한 방법으로 이를 방어해볼 수 있을 것  같아요.
https://camel-context.tistory.com/37

2022-10-28 16:38 UTC, heowc commented on src/main/java/view/LottoWinPrize.java
> +public enum LottoWinPrize {
enum 시용 좋습니다 👍

2022-10-28 16:38 UTC, heowc commented on src/main/java/view/LottoWinResultView.java
> +	}
1) get 메소드이기 때문에 어떤 값을 꺼낼 것이라고 기대하지만 반환타입이 void 이기 때문에 적절하지 않은 네이밍인 것 같습니다.

이는 View에서 너무 많은 것을 하고 있기 때문이라고 생각되는데요. View에서는 서비스 로직이 포함되기 보다는 결과를 출력하는데 필요한 로직만 포함되면 좋을 것 같습니다.

2) `lottoMatchResult#getMatchCount(...)` 을 다시 보니, 호출시 마다, 리스트를 순회하며 매치된 갯수를 세는군요. `LottoMatchResult`를 만들 때 한번만 순회하여 캐싱해둔다면 보다 효율적이지 않을까요? 🤔  

3) `총 수익률은 0.35입니다.(기준이 1이기 때문에 결과적으로 손해라는 의미임)`이 누락된 것 같습니다. 확인 한 번만 해주세요~ 🙇

2022-10-28 16:38 UTC, heowc commented on src/test/java/lotto/LottoTicketTest.java
> +	}
아무 것도 테스트하지 않는 것 같아요 😢

2022-10-28 16:38 UTC, heowc commented on src/test/java/lotto/LottoTicketTest.java
> +	}
갯수가 적을 때에 대한 테스트 재료도 있으면 좋을 것 같아요 👍

2022-10-28 16:38 UTC, heowc commented on src/main/java/view/LottoApplication.java
> +package view;
해당 클래스가 view 패키지 내부에 위치하는 것이 맞을까요?
특히 main 메소드가 있는 클래스는 첫 진입점을 찾을 수 있도록 상위 패키지 하위에 두는 것이 좋다고 생각합니다.

어떻게 생각하시나요? 🤔

2022-10-29 01:16 UTC, cwJohnPark commented on src/main/java/lotto/LottoNumberGenerator.java
> +public interface LottoNumberGenerator {
원래 `LottoTIcket` 가 `LottoNumber` 였었어요.
미처 따라서 바꾸지 못했네요! 
감사합니다 👍

2022-10-29 01:18 UTC, cwJohnPark commented on src/main/java/lotto/AutoLottoNumberGenerator.java
> +			LottoNumber.MIN_NUMBER, LottoNumber.MAX_NUMBER, LottoTicket.NUMBER_COUNT);
감사합니다!

2022-10-29 01:25 UTC, cwJohnPark commented on src/main/java/lotto/LottoMatchResult.java
> +	private final List<Integer> equalNumbersCount;
로또 번호가 일치한 갯수를 의미하니,
matchCounts  가 어떨까요?

2022-10-29 01:27 UTC, cwJohnPark commented on src/main/java/lotto/LottoNumber.java
> +public class LottoNumber {
성능을 더 높일수 있는 방법이 있었군요. 감사합니다!

2022-10-29 01:45 UTC, cwJohnPark commented on src/main/java/lotto/LottoNumber.java
> +	public boolean isEqualTo(int number) {
확인 감사합니다!

2022-10-29 01:51 UTC, cwJohnPark commented on src/main/java/lotto/LottoVendor.java
> +	public LottoTickets purchase(Money amount) {
이후 미션에 수동이 있으니 그냥 구매한다는 것이 어색하다는 말씀이실까요?
로또 자동발급을 영어로 quick pick이라고 하는데,
로또 판매기를 통해 로또티켓을 자동 발급(quickPick)이 어울리지 않을까요?

2022-10-29 02:00 UTC, cwJohnPark commented on src/main/java/utils/CollectionUtils.java
> +public class CollectionUtils {
시큐어 코딩 팁 감사합니다 !
마침 Sonar Lint 에서도 오류를 보고하네요.

2022-10-29 02:41 UTC, cwJohnPark commented on src/main/java/view/LottoWinResultView.java
> +	}
1. printMatchCount 로 수정해보았습니다.
2. LottoWinResult 가 상태를 갖도록 수정하였습니다!
3. 추가하였습니다!

2022-10-29 03:13 UTC, cwJohnPark commented on src/test/java/lotto/LottoTicketTest.java
> +	}
이 테스트 케이스는 필요 없을 것 같아서 제거하겠습니다!

"중복이 될 경우 예외를 던진다" 는 테스트 케이스를 만들었으니,
이 테스트 케이스가 통과하면 중복이 되는 경우가 없음을 동시에 증명할 수 있을 것 같습니다.

2022-10-29 03:14 UTC, cwJohnPark commented on src/test/java/lotto/LottoTicketTest.java
> +	}
미처 생각하지 못했네요! 감사합니다 👍

2022-10-29 03:17 UTC, cwJohnPark commented on src/main/java/view/LottoApplication.java
> +package view;
상위 패키지는 패키지 이름이 없는 상태여서 view쪽으로 넣었었네요.
view 를 포함해서 메인 애플리케이션 클래스는 lotto 패키지에 넣어야 할 것 같네요!

2022-10-29 03:18 UTC, cwJohnPark commented
안녕하세요. 원철님.
피드백 반영하였습니다 😀

2022-10-29 05:32 UTC, heowc approved these changes
리뷰 반영 감사합니다 🙇 

이번 단계는 여기서 마무리 하도록 할게요 👍 
다음 단계를 진행하기 이전에 확인 해주셨으면 하는 소소한(?) 코멘트를 몇개 남겼습니다. 🙏 

코멘트 보시고 궁금하신 점이나 함께 이야기해보면 좋을 내용이 있다면 깃헙 코멘트 또는 슬랙 DM으로 편하게 말씀 부탁드립니다 🙇

2022-10-29 05:32 UTC, heowc commented on src/main/java/lotto/LottoApplication.java
> +
메소드마다 빈 라인을 넣으신 이유가 있으신가요? 🤔

2022-10-29 05:32 UTC, heowc commented on src/main/java/lotto/domain/LottoNumber.java
> +		return CachedLottoNumber.fetch(number);
Cache 활용 좋습니다 👍

2022-10-29 05:32 UTC, heowc commented on src/main/java/lotto/domain/LottoTicket.java
> +	public int match(LottoTicket other) {
창원님 만의 메소드를 나열하는 순서가 있으실까요?

팀 마다 / 오픈소스마다 / 개인 마다 컨밴션 다를 수 있겠지만
`toString`, `equals`, `hashCode` 같은 메소드는 아래로 두는 것이 가독성에 더 좋지 않을까 싶습니다. 🤔

2022-10-29 05:32 UTC, heowc commented on src/main/java/lotto/domain/LottoTickets.java
> +	private final List<LottoTicket> lottoTicketList;
특정 구현체에 의존하는 변수명은 지양하는 것이 좋다고 생각합니다. `lottoTickets`는 어떨까요? 🤔

2022-10-29 05:32 UTC, heowc commented on src/main/java/lotto/domain/ProfitMargin.java
> +	public boolean isProfitDecimal() {
1. 0 초과 ~ 1 미만의 소수인지 확인하기 위한 표현일까요? 

    오히려 해당 메소드를 사용하는 메소드에서 힌트를 얻어 `isLoss`는 어떨까요? 어떻게 생각하시나요? 🤔 

2. 아무것도 맞춘 것이 없다면 0일 수도 있지 않을까요? 

    테스트가 누락되었다면 관련 테스트도 추가해주면 좋을 것 같아요 😄

2022-10-29 05:32 UTC, heowc commented on src/test/java/lotto/FixedLottoTicketGenerator.java
> +public class FixedLottoTicketGenerator implements LottoTicketGenerator {
테스트를 위한 클래스라도 테스트 케이스를 작성해보이는 걸 권장드립니다 👍

2022-10-29 05:32 UTC, heowc commented on src/test/java/lotto/LottoTicketTest.java
> +	}
좋은 것 같습니다 👍

2022-10-29 05:32 UTC, heowc commented on src/main/java/lotto/LottoMatchResult.java
> +	private final List<Integer> equalNumbersCount;
> matchCounts 가 어떨까요?

변수명과 클래스명까지 바꿔주셨네요 😄 좋은 방법인 것 같아요!

2022-10-29 05:32 UTC, heowc commented on src/main/java/lotto/LottoVendor.java
> +	public LottoTickets purchase(Money amount) {
구매를 하는 건 누가 하는 것일까? 라는 관점에서 생각해보면 어떨까요?

로또 판매기 입장에서는 오히려 판매한다 등의 표현이 더 적절하진 않나? 라는 의문이 들었습니다.
말씀하신 자동발급이라는 표현도 좋은 표현이라고 생각됩니다 👍

2022-10-29 05:33 UTC, merged

2022-10-29 05:46 UTC, cwJohnPark commented on src/main/java/lotto/LottoApplication.java
> +
분리해보는게 좋을것 같아서 했는데 같은 것끼리는 띄우지 않는게 좋을 것 같네요! 🙏

2022-10-29 05:47 UTC, cwJohnPark commented on src/main/java/lotto/domain/LottoTickets.java
> +	private final List<LottoTicket> lottoTicketList;
포매팅이 적용이 안되었네요. 확인 감사합니다 😁

2022-10-29 05:49 UTC, cwJohnPark commented on src/main/java/lotto/domain/ProfitMargin.java
> +	public boolean isProfitDecimal() {
말씀주신 대로 수정하겠습니다!

처음에 말씀하신 1,2번 그대로 적용했었습니다.
"기준이 1이기 때문에 결과적으로 손해라는 의미임"  이라는 콘솔에 뜨는 이유가 소수점으로 나오면 수익이 나왔음으로 오해할 수 있다고 판단해서 저렇게 했었네요 😅

2022-10-29 05:56 UTC, cwJohnPark commented
원철님 빠른 피드백 감사합니다. 🙏🏼
피드백 모두 반영하였습니다!

2022-10-29 07:20 UTC, heowc commented
> 원철님 빠른 피드백 감사합니다. 🙏🏼
> 
> 피드백 모두 반영하였습니다! 
> 
> 

제가 오해하게끔 말씀을 드렸네요 😅
다음 단계 진행시에 같이 반영 및 코멘트 해주시면 됩니다!
무튼 다음 단계도 화이팅입니다 💪💪