Step3 리뷰 요청합니다!
next-step/java-lotto-pro pull request #771
Opened 2022-10-28 18:00 UTC by jisu1211

안녕하세요~ 
2단계에서 세심한 피드백 감사했습니다 ㅎㅎ
피드백 주신 부분들 수정하였고, 
3단계도 열심히 구현해봤는데 피드백 부탁드립니다!
감사합니다 😊

2022-10-29 08:50 UTC, limwoobin requested changes
안녕하세요 지수님 
2단계때 말씀드린 내용 피드백 잘 해주셨네요 ㅎㅎ
3단계 미션 또한 굉장히 잘 수행해주셨습니다! 객체를 나누는 부분이 굉장히 인상적이었습니다. 

다만 같이 고민해보면 좋을만한 내용이 있어 코멘트 드렸습니다
확인 후 다시 요청부탁드립니다!

+ 추가로 테스트코드에 대해서는 도메인의 클래스 단위로 작성해보면서 연습하는것을 추천드립니다! 이번 경우엔 아쉽게도 몇몇클래스가 빠져있었네요ㅠ 이부분도 같이 확인부탁드려요 ㅎㅎ

2022-10-29 08:50 UTC, limwoobin commented on README.md
> +총 수익률은 0.35입니다.(기준이 1이기 때문에 결과적으로 손해라는 의미임)
요구사항 정리 👍

2022-10-29 08:50 UTC, limwoobin commented on src/main/java/study/lotto/domain/Lotto.java
> +    }
```java
private final List<Integer> numbers;

public Lotto(List<Integer> numbersFromStore) {
    numbers = .numbersFromStore;
}
```
와 같이 객체 생성시에 생성자에서 바로 할당하는건 어떨까요??
리스트를 선언하고 객체를 add하는것보다 간소화할 수 있을것같아요!

2022-10-29 08:50 UTC, limwoobin commented on src/main/java/study/lotto/domain/Lotto.java
> +            result += Collections.frequency(winningNumbers, num);
로또번호가 있는경우 result에 더해주는군요
그런데 frequency의 경우 해당 값이 몇 개가 있는지의 목적으로 사용되는게 더 알맞다고 생각들어
contains를 이용해하는건 어떨까 생각듭니다!

이 부분은 개인적인 의견이니 참고만 해주세요!

2022-10-29 08:50 UTC, limwoobin commented on src/main/java/study/lotto/domain/Lottos.java
> +    }
생성자로 `List<List<Integer>>` 를 사용하시는것보다는 어느 객체를 인자로 전달받는지 보다 명확한
`List<Lotto>` 는 어떨까요?? 
해당 객체를 사용하는쪽에서 보면 복잡도가 높아보일수도 있을것같아서요!

2022-10-29 08:50 UTC, limwoobin commented on src/main/java/study/lotto/domain/Store.java
> +    }
로또번호를 캐싱해서 추출하셧군요 굉장히 좋네요 ㅎㅎ

2022-10-29 08:50 UTC, limwoobin commented on src/main/java/study/lotto/domain/WinningNumbers.java
> +        String[] strings = Splitter.split(winningNumbers);
strings보다는 입력받은 당첨번호인것을 더 드러내는 네이밍이 오면 좋겠습니다!

2022-10-29 08:50 UTC, limwoobin commented on src/main/java/study/lotto/domain/WinningNumbers.java
> +        return Collections.EMPTY_LIST;
checkSize에서 예외를 바로 던져버리기때문에 
맨 아래의 return Collections.EMPTY_LIST는 실행될 일이 없을것같아요!

checkSize를 void로 변경해 아래와 같이 사용하는건 어떻게생각하시나요??
```java
checkSize(strings);
return convertStringArrToList(strings);
```

2022-10-29 08:50 UTC, limwoobin commented on src/main/java/study/lotto/domain/Lottos.java
> +            buffer.append(lotto.toString() + "\n");
StringBuffer를 쓰셧으니 통일감있게
`buffer.append(lotto.toString()).append("\n");` 이렇게 쓰는건 어떨까요??

2022-10-29 08:50 UTC, limwoobin commented on src/test/java/study/lotto/domain/WinningNumbersTest.java
> +class WinningNumbersTest {
저의 경우 테스트코드 작성시 제일 우선시하는게 
어느 기능에 대한 테스트인지 명확하게 나타내는것입니다. 
메소드에도 꼼꼼하게 작성해주셧지만 클래스에도 `@DisplayName("당첨번호 테스트")` 와 같은 description을 남겨주는것도 좋은방법입니다!

이 부분은 개인의견이라 참고만 해주세요!

2022-10-29 08:50 UTC, limwoobin commented on src/main/java/study/lotto/Application.java
> +}
로또게임의 시작인에 단순 Console이라기엔 명확하게 와닿지가 않네요
`LottoController or LottoGames` 와 같은 명시적인 이름은 어떨까요?

2022-10-29 08:50 UTC, limwoobin commented on src/main/java/study/lotto/domain/WinStats.java
> +    }
해당 문구는 view영역에서 하는개 알맞지 않을까요??

2022-10-29 08:50 UTC, limwoobin commented on src/test/java/study/lotto/domain/ProfitRateTest.java
> +    }
`@ParameterizedTest` 을 이용해 다양한 수익률을 계산해보는것도 좋아보입니다!

2022-10-29 09:12 UTC, jisu1211 commented on src/main/java/study/lotto/domain/Lotto.java
> +    }
네~ 제안해주신 부분이 더 간단해보이네요! 수정하도록 하겠습니다 ㅎㅎ

2022-10-29 09:14 UTC, jisu1211 commented on src/main/java/study/lotto/domain/Lotto.java
> +            result += Collections.frequency(winningNumbers, num);
저도 저 부분 작성하면서 애매하다고 생각했는데, 말씀해주신 내용으로 변경해보도록 하겠습니다 ☺️

2022-10-29 09:14 UTC, jisu1211 commented on src/main/java/study/lotto/domain/Lottos.java
> +    }
List<Lotto>로 변경하니까 훨씬 보기에 간단해지네요! 좋은 피드백 감사합니다 ㅎㅎ

2022-10-29 09:15 UTC, jisu1211 commented on src/main/java/study/lotto/domain/WinningNumbers.java
> +        return Collections.EMPTY_LIST;
제가 작성한 부분에서 말씀해주신 대로 마지막 return은 의미가 없어보이네요 ㅎㅎ 수정하겠습니다!

2022-10-29 11:27 UTC, jisu1211 commented
피드백 주신 부분들 수정했는데 다시 리뷰 부탁드리겠습니다!
반영하고나니 코드가 훨씬 깔끔해졌네요 ㅎㅎ 감사합니다👍

2022-10-29 18:39 UTC, jisu1211 commented
코드를 다시 살펴보니, 요구사항에서 부족했던 부분들이 보여서 코드를 수정했습니다!
그리고 `로또 피드백` 영상을 미리 시청하고, 좀 더 개선하고 싶은 부분들 반영했습니다 ㅎㅎ
아직 많이 익숙하지 않아 어렵네요 ㅠㅠ 감사합니다 ☺️

2022-10-30 06:49 UTC, limwoobin commented on src/main/java/study/lotto/domain/Lotto.java
> +    private static Set<LottoNumber> toSet(List<Integer> numbersFromStore) {
static으로 사용한 이유가 따로 있을까요??~

2022-10-30 06:49 UTC, limwoobin commented on src/main/java/study/lotto/domain/Lotto.java
> +                .map((num) -> LottoNumber.of(num))
메서드참조를 이용해 `.map(LottoNumber::of)` 로 사용할 수 있겠군요

2022-10-30 06:49 UTC, limwoobin commented on src/main/java/study/lotto/domain/LottoNumber.java
> +    }
코드 전체적으로 자바 코드컨벤션을 한번 확인해주세요! (줄개행, space 등등)

2022-10-30 06:49 UTC, limwoobin commented on src/main/java/study/lotto/domain/Lottos.java
> +    }
해당 클래스의 인스턴스변수는 this 를 붙여주시는걸 추천드려요!
그래야 해당 클래스에서 쓰이는 변수라는걸 명확히 할 수 있습니다

2022-10-30 06:49 UTC, limwoobin commented on src/test/java/study/lotto/domain/WinningNumbersTest.java
> +class WinningNumbersTest {
<img width="490" alt="image" src="https://user-images.githubusercontent.com/28802545/198866204-c17557f2-a815-401a-abd8-138b85fc4f17.png">

테스트 수행시 테스트 케이스가 전보다 명확해진것같네요 👍

2022-10-30 07:04 UTC, limwoobin approved these changes
안녕하세요 지수님 피드백드린 내용 꼼꼼히 잘 반영해주셨네요
테스트 코드도 굉장히 촘촘합니다! ㅎㅎ
요구사항을 충족하지 못한 부분 또한 잘 반영해주셨습니다

다음미션 시작할때 같이 확인하면 좋을 코멘트 몇개 드렸습니다
이번미션은 여기서 merge 하겠습니다 
다음미션도 화이팅입니다!

+ 궁금하신 내용이나 논의하고픈 내용이 있으면 편하게 코멘트나 dm으로 문의주세요!

2022-10-30 07:04 UTC, limwoobin commented on src/main/java/study/lotto/view/LottoGames.java
> +public class LottoGames {
LottoGames는 어플리케이션에서 게임실행을 담당하는 핵심 클래스인데
view영역에 있는게 맞을까 하는 의문이 있네요 ㅎㅎ 지수님은 어떻게 생각하시나요?

2022-10-30 07:04 UTC, merged

2022-10-30 09:50 UTC, jisu1211 commented on src/main/java/study/lotto/domain/Lotto.java
> +    private static Set<LottoNumber> toSet(List<Integer> numbersFromStore) {
다른 생성자를 사용하려고 static을 사용했는데 생각해보니 static을 사용하지 않고도 해결이 가능했네요!
`this.numbers = toSet(numbersFromStore);`
이렇게 수정해보겠습니다!

2022-10-30 09:51 UTC, jisu1211 commented on src/main/java/study/lotto/domain/LottoNumber.java
> +    }
그 부분을 자세히 보지 못했네요,, 부족한 점 짚어주셔서 감사합니다~

2022-10-30 09:54 UTC, jisu1211 commented on src/main/java/study/lotto/view/LottoGames.java
> +public class LottoGames {
아직 클래스들을 패키지로 분류할 때 어떤 패키지가 적정할지 고민이 많이 됩니다ㅠㅠ 
우빈님은 어디가 적정하다고 생각하시는지 도움 주실 수 있으실까요..? 😢