Step3
next-step/java-lotto-pro pull request #788
Opened 2022-10-29 10:47 UTC by diqksrk

후... 일급컬렉션 적용이 어렵네요 ㅠㅠ
그래도 열심히....
리뷰 부탁드립니다.

2022-10-29 16:15 UTC, shared-moon requested changes
민준님 안녕하세요!
3단계 미션 잘 진행 해 주셨네요 :)
다음미션 진행하기 전에 한번 정리하고 가면 좋을 것 같아서, 코멘트 확인 후에 다시 리뷰 요청 부탁드려요!
화이팅입니다 🔥

2022-10-29 16:15 UTC, shared-moon commented on src/main/java/enums/Match.java
> +    THREE(3, 5000),
숫자 천 단위를 `_` 로 끊어 표현하면 읽기가 쉬워요!

2022-10-29 16:15 UTC, shared-moon commented on src/main/java/controller/Lotto.java
> +        OutputWriter.answerLottoQuantity(lottoPurchaseAmount.getQuantityPerAmountLotto());
이거는 취향차이이긴 한데 .. print 같은 보편적은 prefix를 사용하는게 더 좋지 않을까요 ?

2022-10-29 16:15 UTC, shared-moon commented on src/main/java/exception/DuplicationLottoNumbersException.java
> +public class DuplicationLottoNumbersException extends IllegalArgumentException {
예외 정의 좋네요 👍 하지만 상속은 RuntimeException을 받는게 더 좋을 것 같아요!

2022-10-29 16:15 UTC, shared-moon commented on src/main/java/model/LottoNumberGenerator.java
> +        List<Integer> lottoNumbers = IntStream.rangeClosed(number.getMinimumRangeNumber(), number.getMaximumRangeNumber())
이 숫자들은 미리 만들어둬도 괜찮지 않을까요 ?

2022-10-29 16:15 UTC, shared-moon commented on src/main/java/model/LottoLotteryTickets.java
> +    public LottoLotteryTickets(int lottoQuantity, LottoNumberGenerator lottoNumberGenerator) {
`LottoNumberGenerator`를 전달받아 사용하는 이유가 혹시 어떤걸까요 ?

2022-10-29 16:15 UTC, shared-moon commented on src/main/java/model/LottoNumber.java
> +    private final int MINIMUM_RANGE_NUMBER = 1;
요거는 static이 빠졌네요!

2022-10-29 16:15 UTC, shared-moon commented on src/main/java/model/LottoNumber.java
> +        if (!isRightNumber(number)) {
부정연산자 `!`를 사용 할 일이 있을 땐, 메서드이름을 부정형으로 제공해보는 건 어떨까요 ?

2022-10-29 16:15 UTC, shared-moon commented on src/main/java/model/LottoNumbers.java
> +    public boolean contain(LottoNumber targetlottoNumber) {
`lottoNumbers.contains()`와 어떤게 다른걸까요 ?

2022-10-29 16:15 UTC, shared-moon commented on src/main/java/model/LottoPurchaseAmount.java
> +    private boolean isRightAmountUnit(String amount) {
다른데도 그렇긴 한데 유효성검사는 보통 valid 라는 prefix를 사용해요!

2022-10-29 16:15 UTC, shared-moon commented on src/main/java/model/Result.java
> +        if (matchCount == 3) {
Enum을 이용해서 조금 간소화 할 수 있지 않을까요 ? 약간 힌트를 드리자면 Enum은 어플리케이션 스코프에서 유일한 객체라 key로 사용되어도 무방합니다!

2022-10-29 17:59 UTC, diqksrk commented on src/main/java/model/LottoLotteryTickets.java
> +    public LottoLotteryTickets(int lottoQuantity, LottoNumberGenerator lottoNumberGenerator) {
그 밑에 lottoNumbers 만들때 필요해서 전달했습니다!

2022-10-29 18:00 UTC, diqksrk commented on src/main/java/model/LottoNumbers.java
> +    public boolean contain(LottoNumber targetlottoNumber) {
말씀하신 방법으로 시도 해보았는데 잘 안되서 제가 정의했는데 다시 한번 시도해보겠습니다 !

2022-10-29 18:03 UTC, diqksrk commented on src/main/java/model/LottoNumber.java
> +    private final int MINIMUM_RANGE_NUMBER = 1;
한 가지 궁금한게 class 내에서 static 변수가 존재하면 그 변수는 클래스가 생성될때 힙영역에 저장이 되는걸까요?

2022-10-30 07:30 UTC, diqksrk commented on src/main/java/model/LottoNumbers.java
> +    public boolean contain(LottoNumber targetlottoNumber) {
수정 완료했습니다.

2022-10-30 07:30 UTC, diqksrk commented on src/main/java/model/LottoNumber.java
> +    private final int MINIMUM_RANGE_NUMBER = 1;
수정 완료했습니다.

2022-10-30 07:30 UTC, diqksrk commented on src/main/java/exception/DuplicationLottoNumbersException.java
> +public class DuplicationLottoNumbersException extends IllegalArgumentException {
수정 완료했습니다.

2022-10-30 07:38 UTC, diqksrk commented on src/main/java/model/LottoNumber.java
> +        if (!isRightNumber(number)) {
수정 완료했습니다. 음.... 근데 저는 아직까지는 긍정형에 ! 해보는게 좀더 코딩하기 편하네요. 읽히는 것도 그 편이 훨씬 잘 읽히구요. 상황에 맞춰서 사용하겠습니다 !

2022-10-30 07:40 UTC, diqksrk commented on src/main/java/model/LottoPurchaseAmount.java
> +    private boolean isRightAmountUnit(String amount) {
validCheck가 valid를 체크하는 상위함수로 존재하고, 안쪽에서 세부 내용들을 체크하는 과정에서 사용하는것도 안되나요 ?

2022-10-30 07:45 UTC, diqksrk commented on src/main/java/model/LottoNumberGenerator.java
> +        List<Integer> lottoNumbers = IntStream.rangeClosed(number.getMinimumRangeNumber(), number.getMaximumRangeNumber())
수정 완료했습니다.

2022-10-30 08:46 UTC, diqksrk commented on src/main/java/model/Result.java
> +        if (matchCount == 3) {
수정 완료했습니다.

2022-10-30 09:12 UTC, diqksrk commented on src/main/java/controller/Lotto.java
> +        OutputWriter.answerLottoQuantity(lottoPurchaseAmount.getQuantityPerAmountLotto());
수정 완료했습니다.

2022-10-30 09:12 UTC, diqksrk commented on src/main/java/enums/Match.java
> +    THREE(3, 5000),
넵. 알겠습니다 ㅎㅎ

2022-10-30 13:13 UTC, shared-moon commented on src/main/java/model/LottoLotteryTickets.java
> +    public LottoLotteryTickets(int lottoQuantity, LottoNumberGenerator lottoNumberGenerator) {
오 그냥 클래스 내부에서 생성해도 괜찮을 것 같아서 말씀드려봤어요!

2022-10-30 13:16 UTC, shared-moon commented on src/main/java/model/LottoNumber.java
> +    private final int MINIMUM_RANGE_NUMBER = 1;
아뇨 static 영역에 저장됩니다! 다만 객체인 경우는 레퍼런스는 static 영역에 저장 되지만 실제 레퍼런스가 가리키는 객체 정보는 힙영역에 있습니다!

2022-10-30 13:16 UTC, shared-moon commented on src/main/java/model/LottoNumber.java
> +        if (!isRightNumber(number)) {
넵! 부정연산자를 이용하면 종종 못보고 놓치는 경우가 있어서 한번 말씀드려봤어요! 취향 존중합니다 :)

2022-10-30 13:20 UTC, shared-moon commented on src/main/java/model/LottoPurchaseAmount.java
> +    private boolean isRightAmountUnit(String amount) {
안되는건 아닌데 약간 관례같은거라 말씀드려봤어요!
혹시나 해서 코멘트 해봅니다! 제가 피드백 드리는 내용은 `내가 맞으니까 내 말대로 해` 라는 의미는 아니구요, `이런 의견도 있는데 어떻게 생각해?` 가 기본적인 스탠스라고 생각 해 주세요!
제 워딩이 `이렇게 해라!` 라고 들리실 수도 있지만, 텍스트의 오해라고 이해해 주시면 감사하겠습니다. 그런사람 아닙니다 ㅎㅎ
제 피드백을 보시고 한 번 더 생각하는 시간이 되면 좋을 것 같아요! 그리고 마음껏 의견을 내 주시면 됩니다!

오해 없으시길 바라며 호옥시나 해서 몇자 적어봤어요! :)

2022-10-30 13:25 UTC, shared-moon approved these changes
민준님 안녕하세요!
피드백 반영 잘 해 주셨네요 :)
코멘트를 몇 개 남겨 두었는데, 다음 미션 진행 전 확인 부탁드려요!
고생 많으셨습니다 :)

2022-10-30 13:25 UTC, shared-moon commented on src/main/java/controller/Lotto.java
> +        OutputWriter.print(lottoLotteryTickets.toString());
👍

2022-10-30 13:25 UTC, shared-moon commented on src/main/java/enums/Match.java
> +    public static Match findMatch(int matchCount) {
👍

2022-10-30 13:25 UTC, shared-moon commented on src/main/java/exception/LottoAmountUnitException.java
> +public class LottoAmountUnitException extends RuntimeException {
👍

2022-10-30 13:25 UTC, shared-moon commented on src/main/java/model/LottoLotteryTickets.java
> +            lottoResults.put(match, lottoResults.getOrDefault(match, RESULT_DEFAULT_VALUE) + RESULT_ADD_VALUE );
getOrDefault를 위에서 먼저 해서 변수로 받아보는 건 어떨까요?

2022-10-30 13:25 UTC, shared-moon commented on src/main/java/model/LottoNumber.java
> +        if (isNotRightNumber(number)) {
👍

2022-10-30 13:25 UTC, shared-moon commented on src/main/java/model/LottoNumberGenerator.java
> +        List<Integer> lottoNumbers = IntStream.rangeClosed(MINIMUM_RANGE_NUMBER, MAXIMUM_RANGE_NUMBER)
👍

2022-10-30 13:25 UTC, shared-moon commented on src/main/java/model/Result.java
> +    public int findTotalProfits() {
👍

2022-10-30 13:25 UTC, merged

2022-10-31 13:47 UTC, diqksrk commented on src/main/java/model/LottoLotteryTickets.java
> +            lottoResults.put(match, lottoResults.getOrDefault(match, RESULT_DEFAULT_VALUE) + RESULT_ADD_VALUE );
넵 알겠습니다 !