Step3 리뷰 요청드려요
next-step/java-lotto-pro pull request #795
Opened 2022-10-29 15:43 UTC by meeingjae

step2 피드백 내용도 포함하였습니다

좋은 주말 되세요 😊

2022-10-30 11:08 UTC, devyonghee requested changes
안녕하세요 민재님!
로또 (자동) 굉장히 잘 구현해주신 것 같아요 👍👍👍
아직 사용되지는 않지만 많은 역할들을 미리 고민해서 요구사항에 명시해주고 
테스트도 꼼꼼하게 작성해주신 점이 인상적이었습니다 🥹

추가적으로 고민해보시면 좋은 부분들에 대해 코멘트를 남겨드렸는데 
이에 대해 의견 부탁드릴게요!! 🙇‍♂️🙇‍♂️

혹시 궁금하시거나 이상한 점이 보인다면 편하게 DM 이나 코멘트 남겨주시기 바랍니다. 😆

2022-10-30 11:08 UTC, devyonghee commented on src/main/java/calculator/StringCalculator.java
>      }
정적 메서드로 정의해주셨군요 👍👍
유틸리티 클래스의 모습으로 변경 된 것 같은데  기본 생성자를 내부로 감춰서 클라이언트에서 객체 생성을 방지하는 건 어떠신가요??🤔

2022-10-30 11:08 UTC, devyonghee commented on src/main/java/lotto/LottoIssuer.java
> +    }
이 클래스 역시 상태는 없고 정적 메소드만 존재하기 때문에 유틸리티 클래스 같은데요.
마찬가지로 객체로 생성되면 안되는 클래스인 것 같은데 기본 생성자를 내부로 감추는 건 어떠신가요??🤔

2022-10-30 11:08 UTC, devyonghee commented on src/main/java/lotto/LottoIssuer.java
> +
돈을 담당하는 역할로 `Money` 로 캡슐화 해주신 점이 인상적입니다!!  👍👍
로또 금액도 마찬가지로 돈을 의미하는 것 같은데
그 역할의 응집도를 높이기 위해 Money 로 정의하시는 건 어떻게 생각하시나요?? 🤔

2022-10-30 11:08 UTC, devyonghee commented on src/main/java/lotto/LottoNumberBag.java
> +    }
저도 개인적으로 테스트를 위한 코드들이 많아지다보면 코드가 많이 어색해보입니다. 😅
하지만 테스트를 위한 코드라는 것보다 해당 코드가 이 객체의 적절한 역할인 것인지를 먼저 고민해보는데요. 
일급 컬렉션을 선언해주시고 클라이언트의 숫자들을 보관하고 관리하는 점에서는 어색하지 않기 때문에 
저는 적절한 역할이라고 생각합니다. 🤔
다만 그 역할을 충실히 행해야 하기 때문에 검증 로직도 있으면 좋은 것 같은데 이 부분에 대해서 어떻게 생각하시나요?

2022-10-30 11:08 UTC, devyonghee commented on src/main/java/lotto/LottoNumberBag.java
> +    }
생성자에서 `LottoNumberGenerator` 을 바로 실행하게 되면서 강한 결합이 생기고 OCP 위반이 생기는 것 같은데요 🤔
확장성을 고려하여 외부에서 `LottoNumberGenerator` 을 주입하고 스트래티지 패턴을 적용해보는 방향은 어떻게 생각하시나요? 
이미 알고 계실수도 있으시겠지만 잘 설명된 자료가 있어서 스트래티지 패턴에 대해 링크 남겨드리겠습니다!!
[전략 패턴 Strategy Pattern](https://victorydntmd.tistory.com/292)

2022-10-30 11:08 UTC, devyonghee commented on src/main/java/lotto/LottoNumberBag.java
> +
도메인의 영역에서 View 의 영역까지 의존성이 생기게 된 것 같아요!!
클린 아키텍처 책을 참고하면 코드 유지보수를 위해 의존성의 방향은 안쪽으로만 향해야 한다고 하는데요.
도메인이 뷰에 의존성이 생기지 않도록 고민해보시면 좋을 것 같은데 혹시 어떻게 생각하시나요?
제가 고민해보고 참고한 자료 링크 남겨드리도록 하겠습니다! [클린 아키텍처: 의존성 역전하기](https://jaime-note.tistory.com/406)

2022-10-30 11:08 UTC, devyonghee commented on src/main/java/lotto/LottoStore.java
> +        int inputSize = (int) Arrays.stream(input.split(WINNING_NUMBER_INPUT_SPLIT_DELIMETER)).count();
`Arrays.stream(input.split(WINNING_NUMBER_INPUT_SPLIT_DELIMETER))` 코드가 중복으로 발생되는 것 같아요
DRY (Don't Repeat Yourself) 법칙에 위반되는 것 같은데 별도의 클래스로 분리해서 캡슐화 하는 방향에 대해서 어떻게 생각하시나요? 🤔
우승 번호들도 결국 로또 번호이기 때문에 `LottoNumberBag`에서 관리되어도 괜찮지 않을까 생각도 됩니다 🤔🤔

2022-10-30 11:08 UTC, devyonghee commented on src/main/java/lotto/LottoStore.java
> +        }
예외가 발생했을 경우 예외 메세지를 작성해주신 점 좋은 것 같아요!! 👍👍
어떤 값이 들어와서 잘못되었는지 더 자세한 내용을 추가해주신다면 디버깅이 수월해질 것 같은데 
이러한 방향에 대해서 어떻게 생각하시나요??
제가 고민했던 자료 남겨드리겠습니다!! [예외의 상세 메시지에 실패 관련 정보를 담으라](https://codingwell.tistory.com/157?category=1013497)

2022-10-30 11:08 UTC, devyonghee commented on src/main/java/lotto/Money.java
> +    }
저는 개인적으로 도메인 객체에 대해서는 가능하다면 불변성을 유지하고 있는데요.
알고 계시겠지만 객체가 많이 생성되어 메모리를 차지하게 되는 단점이 생길 수 있겠지만 유지보수하는 것이 더 중요하다고 생각하기 때문에 불변객체를 선호하고 있습니다. 
혹시 이 `Money` 도 불변 객체로 사용해보시는 것은 어떻게 생각하시나요?? 🤔
제가 참고한 링크 남겨드리도록 하겠습니다! [Immutable Object(불변객체)](https://velog.io/@conatuseus/Java-Immutable-Object%EB%B6%88%EB%B3%80%EA%B0%9D%EC%B2%B4)

2022-10-30 11:08 UTC, devyonghee commented on src/main/java/lotto/README.md
> +* **로또**
기능 역할별로 도메인을 구분하신 모습이 인상적입니다 👍👍👍

2022-10-30 11:08 UTC, devyonghee commented on src/main/java/lotto/WinningResult.java
> +    MATCH_SIX(6);
이 클래스의 역할은 어떤 역할을 캡슐화하기 위함인지 잘 모르겠어요 🥲
매치 카운트가 증가되면 enum 도 같이 추가 될 것 같은데 혹시 이에 대한 설명을 부탁드려도 될까요?🙇‍♂️ 
그리고 매치된 개수가 곧 등수를 의미하게 되는 것 같은데 
응집도를 위해 우승 등수와 우승 금액을 함께 관리하는 방향에 대해서는 어떻게 생각하시나요?  🤔

2022-10-30 11:08 UTC, devyonghee commented on src/main/java/lotto/view/ResultView.java
> +                .append(results.countByWinningResult(WinningResult.MATCH_THREE)).append("개").append(NEW_LINE)
내부에서 수행되는 반복문을 반복해서 호출하는 것보다 
한번에 우승 정보들에 대해 조회를 하는 것은 어떻게 생각하시나요?? 🤔
스트림에서 `collect(groupingBy(..., counting()))` 을 이용하면 `Map<WinningResult, Long>` 으로 가져와서 성능적으로도 괜찮아질 것 같아요.
이외에도 데이터 수집하는 많은 방법들이 있으니 다음 링크를 참고해보세요!!😆
[스트림으로 데이터 수집 정리](https://sah3122.github.io/dev/2020/08/31/modern-java03/)

2022-10-30 11:08 UTC, devyonghee commented on src/test/java/lotto/MoneyTest.java
> +        assertThat(money.getAmount()).isEqualTo(result);
이 부분이 고민이시라면 내부 값을 가져오는 것이 아니라 객체로 비교하는 것을 추천드립니다!!😆
`Money` 에 `hashCode` 와 `equals` 를 정의하시고 
`assertThat(money).isEqualTo(new Money(result))` 하시면 가능할 것 같아요!

2022-10-30 11:08 UTC, devyonghee commented on src/test/java/lotto/MoneyTest.java
> +    }
피드백을 적극 수용해주시고 반영해주셔서 감사합니다 🙇‍♂️🙇‍♂️🙇‍♂️

2022-10-30 11:08 UTC, devyonghee commented on src/test/java/lotto/LottoIssuerTest.java
> +    }
모든 테스트 메소드에 `@DisplayName` 으로 테스트를 이름을 명시해준 점이 아주 인상적입니다!! 👍👍👍
클래스에도 `@DisplayName`을 추가할 수 있는데 혹시 어떤 역할의 클래스를 테스트하는 건지 추가해보는 것은 
어떻게 생각하시나요??

2022-10-30 11:08 UTC, devyonghee commented on src/main/java/lotto/WinningResultBag.java
> +    List<WinningResult> results;
`results` 의 데이터 보호를 위해 접근 제어자를 지정하여 은닉화를 해주시는 것이 좋을 것 같아요!! 😄

2022-10-30 14:20 UTC, meeingjae commented on src/main/java/calculator/StringCalculator.java
>      }
피드백 검토 후 코드를 다시 보니, ```PositiveOperandBag``` 클래스도 유틸 성격의 클래스로 보입니다 !
해당 클래스의 생성자와 sum() 메서드는 생성과 수행의 생명주기를 함께 하기에 
클래스 내부 속성과, 생성자, 메서드를 정의할 필요 없이정적 메서드로 그 기능을 제공할 수 있는 것으로 보여지네요 
코드를 개선하고 나니 기존 구조보다 코드 보기도 훠어얼씬 더 쉽고, 어떤 역할을 하는 지 명확해졌습니다.
멋진 피드백 감사합니다 ! 😆👍

2022-10-30 14:20 UTC, meeingjae commented on src/main/java/lotto/LottoIssuer.java
> +    }
피드백 반영하여 유틸 클래스의 생성자를 내부로 감추고,
로또 목록을 다루는 일급 컬렉션을 생성하였습니다 !
좋은 의견 감사합니다 😊

2022-10-30 14:20 UTC, meeingjae commented on src/main/java/lotto/LottoIssuer.java
> +
피드백 적극 수용하겠습니다 !
상수로 표현했던 로또 금액을 돈을 담당하는 ```Money``` 클래스로 정의하였습니다
리펙토링을 진행하고 나니, lotto 패키지 내에서 ```Money``` 라는 클래스의 역할에 대한 응집도가 늘어났고, ```Money``` 클래스를 정의한 목적도 명확해졌습니다.
```ResultView``` 클래스에서 ```LottoIssuer``` 클래스의 ```LOTTO_PRICE``` 상수를 의존하고 있는 구조에 대해서 약간 미심쩍은 감정을 느끼고 있었는데, 
코드 개선 이후 ```ResultView```의 의존 구조가 ```Money``` 클래스로 이동하게 되어 훨신 더 깔끔한 코드가 되었습니다.
좋은 피드백 감사합니다 ! 😊

2022-10-30 14:20 UTC, meeingjae commented on src/main/java/lotto/LottoNumberBag.java
> +    }
요구사항을 기준으로 보는 것도 좋지만, 객체 그 자체로의 역할을 고민해 보는 것 또한 중요하군요.
좋은 의견 감사합니다! 앞으로 동일한 유형의 고민이 생길 때 꼭 참고하겠습니다 😊
피드백 주신 내용은 반영하여 유효성 검증 로직 및 테스트 추가하였습니다 
감사합니다 ! 👍

2022-10-30 14:20 UTC, meeingjae commented on src/test/java/lotto/MoneyTest.java
> +        assertThat(money.getAmount()).isEqualTo(result);
테스트를 작성할 때마다 항상 고민하던 부분이었습니다
너무 좋은 아이디어 제공해주셔서 감사합니다 !
피드백 주신 부분 참고하여 앞으로는 테스트 작성 시에 조금 더 본질적인 부분에 접근할 수 있겠어요 😊 👍👍

2022-10-30 14:20 UTC, meeingjae commented on src/test/java/lotto/LottoIssuerTest.java
> +    }
```@Target({ ElementType.TYPE, ElementType.METHOD })```
피드백 주신 대로 클래스에도 명시해서 사용이 가능하네요 !
피드백 수용하여 클래스명에도 ```@DispalyName``` 어노테이션 명시하여 테스트 기능을 명시하고 나니,
기존에 메서드의 ```@DisplayName``` 어노테이션에 각 기능을 header처럼 달았던 구조가 개선되었습니다
좋은 피드백 감사합니다 ! 👍👍

2022-10-30 14:20 UTC, meeingjae commented on src/main/java/lotto/WinningResultBag.java
> +    List<WinningResult> results;
접근 제어자 지정을 깜빡 했네요 !! 
피드백 즉시 수용하여 반영하였습니다 !
꼼꼼히 살펴주셔서 감사합니다 🙇‍♂️

2022-10-31 00:53 UTC, meeingjae commented on src/main/java/lotto/LottoNumberBag.java
> +    }
공유해 주신 아티클 잘 읽어보았습니다 !
피드백 주신 내용대로 숫자를 생성하는 행동을 추상화하여 각각의 구현체에서 구현하도록 구조를 변경하고,
로또를 발급하는 과정에서 해당 전략을 사용하여 lotto 어플리케이션 전반적으로 느슨한 결합을 가져갈 수 있도록 개선하였습니다 !
변경에 대처하기 용이한 구조로 개선 된 것 같아요 
좋은 피드백 감사합니다 😊👍👍

2022-10-31 03:51 UTC, meeingjae commented on src/main/java/lotto/LottoNumberBag.java
> +
의존성의 흐름은 바깥에서 안쪽 한방향으로 ! 잊지 않겠습니다.
세부적인 내용으로 들어갈 수록 큰 아키텍쳐의 구성을 놓치기 쉬운 것 같아요..
계층별 의존성의 흐름도 꼭 신경쓰도록 노력해보겠습니다 !
좋은 피드백 감사합니다 ! 👍👍👍

2022-10-31 05:40 UTC, meeingjae commented on src/main/java/lotto/LottoStore.java
> +        int inputSize = (int) Arrays.stream(input.split(WINNING_NUMBER_INPUT_SPLIT_DELIMETER)).count();
피드백 수용하여 기존 로또 숫자에 대한 검증 로직을 별도 클래스로 분리하였고, 
로또 번호 입력에 대한 검증이 필요한 경우 검증 클래스를 사용하는 구조로 개선하였습니다.
또한 6자리 로또 숫자를 생성하는 부분 역시 말씀해주신 대로 ```LottoNumberBag``` 에서 관리 하는 것이 해당 클래스의 응집도를 높히는 방향이라고 생각 되어 6자리 로또 번호를 생성하는 기능은 모두 '''LottoNumberBag''' 에서 관리하도록 개선하였습니다
구조 개선을 하면서 정적으로 선언된 상수들이 각자 자신이 있어야 할 위치를 찾아간 것 같아요
좋은 피드백 감사합니다 ! 😊

2022-10-31 07:07 UTC, meeingjae commented on src/main/java/lotto/LottoStore.java
> +        }
좋은 아이디어 제공 감사합니다 ! 
디버깅 할 때 예외 메세지만 보고도 어떤 부분에서 어떤 값으로 인해 예외가 발생했는지 확인하기 수월해지겠네요
피드백 수용하여 반영하였습니다 ! 👍

2022-10-31 07:52 UTC, meeingjae commented on src/main/java/lotto/Money.java
> +    }
저도 불변값 사용을 지향합니다 😆
```Money``` 케이스에선 말씀하신바와 같이 객체를 생성해 메모리를 차지하는 이슈가 있어서 객체 내부에서 처리하고자 의도했던 것입니다 🤔 
현재는 복권 구매자가 구매할 수 있는 복권 갯수에 제한이 없어서 개인이 수십만개 이상의 복권이 구매 가능하다는 상황을 어느정도 전제했었는데요 
공유해주신 아티클을 읽고 와서 보니, 불변 객체로 선언해서 얻을 수 있는 장점도 확인했습니다 !
1. 변하지 않는 값이기에 신뢰성이 높다
2. 멀티스레드 환경에서 객체 공유에 유리하다 
3. 유지보수에 용이하다
이러한 장점들을 기반으로 피드백 수용하여 반영하겠습니다 ! 
불변 객체에 대한 좋은 피드백 감사합니다 😊 👍

2022-10-31 09:54 UTC, meeingjae commented on src/main/java/lotto/view/ResultView.java
> +                .append(results.countByWinningResult(WinningResult.MATCH_THREE)).append("개").append(NEW_LINE)
좋은 아이디어 제공해주셔서 감사합니다 !
groupingby api를 사용하니 기존에 결과물 출력을 위해 객체 내부에서 stream 연산을 8번 수행하던 구조에서 
2번만 수행하는 구조로 개선되었습니다 !
공유해주신 아티클 참고하여, 앞으로 목적 있는 stream 연산에 최적화 된 기능이 무엇인지 고민해 보겠습니다
피드백 감사합니다 !! 😊

2022-10-31 10:31 UTC, meeingjae commented on src/main/java/lotto/WinningResult.java
> +    MATCH_SIX(6);
WinningResult 클래스의 본래 의도는 언제든 변경될 수 있는 당첨이라는 기준으로부터 분리하여 정확한 일치 count를 비교하기 위해 존재하는 클래스입니다. 
하지만 피드백 주신 내용처럼 우승 등수와, 우승 금액을 함께 관리하는 응집도 있는 클래스로도 멋진 역할을 할 수 있을 것 같아 피드백을 수용하였습니다 ! 
코드를 개선하고 나니 ```WinningResult``` 클래스에서 등수와 금액에 대한 모든 기능을 제공해서 
```WinningResultBag``` 클래스에 존재하던 우승 상금에 대한 상수 정보 또한 제거할 수 있었습니다.
좋은 피드백 감사합니다 ! 😊 👍

2022-10-31 16:35 UTC, devyonghee approved these changes
안녕하세요 민재님!
전체적으로 피드백을 적극적으로 수용해주시고 바로 반영해주셔서 정말 감사합니다 🙇‍♂️🙇‍♂️
이외에도 코드도 전체적으로 개선해주신 것 같아요 👍👍👍

추가적으로 참고해보시면 좋을 것 같은 부분 코멘트 남겨드렸는데
확인 한번만 부탁드리겠습니다. 🙏🙇‍♂️

이번 미션은 여기서 마무리 하고 머지하도록 하겠습니다!
피드백 반영해주시느라 진심으로 고생 많으셨고
다음 로또 2등 미션도 파이팅입니다 💪

2022-10-31 16:35 UTC, devyonghee commented on src/main/java/lotto/LottoBag.java
> +    }
메소드 명이 `hasSize` 인데 동작이 사이즈를 계산하고 있어서 어색한 것 같아요 😅

주석에 대해 답변을 드리자면 
내부의 집합 크기를 계산하는 역할을 일급 컬렉션에서 수행해주는 방향은 괜찮은 역할이라고 생각합니다.

다만 이 메소드가 생겨난 이유는 생성자에 실행 코드가 존재하는 것이 원인이라고 생각되는데요. 
이러한 역할을 별도의 객체로 분리한다면 테스트가 더 수월해지지 않을까 생각됩니다 
제가 참고했던 내용 링크 남겨드리겠습니다!! [생성자에 코드를 넣지 마세요](https://jackjeong.tistory.com/149)

2022-10-31 16:35 UTC, devyonghee commented on src/main/java/lotto/LottoNumberGenerator.java
> +    private static final int MAX_LOTTO_NUMBER_INDEX = 6;
공통된 값을 관리하는 부분에 있어서 응집도가 떨어져서 관리가 어려워질 것 같아요.
상수를 내부에 감추는 것이 좋긴하지만 필요하다면 적절한 수준으로 열어줘도 괜찮을 것 같아요!
현재 패키지 내부에서만 사용하게 되므로 접근제어자를 default 로 열어주는 건 어떻게 생각하시나요??

2022-10-31 16:35 UTC, devyonghee commented on src/main/java/lotto/LottoNumberValidator.java
> +    }
이 메소드가 현재 사용되는 곳이 한 곳 밖에 없는데 `public` 으로 노출 된 것 같아요
코드의 응집도를 위해 해당 객체로 검증을 옮기는 방향은 어떻게 생각하시나요??

2022-10-31 16:35 UTC, devyonghee commented on src/main/java/lotto/Money.java
> +    }
피드백을 수용해주시고 
불변객체 사용을 위해 새롭게 정의해주셔서 감사합니다 🙇‍♂️🙇‍♂️🙇‍♂️

2022-10-31 16:35 UTC, devyonghee commented on src/main/java/lotto/LottoStore.java
> +    }
model 과 view 가 연관되어 있는 것 같은데 
이 클래스는 mvc 패턴에서 컨트롤러의 역할이 더 어울릴 것 같은데 패키지를 옮기는 건 어떻게 생각하시나요??

2022-10-31 16:36 UTC, merged

2022-11-01 01:14 UTC, meeingjae commented on src/main/java/lotto/LottoBag.java
> +    }
피드백 내용 확인하여 ```hsaSize``` 메서드명 수정하였습니다.
말씀주신 대로 ```has```로 시작하는 메서드는 boolean 타입의 결과물이 올 것이라고 예측이 가능해서 오해의 소지가 있어 보이네요 
추가로 일급 컬렉션의 생성자에서 내부 변수 초기화에 대한 실행 코드가 포함되어 있는 구조를 개선하였습니다
현재 ```LottoBag``` 생성자에서 ```Lotto``` 목록을 생성하는 책임을 갖고 있었는데요
다시 곰곰히 고민해보니 로또를 생성하는 책임은 ```LottoIssuer``` 에 있고, ```LottoBag``` 은 생성 된 로또들을 보관하고 추첨 시 내부 로또의 결과물을 취합해서 제공하는 역할만을 하는 것이 바람직하지 않나 생각이 들었습니다
따라서 ```LottoBag```의 생성자에서 money를 검증 및 Lotto 생성하는 로직을 
```LottoIssuer``` 클래스의 ```issue()``` 메서드에서 수행하도록 리펙토링 진행하였습니다
```hasSize()``` 메서드에 대한 고민 때문에 주석을 달았는데
추가적인 피드백을 받아 너무 좋네요 😊
세심한 피드백 감사합니다 !! 👍👍

2022-11-01 01:26 UTC, meeingjae commented on src/main/java/lotto/LottoNumberGenerator.java
> +    private static final int MAX_LOTTO_NUMBER_INDEX = 6;
패키지 내에서 동일한 의미를 갖고 있는 상수들이 중복으로 선언되어 있던 구조 확인하였습니다 !
의미하는 바가 같고, 같은 도메인 내에서 사용되는 개념은 굳이 중복으로 선언하지 않고
말씀하신 대로 적절한 수준으로 열어주는 유연성을 가져가는 것도 괜찮아 보입니다
피드백 적극 수용하여 접근 제어자 수정 및 중복 코드 제거하였습니다
피드백 감사합니다 ! 😊

2022-11-01 01:41 UTC, meeingjae commented on src/main/java/lotto/LottoNumberValidator.java
> +    }
동의합니다 !
```LottoNumberBag``` 클래스 내부 데이터 만을 검증하는 역할을 수행한다면
```LottoNumberBag``` 클래스 내부에 외부로부터 감춰진 유효성 검증을 수행하는 것이 응집도를 높히는 구조라고 생각합니다
피드백 수용하여 반영하였습니다
감사합니다 ! 😊

2022-11-01 01:50 UTC, meeingjae commented on src/main/java/lotto/LottoStore.java
> +    }
동의합니다
mvc 패턴에 비추어보면 ```LottoStore```는 
모델을 다루고, View에 뿌려주는 중간 다리 역할을 하는 컨트롤러 역할이 맞는 것 같아요
피드백 수정하여 controller 패키지로 분리하였습니다 !
mvc 패턴 관점에서의 세심한 피드백 감사합니다 ! 😊👍