[OptimistLabyrinth] 🚀 3단계 - 로또(자동)
next-step/java-lotto-pro pull request #802
Opened 2022-10-29 20:41 UTC by OptimistLabyrinth

Controller, Model, View 로 분리해서
각각의 역할에 맞게 실행하도록 최대한 맞춰서 구현해봤습니다.

구현하는 내내 테스트 코드를 되도록 거의 동시에 작성하면서 작업하려고 노력했어요.
결과적으로 Model 쪽에 단위 테스트를 상당히 충실하게 작성할 수 있게 되었고
작업을 진행하는 중간 중간에 리팩터링이 필요한 경우에도
코드 변경하는게 굉장히 편하다고 느낄만큼 테스트 코드를 작성하는 것의 장점을 많이 느끼는 시간이었어요 🙂😄

시간 되실때 피드백 부탁드리겠습니다 ㅎㅎ

2022-10-30 02:37 UTC, seokhongkim requested changes
기성님, 3단계 미션 잘 구현해주셨습니다. 👍 
역할을 분리하기 위해 노력하신 것 같고, 단위 테스트도 꼼꼼하게 작성해주셨네요!

조금 더 고민해보시면 도움이 될 것 같은 내용을 코멘트로 남겼습니다.
코멘트 확인 부탁드립니다. 🙏

2022-10-30 02:37 UTC, seokhongkim commented on docs/LOTTO.md
> +# 🚀 3단계 - 로또(자동)
요구사항 잘 정리해주셨습니다. 👍

2022-10-30 02:37 UTC, seokhongkim commented on docs/LOTTO.md
> +- 번호 일치 개수 멸로 로또 장 수를 계산해서 최종적으로 수익률을 0 ~ 1 사이의 실수로 나타난다.
수익률은 1을 넘어갈 수 있을 것 같아요!

2022-10-30 02:37 UTC, seokhongkim commented on src/main/java/lotto/controller/LottoController.java
> +        // * 사용자가 구입 금액을 입력한다.
주석 관련해서 클린 코드의 주석 부분을 읽어보시면 도움이 될 것 같습니다. :)

2022-10-30 02:37 UTC, seokhongkim commented on src/main/java/lotto/controller/LottoController.java
> +    public void run() {
메소드가 20라인을 넘어가네요.
프로그래밍 요구사항을 지켜보시면 좋겠습니다.
> 함수(또는 메소드)의 길이가 15라인을 넘어가지 않도록 구현한다.

2022-10-30 02:37 UTC, seokhongkim commented on src/main/java/lotto/controller/LottoController.java
> +        DemandMoneyToBuyInputPrinter.print();
컨트롤러가 금액을 입력받기 위해서 `DemandMoneyToBuyInputPrinter` 를 이용해 입력을 요청하고, `MoneyToBuyAcceptor` 를 이용해 값을 가져와야 한다는 것을 알아야 하네요.

컨트롤러에게 중요한 건 `구매 금액을 입력받는다` 일 것이고, `구매 금액 입력을 위한 문구를 출력하는 것` 은 `MoneyToBuyAcceptor` 의 관심사여야 하지 않을까요? :)

2022-10-30 02:37 UTC, seokhongkim commented on src/main/java/lotto/model/money/to/buy/MoneyToBuy.java
> +public class MoneyToBuy {
구입 금액을 값 객체로 관리하신 점 좋습니다. 👍 
로또는 1000원 단위로만 구매가 가능하니, 1000원으로 나누어 떨어지지 않는다면 예외가 발생해야 할 것 같아요!
현재 로직상으로는 1500원을 입력했을 때 1000원어치만 구매가 되는데, 수익률은 1500원을 기준으로 계산이 될 것 같습니다.

2022-10-30 02:37 UTC, seokhongkim commented on src/test/java/lotto/model/money/to/buy/MoneyToBuyTest.java
> +        public boolean isMoneySameWith(int money) {
이 메소드에 대한 테스트는 `MoneyToBuy` 에 대한 테스트가 아닌 것 같아요.
테스트를 위한 클래스를 만든 후, 새로 만든 클래스에 대한 테스트만 작성했다면, 이는 프로덕션 코드에 대한 테스트가 아니니 삭제해도 괜찮을 것 같습니다. :)

2022-10-30 02:37 UTC, seokhongkim commented on src/main/java/lotto/model/lotto/ticket/LottoTicketsBucket.java
> +    public LottoTicketsBucket(List<LottoTicket> lottoTickets) {
일부 생성자는 테스트를 위해서 추가된 생성자로 보이네요.
테스트를 위해 프로덕션 코드가 변경되어야 한다면, 이는 프로덕션 코드가 테스트에 의존하고 있는 것일수도 있습니다.
테스트만을 위한 코드를 제거하고, 프로덕션 코드를 기준으로 테스트를 해보시면 좋을 것 같아요!

2022-10-30 02:37 UTC, seokhongkim commented on src/main/java/lotto/controller/LottoController.java
> +            final LottoNumberGenerator lottoNumberGenerator = new LottoNumberGenerator(candidates);
매번 새로운 값을 저장하는 새로운 객체를 만들고, `Random` 위치에 있는 특정 값을 꺼내서 반환하는 형태이다보니 객체 생성이 많이 발생할 수 있겠네요.
로또에서 생성할 수 있는 번호 목록을 만들어 놓고, `Collections.shuffle` 을 이용해서 섞은 후 앞에서 N개의 번호만 반환하면 임의의 수를 매번 반환해줄 수 있을 것 같아요!
미션에 있는 힌트를 참고해보시면 좋겠습니다. :)

> https://edu.nextstep.camp/s/urD8knTu/ls/DDyZo2rO
로또 자동 생성은 Collections.shuffle() 메소드 활용한다.

2022-10-30 02:37 UTC, seokhongkim commented on src/main/java/lotto/view/LottoTicketPrinter.java
> +        System.out.println(lottoTicket);
발급한 로또 번호를 출력할 때 정렬해서 출력해야 하는데, 이에 대한 로직은 어디에 있을까요?

2022-10-30 02:37 UTC, seokhongkim commented on src/main/java/lotto/constant/numbers/LottoConstant.java
> +public class LottoConstant {
상수 클래스가 유용한 경우도 있지만 주의해서 사용이 필요하다고 생각합니다.
1. 로또 번호의 최솟값과 최댓값, 로또 번호의 개수 등은 도메인의 규칙인데, `LottoConstant` 에서 관리되면 도메인이 스스로 알고 있어야 하고 관리해야 할 정책을 찾기 위해 한 단계를 더 찾아야 합니다. 이는 도메인의 규칙을 찾기 어렵게 만들고, 코드 수정도 어렵게 만드는 경향이 있습니다.
2. 공통 상수로 관리하는 경우 자칫 같은 값을 가진 다른 목적의 상수가 하나로 정의되는 경우가 생길 수 있습니다.
3. 여러 상수가 정의되었을 때 맥락에 따라 구분을 해야 한 눈에 들어오는데, 구분이 어려운 경우가 생기면 상수가 정의된 코드가 한 눈에 안 들어오기도 합니다.
4. 상수 클래스는 값을 `public` 으로 선언하게 되는데, 이는 특정 객체가 가지고 있어야 할 책임을 다른 곳에서도 쉽게 접근하게 만듭니다. 예를 들어, 로또는 6개의 번호로 구성되어야 한다는 것은 도메인 규칙이고 다른 곳에서는 임의로 접근하지 않아야 합니다. 하지만 다른 곳에서도 6이라는 값이 필요할 때 쉽게 접근할 수 있고, 이는 도메인 규칙이 외부에서 쉽게 사용되게 만들며 강한 결합을 발생시킬 수 있습니다.

2022-10-30 02:37 UTC, seokhongkim commented on src/main/java/lotto/constant/utils/StringUtils.java
> +public class StringUtils {
유틸리티 클래스 만들어서 사용하시는 것 좋습니다. 👍

2022-10-30 02:37 UTC, seokhongkim commented on src/main/java/lotto/model/lotto/ticket/LottoNumberGenerator.java
> + * 1 이상 45 이하의 번호 중에서 무작위 번호를 하나 선택하는 객체이다.
구현만 봤을 때 1 이상 45 이하라는 것은 보장되지 않는 것 같아요.

2022-10-30 02:37 UTC, seokhongkim commented on src/main/java/lotto/model/lotto/ticket/LottoTicket.java
> +    protected final List<Integer> numbers;
로또 번호를 관리하기 위한 객체를 구현해보시면 좋겠습니다.
1에서 45 사이의 값만 가지고 있어야 하는데, `Integer` 를 사용하면 이에 대한 보장이 어려울 것 같아요.

2022-10-30 02:37 UTC, seokhongkim commented on src/main/java/lotto/model/lotto/ticket/LottoTicket.java
> +    public LottoTicket(List<Integer> numbers) {
로또는 6개의 숫자로 구성되어 있어야 하고 중복이 없어야 하는데, 이에 대한 밸리데이션을 추가해보는 건 어떨까요?

2022-10-30 02:37 UTC, seokhongkim commented on src/main/java/lotto/model/lotto/ticket/LottoTicket.java
> +            final int generatedRandomNumber = lottoNumberGenerator.generate();
`LottoNumberGenerator` 가 `generate` 를 요청할 때마다 중복 없이 값을 반환해준다는 사실을 알고 있고, `COUNT_OF_NUMBERS_IN_SINGLE_LOTTO_TICKET` 횟수만큼 호출해도 안전하다는 사실도 알고 있어야 하네요.
`LottoTicket` 이 `LottoNumberGenerator` 의 구현을 자세히 알고 사용하는 것은 아닐까요?

2022-10-30 02:37 UTC, seokhongkim commented on src/main/java/lotto/model/lotto/ticket/LottoTicketsBucket.java
> +    public int sameThreeNumbersCount() {
로또가 확장되어 번호가 20개 일치하는 케이스까지 늘어난다면 구현이 어떻게 될까요? :)
비슷한 코드가 반복되면 호출하는 과정에서 실수할 수 있고, 변경이 어려워집니다.
`List` 또는 `Array` 가 아닌 `등수와 개수` 의 관계를 쉽게 관리할 수 있는 자료 구조를 사용해보셔도 좋겠습니다.

hint: `Map`

2022-10-30 02:37 UTC, seokhongkim commented on src/main/java/lotto/model/winning/numbers/WinningNumberEach.java
> +        try {
예외로 발생시키는 일부 규칙이 `로또에 사용되는 숫자` 가 지켜야 할 규칙으로 보이네요!

2022-10-30 02:37 UTC, seokhongkim commented on src/main/java/lotto/model/winning/numbers/WinningNumbers.java
> +    public WinningNumbers(String input) {
문자를 입력 받아서 숫자로 컨버팅하는 것은 입력에서 관리해야 할 로직은 아닐까요?
컨트롤러에 남긴 코멘트처럼 로또라는 코드를 그대로 남기고 콘솔에서 웹 환경으로 변경할 때, 어느 코드를 변경해야 하는지 한번 고민해보셔도 도움이 될 것 같습니다.

2022-10-30 02:37 UTC, seokhongkim commented on src/main/java/lotto/view/LottoWinningStatisticsPrinter.java
> +    private static final String THREE_DIGITS_MATCH_MESSAGE = "3개 일치 (5000원)- ";
등수를 관리하는 객체를 활용해보면 어떨까요?
1등은 6개의 번호가 일치해야 하고, 20억의 상금을 가지고 있네요.

hint: `enum`

2022-10-30 02:37 UTC, seokhongkim commented on src/test/java/lotto/model/lotto/ticket/LottoTicketTest.java
> +class LottoTicketTest {
단위 코드 테스트를 꼼꼼하게 작성해주셨네요! 👍

2022-10-30 02:37 UTC, seokhongkim commented on src/main/java/lotto/view/BlankLinePrinter.java
> +public class BlankLinePrinter {
하나하나의 출력을 각 클래스로 분리하셨네요. 이렇게 하니 각 클래스가 무엇을 출력하는지 잘 들어오는 장점이 있네요.

현재 구조와 관련하여 두 가지 생각이 들었습니다.
1. 컨트롤러가 모든 구현체를 알아야 하네요. 한 클래스에 여러 메소드를 넣고 무엇을 출력하는지를 메소드의 이름으로 구분할지, 클래스의 이름으로 구분할지에 대한 선택인 것 같습니다. 구현을 직접 하지 않은 개발자 입장에서 사용할 때, 클래스 하나에 메소드가 있으면 자동완성이 용이하지만 N개의 클래스가 있다면 무엇이 있는지 직접 찾아야 할 것 같기도 합니다.
2. 출력하는 내용이 너무 구체적인 단위로 나뉘어 있어서, 컨트롤러가 결국 출력을 하는 순서에 맞춰 메소드를 다 호출해줘야 하는 것으로 보입니다. 예를 들어, 구매한 로또 결과를 출력할 때 컨트롤러는 "구매 결과를 출력해줘"가 관심사일테고, 출력은 "N장을 구매했고 각 내용을 보여줘"가 관심사가 될 수 있을텐데, 현재는 컨트롤러가 출력 내용에 대해서도 모두 알아야 하는 것으로 보이네요. 결과를 출력하는 것도 모두 컨트롤러가 자세히 알아야 하는 것 같습니다.

2022-10-30 02:51 UTC, OptimistLabyrinth commented on src/main/java/lotto/constant/numbers/LottoConstant.java
> +public class LottoConstant {
그렇군요. 상수를 static 으로 선언하는게 가장 큰 문제일까요??

2022-10-30 02:53 UTC, OptimistLabyrinth commented on src/main/java/lotto/constant/numbers/LottoConstant.java
> +public class LottoConstant {
상수를 static 으로 선언하는 것도 문제가 될까요??

2022-10-30 02:54 UTC, OptimistLabyrinth commented on src/main/java/lotto/controller/LottoController.java
> +        // * 사용자가 구입 금액을 입력한다.
주석을 되도록 사용하지 말라는 의미시죠??

2022-10-30 02:54 UTC, OptimistLabyrinth commented on src/main/java/lotto/controller/LottoController.java
> +    public void run() {
예

2022-10-30 02:56 UTC, OptimistLabyrinth commented on src/main/java/lotto/controller/LottoController.java
> +        DemandMoneyToBuyInputPrinter.print();
서로 관계가 많은 기능은 서로 묶어서 호출하도록 고쳐볼께요

2022-10-30 02:58 UTC, OptimistLabyrinth commented on src/main/java/lotto/controller/LottoController.java
> +            final LottoNumberGenerator lottoNumberGenerator = new LottoNumberGenerator(candidates);
좋은 아이디어네요 ㅎㅎ 그렇게 수정해볼께요

2022-10-30 03:00 UTC, OptimistLabyrinth commented on src/main/java/lotto/model/lotto/ticket/LottoNumberGenerator.java
> + * 1 이상 45 이하의 번호 중에서 무작위 번호를 하나 선택하는 객체이다.
이거는 주석이 개발자를 헷갈리게 한 부분이라고 봐야겠군요.
LottoNumberGenerator 클래스, LottoTicket 클래스, LottoTicketsBucket 클래스를 구현하다보니
테스트 코드 작성이나 이런 부분까지 생각하다보니
LottoNumberGenerator 에서 사용하는 "번호 생성 후보군" 을 외부에서 주입받는게 더 낫다고 판단하게 되었어요.

private final List<Integer> lottoNumberCandidates
멤버 변수 자체도 LottoNumberGenerator 객체가 스스로 생성해서 갖고 있는게 나을까요???

2022-10-30 03:02 UTC, OptimistLabyrinth commented on src/main/java/lotto/model/lotto/ticket/LottoTicket.java
> +    protected final List<Integer> numbers;
아이디어 제안 고맙습니다.
그런 객체를 만들면 WinningNumbers 쪽에서도 동시에 사용할 수 있을 것 같네요 😄👍👍

2022-10-30 03:03 UTC, OptimistLabyrinth commented on src/main/java/lotto/model/lotto/ticket/LottoTicket.java
> +            final int generatedRandomNumber = lottoNumberGenerator.generate();
저도 그 부분이 마음에 걸리긴 하는데
테스트 작성이 편해지려면 계속 잘게 분리하는게 편한 것 같아서 이런 모양이 되어버렸어요.

2022-10-30 03:03 UTC, OptimistLabyrinth commented on src/main/java/lotto/model/lotto/ticket/LottoTicket.java
> +            final int generatedRandomNumber = lottoNumberGenerator.generate();
혹시 어떻게 수정하면 좋을지
생각나는 간단하게 방법을 간단하게 소개해주실 수 있나요??

2022-10-30 03:06 UTC, OptimistLabyrinth commented on src/main/java/lotto/model/lotto/ticket/LottoTicketsBucket.java
> +    public LottoTicketsBucket(List<LottoTicket> lottoTickets) {
저도 처음에는 그렇게 하려고 했는데
제가 테스트 하려는 객체의 상태에 딱 맞게 만들기 위해서 실행하는
BeforeEach 로직에 해당하는 setup 이 너무 복잡해져서 테스트 코드 작성이 너무 힘겹더라구요.

객체를 제가 테스트하려고 하는 상태로 좀 더 빠르게 만들기 위해서
생성자를 추가로 구현해서 사용했어요.

이런 경우에도 불구하고 석홍님은 정말로 프로덕션에서 사용하는 코드만 사용해서 테스트하는게 더 낫다고 생각하시나요??

2022-10-30 03:07 UTC, OptimistLabyrinth commented on src/main/java/lotto/model/lotto/ticket/LottoTicketsBucket.java
> +    public int sameThreeNumbersCount() {
아 ㅋㅋㅋㅋㅋㅋㅋ 그렇네요. 제안 내용대로 수정해볼께요

2022-10-30 03:09 UTC, OptimistLabyrinth commented on src/main/java/lotto/model/money/to/buy/MoneyToBuy.java
> +public class MoneyToBuy {
구현하면서 저도 그 생각을 했었습니다.
대신에 저는 거스름돈을 버리면 된다고 생각해서 현재 파일의 26 라인처럼 구현했습니다.

딱 나누어 떨어지지 않을 때 예외 발생하도록 수정할까요, 아니면 제가 한 방식을 유지해도 괜찮을까요??

2022-10-30 03:11 UTC, OptimistLabyrinth commented on src/main/java/lotto/model/winning/numbers/WinningNumbers.java
> +    public WinningNumbers(String input) {
문자를 입력받아서 숫자로 바꾸는 것은
Model 이 아니고 Controller 에서 해야하는 역할이라고 생각하시는 것 같습니다.

제가 석홍님의 생각을 제대로 이해한게 맞나요???

2022-10-30 03:14 UTC, OptimistLabyrinth commented on src/main/java/lotto/view/LottoWinningStatisticsPrinter.java
> +    private static final String THREE_DIGITS_MATCH_MESSAGE = "3개 일치 (5000원)- ";
이 부분을 한번 고민해볼께요

2022-10-30 03:18 UTC, OptimistLabyrinth commented on src/test/java/lotto/model/money/to/buy/MoneyToBuyTest.java
> +        public boolean isMoneySameWith(int money) {
이 부분에 대해서는 제가 어떤식으로 생각했는지 간단하게 말씀을 드려보겠습니다.

테스트 코드에서 MoneyToBuy 클래스를 상속해서  MoneyToBuyForTest 클래스를 만든 이유는
MoneyToBuy 클래스에 프로덕션에서 사용하지 않는 메서드를 추가하지 않고
MoneyToBuy 클래스의 멤버 변수가 원하는 상태에 있는지 테스트 하고 싶었어요.
그래서 원래 
private int money 였던걸 
protected int money 로 바꿨습니다.
그리고 나서 테스트 할때 MoneyToBuyForTest 클래스의 isMoneySameWith 메서드를 통해서 테스트 하면
MoneyToBuy 클래스의 money 변수의 유효성을 검증하게 된다고 생각했어요.

테스트 코드 작성 시에 이런식으로 하는 경우는 잘 없나요??
또는 이런 방식은 오류를 불러올 수 있는 생각일까요??

2022-10-30 03:20 UTC, OptimistLabyrinth reviewed
매번 정성스럽게 리뷰해주셔서 감사해요 👍👍
달아주신 코멘트에 대해서 추가로 궁금한 부분 답변 달았어요.

읽어보시고 답변 주시면 감사하겠습니다.

2022-10-30 03:22 UTC, OptimistLabyrinth commented on src/main/java/lotto/view/BlankLinePrinter.java
> +public class BlankLinePrinter {
메시지 출력하는 로직을 사용자 입력을 받는 객체로 이동하라는 말씀이시죠??

2022-10-30 03:30 UTC, OptimistLabyrinth commented on src/main/java/lotto/view/BlankLinePrinter.java
> +public class BlankLinePrinter {
아아 
이 컨트롤러 로직도 테스트 코드 작성하기 쉽도록 잘 분리하고 싶은데
어떻게 해야할지 잘 모르겠네요.
내부적으로 사용하는 모든 의존성을 외부에서 주입받도록 구현해야 하는걸까요

리뷰어님은 어떻게 하실 것 같으신가요??

2022-10-30 03:33 UTC, OptimistLabyrinth commented on src/main/java/lotto/view/LottoTicketPrinter.java
> +        System.out.println(lottoTicket);
요구사항을 제가 착각한 것 같아요 😆
정렬하는 로직도 추가할께요

2022-10-30 10:37 UTC, OptimistLabyrinth commented on src/test/java/lotto/model/money/to/buy/MoneyToBuyTest.java
> +        public boolean isMoneySameWith(int money) {
다시 보니까 이 부분은 MoneyToBuy 클래스 생성자 맨 마지막 줄(26번 라인)을 테스트하려고 만든 테스트 케이스 였네요.
생성자 테스트를 위한 테스트 스윗(test suite) 안에 있었으면
저의 의도를 명확하게 드러낼 수 있었을 것 같다는 생각이 듭니다.

이 부분은 삭제할까요, 아니면 MoneyToBuy 생성자에 대한 Nested 테스트 스윗으로 옮길까요??

2022-10-30 12:26 UTC, OptimistLabyrinth commented on src/main/java/lotto/view/BlankLinePrinter.java
> +public class BlankLinePrinter {
유지보수의 측면에서 
별도 클래스로 구분하는 것보다
하나의 클래스 내에 여러 개의 메서드로 구분하는 게

더 좋은 것 같다는 말씀이신가요??

2022-10-30 12:26 UTC, OptimistLabyrinth reviewed
코멘트 추가했습니다 ㅎㅎ

2022-10-30 12:30 UTC, OptimistLabyrinth commented
다 지우고 다시 처음부터 시작할까요??

2022-10-30 14:52 UTC, seokhongkim commented
> 프로젝트를 괜찮은 구조로 구성하는게 쉽지가 않네요.
다 지우고 다시 처음부터 시작할까요??

제가 이번에 피드백을 많이 남겨서 기성님께서 당황스러우셨을 것 같기도 하고, 좋은 구조에 대해 고민이 되셨을 것 같기도 합니다.
저는 처음부터 다시 시작하시는 것보다 현재 구조를 조금씩 바꿔보는 경험을 하시는 것도 도움이 될 것 같아요. 이유는 아래와 같습니다.
1. 먼저, 제가 드린 리뷰 요청 내용이 정답은 아닙니다. 그리고 기성님께서 처음에 이렇게 개발하신 이유가 있을 것이라고 생각합니다. 제 리뷰에 맞춰 기성님의 코드를 고치는 것이 아니라, 제가 말씀드린 내용 중 일부는 수용하실수도 있을 것 같고, 기성님이 생각하시기에 적절하지 않다면 기성님의 생각을 말씀해주셔도 좋겠습니다.
2. 제 경험으로는 개발하는 과정에서 코드를 처음부터 만드는 일보다, 이미 만들어진 코드를 요구사항에 맞춰 변경하고 리팩토링하는 일이 더 많은 것 같습니다. 그래서, 이번 미션에서도 제 리뷰에 맞춰 처음부터 만드시거나, 새로운 요구사항에 맞춰 처음부터 개발하시는 것보다는 현재 만드신 코드를 리팩토링하면서 적정한 지점을 찾아가는 것이 기성님의 학습과 성장에 더 도움이 될 것이라고 생각합니다.

2022-10-30 14:53 UTC, seokhongkim commented on src/main/java/lotto/controller/LottoController.java
> +        // * 사용자가 구입 금액을 입력한다.
이 내용은 주석을 일부 정리했으면 하는 맥락에서 말씀드린 것이 맞습니다.

한편으로 책을 통해 어떤 주석을 남기고, 어떤 주석을 남기지 않는 것이 좋을지에 대해 고민해보셨으면 좋겠다는 의미도 있었습니다. :)

2022-10-30 14:55 UTC, seokhongkim commented on src/main/java/lotto/model/money/to/buy/MoneyToBuy.java
> +public class MoneyToBuy {
저는 도메인의 규칙 상 1000원 단위로만 돈을 입금받을 수 있을 것이라고 생각하여 나누어 떨어지지 않으면 예외가 발생하는 것이 좋다고 생각합니다.
코멘트에 말씀드린 것처럼 수익률도 정확히 계산하려면 추가 로직이 들어가야해서 복잡도가 올라갈 것 같고, 설명이 필요한 코드가 될 것 같습니다.

2022-10-30 15:20 UTC, seokhongkim requested changes
기성님, 코멘트 남겨주신 부분에 대해 답변 남겼습니다. :)
확인 부탁드립니다.

2022-10-30 15:20 UTC, seokhongkim commented on src/test/java/lotto/model/money/to/buy/MoneyToBuyTest.java
> +        public boolean isMoneySameWith(int money) {
1000원 미만 단위의 금액을 버림 처리하고, 금액이 잘 계산되는지 검증하기 위한 테스트가 필요하군요.
이 부분은 저는 금액을 1000원 단위로 입력하지 않으면 예외가 발생되게 하고, 예외를 검증하는 것이 더 좋다고 생각합니다.

현재 로직을 유지한다면 필요한 테스트 코드라고 생각합니다.
테스트를 위해 프로덕션 코드를 변경하는 것은 좋지 않다고 생각하지만, 이 경우에는 getter 를 사용한 검증이 낫다고 생각합니다.
테스트를 위해서만 추가된 클래스의 로직은 프로덕션 코드의 로직과 달라질 수 있기에(예를 들어, isMoneySameWith 의 로직에 문제가 있을 수 있겠죠), 테스트를 위해 추가된 클래스의 로직을 통해 검증하는 것은 지양하는게 좋다고 생각합니다.

2022-10-30 15:20 UTC, seokhongkim commented on src/main/java/lotto/model/lotto/ticket/LottoTicketsBucket.java
> +    public LottoTicketsBucket(List<LottoTicket> lottoTickets) {
테스트 코드 작성이 어렵다면, 이를 프로덕션 코드의 설계를 고민해봐야하는 신호로 생각해보셔도 좋겠습니다. :)
설계를 변경하기가 어렵거나, 비용이 너무 크다면 불가피하게 프로덕션 코드에 테스트에 필요한 일부 코드를 추가할 수 있겠습니다. 그럼에도 저는 기본적으로 프로덕션 코드를 테스트를 위해 변경하는 것은 지양해야 한다고 생각합니다.

2022-10-30 15:20 UTC, seokhongkim commented on src/main/java/lotto/constant/numbers/LottoConstant.java
> +public class LottoConstant {
상수를 static 으로 관리하시는 것은 좋습니다. 👍

2022-10-30 15:20 UTC, seokhongkim commented on src/main/java/lotto/model/lotto/ticket/LottoNumberGenerator.java
> + * 1 이상 45 이하의 번호 중에서 무작위 번호를 하나 선택하는 객체이다.
`LottoNumberGenerator` 는 정해진 범위의 `LottoNumber` 중에서만 난수를 반환(혹은 6개의 번호를 반환할 수도 있겠네요.)해야 할 것 같아요.
이를 외부에서 주입할 수 있도록 하는 것은 `LottoNumberGenerator` 가 지켜야 할 규칙을 어렵게 만드는 것은 아닐까요?
`외부에서 주입된 목록에서 랜덤한 값을 1개씩 꺼내주는 클래스`라면, `LottoNumberGenerator` 가 아닌 `RandomNumberPicker` 와 같은 네이밍이 되어야 하지 않을까요? :)

2022-10-30 15:20 UTC, seokhongkim commented on src/main/java/lotto/model/lotto/ticket/LottoTicket.java
> +            final int generatedRandomNumber = lottoNumberGenerator.generate();
현재 `LottoTicket` 이 `LottoNumberGenerator` 에 의존하고 있는데, 이 의존 방향을 반대로 구현해보셔도 좋겠습니다.
`LottoNumberGenerator` 대신 `AutoLottoGenerator`, `AutoLottoIssuer` 와 같은 클래스를 만든다고 상상해보면, 해당 클래스는 `자동으로 6개의 번호를 추출하여 Lotto를 생성`하는 역할을 할 수 있을 것 같습니다. :)

2022-10-30 15:20 UTC, seokhongkim commented on src/main/java/lotto/model/winning/numbers/WinningNumbers.java
> +    public WinningNumbers(String input) {
저는 Controller 또는 InputView(Acceptor 로 구현하신 클래스) 에서 해야 할 역할이라고 생각합니다.
이를 통해 도메인의 재사용성이 증대되고, UI에 대한 의존성도 제거할 수 있을 것 같습니다. `WinningNumber` 는 `WinningNumber` 가 알아야 하는 주요 로직에 집중하면 좋겠습니다.

2022-10-30 15:20 UTC, seokhongkim commented on src/main/java/lotto/view/BlankLinePrinter.java
> +public class BlankLinePrinter {
> 이 컨트롤러 로직도 테스트 코드 작성하기 쉽도록 잘 분리하고 싶은데
어떻게 해야할지 잘 모르겠네요.
내부적으로 사용하는 모든 의존성을 외부에서 주입받도록 구현해야 하는걸까요
석홍님은 어떻게 하실 것 같으신가요??

컨트롤러가 의존하는 클래스가 많을수록 외부에서 주입받기 어려울 것 같습니다.
컨트롤러가 입력값을 읽어오는 객체, 결과를 출력하는 객체만 외부에서 받아오면 어떨까요? 그럼 컨트롤러 테스트를 위해 사용자가 입력하는 값은 입력값을 읽어오는 객체의 행동을 변경해서 테스트할 수 있을 것 같습니다. 예를 들어, 사용자의 금액 입력을 요청하면 5000이라는 값을 반환하도록 객체의 행위를 조작할 수 있겠죠.
출력에 대한 검증도 출력하는 객체의 메소드를 조작해서 검증이 가능할 것 같습니다.
도메인의 로직은 입력에 따라 정상적으로 실행될 것이고, 출력 메소드를 통해 값의 검증이 가능할 것 같습니다.
이 내용은 어려우시면 처음에는 컨트롤러에 대한 테스트는 작성하지 말고, 인풋과 아웃풋 처리를 위한 클래스만 하나로 변경해서 구현해보셔도 좋겠습니다.
그리고 static method를 많이 사용할수록 강한 결합이 되고 주입이 어려워져 테스트 작성이 어렵습니다. 컨트롤러를 아래 구조로 생성하는 것으로 시작해보시면 도움이 될 것 같습니다.
```java
public class LottoController {
    private final InputView inputView;
    private final OuputView outputView;

    public LottoController(InputView inputView, OuputView outputView) {
        this.inputView = inputView;
        this.outputView = outputView;
    }
}
```

> 유지보수, 가독성 증대 측면에서
별도 클래스로 구분하는 것보다
하나의 클래스 내에 여러 개의 메서드로 구분하는 게
더 좋은 것 같다는 말씀이신가요??

네, 저는 지금은 그렇게 생각합니다.
기성님께서 다르게 생각하실 수 있고, 그 방향이 더 좋을 수 있기에 고민해보시고 함께 이야기 나눠봐도 좋겠습니다. :)

2022-11-01 00:17 UTC, OptimistLabyrinth commented on src/main/java/lotto/model/money/to/buy/MoneyToBuy.java
> +public class MoneyToBuy {
생각해보니까 그렇네요. 그게 더 좋은거 같아요.

2022-11-01 00:18 UTC, OptimistLabyrinth commented on src/main/java/lotto/model/winning/numbers/WinningNumbers.java
> +    public WinningNumbers(String input) {
무슨 의미인지 알 것 같네요. 수정해볼께요 😄👍👍

2022-11-01 00:19 UTC, OptimistLabyrinth commented on src/main/java/lotto/view/BlankLinePrinter.java
> +public class BlankLinePrinter {
오 이거 괜찮은데요??? ㅋㅋㅋㅋ 왜 이걸 진작 생각하지 못했을까요
수정해볼께요

2022-11-01 00:20 UTC, OptimistLabyrinth reviewed
어제는 제가 늦게까지 처리해야하는 일이 있어서 답변이 늦었습니다.
피드백 주신 부분 중점으로 해서 수정해볼께요

2022-11-02 13:34 UTC, OptimistLabyrinth commented
@seokhongkim 

쉽지 않군요 ㅎㅎ
피드백 코멘트 하나씩 보면서 최대한 수정해보려고 했습니다

2022-11-03 08:03 UTC, seokhongkim requested changes
기성님, 3단계 미션 피드백 잘 반영해주셨습니다. 👍 

3단계 미션에서 조금 더 고민해보시면 좋을 것 같은 부분이 있어 코멘트 추가로 남겼습니다.
코멘트 확인 부탁드립니다. 🙏

2022-11-03 08:03 UTC, seokhongkim commented on src/main/java/lotto/MainApplication.java
> +        final int[][] prizes = new int[][]{{3, 5000}, {4, 50000}, {5, 150000}, {6, 2000000000}};
일치하는 개수와 상금은 로또의 규칙이므로 도메인에서 enum 을 활용해서 관리해보셔도 좋겠습니다. :)

2022-11-03 08:03 UTC, seokhongkim commented on src/main/java/lotto/controller/LottoController.java
> +        while (moneyToBuy.canBuyMoreLotto()) {
`MoneyToBuy` 를 이용해서 로또를 몇 장이나 구매했는지 관리하셨군요.
클래스가 하는 역할이 늘어나고, 이름으로 설명하기 어려운 역할인 것 같아요.
1. 로또를 구매할 돈을 관리한다.
2. 구매한 로또의 수량을 관리한다.

돈으로부터 몇 장이나 구매할 수 있는지는 `MoneyToBuy` 가 알려주는 것이 괜찮다고 생각하지만, 실제로 몇 장이나 구매했는지가 `MoneyToBuy` 의 관심사인지는 고민해보시면 좋겠습니다. :)
로직상 `LottoTicketsBucket` 도 몇 장을 구매했는지 알고 있을 것 같네요!

2022-11-03 08:03 UTC, seokhongkim commented on src/main/java/lotto/controller/LottoController.java
> +    private void numberOfAffordableLottoLeft(LottoTicketsBucket lottoTicketsBucket) {
로또를 구매하는 행위를 하는데, 메소드 명은 이를 잘 설명해주지 못하는 것 같아요.
`로또를 구매한다`는 행위를 설명해보면 어떨까요?

2022-11-03 08:03 UTC, seokhongkim commented on src/main/java/lotto/controller/LottoController.java
> +    private void numberOfAffordableLottoLeft(LottoTicketsBucket lottoTicketsBucket) {
`LottoTicketsBucket` 의 역할이 구매한 로또를 담고 있는 것이라면, `로또를 구매한다` 또는 `로또를 발급한다` 는 메소드를 통해 발급한 `Lotto`를 반환 받아서 메소드 외부에서 결과를 출력하고, `LottoTicketsBucket` 에 담는 것이 더 이해하기 쉬울 것 같네요.

2022-11-03 08:03 UTC, seokhongkim commented on src/main/java/lotto/controller/LottoController.java
> +        final Map<Integer, Integer> prizeMoney = new HashMap<>();
`MainApplication` 에 남긴 코멘트처럼 prize 는 enum 으로 관리해보시는 게 좋겠습니다.
또한 `calculateNumbersMatchCount` 에게 `Map` 을 이용해서 요청을 보내는데, `Map` 구조는 key 와 value 를 알아야 하므로 저장하는 값에 대해 자세히 알아야 하고, 특히나 key 와 value 가 같은 타입인 경우 더 어려울 수 있습니다. :)

2022-11-03 08:03 UTC, seokhongkim commented on src/main/java/lotto/controller/LottoController.java
> +    private LottoResult displayLottoStatistics(LottoTicketsBucket lottoTicketsBucket, WinningNumbers winningNumbers) {
메소드의 이름은 `display` 하는 것인데, 실제로는 `LottoResult` 를 계산하는 행위와 결과를 출력하는 행위를 모두 하고 있네요.
메소드를 나눠보셔도 좋겠습니다.

2022-11-03 08:03 UTC, seokhongkim commented on src/main/java/lotto/controller/LottoController.java
> +        final Map<Integer, Integer> countsOfNumbersMatch = lottoTicketsBucket.calculateNumbersMatchCount(prizeMoney,
`calculateNumbersMatchCount` 는 구현을 설명하는 이름으로 보입니다.
로또와 우승 번호를 비교하며 `당첨 여부를 확인`하는 것이 해당 메소드의 기능 아닐까요? :)

2022-11-03 08:03 UTC, seokhongkim commented on src/main/java/lotto/model/lotto/ticket/LottoNumber.java
> +            throw new NumberFormatException("개별 당첨 번호는 1 이상 45 이하의 숫자 중에 하나여야 합니다.");
메소드 전체적으로 `NumberFormatException` 보다는 `IllegalArgumentException` 이 `로또 번호`의 입장에서 `인자가 잘못되었음`을 더 잘 설명해줄 수 있는 예외 같습니다.

2022-11-03 08:03 UTC, seokhongkim commented on src/main/java/lotto/model/lotto/ticket/LottoNumber.java
> +    private boolean lessThanOneOrGreaterThanFortyFive(int tokenValue) {
메소드의 구현을 설명하는 이름보다 행위를 설명해주는 이름이 좋습니다.
예를 들어, 숫자의 범위가 1-50으로 늘어나면 이 메소드는 `lessThanOneOrGreaterThanFifty` 로 이름을 함께 변경해줘야 합니다.
반면, `유효한 로또 숫자인가` 혹은 `숫자가 유효한지 검증한다` 와 같이 `isValidLottoNumber`, `validateLottoNumber (예외 던지는 로직을 이동하는 경우)` 이름을 지으면 범위가 달라져도 행위가 변하지 않으므로 메소드명은 그대로 사용할 수 있습니다.

2022-11-03 08:03 UTC, seokhongkim commented on src/main/java/lotto/model/lotto/ticket/LottoNumberGenerator.java
> +    private static final int LOTTO_MINIMUM_NUMBER = 1;
1-45 사이라는 값을 `LottoNumber` 에서도 관리하고, `LottoNumberGenerator` 에서도 관리하게 되는데 `LottoNumberGeneartor` 가 `Integer` 리스트를 이용하여 숫자를 먼저 정한 후 `LottoNumber` 로 컨버팅하기 때문에 필요한 값으로 보입니다.

`LottoNumber` 가 생성될 수 있는 객체(1-45 사이의 값)를 미리 목록으로 가지고 있다면, `LottoNumberGenerator` 는 그 목록을 요청해서 랜덤하게 6개의 값만 꺼내주면 될 것 같아요.
예시 코드를 보면 아래와 같습니다.
```java
public class LottoNumber
  // 중략
  private static final List<LottoNumber> LOTTO_NUMBERS;

  static {
    LOTTO_NUMBERS = Collections.unmodifiableList(
      IntStream.rangeClosed(LOTTO_MIN_VALUE, LOTTO_MAX_VALUE)
        .mapToObj(LottoNumber::new)
        .collect(Collectors.toList())
    );
  }

  public LottoNumber(int lottoNumber) {
    validateLottoNumber(lottoNumber);
    LOTTO_NUMBERS.get(lottoNumber - 1);  // 리스트는 0번부터 시작하므로 1을 빼줌. 맵으로 관리하거나, 0번을 리스트에 추가하면 더 이해하기 쉽게 구현 가능.
  }

  public static List<LottoNumber> selectableLottoNumbers() {
    return new ArrayList<>(LOTTO_NUMBERS);
  }
}

public class LottoNumberGenerator {
  public List<LottoNumber> generate() {
    List<LottoNumber> selectableLottoNumbers = LottoNumber.selectableLottoNumbers();
    Collections.shuffle(selectableLottoNumbers);
    return selectableLottoNumbers.subList(0, NUMBER_COUNT_IN_SINGLE_LOTTO_TICKET);
  }
}
```

2022-11-03 08:03 UTC, seokhongkim commented on src/main/java/lotto/model/lotto/ticket/LottoNumberGenerator.java
> +        Collections.sort(numbers);
정렬을 하는 것이 언제 필요한지 고민해보셔도 좋겠습니다. :)
`Lotto` 에게 필요한 규칙이라면, `Lotto` 생성자 내부에서 하는 것이 좋아 보입니다. 외부에서 어떻게 값을 전달할지 보장할 수 없기 때문입니다.
출력 할 때 필요한 규칙이라면 출력하는 곳에서만 정렬해서 보여주는 것도 방법일 것 같습니다.

2022-11-03 08:03 UTC, seokhongkim commented on src/main/java/lotto/model/lotto/ticket/LottoTicket.java
> +    public LottoTicket(LottoNumberGenerator lottoNumberGenerator) {
`LottoTicket` 이 `LottoNumberGenerator` 를 전달 받아서 값을 생성해야 할 이유가 있을까요?
`LottoNumberGenerator` 가 `List<LottoNumber>` 를 생성한 후, 이 값을 `LottoTicket` 의 생성자에게 전달해서 객체를 만드는 방법은 어떨까요?

2022-11-03 08:03 UTC, seokhongkim commented on src/main/java/lotto/model/lotto/ticket/LottoTicket.java
> +    private int incrementCountIfLottoNumberMatch(int count, LottoNumber winningNumber) {
`count + 1` 값을 반환하기 위해 `count` 인자를 전달 받아야 하네요.
메소드가 값이 있는 경우 1을 반환해주고, `numberMatch` 에서 `count +=` 의 형태로 호출해주면 `count` 인자를 제거할 수 있을 것 같아요!

2022-11-05 13:54 UTC, OptimistLabyrinth commented on src/main/java/lotto/model/lotto/ticket/LottoNumberGenerator.java
> +    private static final int LOTTO_MINIMUM_NUMBER = 1;
```java
class A {
    static {
    }
}
```

처럼 클래스 내부에 static 할 수 있는건 처음 알았네요

2022-11-05 14:11 UTC, OptimistLabyrinth commented on src/main/java/lotto/controller/LottoController.java
> +    private LottoResult displayLottoStatistics(LottoTicketsBucket lottoTicketsBucket, WinningNumbers winningNumbers) {
수정 완료했습니다.

여기 외에 다른 곳도 필요한 부분을 찾아서 메서드 분리했습니다.

2022-11-05 14:11 UTC, OptimistLabyrinth commented on src/main/java/lotto/model/lotto/ticket/LottoNumber.java
> +            throw new NumberFormatException("개별 당첨 번호는 1 이상 45 이하의 숫자 중에 하나여야 합니다.");
수정 완료했습니다.

2022-11-05 14:11 UTC, OptimistLabyrinth commented on src/main/java/lotto/model/lotto/ticket/LottoNumber.java
> +    private boolean lessThanOneOrGreaterThanFortyFive(int tokenValue) {
수정 완료했습니다.

2022-11-05 14:11 UTC, OptimistLabyrinth commented on src/main/java/lotto/model/lotto/ticket/LottoNumberGenerator.java
> +    private static final int LOTTO_MINIMUM_NUMBER = 1;
수정 완료했습니다.

2022-11-05 14:11 UTC, OptimistLabyrinth commented on src/main/java/lotto/model/lotto/ticket/LottoTicket.java
> +    public LottoTicket(LottoNumberGenerator lottoNumberGenerator) {
수정 완료했습니다.

2022-11-05 14:11 UTC, OptimistLabyrinth commented on src/main/java/lotto/model/lotto/ticket/LottoTicket.java
> +    private int incrementCountIfLottoNumberMatch(int count, LottoNumber winningNumber) {
수정 완료했습니다.

2022-11-05 14:28 UTC, OptimistLabyrinth commented on src/main/java/lotto/model/lotto/ticket/LottoNumberGenerator.java
> +        Collections.sort(numbers);
수정 완료했습니다.

2022-11-06 06:42 UTC, seokhongkim approved these changes
기성님, 3단계 미션 코멘트 잘 반영해주셨습니다. 💯 
3단계 PR은 이만 머지하도록 하겠습니다.

코멘트 조금 남겼는데, 4단계 미션 진행하실 때 여유가 되시면 함께 고민해보셔도 좋겠습니다.
4단계 미션에서 뵙겠습니다. 😀

2022-11-06 06:42 UTC, seokhongkim commented on src/main/java/lotto/model/money/to/buy/MoneyToBuy.java
> +        int moneyRemainderDiscarded = inputMoney / PRICE_OF_SINGLE_LOTTO_TICKET * PRICE_OF_SINGLE_LOTTO_TICKET;
로또 가격으로 나눈 금액의 나머지가 0원인지 검증하는 것으로 써볼 수도 있겠네요! :)
```suggestion
        return (inputMoney % PRICE_OF_SINGLE_LOTTO_TICKET) == 0;
```

2022-11-06 06:42 UTC, seokhongkim commented on src/main/java/lotto/view/NumberOfLottoTicketsPrinters.java
> +//        System.out.println(moneyToBuy.affordableLottoTicketNumber() + NUMBER_OF_AFFORDABLE_LOTTO_TICKETS_MESSAGE);
사용하지 않는 코드는 주석으로 변경하지 말고 삭제하시는 게 좋습니다.
* 과거의 코드가 필요한 경우 git 이력을 통해 다시 찾을 수 있습니다.
* 주석 처리된 코드인 경우 의도적으로 처리한 것인지, 실수로 처리한 것인지 헷갈리는 때가 있기도 합니다. 또한 실수로 주석 처리를 푸는 경우도 발생합니다.

2022-11-06 06:42 UTC, seokhongkim commented on src/main/java/lotto/model/lotto/enums/LottoNumberMatchCount.java
> +    FIVE(4),
FIVE는 5개고, SIX는 6개의 값을 가질 것 같아요!

2022-11-06 06:42 UTC, seokhongkim commented on src/main/java/lotto/MainApplication.java
> +        prizeMoney.put(LottoNumberMatchCount.THREE, 5000);
로또 번호의 매치 카운트와 금액을 포함해서 enum 에서 관리해보시면 좋을 것 같습니다. :)
로또 게임을 해보시면 1등인 경우 6개의 번호가 일치하고, 20억의 상금(상금은 유동적이지만 미션의 제한 사항으로 20억으로 설정)을 가지고 있는 것을 알 수 있습니다.

따라서, enum 에서 등수를 관리한다면 아래와 같은 코드로 관리해보실 수 있을 것 같아요.
이렇게 하면 로또의 등수(도메인) 규칙을 한 클래스에서 관리하고, 이와 관련된 값을 하나의 클래스에서 관리할 수 있습니다.
각 등수에 대한 규칙(매치되어야 하는 개수, 상금)을 enum 내부에서 관리하므로 응집도가 올라간다고 볼 수 있습니다.
```java
public enum LottoRank {
    FIRST(6, 2_000_000_000)
    ;

    private final int matchCount;
    private final int prizeMoney;
}
```

다음 단계 미션을 진행하실 때 여유가 되신다면 위 코드를 참고하시어 `LottoNumberMatchCount` 부분을 리팩토링해보셔도 좋겠습니다.

2022-11-06 06:42 UTC, merged

2022-11-07 13:40 UTC, OptimistLabyrinth commented on src/main/java/lotto/model/money/to/buy/MoneyToBuy.java
> +        int moneyRemainderDiscarded = inputMoney / PRICE_OF_SINGLE_LOTTO_TICKET * PRICE_OF_SINGLE_LOTTO_TICKET;
수정 완료했습니다.

2022-11-07 13:40 UTC, OptimistLabyrinth commented on src/main/java/lotto/view/NumberOfLottoTicketsPrinters.java
> +//        System.out.println(moneyToBuy.affordableLottoTicketNumber() + NUMBER_OF_AFFORDABLE_LOTTO_TICKETS_MESSAGE);
수정 완료했습니다.

2022-11-07 13:40 UTC, OptimistLabyrinth commented on src/main/java/lotto/model/lotto/enums/LottoNumberMatchCount.java
> +    FIVE(4),
수정 완료했습니다.

2022-11-07 14:28 UTC, OptimistLabyrinth commented on src/main/java/lotto/MainApplication.java
> +        prizeMoney.put(LottoNumberMatchCount.THREE, 5000);
수정 완료했습니다.