4단계 - 로또(2등)
next-step/java-lotto-pro pull request #858
Opened 2022-11-01 04:23 UTC by victor-jo

4단계 - 로또(2등) 리뷰 요청드립니다!

2022-11-01 15:19 UTC, joojimin requested changes
안녕하세요~ 원준님!
소소한 코멘트 하나 드렸는데 
확인해보시고 리뷰재요청 부탁드립니다!

2022-11-01 15:19 UTC, joojimin commented on docs/README_LOTTO.md
>    - 랜덤하게 생성하는 전략
요구사항 업데이트 좋습니다! 💯

2022-11-01 15:19 UTC, joojimin commented on src/main/java/lotto/Lotto.java
> +            throw new IllegalArgumentException(LOTTO_SIZE_ERROR);
피드백 반영 💯

2022-11-01 15:19 UTC, joojimin commented on src/main/java/lotto/LottoApp.java
> +        if (winLotto.contains(bonusLottoNumber)) {
해당 로직이 보너스 번호 검증 로직인 것 같은데요! 어플리케이션의 동작을 담당하고있는 LottoApp의 run 메서드에서 노출이 되는게 관심사가 조금 달라보이는 것 같아요! 어떻게 개선할 수 있을까요?

2022-11-02 00:58 UTC, victor-jo commented
피드백 감사드립니다!
보너스 로또번호 자체를 포장하여 메시지를 전달받을 수 있도록 하여
예외처리는 생성자에서 처리하고
매칭여부는 match 메시지로 처리하도록 수정하였습니다

2022-11-02 10:44 UTC, joojimin approved these changes
미션진행 고생많으셨습니다!!
다음미션도 화이팅입니다!!

2022-11-02 10:44 UTC, merged