3단계 로또(자동) 리뷰 요청
next-step/java-lotto-pro pull request #861
Opened 2022-11-01 09:49 UTC by cylee9409

안녕하세요. 이채영입니다.

3단계 로또(자동) 리뷰요청 드립니다.

뒤늦게 코로나에 걸리는 바람에 앓느라 지난 번 리뷰 요청 이후로 오랜 텀을 두고 요청드리게 되어서 죄송합니다.
환절기인데 태경님께서도 건강 유의하시길 바랄게요.🥲

지난 번 장문으로 객체 설계 기준에 대해서 공유해주셔서 감사합니다. 👍
실습하는 것 이상으로 리뷰해주시는 내용을 토대로 고민하면서 개발에 임하는 것만으로도 크게 배우고 성장할 수 있다는 느낌이 듭니다.

이번 3단계에서는 실습하는 과정에서 아래의 궁금증이 떠오르더라구요.
# getter/setter 에 대해서는 가급적 지양하며 개발해야 한다고 알고 있지만 ResultView 같은 UI 쪽에서 결과를 출력하거나 혹은 테스트 코드를 위해서는 불가피하게 사용해야 하는 경우가 있는 것으로 보입니다.
이런 목적으로는 getter/setter를 사용함에 문제가 없을까요?

추가로 제가 놓친 부분이나 더 좋은 설계에 대한 의견이 있다면 편하게 남겨주시면 리팩토링 바로 진행하겠습니다.

감사합니다. 🙏😄

2022-11-02 04:44 UTC, ohtaeg requested changes
안녕하세요 채영님!
리뷰가 늦어서 죄송합니다 🙇 🙇 
컨디션이 안좋으셨군요 ㅠㅠ 조금이나마 괜찮아지신 것 같아 다행입니다 :)
일보다 건강이 중요하기에 무리없이 진행하셨면하는 바램입니다 😊 

다음 미션을 진행하기전에 같이 고민해보면 좋을 포인트가 존재하여 Request changes 하였습니다!
확인 후 반영하여 재요청주시면 감사하겠습니다 :)
다시 한번 늦어서 죄송하며, 환절기 감기 조심하시길 바라겠습니다 🙏

2022-11-02 04:44 UTC, ohtaeg commented on src/main/java/calculator/StringAddCalculator.java
> +        Numbers numbers = new Numbers(input);
피드백 반영 👍

2022-11-02 04:44 UTC, ohtaeg commented on src/main/java/calculator/domain/Numbers.java
> +    private final Pattern pattern = Pattern.compile(CUSTOM_DELIMITER_PATTERN);
이 부분은 같이 고민해보면 좋을 것 같아요 :)
인스턴스화 될 때 마다 Pattern을 새로 생성해주도록 해주신 의도가 있으신지요?
개인적으로는 static 키워드까지 붙인다면 런타임시 최초 한번만 메모리에 적재하도록 하여 
Numbers라는 타입을 가진 객체의 모든 인스턴스가 공유하도록 해도 되지 않을까? 라는 생각을 가지고 있었어요!

2022-11-02 04:44 UTC, ohtaeg commented on src/main/java/lotto/domain/Lottos.java
> +        if (payment.getPayment() < UNIT_PRICE_PER_LOTTO) {
구입 금액에 대한 validaton은 Payment 스스로가 해줘도 괜찮지 않을까 합니다!
getter를 통해 정보를 안가져와도 되는 장점도 있을 것 같은데 채영님은 어떻게 생각하시나요 :) ?

2022-11-02 04:44 UTC, ohtaeg commented on src/main/java/lotto/domain/Lottos.java
> +        int rotate = payment.getPayment() / UNIT_PRICE_PER_LOTTO;
https://github.com/next-step/java-lotto-pro/pull/861#discussion_r1011118162

만약 위 피드백이 반영이 된다면 Payment 라는 객체가 몇개를 구입할 수 있는지도 스스로 계산할 수 있을 것 같아요!
그렇게 된다면 Lottos는 Payment 대신 생성해야되는 갯수만 받아서 그 갯수에 맞게 로또를 생성해주도록 리팩토링 될 것 같아요!

해당 피드백을 반영함으로써 얻는 장점은 의존성이 제거되는 부분과
Payment 자신이 가지고 있는 필드 외부에 노출하지 않고 스스로 처리를 하도록 캡슐화하는 장점이 있을 것 같지만
단점으로는 조금의 리팩토링이 필요해보이기에 이에 대한 채영님의 의견이 궁금하네요 :)

2022-11-02 04:44 UTC, ohtaeg commented on src/main/java/lotto/domain/Lottos.java
> +    }
Collections.unmodifiablelist()를 활용하여 컬렉션을 외부에서 List를 변조(add, remove 등)를 할 수 없도록
read-only로 리턴하면 좋을 것 같아요 :)

2022-11-02 04:44 UTC, ohtaeg commented on src/main/java/lotto/domain/Payment.java
> +public class Payment {
객체 분리를 잘해주셨네요 👍

2022-11-02 04:44 UTC, ohtaeg commented on src/main/java/lotto/domain/Lotto.java
> +        setWinLottoNum(nums);
사소하지만 Lotto 내부에서 생성되는 당첨번호도 결국 로또 번호랑 같기에
메서드 네이밍에 당첨이라는 개념을 명시안해도 괜찮을 것 같아요 😄

2022-11-02 04:44 UTC, ohtaeg commented on src/main/java/lotto/domain/Lotto.java
> +    private String[] validateInput(String input) {
하나의 메서드에서 두가지 일을 수행하고 있는 것 같아요 :)
1. validation(패턴 체크, 길이 체크, 중복 체크)
2. 문자열을 배열로 형변환

validation을 좀 더 세밀하게 나눠도 괜찮을 것 같아요 :)

2022-11-02 04:44 UTC, ohtaeg commented on src/main/java/lotto/domain/Lotto.java
> +    private List<Integer> lotto;
이 부분은 같이 고민해보면 좋을 것 같아요!
로또 번호를 Integer로 관리하는것도 좋지만 int 값 하나 자체는 의미를 부여하기 힘든 스칼라 값일 뿐이라고 생각해요.

가령 메서드에 여러개의 int 타입을 파라미터로 받는 경우가 존재한다고 가정할 때, foo(int a, int b, int c)
파라미터 순서를 잘못해서 입력할 경우 컴파일 시점에서는 문법에 오류없이 해석되지만
런타임 시점에서는 사이드 이펙트가 발생할 요지가 있지 않을까 합니다!

원시값을 포장해서 객체로 다룬다면 아주 사소하더라도 프로그래머에게 그 값이 어떤 값이며,
왜 쓰고 있는지에 대한 정보를 전할 수 있는 장점이 있다고 생각되어지며
객체를 분리함으로써 책임도 전가하여 코드도 간결해지는 장점도 있다고 생각합니다 :)

Lotto에서 하나의 로또 번호라는 객체를 더 분리해서 해볼 수 있을까요 :) ?
만약 해당 피드백을 수용하기 힘드시거나 변경이 많다고 느껴지신다면 안해주셔도 됩니다!

2022-11-02 04:44 UTC, ohtaeg commented on src/main/java/lotto/domain/Statistics.java
> +public class Statistics {
당첨 결과를 통계할 수 있는 객체를 잘 분리해주셨네요 👍

2022-11-02 04:44 UTC, ohtaeg commented on src/main/java/lotto/domain/Winning.java
> +    SIX_MATCHES(6, 2_000_000_000);
당첨등수를 enum으로 잘 표현해주셨어요 💯

2022-11-02 04:44 UTC, ohtaeg commented on src/main/java/lotto/view/ResultView.java
> +
> getter/setter 에 대해서는 가급적 지양하며 개발해야 한다고 알고 있지만 ResultView 같은 UI 쪽에서 결과를 출력하거나 혹은 테스트 코드를 위해서는 불가피하게 사용해야 하는 경우가 있는 것으로 보입니다. 이런 목적으로는 getter/setter를 사용함에 문제가 없을까요?

말씀해주신대로 무분별한 사용을 위한 getter/setter를 지양하면 된다고 생각합니다 :)
언제든지 외부에 공개된 setter를 통해 외부에서 상태값을 변경할 수 있기때문에 
데이터의 무결성을 보장할 수 없고 캡슐화가 깨져 자율적인 객체의 설계가 무너지는 단점이 존재하게 되다보니

setter를 지양하자는 말이 많지만 절대적이라고는 생각하지 않습니다 ㅎㅎ
예로 스프링에서 의존성 주입 방법으로 생성자를 권장하지만 setter 주입도 지원하니까요 :)
말씀해주신 목적에는 getter/setter를 사용하는데 문제가 없다고 생각합니다!

2022-11-02 04:44 UTC, ohtaeg commented on src/test/java/lotto/domain/LottoTest.java
> +public class LottoTest {
꼼꼼하게 테스트를 잘 작성해주셨네요 👍

2022-11-02 04:44 UTC, ohtaeg commented on src/test/java/lotto/domain/LottoTest.java
> +        for (Integer num : lotto.getLotto()) {
개인적으로 if, for 키워드를 사용하는 구문은 로직이라고 생각하는데요!
테스트 코드 내에 if, for 구문이 있다면 해당 구문은 로직이며, 로직을 검증하기 위한 테스트 코드가 별도로 필요하다고 생각해요 :)

개인적으로 반복적인 검증이 필요하다면 for 문이 아닌 반복 테스트나 다이나믹 테스트를 이용하여 검증하는 방법을 지향하는 편입니다. 테스트 코드를 작성하면서 if, for문을 지양하는 것에 대해 채영님은 어떻게 생각하시는지 궁금하네요 :)

<img width="872" alt="image" src="https://user-images.githubusercontent.com/20432323/199399709-989fe342-7b86-4ef6-bde1-22aae38392cd.png">

https://docs.microsoft.com/ko-kr/dotnet/core/testing/unit-testing-best-practices

물론 꼭 수정해주실 필요없는 점 참고 부탁드릴께요 🙏

2022-11-02 04:44 UTC, ohtaeg commented on src/test/java/lotto/domain/WinningTest.java
> +public class WinningTest {
매치 카운트가 3 미만일 경우도 테스트 케이스를 추가해보시면 좋을 것 같습니다 👍

2022-11-02 04:47 UTC, ohtaeg commented
커밋을 세세하게 잘 나눠주셨습니다 👍

2022-11-02 08:05 UTC, cylee9409 commented
안녕하세요. 이채영입니다.
의견 주신 내용 소스에 반영하여 다시 리뷰 요청 드립니다.

확실히 각 객체의 역할을 나눠 클래스를 생성하니 수정사항이 생겼을 경우 수정해야 할 범위가 작아지고 내용이 명확해지는 것을 느낍니다. 👍👍

2022-11-02 08:05 UTC, cylee9409 commented on src/test/java/lotto/domain/WinningTest.java
> +public class WinningTest {
추가 완료했습니다!

2022-11-02 08:06 UTC, cylee9409 commented on src/test/java/lotto/domain/LottoTest.java
> +        for (Integer num : lotto.getLotto()) {
네네! for문이 아닌 lotto.getLotto() 메서드를 set 생성자로 넘기도록 수정하였습니다.

2022-11-02 08:11 UTC, cylee9409 commented on src/main/java/lotto/domain/Lotto.java
> +    private List<Integer> lotto;
LottoNumber 클래스를 추가하였습니다.
해당 클래스를 추가하니 관련 유효성도 그 클래스에서 처리할 수 있어 Lotto 클래스의 역할이나 범위가 더욱 명확해지네요.

추가로 위에 주신 의견은 제 코드를 제 관점만이 아닌 다른 프로그래머의 관점으로도 생각할 줄 알아야겠다는 깨달음 얻게 해주네요. 앞으로도 이 내용은 개발하면서도 되짚어 고민해보겠습니다.
좋은 조언 고맙습니다! 🙇 🙇

2022-11-02 08:12 UTC, cylee9409 commented on src/main/java/lotto/domain/Lottos.java
> +    }
Collections.unmodifiableList() 로 변경했습니다.
정말 좋은 메서드 하나 배워가네요! 감사합니다 ㅎㅎ

2022-11-02 08:16 UTC, cylee9409 commented on src/main/java/lotto/domain/Lottos.java
> +        if (payment.getPayment() < UNIT_PRICE_PER_LOTTO) {
저는 Payment 라는 클래스가 이 로또만이 아니라 전체적인 구입이라는 행위에 대한 금액이라는 넓은 의미로 접근을 해서 1000원에 대한 유효성 체크를 Lottos 클래스로 위임했습니다. 하지만 태경님께서 제안해주신 것처럼 현재 프로젝트 내에서는 로또 구입만이 유효한 행위이므로 말씀하신 내용을 반영하여 수정 완료했습니다~
다만 get 메서드는 지양하고 싶었으나 통계 정보인 Statistics 에 구매금액에 대한 정보가 필요한데 다른 대안이 떠오르지 않아 getPayment() 자체는 남겨두었습니다! 혹시 좋은 방안이 있다면 알려주세요 :)

2022-11-02 15:47 UTC, ohtaeg commented on src/main/java/lotto/domain/Lottos.java
> +        if (payment.getPayment() < UNIT_PRICE_PER_LOTTO) {
좀 더 큰 범위의 Payment로써 Lottos에게 위임했었군요 👍 

> get 메서드는 지양하고 싶었으나 통계 정보인 Statistics 에 구매금액에 대한 정보가 필요한데 다른 대안이 떠오르지 않아 getPayment() 자체는 남겨두었습니다! 혹시 좋은 방안이 있다면 알려주세요 :)

최대한 getter를 지양하다가 필요한 부분에서는 getter를 사용해도 괜찮다고 생각합니다 :D

2022-11-02 16:13 UTC, ohtaeg approved these changes
피드백 반영을 잘해주셨습니다 👍 
몇 개의 피드백을 드렸는데 다음 미션을 진행하시면서 같이 반영해주시면 감사하겠습니다 :)
다음 미션도 화이팅입니다 🔥

2022-11-02 16:13 UTC, ohtaeg commented on src/main/java/lotto/domain/Lotto.java
> +        validateNonDuplicate(nums);
validation 분리 👍

2022-11-02 16:13 UTC, ohtaeg commented on src/main/java/lotto/domain/LottoNumber.java
> +public class LottoNumber {
피드백 반영 💯

2022-11-02 16:13 UTC, ohtaeg commented on src/main/java/lotto/domain/LottoNumber.java
> +public class LottoNumber {
구입한 로또 출력을 보니 정렬이 안되고 있는 것 같아요 :)
<img width="208" alt="image" src="https://user-images.githubusercontent.com/20432323/199538057-bc752048-3741-4d25-bdb6-038830419935.png">

정렬하여 출력해주면 더 좋을 것 같습니다 😄

2022-11-02 16:13 UTC, ohtaeg commented on src/main/java/lotto/domain/Lotto.java
> +        return Collections.unmodifiableList(lotto);
👍 👍

2022-11-02 16:13 UTC, ohtaeg commented on src/main/java/lotto/domain/Lotto.java
> +        Arrays.stream(nums).forEach(num -> lotto.add(new LottoNumber(num)));
이 부분은 같이 고민해보면 좋을 것 같아요 :)
LottoNumber 객체의 생성 책임을 가진 곳들은 현재
- AutoLottoGenerator
- Lotto

이렇게 두군데로 분리가 되어있는데요! 생성 책임을 한 곳으로 옮겨볼 수 있을까요?
여러 군데에서 객체 생성하는 것 보다 최대한 범위를 줄이면 어떤 장점이 있을까요 :) ?

2022-11-02 16:13 UTC, ohtaeg commented on src/main/java/lotto/domain/AutoLottoGenerator.java
> +            lottoNumbers.add(new LottoNumber(i));
혹시 제너레이터가 List\<LottoNumber>를 가지도록 해주신 이유가 한번 생성하고 재사용 목적으로 해주신걸까요 :) ?
그렇다면 잘해주셨어요 👍 
다만 계속 AutoLottoGenerator의 생성자를 호출하면 같은 타입의 다른 인스턴스가 생성되어 계속 List\<LottoNumber>가 생성될 것 같아요! 한번만 생성하고 해당 타입의 모든 인스턴스가 공유할 수 있도록 static 블록을 이용한 초기화는 어떨까 싶은데
채영님은 어떻게 생각하시나요 :) ?

2022-11-02 16:14 UTC, merged

2022-11-03 08:58 UTC, cylee9409 commented on src/main/java/lotto/domain/AutoLottoGenerator.java
> +            lottoNumbers.add(new LottoNumber(i));
네 태경님! 해당 리스트는 재사용하고자 하는 목적으로 만든 것이 맞습니다.
태경님 리뷰를 보고 static을 적용하고 해당 리스트는 하나의 인스턴스만 생성되도록 반영했습니다.
알려주신 static 블록을 이용한 초기화는 경험이 없어서 해당 로또의 번호를 할당하는 static 메서드를 만들고 해당 메서드로 리스트를 초기화 하였는데 혹시 잘못된 방법이면 편하게 말씀해주세요!