Step5 로또[수동] PR 요청 드립니다.
next-step/java-lotto-pro pull request #868
Opened 2022-11-01 14:14 UTC by giraffelim

안녕하세요 민수님! 어느덧 이번 단계에 마지막 리뷰 요청을 드리게 되었네요 마지막 단계도 잘 부탁드립니다.
기존에 LottoNumber 인스턴스 캐싱이 안되어 있어 이번 단계에서 추가로 적용하였습니다!
마지막으로!.. 고민이 되는 부분이 있어 질문을 드립니다.
1. 현재 `LOTTO_PRICE` 라는 상수 `Money` 객체가 `LottoService`, `LottoVendingMachine` 두 곳에 `private`으로 존재하는데, 이 경우에는 `Lotto` 객체에 해당 상수 객체를 `public`으로 열고 다른 곳에서 해당 상수를 참조하는 식으로 작성하는게 나을까요? 

1번과 같이 진행할 경우 `LottoService`, `LottoVendingMachine` 두 곳에서 `Lotto`에 의존하게 되어 우선 중복으로 두 곳에 작성해둔 상태입니다.

벌써 마지막이라니 너무 아쉽네요. 민수님의 정성스럽고 꼼꼼한 피드백 덕분에 빠르게 한 단계 성장할 수 있었던 시간이 되었던 것 같습니다.
정말 정말 감사합니다. 👍 👍 👍

2022-11-02 10:34 UTC, mskangg requested changes
항상 고민을 공유해주셔서 감사합니다~!
고민하신 부분 피드백 드렸어요!
확인 후 반영 부탁드리겠습니다! 🙇‍♂️

2022-11-02 10:34 UTC, mskangg commented on src/main/java/step3/domain/LottoNumber.java
> +    private static final List<LottoNumber> CACHED_NUMBER = IntStream.rangeClosed(START_INCLUSIVE, END_INCLUSIVE)
👍👍👍

2022-11-02 10:34 UTC, mskangg commented on src/main/java/step3/domain/LottoNumber.java
> +    public static LottoNumber of(final int number) {
매개변수가 하나인경우 of 보단 from 을 권장합니다 :)

2022-11-02 10:34 UTC, mskangg commented on src/main/java/step3/domain/LottoVendingMachine.java
>      private final Money LOTTO_PRICE = new Money(1000L);
이른초기화보단 객체 생성시 `Money`를 주입받게 하는 방법은 어떠신가요??
`LottoApplication` 에서 로또구매기계를 생성할 때 로또 가격을 사용자가 넣어서 사용하듯이요!

2022-11-02 10:34 UTC, mskangg commented on src/main/java/step3/service/LottoService.java
> +        Money change = paidByUser.pay(LOTTO_PRICE.multiply(manualLottos.getHasLottoSize()));
> 현재 LOTTO_PRICE 라는 상수 Money 객체가 LottoService, LottoVendingMachine 두 곳에 private으로 존재하는데, 이 경우에는 Lotto 객체에 해당 상수 객체를 public으로 열고 다른 곳에서 해당 상수를 참조하는 식으로 작성하는게 나을까요?

이런 생각이 드는 부분은 `리팩토링`의 힌트가 되기도 합니다!
그래서 고민을 좀 해보니 더 괜찮은 방법이 있어 저의 생각을 전달 드릴게요!

우선 왜 두곳에서 로또의 가격을 알아야할까?
메세지화하여 전달할 순 없을까?

```java
Money change = paidByUser.pay(LOTTO_PRICE.multiply(manualLottos.getHasLottoSize()));
```

보단

```java
Money change = paidByUser.pay(lottoVendingMachine.calculateTotalMoney(manualLottos.getHasLottoSize()));
```

이렇게 변경하면 로또발급기계는 항상 로또가격을 알아야하지만 로또 서비스는 가격을 모름에도 로또구매기계에게 물어봐서 확인이 가능하게 리팩토링 할 수 있을 것 같아요!

2022-11-02 12:21 UTC, giraffelim commented on src/main/java/step3/domain/LottoNumber.java
> +    public static LottoNumber of(final int number) {
@mskangg 
아래 커밋에서 적용했습니다. 👍 
[23d2e4f](https://github.com/next-step/java-lotto-pro/pull/868/commits/23d2e4f63d0d0e8f35d2851e2afade4fad29d810)

2022-11-02 12:22 UTC, giraffelim commented on src/main/java/step3/domain/LottoVendingMachine.java
>      private final Money LOTTO_PRICE = new Money(1000L);
@mskangg 
말씀해주신대로 Money 객체를 외부에서 주입하게 개선함으로써 고정된 로또 금액의 자판기가 아닌 조금 더 유연한 로또 자판기가 된 것 같습니다!
[8df2a04](https://github.com/next-step/java-lotto-pro/pull/868/commits/8df2a04714c4b96f3a022ca49c7169dec469f414)

2022-11-02 12:26 UTC, giraffelim commented on src/main/java/step3/service/LottoService.java
> +        Money change = paidByUser.pay(LOTTO_PRICE.multiply(manualLottos.getHasLottoSize()));
@mskangg 
마지막까지 제 질문에 성심성의껏 답변해주시고 같이 고민해주셔서 정말 감사합니다. 👍 👍 👍 
말씀해주신 것 처럼, 로또 서비스는 가격을 몰라도 로또 자판기에 가격이 얼마인지 묻는 과정을 통해 풀어나갈 수 있었던 부분인데 자판기는 티켓을 구매할수만 있어야 한다고 생각해 미처 생각하지 못했었던 것 같습니다..

고민해주셨던 부분처럼, 자판기에서 구매하고자 하는 갯수만큼 로또를 구매하면 총 가격이 얼마인지 알려주는 기능을 생성하고, 해당 기능에 메시지화하여 전달함으로써 중복도 제거하고 보다 객체가 상호작용하는 방식으로 풀어나가게 된 것 같습니다. 💯 
[57fc40d](https://github.com/next-step/java-lotto-pro/pull/868/commits/57fc40dddaf1c7d1b155dd308eb7675bd876a2f5)

2022-11-03 03:42 UTC, mskangg approved these changes
태양님 모든 미션 성심성의껏 잘해주셔서 감사해요!
피드백도 깔끔하게 잘 적용되었고 굉장히 잘 설계된 코드로 보입니다! 🚀
처음 과정이라 열정이 넘치고 그럴텐데 총 9주 과정동안 이 마음 변치마시고 페이스조절 잘 하셔서 의미있는 과정이 되셨으면 좋겠습니다 🙏🏻

> 벌써 마지막이라니 너무 아쉽네요. 민수님의 정성스럽고 꼼꼼한 피드백 덕분에 빠르게 한 단계 성장할 수 있었던 시간이 되었던 것 같습니다.
정말 정말 감사합니다. 👍 👍 👍

잘봐주셔서 제가 더 감사하고 다음 미션 JPA 강의도 화이팅입니다!

2022-11-03 03:43 UTC, merged