5단계 - 로또(수동) PR 요청 드립니다.
next-step/java-lotto-pro pull request #872
Opened 2022-11-01 15:45 UTC by crongcm

안녕하세요, 태화님

리뷰 받고 구현을 하면서 계속 부족함이 많이 느껴지네요
엘레강트 오브젝트 책 구매하였습니다. 한번 읽어보겠습니다.

많은 리뷰해주시면 더욱 고민해보겠습니다.

구현하다보니 시간이 많이 늦었네요.. 늦은 시간에 PR 요청드려서 죄송합니다.
잘 부탁드리겠습니다. 감사합니다.

2022-11-02 12:42 UTC, wooobo requested changes
5단계 잘진행해주셨네요 :+1: 

몇가지 코멘트 남겨드렸습니다!
확인 후 재요청 부탁드립니다! :pray:

2022-11-02 12:42 UTC, wooobo commented on src/main/java/lotto/domain/Money.java
> +    private static final char NEGATIVE_CHAR = '-';
`BigInteger` 를 활용해볼수도 있겠네요 🤔

2022-11-02 12:42 UTC, wooobo commented on README.md
## 프로그래밍 요구사항
`예외 처리를 통해 에러가 발생하지 않도록 한다.`

----

```
수동으로 구매할 로또 수를 입력해 주세요.
-1

수동으로 구매할 번호를 입력해 주세요.

수동으로 -1장, 자동으로 3장을 구매했습니다.
```

해당 부분 이슈가 있는것 같아요 :thinking:

2022-11-02 12:42 UTC, wooobo commented on src/main/java/lotto/domain/LottoPurchaseAmount.java
>          return this.amount / LOTTO_PRICE;
좀더 객체지향적으로 바라본다면,

`Money money`를 내부 변수로 가진다면,
`money.divide(LOTTO_PRICE);`
`money.greaterThan(0)`


이런 패턴으로 객체에게 메시지를 던져볼수있겠네요!

참고해주세요~

2022-11-02 12:42 UTC, wooobo commented on src/main/java/lotto/domain/Money.java
> +    private static void isDigit(String inputAmount, int i) {
`is_` 로 시작하는 메서드는 일반적으로는 `boolean` 타입을 반환하는 형태로 인식하는데,
내부 구현은 리턴타입이 `void` 이고   예외처리를 하고 있는부분이 다소 어색하다는 생각이 드네요 :thinking:

2022-11-03 08:36 UTC, crongcm commented on src/main/java/lotto/domain/Money.java
> +    private static final char NEGATIVE_CHAR = '-';
넵 힌트 감사합니다 !

2022-11-03 08:36 UTC, crongcm commented on README.md
검증 한다고 했는데 빠뜨렷네요.. 요구사항 정리가 제대로 안된 것 같습니다.. 추가하겠습니다

2022-11-03 14:38 UTC, wooobo approved these changes
5단계 잘 진행해주셨습니다!

에러에 대한 대응도 잘 해주신것 같아요!
```
수동으로 구매할 로또 수를 입력해 주세요.
[ERROR] 음수는 입력 불가능합니다.
지난 주 당첨 번호를 입력해 주세요.
[ERROR] 로또 번호는 6개 입니다.
지난 주 당첨 번호를 입력해 주세요.
[ERROR] 중복 된 숫자가 있습니다.
지난 주 당첨 번호를 입력해 주세요.
[ERROR] 로또 번호는 6개 입니다.
```

`엘레강트 오브젝트` 를 읽고 나면 로또 미션이 또 다르게 보일수 있는데요!
시간 되시면 다시 한번 해보시는것도 재밌을꺼 같아요!

로또미션을 진행하면서 했던 고민들이 추후 미션에 도움이 되기 바라요~!

로또미션 마무리하겠습니다.
화이팅입니다 :smiley:

2022-11-03 14:38 UTC, wooobo commented on src/main/java/lotto/domain/LottoPurchaseAmount.java
> +        if (amount.remainder(LOTTO_PRICE) > 0) {
고민해주셨네요 :clap:

2022-11-03 14:38 UTC, wooobo commented on src/main/java/lotto/domain/Money.java
> +        return this.money % value;
[불변객체](https://galid1.tistory.com/622)

`return new Money(this.money % value);`
참고해주세요~

2022-11-03 14:38 UTC, wooobo commented on src/main/java/lotto/view/InputView.java
> +    public static Optional<LottoLottery> inputManualNumbersInformation(LottoLotteryQuantity lottoLotteryQuantity) {
`Optional` 사용한곳이 몇몇곳에서 보이네요

[Java Optional 바르게 쓰기](https://homoefficio.github.io/2019/10/03/Java-Optional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%93%B0%EA%B8%B0/)

참고해보시면 재밌을것같아요! 추후 미션에 도움될수도 있구요!

2022-11-03 14:38 UTC, merged

2022-11-03 14:40 UTC, crongcm commented on src/main/java/lotto/domain/Money.java
> +        return this.money % value;
넵 참고해보겠습니다! 감사합니다

2022-11-03 14:40 UTC, crongcm commented on src/main/java/lotto/view/InputView.java
> +    public static Optional<LottoLottery> inputManualNumbersInformation(LottoLotteryQuantity lottoLotteryQuantity) {
넵 참고해보겠습니다! 감사합니다