Step4 PR
next-step/java-lotto-pro pull request #873
Opened 2022-11-01 16:36 UTC by hyeongwon-up

2022-11-02 07:27 UTC, geunhwanlee requested changes
4단계 미션 잘해주셨어요!👍🏻

몇가지 아쉬운 점이 있어서 코멘트 남겼어요.

고민해보시고 재요청 주세요!🙏
궁금한 점 있으시면 언제든 질문주세요🙌

그럼 화이팅입니다 🔥

2022-11-02 07:27 UTC, geunhwanlee commented on src/main/java/lotto/model/LottoRank.java
> +  }
```suggestion
  public static LottoRank getLottoRank(int containsCount, boolean isContainBonusNumber) {
    return Arrays.stream(LottoRank.values())
        .filter(lottoRank -> lottoRank.containsCount == containsCount
                && lottoRank.isContainBonusNumber == isContainBonusNumber)
        .findAny()
        .orElse(NOTHING);
  }
```
이렇게 하는건 어떨까요?🤔

2022-11-02 07:27 UTC, geunhwanlee commented on src/main/java/lotto/model/LottoResult.java
> +    );
```suggestion
    LottoRank lottoRank = winningLotto.rank(lotto);
```
winningLotto에 메시지를 던져서 등수를 리턴받는건 어떤가요?🤔

2022-11-02 07:27 UTC, geunhwanlee commented on src/main/java/lotto/model/LottoResult.java
> +      rankStringList.add(generateRankResultByStringFormat(rankEntry));
> `convertResultMapToString` -> `validNothing` -> `generateRankResultByStringFormat` -> `generateSecondRankResultByStringFormat`

와 같이 메소드 호출이 일어나서 코드의 흐름을 파악하기가 어렵네요..😭
어떻게 개선을 해볼수 있을까요?🤔
적절한 stream 함수와 다른 객체로 역할을 위임하는 방식으로 해결해볼수 있을까요?🙏

2022-11-02 07:27 UTC, geunhwanlee commented on src/main/java/lotto/model/WinningLotto.java
> +  public WinningLotto(String winningLottoNumber, String bonusNUmber) {
```suggestion
  public WinningLotto(String winningLottoNumber, String bonusNumber) {
```
소소하지만 오타가 났네요😀

2022-11-02 07:27 UTC, geunhwanlee commented on src/main/java/lotto/model/WinningLotto.java
> +  private final int bonusNumber;
`보너스번호`는 로또를 이루는 여섯개 각각의 `번호`와 특징이 같을것 같아요!
새로운 객체로 분리하면 유효성검사 등의 역할을 위임해줄수 있을것 같은데 어떻게 생각하시나요?🤔

2022-11-02 07:27 UTC, geunhwanlee commented on src/main/java/lotto/model/WinningLotto.java
> +  }
`보너스번호`는 `당첨번호`와 중복되지 않아야할것 같아요!
유효성검사를 해보는건 어떨까요?

2022-11-02 08:25 UTC, hyeongwon-up commented on src/main/java/lotto/model/LottoRank.java
> +  }
훨씬 깔끔해지는 것 같네요. ㅎㅎ 👍 
수정하였습니다.

2022-11-02 08:38 UTC, hyeongwon-up commented on src/main/java/lotto/model/LottoResult.java
> +    );
WinningLotto 필드에서 관리하는게 아니라, 메세지를 던졌을 때 리턴 받도록 하는걸 말씀하시는게 맞으실까요 ??

2022-11-02 09:02 UTC, hyeongwon-up commented on src/main/java/lotto/model/LottoResult.java
> +    );
넵 반영했습니다.
winningLotto에 메시지를 던져서 등수를 리턴을 받도록 수정을 하였습니다.
근데 한편으로는 winningLotto 에게 LottoRank 를 묻는게 맞는지 확신이 안서는데요.
WInningLotto 가 LottoRank 결과까지 반환하는 기능을 가지고 있어도 괜찮은지, 아니면 WinningLotto 는 LottoRank 까지 관여하지 않아야 하는지 조금 헷갈리는데요.
근환님은 어떤 근거로 winningLotto 에게 해당 메세지를 던져 리턴 받으려고 했는지 알려주시면 감사하겠습니다.
제가 객체 지향 적인 사고에 미숙하여서 답변주시면 감사하겠습니다.

2022-11-02 09:04 UTC, hyeongwon-up commented on src/main/java/lotto/model/WinningLotto.java
> +  public WinningLotto(String winningLottoNumber, String bonusNUmber) {
ㅎㅎ 넵 수정하엿씁니다.

2022-11-02 09:39 UTC, hyeongwon-up commented on src/main/java/lotto/model/LottoResult.java
> +      rankStringList.add(generateRankResultByStringFormat(rankEntry));
넵  stream 을 사용하면서 
generateRankResultByStringFormat, generateSecondRankResultByStringFormat 을 사용하던게 굳이 메서드로 분리하는게 더 이해하기 어려운 코드라고 생각되어 하나로 통일 후 분기를 통해 해당 맞는 문자열을 리턴해주도록 수정을 해보았습니다.
아직 파악하기 어려운지 한번 더 확인 부탁드릴게요.ㅎㅎ

2022-11-02 13:02 UTC, hyeongwon-up commented on src/main/java/lotto/model/WinningLotto.java
> +  }
추가하였습니다.

2022-11-02 13:03 UTC, hyeongwon-up commented on src/main/java/lotto/model/WinningLotto.java
> +  private final int bonusNumber;
넵! LottoNumber 라는 객체를 추가하여 하였는데 맨 최소 단위의 모델을 구성하다보니 많이 생각을 해야하네요. 😢

2022-11-03 02:09 UTC, geunhwanlee commented on src/main/java/lotto/model/LottoResult.java
> +    );
`등수`를 반환하는 역할이 `winningLotto` 외부에 있다면
`등수`를 반환하기 위해 `winningLotto`의 구현에 의존적이 될수밖에 없다고 생각합니다. (로또번호와 보너스번호를 gettter를 통해서 얻어와서 계산하는 등)🤔
만약 `winningLotto`가 변경된다면 외부의 등수반환 로직도 변경해아할 가능성이 높죠.

`winningLotto`가 `등수`를 반환한다면 `winningLotto`를 의존하고 있는 클라이언트는 `winningLotto`의 내부 구현에 대한 의존성을 덜게 됩니다.
반면 `winningLotto`가 `LottoRank`에 대한 의존성을 갖게되죠.

저는 `winningLotto`와 `LottoRank`가 관련성이 높은 관계라고 생각했고, 변경의 주기가 같을것이라고 생각해서 위와 같이 코멘트를 드렸어요.😊

객체지향 설계에 정답은 없으니 상황에 따른 선택을 하시는게 중요할것 같아요!👍

2022-11-03 02:10 UTC, geunhwanlee commented on src/main/java/lotto/model/LottoResult.java
> +      rankStringList.add(generateRankResultByStringFormat(rankEntry));
훨씬 파악하기 좋네요! 👍

2022-11-03 02:20 UTC, geunhwanlee approved these changes
요구사항 반영 너무 잘해주셨어요!👍

그럼 이번 단계는 여기서 머지하도록 하겠습니다 👏

그럼 마지막 단계도 화이팅하세요!

2022-11-03 02:20 UTC, geunhwanlee commented on src/main/java/lotto/model/Lotto.java
> +    return Objects.equals(numbers, lotto.numbers);
로또의 equals를 오버라이딩 한 이유가 무엇일까요?🤔
`1,2,3,4,5,6` 로또와
`1,2,3,4,5,6` 로또를 두장 구매했다면
위 두개의 로또는 같은 로또일까요?

2022-11-03 02:20 UTC, merged

2022-11-03 09:29 UTC, hyeongwon-up commented on src/main/java/lotto/model/Lotto.java
> +    return Objects.equals(numbers, lotto.numbers);
아하... 착각했네요..ㅎㅎ 다음단계에서 수정하겠습니다! 👍