Step4 학습 테스트 PR 요청드립니다.
next-step/java-lotto-pro pull request #893
Opened 2022-11-02 17:00 UTC by SanghoonSon

안녕하세요 태화님 😄
Step4 PR 요청드립니다. 

기존 코드는 최대한 수정하지않는 방향으로 구현해보았습니다.
이번 리뷰도 잘부탁드립니다!

2022-11-03 13:27 UTC, wooobo requested changes
4단계 많은 수정없이 잘진해주셨습니다~

예외처리부분이 다소 아쉬워서 재요청 드립니다.

확인 후 재요청 부탁드릴께요 :pray:

2022-11-03 13:27 UTC, wooobo commented on src/main/java/study/step3/domain/lotto/Lotto.java
> +        return 0L;
리턴이 `0`, `1` 두가지만 존재한다면 `boolean`이 더 어울리지 않을까 싶어요.

```
public boolean matchBonusLottoNumber(LottoNumber bonusNumber) {
  return this.lottoNumbers.contains(bonusNumber);
```

2022-11-03 13:27 UTC, wooobo commented on src/main/java/study/step3/domain/lotto/LottoRank.java
> +    private static LottoRank findLottoLank(LottoRank findRank, LottoRank rank, LottoMatchResult matchResult) {
`LottoRank` 의 내부 인스턴스 변수를 사용하고 있지않고 있네요.

`lottoRank.메소드명(LottoRank rank, LottoMatchResult matchResult)`
혹은
`lottoMatchResult.메소드명(LottoRank findRank, LottoRank rank)`

이런 패턴으로도 접근해볼수 있을것 같네요.
관점 정도로 봐주세요~

2022-11-03 13:27 UTC, wooobo commented on README.md
## 프로그래밍 요구사항
예외 처리를 통해 에러가 발생하지 않도록 한다.

---

- 1000원 미만를 입력했을때
- 지난주 로또 번호, 보너스 번호 등을 잘못입력했을때
- 보너스번호를 45초과한 번호를 입력했을때

등등 예외 케이스를 좀 더 고민해주시면 좋을것 같아요 그리고,
`Exception`을 발생시킨 만큼, try catch를 통해 사용자에게 에러 메시지를 보여주는게 맞는것 같아요!

2022-11-04 15:47 UTC, SanghoonSon commented on src/main/java/study/step3/domain/lotto/Lotto.java
> +        return 0L;
생각해보니 <code>boolean</code>이 더 어울리는 것 같습니다 👍

2022-11-04 15:49 UTC, SanghoonSon commented on src/main/java/study/step3/domain/lotto/LottoRank.java
> +    private static LottoRank findLottoLank(LottoRank findRank, LottoRank rank, LottoMatchResult matchResult) {
내부 인스턴스 변수를 어떻게 사용할까 고민하다가 결국 스트림으로 구현하였네요 😅 
```java
public static LottoRank ofMatchResult(LottoMatchResult matchResult) {
        return Arrays.stream(values())
                .filter(rank -> matchResult.isEqualsLottoMatchCount(rank.matchResult))
                .filter(rank -> matchResult.isGreaterThanOrEqualBonusMatchCount(rank.matchResult))
                .findFirst()
                .orElse(LottoRank.NONE);
    }
```

2022-11-04 15:50 UTC, SanghoonSon commented on README.md
마음이 급해서 예외 처리에 대한 부분이 미숙했던 것 같습니다!
생각나는 케이스별로 예외처리하였으니 다시한번 리뷰 부탁드립니다~!

2022-11-05 11:40 UTC, wooobo approved these changes
상훈님 4단계도 수고 많으셨습니다 ^^

몇가지 코멘트 남겨드렸어요 확인 부탁드립니다.

이만 `merge` 진행하겠습니다.
마지막 5단계 진행해보시죠!
화이팅입니다~

2022-11-05 11:40 UTC, wooobo commented on src/main/java/study/step3/domain/lotto/WinningLotto.java
> +        if(winningLotto.isMatchedBonusLottoNumber(bonusNumber)) {
객체에게 메시지 전달 좋네요!

2022-11-05 11:40 UTC, wooobo commented on src/main/java/study/step3/domain/lottonumber/LottoMatchResult.java
> +    private final long bonusMatchCount;
`보너스 매칭`은 매칭 또는 미매칭 경우만 있으므로, `boolean` 으로 해도 좋을것 같네요!
현재는 그러한 조건만 있기때문이에요 :thinking: 

[3. 필요할 일이 없다](https://www.itworld.co.kr/news/106861)
해당 경우와 관련있을수도 있을것 같아서 공유합니다!

저의 관점입니다 :smile:

2022-11-05 11:40 UTC, wooobo commented on src/main/java/study/step3/view/LottoView.java
>          return new LottoNumbers(lottoNumbers);
`return LottoNumbers.of(String[] numbers);`

`LottoNumbers` 다양한 의미로 생성자를 만들수 있는 `정적 팩토리 메소드`를 사용해 볼 수 있겠네요!
이렇게 된다면 `LottoNumber`에 대해 `LottoNumbers` 외부에서는 몰라도 되겠네요!

2022-11-05 11:40 UTC, merged

2022-11-06 13:26 UTC, SanghoonSon commented on src/main/java/study/step3/domain/lottonumber/LottoMatchResult.java
> +    private final long bonusMatchCount;
좋은 내용 공유해주셔서 감사드립니다 👍 
```
3. 필요할 일이 없다
앞으로 필요할 것 같아서가 아니라, 지금 필요한 기능을 구현하라. 앞으로 필요할 것 같다면 십중팔구 필요할 일이 없다. 나중에 정말 필요해지면 그때 가서 넣으면 된다.

모듈을 설계하면서 그 모듈이 이번 릴리스와 앞으로의 릴리스에서 해야 할 모든 작업을 미리 생각하고 반영하려 한다면 앞으로 일어나지 않을지도 모르는 기능까지 지원하는 쓸데없이 복잡한 소프트웨어를 만들게 된다.

미래를 예측하는 것보다 현실을 이해하는 편이 훨씬 더 정확하다. 현재에 집중하라.
```

현재 요구사항에 집중해야되는말 충분히 공감되는 부분입니다!

2022-11-06 13:30 UTC, SanghoonSon commented on src/main/java/study/step3/view/LottoView.java
>          return new LottoNumbers(lottoNumbers);
```정적 팩토리 메소드```로 여러 타입에 대해서 객체를 생성해주니
 외부에서는 ```LottoNumber```에 대해 몰라도 되는군요!

step5에서 해당 내용으로 수정해보았습니다.