step 4 로또(2등) 리뷰 부탁드립니다.
next-step/java-lotto-pro pull request #923
Opened 2022-11-06 04:10 UTC by joonseolee

좀 늦었습니다!! 확인 부탁드립니다!!

2022-11-06 11:52 UTC, limwoobin requested changes
안녕하세요 준서님 4단계 미션 잘 수행해주셨습니다.
고민해보면 좋을만한 내용들이 있어 몇가지 코멘트 드렸습니다.
확인 후 다시 요청해주세요!

2022-11-06 11:52 UTC, limwoobin commented on src/main/java/step3/model/LottoBonus.java
> +public class LottoBonus extends Lotto {
보너스번호에 대해 `LottoBonus` 라는 객체로 만들어주셨군요 ㅎㅎ
이 방법도 좋지만 로또번호 자체를 객체로 나누어보는것은 어떨까요??
그렇게되면 보너스번호에 대해서도 재사용할 수 있을것같습니다.
`Lotto` 객체 내에서도 로또번호객체를 List 형태로 가지고 있는 형태가 되겠네요

2022-11-06 11:52 UTC, limwoobin commented on src/main/java/step3/model/LottoBonus.java
> +    }
lotto가 List로 있는데 Collection의 contains 기능을 사용하면 더 간단해지지 않을까요??

2022-11-06 11:52 UTC, limwoobin commented on src/main/java/step3/model/LottoResult.java
> +    protected int sixMatchedCount;
각 당첨등수를 인스턴스변수로 갖고있는 형태이군요
이 값들은 `LottoScoreType`에서 관리하는건 어떨까요??

2022-11-06 11:52 UTC, limwoobin commented on src/main/java/step3/model/LottoResult.java
> +    }
로또 결과를 만드는 메소드로 보이는데 generate... 라는 이름은 생성한다는 의미가 강한것같은데
결과를 만드는 다른 네이밍은 어떨까요??

2022-11-06 11:52 UTC, limwoobin commented on src/main/java/step3/model/Lottos.java
>      }
stream을 바로 사용하기 위해 선언하신건가요??
사용되는곳을 보니 결과를 만드는 부분에서 호출되는데 Lottos로 메시지를 전달해서
기능을 작성해보는건 어떨까요?

2022-11-06 11:52 UTC, limwoobin commented on src/main/java/step3/service/LottoGenerator.java
> +    }
한 클래스내에 `generate`라는 이름이 오버라이딩되서 여러개가 있네요
같은 이름이 너무많아 정확히 어떤 액션을 하는지 메소드명으로 의도를 파악하기가 어려워보이는데
어떻게 생각하시나요??

2022-11-06 11:52 UTC, limwoobin commented on src/main/java/step3/LottoController.java
>          String luckyNumberText = inputView.readyLuckyLotto();
당첨번호입력인데 메소드명은 `readyLuckyLotto` 이네요
메소드명 한번 확인부탁드립니다~

2022-11-06 11:52 UTC, limwoobin commented on src/main/java/step3/model/LottoBonus.java
> +    }
객체명은 보너스번호를 나타내는 객체로 보여지는데 생성자에 lotto를 같이 받고있네요
명확하게 표현하기 위해서는 저 Lotto를 제거해보는것에 대해 고민해보면 좋을것같아요!

2022-11-06 11:53 UTC, limwoobin commented
추가로 4단계 미션올라오는데 커밋로그는 이전커밋까지 같이 딸려올라왔네요
다음 미션진행시에는 같이 확인부탁드립니다~

2022-11-07 00:34 UTC, joonseolee commented on src/main/java/step3/model/LottoBonus.java
> +    }
@limwoobin 엇! 그러네요 넵 수정해두겠습니다!

2022-11-07 00:34 UTC, joonseolee commented on src/main/java/step3/LottoController.java
>          String luckyNumberText = inputView.readyLuckyLotto();
@limwoobin 의미가 좀 헷갈릴 수 있겠네요!! `readyWinningLotto` 로 변경해두겠습니다!!

2022-11-07 00:34 UTC, joonseolee commented on src/main/java/step3/model/LottoResult.java
> +    }
@limwoobin 넵 다시 보니 생성해주는 의미가 너무 강한것 같네요 `getLottoReultFromLotto` 로 변경해두겠습니다!!

2022-11-07 00:34 UTC, joonseolee commented on src/main/java/step3/service/LottoGenerator.java
> +    }
@limwoobin 넵 동의합니다!! 오버로딩으로만 하니 매개변수로 의미를 파악하는게 좀 힘드네요 뒤에 이름을 더 추가하도록 하겠습니다!!

2022-11-07 00:34 UTC, joonseolee commented on src/main/java/step3/model/Lottos.java
>      }
@limwoobin 넵 이 메서드는 삭제하도록 하겠습니다!!

2022-11-07 00:34 UTC, joonseolee commented on src/main/java/step3/model/LottoBonus.java
> +public class LottoBonus extends Lotto {
@limwoobin `LottoWinningNumber` 클래스로 분리했습니다!! 확인 부탁드립니다!

2022-11-07 00:34 UTC, joonseolee commented on src/main/java/step3/model/LottoBonus.java
> +    }
@limwoobin `LottoWinningNumber` 에 로또 번호와 보너스 번호를 같이 받게끔 해놨습니다! 7b58b81

2022-11-07 00:34 UTC, joonseolee commented on src/main/java/step3/model/LottoResult.java
> +    protected int sixMatchedCount;
@limwoobin 오.. !! 넵 `Map<LottoScoreType, Integer>` 로 변경했습니다 ! 7b58b81

2022-11-07 08:50 UTC, limwoobin requested changes
준서님 4단계 피드백 반영 잘 해주셨습니다.
다만 이대로 머지하기엔 아쉬운 부분들이 있어 request change 드렸습니다.
코멘트를 보고 한번 고민해보시면 정말 좋을것같습니다
제 의도가 이해되지 않거나 같이 의논하고싶은 부분이 잇으면 편히 dm주세요
조금만 더 화이팅입니다 👍 👍 👍

2022-11-07 08:50 UTC, limwoobin commented on src/main/java/step3/model/LottoWinningNumber.java
> +    private int bonusNumber;
당첨번호객체에서 당첨번호와 보너스번호를 같이 가지고있군요 ㅎㅎ
객체의 역할이 명확해진것같아 좋네요

2022-11-07 08:50 UTC, limwoobin commented on src/main/java/step3/service/LottoService.java
>      }
해당 메소드는 사용되지 않는걸로 보여집니다!
메소드 내의 호출되는 로직들도 같이 제거되도 괜찮지않을까요??

2022-11-07 08:50 UTC, limwoobin commented on src/main/java/step3/model/Lotto.java
>      private List<Integer> lotto;
List<Integer> lotto를 `LottoNumber`로 분리하는건 어떨까요?? 
ex) `List<LottoNumberr>`

2022-11-07 08:50 UTC, limwoobin commented on src/main/java/step3/model/LottoResult.java
> +        this();
this로 호출되는 생성자는 외부에선 사용되지 않네요
이런경우라면 private으로 접근제어자를 변경하던, 혹은 생성자를 제거하는 방법을 고려해보심이 좋습니다.
생성자가 많을경우 어떤 단점이 있을지도 고려봐주세여

2022-11-07 08:50 UTC, limwoobin commented on src/main/java/step3/service/LottoGenerator.java
>      }
여기도 호출되는부분이 다른데서 사용되는 부분일까요?

2022-11-07 08:50 UTC, limwoobin commented on src/main/java/step3/model/LottoWinningNumber.java
> +    }
여기도 호출되는부분이 다른데서 사용되는 부분인지 확인부탁드립니다~

2022-11-07 08:50 UTC, limwoobin commented on src/main/java/step3/view/InputView.java
> +    public String readyWinningLotto() {
메소드명 변경 좋습니다 ㅎㅎ

2022-11-07 08:50 UTC, limwoobin commented on src/test/java/step3/model/LottoBonusTest.java
>  class LottoBonusTest {
`LottoWinningNumber`에 대한 도메인테스트인가요??
그렇다면 이름을 해당 도메인 이름의 suffix에 Test로 클래스명을 지정해주는것은 어떨까요??

2022-11-07 08:50 UTC, limwoobin commented on src/test/java/step3/model/LottoBonusTest.java
> -}
`LottoWinningNumber` 객체의 내부에 보면 중복, 6자리 등등 굉장히 많은 예외처리로직이 있는데
그에 비해 테스트코드가 조금 아쉽네요! 
private method이어도 검증해보는것이 어떨까요??

2022-11-07 08:50 UTC, limwoobin commented on src/main/java/step3/model/LottoResult.java
> +    protected Map<LottoScoreType, Integer> winningMap = new EnumMap<>(LottoScoreType.class);
Map 구조를 이용하셨군요 👍 
이전보다 로직이 깔끔해지겠네요 ㅎㅎ

2022-11-07 08:50 UTC, limwoobin commented on src/test/java/step3/model/LottoResultTest.java
>      }
`LottoResult`에는 `getProfitRate` 로 수익률을 가져오는 기능이 있는데
테스트코드에는 빠져있네요 ㅎㅎ

2022-11-07 12:50 UTC, joonseolee commented on src/main/java/step3/service/LottoService.java
>      }
@limwoobin 그러네요!! 삭제하겠습니다!

2022-11-07 12:50 UTC, joonseolee commented on src/test/java/step3/model/LottoBonusTest.java
>  class LottoBonusTest {
@limwoobin 이름 변경하면서 그대로 수정 안 했었네요.. ㅠ 수정해두겠습니다!

2022-11-07 12:50 UTC, joonseolee commented on src/test/java/step3/model/LottoResultTest.java
>      }
@limwoobin 엇? `getProfitRate` 메서드 테스트하는 곳은 `whenGetProfitRate_thenRate ` 에 정의되어 있는데 더 추가할게 있는건가요??

2022-11-07 12:50 UTC, joonseolee commented on src/main/java/step3/service/LottoGenerator.java
>      }
@limwoobin 안녕하세요!! 보너스 번호를 받지 않은 로또인 경우로 남겼던건데요? 보너스 번호를 무조건 받는다고하고 위 코드는 제거해야되는 부분인가요??

2022-11-07 12:50 UTC, joonseolee commented on src/main/java/step3/model/LottoResult.java
> +        this();
@limwoobin 엇 그러네요!! 제거하고 합치도록 하겠습니다 매개변수로만 오버로딩하게 되면 어떻게 만들어지는지 알기가 쉽지가 않아서 팩토리 메서드로 이름 길게 만들었었는데요 이 생성자는 1개밖에 필요가 없을 것 같아서 말씀 주신대로 진행하겠습니다!!

2022-11-07 12:50 UTC, joonseolee commented on src/main/java/step3/model/Lotto.java
>      private List<Integer> lotto;
@limwoobin 오... 넵 분리하면 `LottoWinningNumber` 에도 같은 멤버로 둘 수 있고 검증도 같이 할 수 있어서 더 좋겠네요!! 변경하겠습니다!

2022-11-07 12:50 UTC, joonseolee commented on src/main/java/step3/model/LottoWinningNumber.java
> +    }
@limwoobin 요기도 보너스번호가 포함되지 않은 로또 발행시 사용하는 생성자인데요 삭제해야되는건가요??? ❓

2022-11-07 15:39 UTC, limwoobin commented on src/main/java/step3/service/LottoGenerator.java
>      }
요구사항이 보너스번호를 받는것으로 변경됨에 따라 사용되지 않는다면 제거되는게 어떨까요??
변경된 버전에서는 테스트코드에서만 사용되고있네요 ㅎㅎ 
그렇다면 아에 제거하는것도 방법입니다.
테스트코드가 프로덕션에 영향을 주는것이 될 수 있습니다

2022-11-07 15:41 UTC, limwoobin commented on src/main/java/step3/model/LottoWinningNumber.java
> +    }
보너스번호가 포함되지 않은 로또를 발행하는 경우가 있다면 유지해야겠지만
그렇지 않다면 삭제하는것에 대해 고민해보심이 좋습니다!

2022-11-07 15:41 UTC, limwoobin commented on src/test/java/step3/model/LottoResultTest.java
>      }
이 부분은 제가 놓쳤네요 
잘 작성해주신게 맞습니다! 👍

2022-11-07 15:52 UTC, limwoobin requested changes
준서님 4단계 피드백반영하느라 고생많으셨습니다.
관련해서 추가 피드백을 코멘트로 남겨드렸으니 다시 확인부탁드립니다.

추가적으로 요구사항이 충족되지 않은 부분이 있어 이번엔 request changes 드렸습니다.
코멘트 확인하시고 다시 요청부탁드립니다!

2022-11-07 15:52 UTC, limwoobin commented on src/main/java/step3/model/LottoNumber.java
> +    private final List<Integer> numbers;
이 부분은 제 코멘트를 잘못받아들이신것같아요!
로또번호 하나가 LottoNumber가 되고 Lotto는 List<LottoNumber>를 가지는 구조에 대해 
고민해보시라고 코멘트드린거였습니다!
다시 한번 고민해봐주세요!

2022-11-07 15:52 UTC, limwoobin commented on src/main/java/step3/model/LottoResult.java
> -    }
이 생성자는 LottoResult 내부에서만 호출되고있네요
접근제어자 설정을 변경해보는건 어떨까요?

2022-11-07 15:52 UTC, limwoobin commented on src/test/java/step3/model/LottoNumberTest.java
> +public class LottoNumberTest {
테스트코드엔 public 접근제어자를 제외하는게 어떨까요?

2022-11-07 15:53 UTC, limwoobin commented
<img width="381" alt="스크린샷 2022-11-08 오전 12 51 23" src="https://user-images.githubusercontent.com/28802545/200354734-014e76c1-68fe-4633-b4ea-59ce12db1b5f.png">

출력부분에 대해 다시 확인부탁드립니다 :)

2022-11-08 04:14 UTC, joonseolee commented on src/main/java/step3/model/LottoNumber.java
> +    private final List<Integer> numbers;
@limwoobin 아하 그렇군요!! 제가 잘못 이해했네요 값 1개를 래핑해주는 `LottoNumber` 를 생성해놓고 이 리스트를 가지고 있는 클래스는 `LottoNumbers` 로 따로 정의해도 괜찮을까요?
```java
class LottoNumbers {
  private List<LottoNumber> numbers;
}

class Lotto {
  private LottoNumbers lottoNumbers;
}

class LottoWinningNumbers {
 private LottoNumbers lottoNumbers;
}
```
`Lotto` 클래스와 `LottoWinningNumbers` 클래스의 필드가 `LottoNumbers` 를 받는게 아닌 `List<LottoNumber>` 로 가지게 되면 유효성 검사하는 로직이 중복해서 들어가는 것 같아서요 위와 같이 진행해도 괜찮을까요??

2022-11-08 04:18 UTC, joonseolee commented on src/main/java/step3/model/LottoResult.java
> -    }
@limwoobin 엇! 그러네요 넵 변경해두겠습니다!!

2022-11-08 04:19 UTC, joonseolee commented on src/test/java/step3/model/LottoNumberTest.java
> +public class LottoNumberTest {
@limwoobin 넵 변경해두겠습니다!!

2022-11-08 05:54 UTC, limwoobin commented on src/main/java/step3/model/LottoNumber.java
> +    private final List<Integer> numbers;
LottoWinningNumbers 에서도 당첨번호에 대해 List<LottoNumber> 가 아닌 Lotto를 가지게되면
유효성검사를 Lotto 한군데에서만 할 수 있지 않을까요??

2022-11-08 13:05 UTC, joonseolee commented on src/main/java/step3/model/LottoNumber.java
> +    private final List<Integer> numbers;
@limwoobin 아아.. 그렇군요 그 생각을 못했네요ㅠㅠ 351a00b 수정했습니다!

2022-11-08 13:34 UTC, limwoobin commented
<img width="390" alt="스크린샷 2022-11-08 오후 10 32 52" src="https://user-images.githubusercontent.com/28802545/200578172-9cdf41e5-d6b4-4b7c-ab8b-966e339d8abc.png">
지난번에 드린 피드백인데 반영이 안되어있네요
당첨번호 입력시 바로 예외를 뱉는 방식에 대해 어떻게생각하시나요?

2022-11-08 13:35 UTC, limwoobin approved these changes
준서님 4단계미션 진행하느라 고생많으셨습니다
소소한 코멘트를 남겨드렸으니 다음미션 진행하기전에 한번 확인부탁드릴게요
그럼 마지막 미션도 화이팅입니다!

2022-11-08 13:35 UTC, limwoobin commented on src/main/java/step4/service/LottoService.java
> +    }
당첨번호를 위한 메소드인가요? 그렇다면 네이밍에 대해 한번 고민해보시져 ㅎㅎ

2022-11-08 13:37 UTC, limwoobin commented
추가로 다음미션 진행시에는 커밋로그를 한번 정리해서 올리길 권장드립니다.
이번 step4에서는 기존 step1,2,3 의 커밋도 같이 딸려온것같아서요
추가로 피드백 반영시 모든 변경사항을 하나의 커밋으로 올리는것은 좋지 않습니다.
커밋을 작업단위별로 쪼개서 해보시는걸 추천드립니다.
다른 개발자들이 리뷰할때 어떤부분이 변경되엇는지 파악하기에도 훨씬 수월할 수 있습니다 ㅎㅎ

2022-11-08 13:37 UTC, merged

2022-11-10 10:31 UTC, joonseolee commented on src/main/java/step4/service/LottoService.java
> +    }
@limwoobin 그러게요 이렇게만 보면 매개변수는 당첨 텍스트인데 메서드 이름이 로또 번호 리스트 가져오는거여서 다르네용 수정해두겠습니다!