[OptimistLabyrinth] 🚀 4단계 - 로또(2등)
next-step/java-lotto-pro pull request #933
Opened 2022-11-07 14:29 UTC by OptimistLabyrinth

2022-11-23 14:40 UTC, OptimistLabyrinth commented
3단계 진행한 코드로 무슨짓을 해도 4단계 2등을 구현할 수가 없어서
어쩔 수 없이
새롭게 시작했습니다.

2022-11-24 00:32 UTC, seokhongkim requested changes
기성님, 4단계 미션 진행을 기다리고 있었습니다.
4단계 미션 잘 구현해주셨습니다. 👍 

리팩터링 해보시면 좋을 것 같은 부분이 있어서 코멘트를 남겼습니다.
코멘트 내용 보시고 궁금하신 점이나 어려우신 점 있다면 언제든 편하게 말씀해주세요.
코멘트 확인 부탁드립니다. 🙏

2022-11-24 00:32 UTC, seokhongkim commented on src/main/java/lotto2/controller/LottoController.java
> +    private MoneyToBuy acceptInputMoney() {
입력 받는 부분(`lottoView.printNumberOfBoughtLotto()` 를 제외한 모든 코드)만 `InputView` 클래스를 만들어서 분리해보면 좋을 것 같아요.
이를 통해 입력에 대한 책임은 `InputView` 로 이동하고, 출력에 대한 책임은 `LottoView` (OutputView 로 이름을 바꿔도 괜찮겠네요) 에서 관리해보시면 좋겠습니다.
이동하는 로직 내부에서 `lottoView` 를 통해 `구매할 돈을 입력 요청하는 문구`를 출력하는 부분에 대한 고민이 들으실 것 같은데요. `InputView`로 분리하면 해당 클래스는 `System.in`에 의존하고 있기에 `System.out`에도 의존해도 괜찮을 것 같습니다. :)

```java
// InputView.java

public MoneyToBuy inputMoney() {
        System.out.println("구입금액을 입력해 주세요.");
        final Scanner scanner = new Scanner(System.in);
        final String input = scanner.nextLine();
        final MoneyToBuy money = new MoneyToBuy(input);
        return money;
}
```

2022-11-24 00:32 UTC, seokhongkim commented on src/main/java/lotto2/controller/LottoController.java
> +        final List<List<LottoNumber>> lottoBucket = new ArrayList<>();
`List<LottoNumber>`를 담는 일급 컬렉션으로 `LottoNumbers.java` 클래스를 만들어보시면 좋겠습니다.
해당 클래스가 생성될 때 `List<LottoNumber>`가 6개의 번호인지, 서로 다른 번호인지를 검증해보면 좋겠습니다.

2022-11-24 00:32 UTC, seokhongkim commented on src/main/java/lotto2/controller/LottoController.java
> +    private WinningNumbers acceptWinningNumbers() {
우승번호는 위에서 말씀드린 새로 추가하는 `LottoNumbers` 객체와 동일한 제약조건(6개의 서로 다른 번호로 구성)을 가지고 있는 당첨번호와 1개의 `LottoNumber` 로 구성될 것 같아요.
이 방향으로 리팩터링해보시면 어떨까요?

2022-11-24 00:32 UTC, seokhongkim commented on src/main/java/lotto2/controller/LottoController.java
> +        final List<LottoNumber> lotto = LottoGenerator.generate();
자동으로 로또 번호를 생성해주는 `LottoGenerator` 구현 좋습니다. 👍 

우승번호는 사용자가 수동으로 입력한 번호를 파싱해서 사용하게 되겠네요.
`,`로 구분된 숫자 목록을 가지고 있는 문자열을 입력 받아서 `LottoNumbers` 객체를 만들어주는 generator 도 하나 만들어서 사용해보시면 좋겠습니다.

`WinningNumber` 클래스 안에서 이미 구현해놓으신 `toLottoNumbers`, `splitBLottoDelimiter` 로직을 이동하면 쉽게 구현하실 수 있을 것 같아요!

2022-11-24 00:32 UTC, seokhongkim commented on src/main/java/lotto2/controller/LottoController.java
> +            int winningCount = 0;
81-86번째 라인에 있는 아래 코드를 `LottoNumbers` 클래스를 만드신 후, `int matchCount(LottoNumbers lottoNumbers)` 메서드로 분리해보시면 `LottoNumbers` 객체를 이용해서 코드를 구현하실 수 있을 것 같아요.
```java
public int matchCount(LottoNumbers lottoNumbers) {
  int matchCount = 0;
  for (LottoNumber currentWinningNumber : lottoWinningNumbers) {
    if (eachLotto.contains(currentWinningNumber)) {
      matchCount++;
    }
  }

  return matchCount;
}
```

2022-11-24 00:32 UTC, seokhongkim commented on src/main/java/lotto2/model/MoneyToBuy.java
> +    public MoneyToBuy(String input) {
값 객체를 만들고 밸리데이션 책임을 관리하신 것 좋습니다. 👍 

밸리데이션 로직을 private method 로 분리해보시면 생성자 코드의 가독성이 한결 더 좋아질 것 같네요! :)

2022-11-24 00:32 UTC, seokhongkim commented on src/main/java/lotto2/model/LottoResultEachRow.java
> +public class LottoResultEachRow {
사용되지 않는 클래스인 것 같아서 삭제해보시면 좋겠습니다.

2022-11-24 00:32 UTC, seokhongkim commented on src/main/java/lotto2/controller/LottoController.java
> +            if (winningCount < 3 || 6 < winningCount) {
`winningCount`에 따라 분기가 있는 코드를 `LottoPrizeEnum` 객체를 아래와 같이 리팩터링 해보신 후, `LottoPrizeEnum`을 이용해서 등수를 가져와보시면 좋겠습니다.
코드에 문법적 오류가 있을 수 있으니 이 부분은 감안해서 참고해주시면 좋겠습니다. :)

```java
// enum 인 것을 클래스 이름에서 빼도 괜찮겠네요.
public enum LottoPrize {
  FIRST(2_000_000_000, (matchCount, hasBonus) -> matchCount == 6),
  SECOND(30_000_000, (matchCount, hasBonus) -> matchCount == 5 && hasBonus == true),
  THIRD(1_500_000, (matchCount, hasBonus) -> matchCount == 5 && hasBonus == false)
  // 이후 구현 생략, 4등, 5등과 당첨되지 않은 경우(NONE) 포함해서 구현
  ;

  private final long prize;
  private final BiFunction<Integer, Boolean, Boolean> matchFunction;

  public static LottoPrize prize(int matchCount, boolean hasBonus) {
    return Arrays.stream(values())
      .filter(prize -> prize.matchFunction.apply(matchCount, hasBonus)
      .findAny()
      .orElse(NONE);
  }
}
```

2022-11-26 05:12 UTC, OptimistLabyrinth commented
enum 안에서 BiFunction 사용하는 로직을 이해할 수가 없어서
제가 할 수 있는 다른 방법으로 함수 길이를 줄이는 리팩터링을 진행했습니다.

이외에도 피드백 주신 내용대로 최대한 수정해봤어요.

2022-11-26 05:13 UTC, OptimistLabyrinth commented on src/main/java/lotto2/controller/LottoController.java
> +    private MoneyToBuy acceptInputMoney() {
수정 완료했습니다.

2022-11-26 05:13 UTC, OptimistLabyrinth commented on src/main/java/lotto2/controller/LottoController.java
> +    private WinningNumbers acceptWinningNumbers() {
수정 완료했습니다.

2022-11-26 05:13 UTC, OptimistLabyrinth commented on src/main/java/lotto2/controller/LottoController.java
> +        final List<LottoNumber> lotto = LottoGenerator.generate();
수정 완료했습니다.

2022-11-26 05:13 UTC, OptimistLabyrinth commented on src/main/java/lotto2/controller/LottoController.java
> +            int winningCount = 0;
수정 완료했습니다.

2022-11-26 05:13 UTC, OptimistLabyrinth commented on src/main/java/lotto2/model/MoneyToBuy.java
> +    public MoneyToBuy(String input) {
수정 완료했습니다.

2022-11-26 05:13 UTC, OptimistLabyrinth commented on src/main/java/lotto2/model/LottoResultEachRow.java
> +public class LottoResultEachRow {
수정 완료했습니다.

2022-11-26 05:19 UTC, OptimistLabyrinth commented on src/main/java/lotto2/controller/LottoController.java
> +        final List<List<LottoNumber>> lottoBucket = new ArrayList<>();
수정 완료했습니다.

2022-11-26 06:20 UTC, seokhongkim approved these changes
기성님, 4단계 미션 코멘트 잘 반영해주셨습니다. 💯 
4단계 PR 머지하도록 하겠습니다.

코멘트를 조금 남겼는데, 다음 단계 미션 진행하실 때 가능하면 참고해보셔도 좋겠습니다.
이제 마지막 단계만 남았네요. 마지막 미션까지 화이팅입니다!
5단계 미션에서 뵙겠습니다. 😀

2022-11-26 06:20 UTC, seokhongkim commented on src/main/java/lotto2/model/Lotto.java
> +public class Lotto {
로또는 6개의 번호로 구성되어야 하고, 중복이 없어야 할 것 같아요.
생성자에서 밸리데이션을 해보는 건 어떨까요? :)

2022-11-26 06:20 UTC, seokhongkim commented on src/main/java/lotto2/model/LottoCalculationUtils.java
> +        final List<LottoNumber> lottoWinningNumbers = winningNumbers.lottoNumbers();
이 로직을 `Lotto` 클래스에서 구현해보면 어떨까요?

```java
public int getMatchCount(Lotto other) {
  final List<LottoNumber> otherNumbers = other.lottoNumbers();
  int matchCount = 0;
  for (LottoNumber lottoNumber : lottoNumbers) {
    if (otherNumbers.contains(lottoNumber) {
      matchCount++;
    }
  }
  return matchCount;
}
```

2022-11-26 06:20 UTC, seokhongkim commented on src/main/java/lotto2/model/Lotto.java
> +    public String toString() {
출력할 때 로또 번호를 정렬해서 보여줘야 하는 것 같아요.
정렬해서 정해진 형식으로 출력하는 것을 `OutputView`에 구현해보시면 좋겠습니다. :)

2022-11-26 06:20 UTC, seokhongkim commented on src/main/java/lotto2/model/enums/WinningRank.java
> +public enum WinningRank {
`LottoPrize`에서 매치되는 개수도 가지고 있으니, 거기에 있는 값을 사용해보셔도 괜찮을 것 같네요. :)

2022-11-26 06:20 UTC, seokhongkim commented on src/main/java/lotto2/controller/LottoController.java
> +            Lotto winningNumbers,
`Lotto`로 관리되는 `winningNumbers`와 `LottoNumber`로 관리되는 `bonusNumber`를 필드로 관리하는 `WinningLotto` 객체를 만들어 보셔도 좋겠습니다. :)

```java
public class WinningLotto {
  private final Lotto lotto;
  private final LottoNumber bonusNumber;

/*
  public WinningRank matchRank(Lotto lotto) {
    등수 반환
  }

  또는,

  public LottoPrize calculatePrize(Lotto lotto) {
    등수 반환
  }
*/
}
```

2022-11-26 06:21 UTC, merged

2022-11-26 13:21 UTC, OptimistLabyrinth reviewed
말씀해주신 피드백 내용 대부분 반영했습니다.

그런데 WinningRank Enum 에서 LottoPrize Enum 에 있는 값을 사용한다는게
어떤건지 잘 감이 안 옵니다.
조금 더 힌트를 주실 수 있나요???

미션은 아래 링크에서 진행중입니다.

https://github.com/next-step/java-lotto-pro/pull/949

2022-11-26 13:21 UTC, OptimistLabyrinth commented on src/main/java/lotto2/model/enums/WinningRank.java
> +public enum WinningRank {
java enum 이 이렇게 어려운건 몰랐네요 ㅎㅎㅎ
지금까지 저한테 enum 은 그냥 상수를 대신하는거였는데

어떻게 고쳐야 햐는지 힌트를 조금 더 주실 수 있나요???

2022-11-26 13:21 UTC, OptimistLabyrinth commented on src/main/java/lotto2/model/LottoCalculationUtils.java
> +        final List<LottoNumber> lottoWinningNumbers = winningNumbers.lottoNumbers();
수정 완료했습니다.

2022-11-26 13:21 UTC, OptimistLabyrinth commented on src/main/java/lotto2/model/Lotto.java
> +    public String toString() {
수정했습니당

2022-11-26 13:21 UTC, OptimistLabyrinth commented on src/main/java/lotto2/model/Lotto.java
> +public class Lotto {
수정 완료했습니다.

2022-11-26 13:21 UTC, OptimistLabyrinth commented on src/main/java/lotto2/controller/LottoController.java
> +            Lotto winningNumbers,
WinningLotto 클래스 만들었습니다.