Step5 리뷰 요청드립니다.
next-step/java-lotto-pro pull request #937
Opened 2022-11-08 15:00 UTC by jooh95

2022-11-09 09:49 UTC, mskangg requested changes
마지막 단계까지 오시느라 고생 많으셨습니다!!
요구사항 구현 잘해주셨고 일급컬렉션 및 모든 원시값과 문자열 포장 잘하셨습니다 👍 
다만, 몇가지 수정되면 더욱더 좋은 설계가 될 것 같아 피드백드렸어요!
이 부분은 고민해보시고 준오님 생각대로 반영해주시면 됩니다!
그럼 피드백 반영 부탁드려요 🙏

2022-11-09 09:49 UTC, mskangg commented on README.md
> +  - [x] 당첨 결과 일등컬렉션 구현 (WinningResult)
요구사항 정의 좋아요 👍

2022-11-09 09:49 UTC, mskangg commented on src/main/java/domain/SelfPickLottos.java
> +public class SelfPickLottos {
자동로또와 수동로또를 `QuickPickLottos`와 `SelfPickLottos`로 나누는것보단 `NumberGenerateStrategy` 전략을 다르게 가져가는 방식은 어떠신가요?
만약 2배수만 뽑을 수 있는 로또가 추가되면 클래스를 또 추가해야될까요?
현재 두 클래스의 차이는 로또를 생성하는 방식의 차이가 있기에 전략패턴을 가져간 것으로 보여집니다.
준오님 생각은 어떠신가요?

2022-11-09 09:49 UTC, mskangg commented on src/main/java/domain/LottoMachine.java
> +        return Lottos.createLottos(selfPickLottos, money);
단순히 Lottos.createLottos 를 호출하는 클래스를 따로 구현하신 이유가 있으실까요??
이 클래스는 없애는게 나아보입니다 🤔

2022-11-10 14:34 UTC, jooh95 commented on src/main/java/domain/SelfPickLottos.java
> +public class SelfPickLottos {
`QuickPickLottos`와 `SelfPickLottos`를 만든 이유는 일급컬렉센을 만들어주기 위해서 한번 더 `NumberGenerateStrategy`를 사용하는 `List<Lotto>`를 랩핑했습니다. 말씀하신 대로 이렇게 하면, 클래스는 늘어나는 단점이 있지만, 일등컬렉션 사용으로 오는 장점도 있을 거라 생각됩니다. 어떻게 생각하시나요?

2022-11-10 14:34 UTC, jooh95 commented on src/main/java/domain/LottoMachine.java
> +        return Lottos.createLottos(selfPickLottos, money);
삭제했습니다!

2022-11-11 12:21 UTC, mskangg commented on src/main/java/domain/SelfPickLottos.java
> +public class SelfPickLottos {
> QuickPickLottos와 SelfPickLottos를 만든 이유는 일급컬렉센을 만들어주기 위해서 한번 더 NumberGenerateStrategy를 사용하는 List<Lotto>를 랩핑했습니다.

한번더 사용한다고 하셨는데 `SelfPickLottos`는 `NumberGenerateStrategy`를 사용하고 있지 않고 있네요.
제가 잘못 이해한 부분일까요??

이전에 피드백 드린부분은 수동로또 요구사항이 추가됨으로 인해 중복코드가 발생하고 있고 리팩토링 가능해보여서 말씀드렸었습니다.
다만, 준오님 생각이 일급컬렉션으로 만들어 사용하는 장점이 더 높다고 판단되어 구현하셨다하니 이제 이해했습니다. 👍

2022-11-11 12:26 UTC, mskangg approved these changes
피드백 반영 잘해주셨고 코멘트 잘봤습니다.
마지막 미션까지 잘 해주셨어요 💯 
로또 미션이 1주차 미션이지만, 절대 늦은거라 생각하지 않았으면 좋겠어요~~

우테캠은 `일이 아닌 학습`이기에 자칫 오버엔지니어링이 될 수도 있는 경험을 해보는 것도 이 과정에서 느낄 수 있을거라 생각해요.
앞으로 미션 진행함에 있어서 `일이 아닌 학습`으로 생각하고 임해주신다면, 많은 것을 얻을 수 있으실거에요!
5단계까지 리뷰받아주셔서 감사하고 우테캠 모든 과정 끝까지 포기하지 않고 수료하시길 바랍니다!!

그럼 다음 미션도 화이팅입니다!! 🚀

2022-11-11 12:26 UTC, merged