Step5 로또 수동
next-step/java-lotto-pro pull request #944
Opened 2022-11-11 22:05 UTC by chosundeveloper

로또 수동 리뷰 부탁드립니다~
이번 미션을 계기로 기본적으로 놓치고 있는 부분이나 짚고 가야할 부분을 많이 
잡을수 있어서 좋은 시간이었습니다. 
향후 미션 뿐만 아니라 실무에서도 많은 도움이 될 것 같아 좋은 시간이었습니다.
좋은 피드백 감사드립니다.~

2022-11-13 02:36 UTC, chae-yh requested changes
요한님 안녕하세요. 벌써 마지막 step이네요...! 코드도 전체적으로 잘 작성해주셨습니다 👍 
바로 merge해도 될 것 같지만, 조금만 더 고민해주시면 좋을만한 내용이 있어서 코멘트 드렸으니 확인 부탁드립니다.

감사합니다 : )

2022-11-13 02:36 UTC, chae-yh commented on docs/README.md
> +### 숫자 유틸
마지막 step에 대한 기능 요건 작성도 기존 처럼 상세하면 좋을 것 같아요...!

2022-11-13 02:36 UTC, chae-yh commented on src/main/java/lotto/domain/LottoGenerator.java
> +        for (int i = MINIMUM_NUMBER; i <= MAXIMUM_NUMBER; i++) {
캐시 해주신 것 좋네요 👍

2022-11-13 02:36 UTC, chae-yh commented on src/main/java/utils/NumberUtil.java
> +public class NumberUtil {
이 부분은 의견여쭤보고 싶습니다. 패키지를 lotto와 같은 레벨로 두신 걸로 봤을 때 공통으로 사용하는 로직으로 판단하신 것 같아요...!
하지만, 로직 내용을 보면 입력 String의 배열을 Integer의 숫자 배열로 변경 시켜주는 내용을로 보입니다. 이 정도면 도메인에 밀접한 것 같아서, controller나 view정도에서 실행 시켜줄 수도 있을 것 같고, 아니면 도메인 으로 넣어주어도 될 것 같은데 혹시 util로 추출하신 이유가 있을까요...?

2022-11-13 02:36 UTC, chae-yh commented on src/test/java/lotto/domain/LottoGeneratorTest.java
> +    @CsvSource(value = {"3000:1", "4000:1", "5000:1"}, delimiter = ':')
`@CsvSource로 잘 바꿔 주셨습니다 👍

2022-11-13 02:36 UTC, chae-yh commented on src/main/java/lotto/ui/outputView/StatisticsOutputView.java
> +        Lottos lottos = new Lottos();
수동과 자동 로또의 개념이 view까지 올라와있어서, 실제 당첨금을 계산하기 위한 작업이 view에서 일어나는 것 같아요. 혹시 이 부분을 domain까지 내려볼 수 있을까요...? 약간 구조 변경이 있어야 할 것 같은데, 혹시 작업이 어렵거나 많다면 말씀주시면 merge하겠습니다...!

2022-11-13 15:12 UTC, chosundeveloper commented on src/main/java/lotto/ui/outputView/StatisticsOutputView.java
> +        Lottos lottos = new Lottos();
LottosMap 클래스를 만들어서 view쪽 비즈니스 로직을 담당하는 방향으로 수정해봤습니다. 피드백 부탁드립니다.

2022-11-13 15:27 UTC, chosundeveloper commented on src/main/java/utils/NumberUtil.java
> +public class NumberUtil {
도메인과 관련된 로직이어서 패키지 이동이 맞는것 같습니다.
클래스로 추출했던 이유는 테스트가 필요한 부분이어서 별도로 클래스를 만들어서 해당 로직에 대해 테스트를 작성하려고 만들었었는데 컨트롤러로 로직을 이동 한 후 테스트 코드를 작성해봤습니다.

2022-11-14 01:36 UTC, chae-yh approved these changes
요한님 안녕하세요! 마지막까지 피드백 반영 잘 해주셨습니다 💯 그리고 아쉽지만, 이것으로 제가 드리는 리뷰는 마지막인 듯 합니다 ㅎㅎ

피드백 받은 내용에 대해 계속해서 고민하시면서 잘 반영해주셔서 감사했습니다. 그리고, 나름 열심히 리뷰드리려고 했는데 요한님의 성장에 조금이라도 도움이 되었다면 정말 좋을 것 같습니다 ㅎㅎ

제 리뷰는 여기까지만, 남은 미션에서 저보다 훌륭하신 리뷰어님들과 함께 많은 성장있으시길 바라겠습니다. 그동안 고생많으셨습니다 감사합니다 : )

2022-11-14 01:36 UTC, chae-yh commented on src/test/java/lotto/domain/LottosMapTest.java
> +class LottosMapTest {
새로 추가된 도메인에 대한 테스트 👍

2022-11-14 01:37 UTC, merged