Step5 로또(수동)
next-step/java-lotto-pro pull request #945
Opened 2022-11-12 13:01 UTC by sueH237

근환리뷰어님, 안녕하세요! 
로또 마지막 미션 PR 요청드립니다. 
이번 미션동안 많은 도움과 친절한 피드백 주셔서 정말 감사합니다!! 
마지막 리뷰도 잘 부탁드립니다~😊😊

2022-11-13 12:21 UTC, geunhwanlee requested changes
5단계 미션 잘 해주셨어요! 👍🏻

몇가지 아쉬운 부분이 있어서 코멘트 드렸습니다.

확인해보시고 재 리뷰요청 주세요. 🙏

2022-11-13 12:21 UTC, geunhwanlee commented on src/main/java/lotto/Controller/LottoController.java
> +        }
Controller에 매뉴얼로 로또를 구매하고 검증하는 로직이 들어가있네요. 😭
적절한 객체에게 역할을 위임하는건 어떨까요?

2022-11-13 12:21 UTC, geunhwanlee commented on src/main/java/lotto/utils/LottoUtils.java
> +    public static int StringToIntNum(String str) {
우선 메서드 이름이 명확하지 않네요.
`문자열을 숫자로 변환 + 양수인지 체크`하는 기능이니 적절한 이름을 지어야할것 같아요! 😀

그리고 입력값이 음수가 될수 없다는건 도메인 로직일것 같아요!
LottoUtils에서는 사용자입력을 숫자로만 바꾸고
그 입력의 검증은 적절한 도메인에서 해야하지 않을까요? 🤔

2022-11-13 12:21 UTC, geunhwanlee commented on src/main/java/lotto/Controller/LottoController.java
> +        return new Lottos(manualLottos);
`manualLottoCount`는 필요없을것 같아요!
그리고
```suggestion
        return new Lottos(readManualLotto.stream()
                .map(LottoUtils::stringToLottoNumbers)
                .map(Lotto::new)
                .collect(Collectors.toList()));
```
이렇게 해도 될거같네요!😀

2022-11-13 14:14 UTC, sueH237 commented on src/main/java/lotto/Controller/LottoController.java
> +        return new Lottos(manualLottos);
👍👏👍👏👍👍👍 이렇게 하면 manualLottoCount가 필요 없네요!! 자세히 알려주셔서 감사합니다👍

2022-11-13 15:12 UTC, sueH237 commented on src/main/java/lotto/Controller/LottoController.java
> +        }
네~ 역활 위임하도록 수정하겠습니다!

2022-11-13 15:28 UTC, sueH237 commented on src/main/java/lotto/utils/LottoUtils.java
> +    public static int StringToIntNum(String str) {
네 입력 검증은 도메인에서 하도록 수정하겠습니다!

2022-11-14 14:12 UTC, geunhwanlee approved these changes
리뷰사항 반영 잘 해주셨어요! 👍🏻

이번 단계는 여기서 머지하도록 할게요. 😀

로또 미션이 끝났네요! 👏
너무 고생하셨고 수고 많으셨습니다.

앞으로 남은 미션들도 열심히 하시고 많은걸 얻어가셨으면 좋겠습니다! 🙏

2022-11-14 14:12 UTC, merged